### ISSUE TITLE
Connection reset running on CPython 3.6.8

### ISSUE THREAD

**Issue by bkt0031** [PyMySQL/PyMySQL#1002]
When running a simple select query (SELECT 1) or even a connection.ping() command on an RHEL 7.5 server using Python 3.6.8 installed from the rpm python3-3.6.8-18.el7.x86_64 the script fails with "connection reset by peer" from socket.py.  I run the same script from my Windows 10 laptop with Python 3.8.8 and it works fine.

**To Reproduce**
Any database will fail including an empty one for this test. 

Set up a virtual environment in a test directory:
$ python3 -m venv venv
$ source ./venv/bin/activate
(venv)$ python3 -m pip install pymysql

The code that is failing:

```
import pymysql.cursors

connection = pymysql.connect(
    host = 'dbserver',
    user = 'testuser',
    password = 'test1234,
    database = 'testdb',
    cursorclass = pymysql.cursors.DictCursor
)
with connection:
    with connection.cursor() as cursor:
        $sql = "SELECT 1"
        cursor.execute(sql)
        result = cursor.fetchone()
        print(result)
```
The resulting output:

>(venv)$ python --version
>
>Python 3.6.8
>(venv)$ python dbtest.py
>Traceback (most recent call last):
>  File "/home/user/Development/Python/test/venv/lib64/python3.6/site-packages/pymysql/connections.py", line 732, in  read_bytes
>    data = self._rfile.read(num_bytes)
>  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
>    return self._sock.recv_into(b)
>ConnectionResetError: [Errno 104] Connection reset by peer
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "dbtest.py", line 13, in <module>
>    cursor.execute(sql)
>  File "/home/user/Development/Python/test/venv/lib64/python3.6/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
>  File "/home/user/Development/Python/test/venv/lib64/python3.6/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
>  File "/home/user/Development/Python/test/venv/lib64/python3.6/site-packages/pymysql/connections.py", line 548, in query     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
>  File "/home/user/Development/Python/test/venv/lib64/python3.6/site-packages/pymysql/connections.py", line 775, in  >read_query_result
>    result.read()
>  File "/home/user/Development/Python/test/venv/lib64/python3.6/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
>  File "/home/user/Development/Python/test/venv/lib64/python3.6/site-packages/pymysql/connections.py", line 692, in _read_packet
>    packet_header = self._read_bytes(4)
>  File "/home/user/Development/Python/test/venv/lib64/python3.6/site-packages/pymysql/connections.py", line 740, in _read_bytes
>    "Lost connection to MySQL server during query (%s)" % (e,),
>pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query ([Errno 104] Connection reset by peer)')

**Expected behavior**
When I run the same code on my Windows 10 laptop (10.0.18363) I see the expected behavior:

>(venv) C:\Home\user\Development\Python\test>python --version
>Python 3.8.8
>
>(venv) C:\Home\user\Development\Python\test>python dbtest.py
>{'1': 1}

**Failing Environment**
 - OS: RHEL 7.5
 - Server and version: Windows Server 2012 R2, MySQL 8.0.20
 - PyMySQL version: 1.0.2
 - CPython version: 3.6.8
 
**Working Environment**
 - OS: Windows 10 10.0.18363
 - Server and version: Windows Server 2012 R2, MySQL 8.0.20
 - PyMySQL version: 1.0.2
 - CPython version: 3.8.8

**Additional context**
I can connect to TCP/3306 from the RHEL server:
>(venv)$ curl -v telnet://dbserver:3306
>\* About to connect() to dbserver port 3306 (#0)
>\*   Trying 192.168.0.100...
>\* Connected to dbserver (192.168.0.100) port 3306 (#0)

**Comment by methane** [comment]
SELinux, maybe?
Anyway, I won't investigate environment specific issue without access to the environment.

**Comment by bkt0031** [comment]
Not SELinux - Red Hat Enterprise Linux (RHEL). 

I did a little more testing over the weekend by installing the Oracle mysql-connector-python package and setting the connection with the use_pure = True option set which is supposed to use only Python (not the MySQL C library) as the means to connect to the database. This failed with the same error - connection reset upon query. There were a few discussion on the Internet concerning socket issues with 3.6.7, but not exactly the same issue so inconclusive. 

I ended moving over to another development server running RHEL 7.6 with Python 3.8.6 installed and it works fine. Since I'm short on time I'll run the code there and SCP the resulting YAML output over to the other system (the one that fails the MySQL connection) as it is our production Ansible environment.

**Comment by methane** [comment]
> Not running SELinux - stock Red Hat Enterprise Linux (RHEL).

Google "RHEL SELinux"

**Comment by bkt0031** [comment]
Sorry - for some reason I had CentOS on the brain there. At present no SELinux is enabled/configured on this (or any) server at where I work, but I'm sure it is only a matter of time given how security conscious (paranoid) the security department is here.

**Comment by methane** [comment]
Someone (not Python) close your connection. You need to find it by yourself.
If SELinux is disabled, you should check MySQL error log next.
