### ISSUE TITLE
I got encoding error when connecting to MySQL 8.0

### ISSUE THREAD

**Issue by allgrowsm** [PyMySQL/PyMySQL#1011]
When the password contains a string like "=" and/or "@", it gives me encoding error like following.

https://stackoverflow.com/questions/69402837/i-am-getting-uncaught-error-latin-1-codec-cant-encode-character-ufffd-in

**Comment by methane** [comment]
Do not ignore the issue template.

Your issue report is very bad. You didn't post a code to reproduce. You didn't post even complete error message and stack trace. It's very basic manner.

**Comment by allgrowsm** [comment]
It took 2 hours to find out this issue.
So, if you can fix it out, I really appreciate it.
Thanks :)

**Comment by allgrowsm** [comment]
@methane 
Thank you for suggestion.

Yes, exactly.
**\ufffd** is not "=".
\ufffd is gabled string.
So, I do not what it is actually.

As you can see from the stacktrace, there is encoding error from PyMySQL as follwing.

```
File "/var/api/lib/python3.6/site-packages/pymysql/connections.py", line 294, in __init__
self.password = self.password.encode("latin1")
```

The error message says "'latin-1' codec can't encode character".
Even I set the charset to utf8mb4 to the connection string, I get this error.
So, I guess following source code is doing some encoding error.
 
``
self.password = self.password.encode("latin1")
``

Do you have any furture sugesstion for this?
Regards,

**Comment by methane** [comment]
The encoding error happened because `\ufffd` is passed as password, not '=' is used in password. That's all. That's what you should try to fix.

**Comment by methane** [comment]
See this section carefully.
https://docs.sqlalchemy.org/en/14/core/engines.html#database-urls
