### ISSUE TITLE
how to connect from a client machine with an ssl connection and don't have access to the cert and key

### ISSUE THREAD

**Issue by stevenxuwoss** [PyMySQL/PyMySQL#1014]
**Describe the bug**
don't have access to the cert and key, is there any way to simple add ssl=true ?
<img width="540" alt="ssh" src="https://user-images.githubusercontent.com/17000812/141420944-2d9b691c-01ef-4018-a7ac-bfac3197d99b.png">

**To Reproduce**
Complete steps to reproduce the behavior:

Schema:

```
CREATE DATABASE ...
CREATE TABLE ...
```

Code:

```py
import pymysql
con = pymysql.connect(...)
```

**Expected behavior**

**Environment**
 - OS: [e.g. Windows, Linux]
 - Server and version: [e.g. MySQL 8.0.19, MariaDB]
 - PyMySQL version: 

**Additional context**

**Comment by cakemanny** [comment]
Ok. A shorter working example. Not sure if if violates some knowledge of the internals, but this works as at writing.
```python
import pymysql
conn = pymysql.connect(user='root', host='127.0.0.1', ssl={"verify_mode": None})
```
or any non-empty `dict` really

**Comment by cakemanny** [comment]
For the documenting of `ssl` taking an SSLContext, #1045 has been merged.
I forgot to mention this issue in there when opened that PR, 😅 , but hopefully that will help others in future.
