### ISSUE TITLE
Warning: (1300, "Invalid utf8mb4 character string: '800495'")

### ISSUE THREAD

**Issue by harshitsinghai77** [PyMySQL/PyMySQL#1016]
**Describe the bug**
```
site-packages/pymysql/cursors.py:170: Warning: (1300, "Invalid utf8mb4 character string: '800495'")
  result = self._query(query)
```

**To Reproduce**
No clear steps to reproduce. I'm using aiomysql. PyMySQL is being using inside aiomysql.

Schema:

```
CREATE DATABASE ...
CREATE TABLE ...
```

Code:

```py
import pymysql
con = pymysql.connect(...)
```

**Expected behavior**

**Environment**
 - OS: [e.g. Windows, Linux]
 - Server and version: [e.g. MySQL 8.0.19, MariaDB]
 - PyMySQL version: 0.9.3

**Additional context**

**Comment by methane** [comment]
Since you can not provide clear steps to reproduce, I can not do anything.
