### ISSUE TITLE
read_default_file doesn't work for SSL parameters

### ISSUE THREAD

**Issue by ryantm** [PyMySQL/PyMySQL#1020]
**Describe the bug**
I am trying to use `read_default_file` to configure the pymysql connection

**To Reproduce**

Use pymysql version 1.0.2.

Have a mysql config file like:

```
[mysql]
comments=1
default-character-set = utf8mb4
host = databasehost.example.com
database = dbname
ssl_key = /etc/mysql/client/key.pem
ssl_cert = /etc/mysql/client/cert.pem
ssl_ca = /etc/mysql/client/ca.pem
```

Code:

```py
import pymysql
conn = pymysql.connect(
          read_default_file=database_default_file,
          read_default_group='mysql',
          user=username, password=password, autocommit=True)
```

and if the user grant requires SSL it fails to connect.

If I change the code to 

```py
import pymysql
conn = pymysql.connect(
          read_default_file=database_default_file,
          read_default_group='mysql',
          user=username, password=password, autocommit=True,
          ssl_ca="/etc/mysql/client/ca.pem",
          ssl_cert= "/etc/mysql/client/cert.pem",
          ssl_key="/etc/mysql/client/key.pem")
```
It connects

**Expected behavior**

The ssl parameters don't have to be separately specified.

**Environment**
 - OS: NixOS
 - Server and version: mysql  Ver 15.1 Distrib 10.1.47-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
 - PyMySQL version: 1.0.2

**Additional context**

**Comment by methane** [comment]
Would you try to replace this "-" with "_"?
https://github.com/PyMySQL/PyMySQL/blob/f24cb9aa7295921bcd8f34f752c8a05b981d3125/pymysql/connections.py#L261

**Comment by ryantm** [comment]
Thanks. Changing the config file's fields from "_" to "-" like
```
[mysql]
comments=1
default-character-set = utf8mb4
host = databasehost.example.com
database = dbname
ssl-key = /etc/mysql/client/key.pem
ssl-cert = /etc/mysql/client/cert.pem
ssl-ca = /etc/mysql/client/ca.pem
```

made it work. The MySQL CLI supports either dash or underscore there (as dones Ruby's mysql), so I think it makes sense for PyMySQL to support either one too.

**Comment by alimp5** [comment]
Dear @ryantm,
I'm thankful if it's possible, Plz tell me difference between `ssl-cert`, `ssl-ca`, `ssl-key`.
thanks you.

**Comment by ryantm** [comment]
@alimp5 as far as MySQL is concerned they are the same, but this library treats them differently.
