### ISSUE TITLE
Update tested DB and Python versions

### ISSUE THREAD

**Issue by Nothing4You** [PyMySQL/PyMySQL#1025]
considering Python 3.6 and MySQL 5.6 are EOL, can they be dropped from tests?
tests for MariaDB 10.7 could be added to replace the MySQL 5.6 test.
3.10 build could be moved to a stable release, maybe already start testing on 3.11?

**Comment by Nothing4You** [comment]
@methane do you want to ensure compatibility for EOL python and MySQL versions or can I submit a PR to remove them from tests/docs?

**Comment by methane** [comment]
No. Please do it.
