### ISSUE TITLE
cursor.fetchall() returns a tuple on empty result

### ISSUE THREAD

**Issue by nmenardg-keeper** [PyMySQL/PyMySQL#1042]
**Describe the bug**
Doing a SELECT, if the result set is empty (no row found), `cursor.fetchall()` returns `()` (empty tuple)

**To Reproduce**
```py
import pymysql
con = pymysql.connect(...)
with con.cursor() as cursor:
    cursor.execute("select * from information_schema.TABLES where TABLE_NAME = 'patate';")
    data = cursor.fetchall()
```

**Expected behavior**
PEP-0249 mentions:
> returning them as a sequence of sequences (e.g. a list of tuples)
https://peps.python.org/pep-0249/#fetchall

I would expect an empty list `[]`

**Environment**
 - OS: Manjaro Linux
 - Server and version: MySQL 8.0.20
 - PyMySQL version: 1.0.2

**Comment by methane** [comment]
See #1008

**Comment by Nothing4You** [comment]
As per https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range `tuple` is also a sequence type, so I don't see how this would violate PEP 249?

#1008 would make PyMySQL behave more like `mysql.connector`, but this should be fine either way in terms of PEP 249 compliance.

**Comment by methane** [comment]
Yes, it doesn't violate the PEP. But I like sequence in this case, because we need additional list -> tuple convertion in the PyMySQL.

Django checks `fetchmany() == ()` to find when `fetchmany()` finished.
So we can use `()` only when `fetchmany()` returns EOF.

**Comment by Nothing4You** [comment]
I don't fully understand your last message, I was mainly referring to the issue description in this issue, as that suggests it's a bug and not following PEP 249.

**Comment by methane** [comment]
@Nothing4You I said just you are right.

**Comment by Nothing4You** [comment]
As a consumer of a DB API 2.0 compliant library you should just need to check whether `len(rows)` is `0` or not?

Does it make a significant performance difference or why would that not be used?

I'm trying to understand why this would even matter.

**Comment by nmenardg-keeper** [comment]
There is no performance difference. Perhaps it's sort of a philosophical question. As I said, it goes against the principle of least astonishment.

**Comment by methane** [comment]
https://github.com/django/django/blob/1250483ebf73f7a82ff820b94092c63ce4238264/django/db/backends/mysql/features.py#L8

https://github.com/django/django/blob/1250483ebf73f7a82ff820b94092c63ce4238264/django/db/models/sql/compiler.py#L1555

**Comment by methane** [comment]
I change to:

* fetchall() always return list
* fetchmany() returns empty tuple when it read all rows.
