### ISSUE TITLE
AttributeError: module 'pymysql.constants' has no attribute 'FLAG'

### ISSUE THREAD

**Issue by hzr1140521792** [PyMySQL/PyMySQL#1044]
**Describe the bug**
when I tried to edit torndb for python3
I got this problem:
AttributeError: module 'pymysql.constants' has no attribute 'FLAG'
but I find pymysql has this module

**To Reproduce**
Complete steps to reproduce the behavior:

Schema:

```
CREATE DATABASE ...
CREATE TABLE ...
```

Code:

```py
import pymysql
con = pymysql.connect(...)
```

**Expected behavior**

**Environment**
 - OS: [e.g. Windows, Linux]
 - Server and version: [e.g. MySQL 8.0.19, MariaDB]
 - PyMySQL version: 

**Additional context**

**Comment by Nothing4You** [comment]
Hi,

the text below `Describe the bug` is a template for you to fill out.
Without more information it's impossible to understand your problem.
