### ISSUE TITLE
'utf-8' codec can't decode byte 0xf0 /0xe2 /0xe5...

### ISSUE THREAD

**Issue by earl86** [PyMySQL/PyMySQL#1046]
**Describe the bug**
when use utf8 connect to database,  query like "show engine innodb status" etc.
conn = pymysql.connect(host=xx, port=xx, user=USERNAME, passwd=PASSWORD,db='',charset="utf8",connect_timeout=3)
sometime there is Exception like:
'utf-8' codec can't decode byte 0xf0
'utf-8' codec can't decode byte 0xef

Exception  in this line in PyMySQL/pymysql/connections.py
data = data.decode(encoding)

can change this line  to: 
data = data.decode(encoding, 'ignore')  ?

**Comment by methane** [comment]
> can change this line to:
> data = data.decode(encoding, 'ignore') ?

No.

You need to fix your data by yourself, or `use_unicode=False` to get raw bytes.
