### ISSUE TITLE
MULTI_STATEMENTS do not return if variable defined.

### ISSUE THREAD

**Issue by KingMichaelPark** [PyMySQL/PyMySQL#1047]
**Describe the bug**
When executing multiple statements, if a variable is declared and then referenced
in a sql query there is no result returned from the statement.

**To Reproduce**
Complete steps to reproduce the behavior:

```py
import pymysql
from pymysql.constants import CLIENT


if __name__ == "__main__":
    database_user = ""
    database_host = ""
    database_name = ""
    database_password = ""
    with pymysql.connect(
        user=database_user,
        passwd=database_password,
        host=database_host,
        db=database_name,
        client_flag=CLIENT.MULTI_STATEMENTS,
    ) as conn:

        with conn.cursor() as cursor:
            # Does not work
            cursor.execute(
                """
                SET @ip_address = 1;
                """,
            )
            cursor.execute(
                """
                SELECT @ip_address;
                """,
            )
            result = cursor.fetchone()
            print("Nothing")
            print(result)
            # Does work but returns 0.0.0.0 not 0.0.0.1
            cursor.execute(
                """
                SELECT "0.0.0.0";
                SELECT "0.0.0.1";
                """
            )
            result = cursor.fetchone()
            print("A result")

```

**Expected behavior**

I expect the select statement to return values from the query

**Environment**
 - OS: Linux
 - Server and version: MySQL 8.0.17
 - PyMySQL version: 1.0.2

**Additional context**
This example is obviously simplified down but it came about that passing %s arguments into
a multi statement query where variables are declared and reused in the subsequent select statement
just don't return a response. (Returning None)

```sql
SET @var = 2;

SELECT 1 * @var as example 
```
Will fail to return for example

**Comment by KingMichaelPark** [comment]
The workaround appears to be doing this:

Shall I raise a PR where the fetch methods have a `last` argument that let's you return
the final result of the statement not the first?

```python
    with pymysql.connect(
        user=database_user,
        passwd=database_password,
        host=database_host,
        db=database_name,
        client_flag=CLIENT.MULTI_STATEMENTS,
    ) as conn:

        with conn.cursor() as cursor:
            # Does not work
            cursor.execute(
                """
                SET @ip_address = 1;
                SELECT * from api_keys;
                """
            )
            while cursor._result.has_next:
                cursor.nextset()
            print(cursor.fetchmany())

```

**Comment by methane** [comment]
It is intended behavior. Not a bug. Please don't send a PR.

**Comment by KingMichaelPark** [comment]
I won't, is there a better way to do what I accomplished above without accessing _result which I would assume isn't meant to be used like this? It isn't super intuitive that you need to access result to get to the last returned value.

**Comment by methane** [comment]
Just use cursor.nextset().
https://peps.python.org/pep-0249/#nextset

**Comment by KingMichaelPark** [comment]
Cheers, thank you for taking the time to respond. I really appreciate it.

Michael Park
Data Engineer
[The Data Shed Logo]
T:      0113 2433739
W:      https://thedatashed.co.uk<http://www.thedatashed.co.uk>
The Data Shed | Mabgate Mills, Mill One, Floor Three, Mabgate, Leeds, LS9 7DZ
[ISO-27001] [Cyber Essentials]  [Crown Commercial Service Supplier]  [Leeds Digital Festival]
[LinkedIn]<https://www.linkedin.com/company/the-datashed> [Twitter] <https://twitter.com/thedatashed>
________________________________
From: Inada Naoki ***@***.***>
Sent: 03 May 2022 09:47
To: PyMySQL/PyMySQL ***@***.***>
Cc: Michael Park ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL]Re: [PyMySQL/PyMySQL] MULTI_STATEMENTS do not return if variable defined. (Issue #1047)


Just use cursor.nextset().
https://peps.python.org/pep-0249/#nextset<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpeps.python.org%2Fpep-0249%2F%23nextset&data=05%7C01%7Cmichaelpark%40thedatashed.co.uk%7C026aacaa90c44b340c3108da2ce19611%7Cf420563810bb4ebda523e746a01ddade%7C0%7C0%7C637871644652690580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EzVAmRAZQ5AZWT%2BtRBjq1FkXWyqC8yvU4C%2F5mTZd6Zs%3D&reserved=0>
