### ISSUE TITLE
MyPy compliance / typing

### ISSUE THREAD

**Issue by tgross35** [PyMySQL/PyMySQL#1050]
PyMySQL should aim for mypy compliance to help users with static type checking, and provide better IDE support.

Adding types should be pretty straightforward, and stubs are already available on typeshed (https://github.com/python/typeshed/tree/master/stubs/PyMySQL) so a lot of that could likely be ported.

Would a PR be accepted?

**Comment by methane** [comment]
Unlikely, but I'm not sure.

**Comment by tgross35** [comment]
I'll do a couple files and submit a PR. If it gets a thumbs up at that point, I'll do the rest
