### ISSUE TITLE
placeholders broken

### ISSUE THREAD

**Issue by 9EOR9** [PyMySQL/PyMySQL#1051]
In parameterized SQL statement parameter should be not treated as parameters if they are enclosed by comments or quotation marks. However this works not with PyMySQL, simple executes fail:

**Code:**
```
# 0 placeholders, no data -> works ok
cursor.execute("select airline, iata from airlines where airline like '%ss'")
print(cursor.fetchall())
# 1 placeholder, data contains tuple of size 1 -> not ok
cursor.execute("select airline, iata from airlines where airline like '%ss' and destination=%s", ("Turkey",))
print(cursor.fetchall())

```

**Output:**
```
(('Federal Express', 'FX'), ('SunExpress', 'XQ*'), ('SWISS', 'LX'))

Traceback (most recent call last):
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/PyMySQL-0.10.1-py3.9.egg/pymysql/cursors.py", line 161, in execute
  File "/usr/local/lib/python3.9/site-packages/PyMySQL-0.10.1-py3.9.egg/pymysql/cursors.py", line 140, in mogrify
TypeError: not enough arguments for format string

**Comment by 9EOR9** [comment]
This is a valid SQL statement and works with command line client (using prepare syntax) but also with Python's mariadb module. 
Imho parsing and rewriting statements in applications doesn't make sense, if it could be fixed in driver. 
While your suggestion might be a workaround for the statement above, it cannot be used for MySQL and MariaDB's comment syntax.

**Comment by methane** [comment]
> This is a valid SQL statement and works with command line client (using prepare syntax)

MySQL uses `?`, not `%s`. I don't know much about mariadb module. Backward compatibility is far much important.

BTW, you can use one more placeholder for compatibility with mariadb.

```
cursor.execute("select airline, iata from airlines where airline like %s and destination=%s", ("%ss", "Turkey"))
```
