### ISSUE TITLE
cursor.execute() - inconsistent None handling for insert with values sets

### ISSUE THREAD

**Issue by dj-mothman** [PyMySQL/PyMySQL#1058]
**Describe the bug**
When calling `cursor.execute()` to perform a values insert with only a single set of values to be inserted, if attempting to insert `None` into a non-nullable column, then an IntegrityError is raised: `pymysql.err.IntegrityError: (1048, "Column 'A' cannot be null")` - this is expected.

However when trying this with more than one set of values to be inserted, no error is raised and a default value is used silently instead. `cursor.mogrify()` does appear to return the expected SQL string (with `None` replaced with `NULL`) but this doesn't feel like any issue related to the setup of the server, as when trying to run that generated SQL directly against the database it results in an error as expected.

**To Reproduce**
Complete steps to reproduce the behavior:
1. Create the table
2. Run the code
3. Both records are inserted with empty string instead of an error being raised

Schema:

```sql
CREATE TABLE TEST (
	PK varchar(64) NOT NULL,
	A varchar(64) NOT NULL,
	PRIMARY KEY (PK)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

Code:

```py
import pymysql

with pymysql.connect(...) as con:
  with con.cursor() as cursor:
    sql = "INSERT INTO TEST (`PK`, `A`) VALUES (%s, %s), (%s, %s)"
    parameters = ['testPK', None, None, 'testA']
    try:
      cursor.execute(sql, parameters)
      con.commit()
    except Exception as ex:
      con.rollback()
      raise	
```

**Expected behavior**
An IntegrityError should be raised for the first set of values which cannot be inserted: `pymysql.err.IntegrityError: (1048, "Column 'A' cannot be null")`. If the parameters above were changed to: `['testPK', 'testA', None, 'testA']` then the error should indicate that it is the second set which is invalid: `pymysql.err.IntegrityError: (1048, "Column 'PK' cannot be null")`

**Environment**
 - OS: Windows
 - Server and version: MySQL 5.7 Aurora
 - PyMySQL version: 1.0.2

**Additional context**
Could be something glaringly obvious that I'm missing here, but it doesn't seem possible for this to be intended behaviour as it behaves totally differently depending on how many sets of values you are trying to insert. Also seems like it would be a fairly major problem mostly due to the fact that it occurs silently...

**Comment by methane** [comment]
Check your aurora configurations.
PyMySQL raise an error when MySQL returned an error.

**Comment by dj-mothman** [comment]
@methane Thanks for your reply. However as I mentioned in the description when I run the SQL that is output by `cursor.mogrify()` against the DB manually then I get the error as expected. Therefore I don't see how the Aurora configuration could be causing this. If this was caused by Aurora configuration then I would expect the same result when I run the query manually compared to via PyMySQL.

To be clear, the output of `cursor.mogrify()` in this scenario is: `INSERT INTO TEST (`PK`, `A`) VALUES ('testPK', NULL), (NULL, 'testA')` which gives the following when running manually (as expected):
![image](https://user-images.githubusercontent.com/73363118/181207370-f3170c0d-a770-48ec-9b8d-99c3f8092f47.png)

It seems clear to me that if the result of `cursor.mogrify()` was actually the query which was being sent to the DB then this error would have occurred which, as you advised, would result in the error being raised by PyMySQL. As the error is not being raised by PyMySQL then surely there must be something going on in the library behind the scenes which is causing these NULL values to be defaulted.

**Comment by methane** [comment]
I don't know your environment. In my environment, PyMySQL raises Exception as you expected.
So you should investigate your enviornment by yourself.
Or you should create *reproducible* example using docker mysql container.

```
>>> import pymysql
>>> pymysql.connect(user="root", database="test")
<pymysql.connections.Connection object at 0x10ad1a130>
>>> con = _
>>> cur = con.cursor()
>>> sql = "INSERT INTO TEST (`PK`, `A`) VALUES (%s, %s), (%s, %s)"
>>> parameters = ['testPK', None, None, 'testA']
>>> cur.execute(sql, parameters)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/inada-n/work/PyMySQL/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "/Users/inada-n/work/PyMySQL/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "/Users/inada-n/work/PyMySQL/pymysql/connections.py", line 546, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/inada-n/work/PyMySQL/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/Users/inada-n/work/PyMySQL/pymysql/connections.py", line 1152, in read
    first_packet = self.connection._read_packet()
  File "/Users/inada-n/work/PyMySQL/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/Users/inada-n/work/PyMySQL/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/inada-n/work/PyMySQL/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'A' cannot be null")
```
