### ISSUE TITLE
Wrong character column size

### ISSUE THREAD

**Issue by kxmatjob** [PyMySQL/PyMySQL#1060]
create table test_tab (C1 CHAR(8));
```
cursor.execute("select * from test_tab")
attr_list = cursor.description
for value in attr_list:
    print("display_size="+value[3],"internal_size="+value[4])
```
`display_size=16,internal_size=16`
but C1 length is 8.

**Comment by methane** [comment]
It is not you expect.

**Comment by kxmatjob** [comment]
@methane  How to get the field length？

**Comment by kxmatjob** [comment]
@methane  Have you tested it? This is the result of my test.
