### ISSUE TITLE
How to assign a variable to table/column without using python string formatting?

### ISSUE THREAD

**Issue by gfyts0123** [PyMySQL/PyMySQL#1063]
Hello, I met the same issue with [stackoverflow](https://stackoverflow.com/questions/42264991/pymysql-assigning-a-variable-to-table-name-in-python)

```python
name = 'id'
sql = 'SELECT * FROM demo ORDER BY %s DESC'
cursor.execute(sql, (name,))
```

The sql can be executed but the `ORDER BY` is useless since the real sql is : 
`SELECT * FROM demo ORDER BY 'id' DESC`

I'm wondering is there any way to fix this without using python string formatting?
 Since `f'SELECT * FROM demo ORDER BY {name} DESC' ` may has a risk of sql injection.
Or will we fix this problem in pymysql in the next several versions?

My pymysql version is: 1.0.2
My python version is: 3.7.9

**Comment by methane** [comment]
> I'm wondering is there any way to fix this without using python string formatting?

No



> Since `f'SELECT * FROM demo ORDER BY {name} DESC' ` may has a risk of sql injection.

You need to avoid any SQL injection risk by yourself. (e.g. avoid using user input, or check by allowlist).



> Or will we fix this problem in pymysql in the next several versions?

No.
