### ISSUE TITLE
BLOB data messes up cursor

### ISSUE THREAD

**Issue by charles-001** [PyMySQL/PyMySQL#1064]
**Describe the bug**
Hello. I'm creating a top tool for MySQL and it seems BLOB data it reads from SHOW PROCESSLIST is messing up the cursor.

The error I get is: 
`InternalError: Packet sequence number wrong - got 7 expected 1`.  I am not using any multi-threading or anything of the sort. My code is single-threaded.

With MySQLdb, the error is:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 2043: invalid continuation byte`

With mysql.connector , the error is: 
`InternalError: Unread result found`

My default character set is utf8mb4, and from what I read `0xed` is a latin1 character.

Is there anything I can do to fix this? It seems like it's a Python driver issue. I have a similar tool in Perl + PHP and neither have this type of issue. I'm curious why Python seems to fail to work with BLOB data. 

[traceback.txt](https://github.com/PyMySQL/PyMySQL/files/9435812/traceback.txt)

Thank you in advance!

**Comment by charles-001** [comment]
[traceback.txt](https://github.com/PyMySQL/PyMySQL/files/9435812/traceback.txt)

**Comment by methane** [comment]
https://github.com/PyMySQL/mysqlclient/issues/553#issuecomment-1229128788

**Comment by charles-001** [comment]
@methane - wouldn't that mean I need to decode every single thing I SELECT?

**Comment by methane** [comment]
If you want to keep mixing latin1 and UTF-8, yes.

Making everything valid UTF-8 is far much better, of course.

**Comment by charles-001** [comment]
@methane - I don't really have a choice in the mixing since it's BLOB data. So in Perl/PHP, it automatically converts it to what it should be in a smart way? Python is unable to do that?

**Comment by methane** [comment]
If it is really BLOB column data, PyMySQL and mysqlclient uses bytes instead of Unicode. So UnicodeDecodeError won't happen.



> So in Perl/PHP, it automatically converts it to what it should be in a smart way?

No. They don't distinguish text and binary. Both are string. No need to be smart.

**Comment by charles-001** [comment]
@methane - OK, thanks for your help! I've switched over to `use_unicode=False` and am using charset_normalize to detect the character set of the query text so it can be decoded using the proper one.
