### ISSUE TITLE
v 1.0.2 crypto error, downgrade to 0.9 no crypto error, upgrade back to v 1.0.2 no error

### ISSUE THREAD

**Issue by Hammurabi1750BC** [PyMySQL/PyMySQL#1068]
PyMySQL 1.0.2 was working for days.  Today I got the error:

RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods

I downgraded to PyMySQL 0.9
- works, no crypto error

Upgrade back to 1.0.2, which I started with
- works, no crpto error.

Running Ubuntu 22.  Same exact thing happened a few days ago on a different set up running Ubuntu 20.

**Comment by methane** [comment]
I can not debug your environment.
Please provide a full reproduce step with Docker MySQL.
