### ISSUE TITLE
I don't know what happend 

### ISSUE THREAD

**Issue by simplemrchen** [PyMySQL/PyMySQL#1070]
select 
	erp_price.erp_id,
	erp_price.unit_price_tax,
	erp_stock.mfr_qty,
	erp_stock.six_qty
from (
	select 
		t2.erp_id, 
		t2.unit_price_tax 
	from(
		SELECT 
			@r:= CASE WHEN @rank=t1.erp_id THEN @r+1 ELSE 1 END AS quoteRanking,
			@rank:=t1.erp_id AS TYPE,
			t1.* 
		FROM (
			select 
				erp_id, 
				unit_price_tax, 
				ds_mfr 
			from realtime_stock where country_code='kz') t1 
			ORDER BY t1.erp_id, t1.ds_mfr desc) t2 
			where t2.quoteRanking=1) erp_price
inner join (
	select erp_id, 
			   sum(IF(ds_exp > '2023-04-20' ,qty, 0)) mfr_qty,
				 sum(IF(ds_exp <= '2023-04-20' ,qty, 0)) six_qty
	from realtime_stock where country_code='kz' GROUP BY erp_id) erp_stock
on erp_price.erp_id=erp_stock.erp_id;

when I submmit this sql in navicat ,it is 55 pieces of datas. but when I use pymysql submmit this, it is 149 pieces of datas.
In my table, it is 149 pieces of data in total.

pymysql version:1.0.2
python:3.8.4
mysql version:5.7.28

**Comment by methane** [comment]
I don't know what is problem.

**Comment by simplemrchen** [comment]
select t2.erp_id, t2.unit_price_tax, quoteRanking from(SELECT @r:= CASE WHEN @rank=t1.erp_id THEN @r+1 ELSE 1 END AS quoteRanking, @rank:=t1.erp_id AS TYPE, t1.* 
FROM (
select 
erp_id, 
unit_price_tax, 
ds_mfr 
from realtime_stock where country_code='kz') t1 
ORDER BY t1.erp_id, t1.ds_mfr desc) t2 
where t2.quoteRanking = 1;

when I use navicat or mysql client command, It is 43 pieces of data. when I use pymysql , It is 149 pieces of data; 
please help me;

**Comment by methane** [comment]
not reproducible
i don't know navicat

I am not free teacher or tech support. Please write an "issue report" here.
If you want to get help, please use Python or MySQL communities.
