### ISSUE TITLE
LookupError: unknown encoding: utf8mb3

### ISSUE THREAD

**Issue by blackoctop** [PyMySQL/PyMySQL#1072]
**Describe the bug**
I work for a "X" company which wants MariaDB replication on another db, so I found "mysqlreplication" to read row_based binlog. Still, I got lookuperror as charset of the tables are "utf8mb3" which happens to be deprected, upgrading to "utf8mb4" is no solution for the "X" and I couldn't find any workaround except adding these lines directly in pymysql/charset.py: 
_charsets.add(Charset(256, "utf8mb3", "utf8mb3_general_ci", "Yes"))
_charsets.add(Charset(257, "utf8mb3", "utf8mb3_bin", ""))
 
Which fixed my problem but I don't feel it is a good practice.

**To Reproduce**
Complete steps to reproduce the behavior:
Just use utfmb3 in your DB.
For newer version of mysql, mariadb I guess you should use variable "old_mode = UTF8_IS_UTF8MB3"

Code:
mysql_settings =
{'host': host,
'port': port,
'user': user,
'passwd': passw
}

stream = BinLogStreamReader(
connection_settings=mysql_settings,
server_id=1024,
is_mariadb=True,
# blocking=True,
only_events=[DeleteRowsEvent, UpdateRowsEvent, WriteRowsEvent],
# resume_stream=True,
only_tables=[table],
only_schemas=[schema]
)

which goes on exception on line "for row in binlogevent.rows:"

for binlogevent in stream:
for row in binlogevent.rows:
print(row)
stream.close()

Traceback (most recent call last):
File "C:\Users\user\Desktop\pyProjects\replica\binlogreader\test.py", line 93, in
print(binlogevent.rows)
File "C:\Users\user\Desktop\pyProjects\replica.env\lib\site-packages\pymysqlreplication\row_event.py", line 459, in rows
self._fetch_rows()
File "C:\Users\user\Desktop\pyProjects\replica.env\lib\site-packages\pymysqlreplication\row_event.py", line 454, in _fetch_rows
self.__rows.append(self._fetch_one_row())
File "C:\Users\user\Desktop\pyProjects\replica.env\lib\site-packages\pymysqlreplication\row_event.py", line 545, in _fetch_one_row
row["after_values"] = self._read_column_data(self.columns_present_bitmap2)
File "C:\Users\user\Desktop\pyProjects\replica.env\lib\site-packages\pymysqlreplication\row_event.py", line 154, in _read_column_data
values[name] = self.__read_string(2, column)
File "C:\Users\user\Desktop\pyProjects\replica.env\lib\site-packages\pymysqlreplication\row_event.py", line 250, in __read_string
string = string.decode(encoding)
LookupError: unknown encoding: utf8mb3

**Expected behavior**
String should be decoded with utf8.

**Environment**
 - OS: Windows 11
 - Server and version: MariaDB 10.6.8
 - PyMySQL version: 1.0.2

**Additional context**
exception path:
**pymsqlreplication** 
    @staticmethod
    def charset_to_encoding(name):
        charset = charset_by_name(name)  # pymsql function
        return charset.encoding if charset else name

_name is 'utf8mb3'_

**pymysql**
charset_by_name = _charsets.by_name

    def by_name(self, name):
        return self._by_name.get(name.lower())

_there is no entry for utf8mb3 in _charsets._

Thanks.

**Comment by methane** [comment]
This is pymysqlreplication issue.
