### ISSUE TITLE
SSL version number

### ISSUE THREAD

**Issue by ekwan** [PyMySQL/PyMySQL#1073]
Hi All,

This code is producing an SSL version error:

```
connection = pymysql.connect(host="someplace.com",
                             user='username',
                             password='password',
                             database='dbname',
                             port=3306,
                             cursorclass=pymysql.cursors.DictCursor,
                             ssl={"verify_mode": None})
```

`OperationalError: (2003, "Can't connect to MySQL server on 'someplace.com' ([SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997))")`

I do have a `.pem` file, but it's not clear to me how to use it (I've tried various permutations).

Any suggestions?  Thanks!

**Comment by methane** [comment]
Not reproducible.
See https://stackoverflow.com/help/minimal-reproducible-example
