### ISSUE TITLE
cryptography is required 

### ISSUE THREAD

**Issue by Tusenka** [PyMySQL/PyMySQL#1079]
**Describe the bug**
cryptography doesn't found when used with --target destination.

`
pip3 install --target ./python PyMySQL\[rsa\]
`

```
import json
import pymysql
import cryptography
try:
    conn = pymysql.connect(host=rds_host,user=name,
                           passwd=password,db=db_name,
                           connect_timeout=5,
                           cursorclass=pymysql.cursors.DictCursor)
except Exception as e:
    print(e)
    exit()
    with conn.cursor() as cur:
        qry = "SHOW tables"
        cur.execute(qry)
        body = cur.fetchall()
        'body': json.dumps(body)               
```

Got:

'cryptography' package is required for sha256_password or caching_sha2_password auth methods

**Comment by kanarian** [comment]
Are you sure that your database password is correct? I had the same issue, it was due to my password being incorrect

**Comment by methane** [comment]
Not reproducible.
