### ISSUE TITLE
ssl connect not safe or the method of connect mysql with ssl error?

### ISSUE THREAD

**Issue by chengcxy** [PyMySQL/PyMySQL#1083]
dba create a new db user to test the ssl of pymysql

mysqlserver sure  open ssl checkValid and create new three pem files

```
ca.pem
client-cert.pem
client-key.pem
```

pymysql version 0.9.3

we used pymysql to connect mysqlserver ,the connect params ssl is a dict params  like 

```
 "ssl" :{
                "ssl":{
                }
            }
```
it can connect mysql success, this is a error,because the client  need upload client-key.pem/ca.pem/client-cert.pem
to server,we don't upload

first  the config is 
![image](https://user-images.githubusercontent.com/25173362/211834348-50030cc6-cf6a-495f-b201-d274e6e289bc.png)

raised an exception

![image](https://user-images.githubusercontent.com/25173362/211834476-38b2bc55-130e-4895-b058-ebf8d7657d3b.png)

second,we changed config 
```
config =  {
            "host": "host",
            "user": "USER",
            "password": "PASSWORD",
            "port": 3306,
            "db": "db",
            "charset": "utf8",
            "ssl" :{
                "ssl":{
                }
            }
}
```

the result success
![image](https://user-images.githubusercontent.com/25173362/211834763-c8128167-6994-4cb3-9c1c-10778f775520.png)

Code:

```py
import pymysql
config =  {
            "host": "host",
            "user": "USER",
            "password": "PASSWORD",
            "port": 3306,
            "db": "db",
            "charset": "utf8",
            "ssl" :{
                "ssl":{
                }
            }
}
con = pymysql.connect(**config)
```

**Comment by methane** [comment]
> it can connect mysql success, this is a error,because the client need upload client-key.pem/ca.pem/client-cert.pem
> to server,we don't upload

It is an error of your MySQL. Don't ask me supporting your environment.
OSS maintainer is not free tech support.
