### ISSUE TITLE
Change default encoding for utf8mb4 and mysql 8 or allow setting encoding when connecting

### ISSUE THREAD

**Issue by jin-harmoney** [PyMySQL/PyMySQL#1092]
**Describe the bug**

We're getting the following error when connecting to our mysql 8 database with the standard collation `utf8mb4_0900_ai_ci` for `utf8mb4`:

```
Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
```

**To Reproduce**

* Create a simple table with a varchar column on a standard mysql 8 database
* Run query:

```
set @test = 'test';
select * from table where col_name = @test;
```

This does work, but it shouldn't be necessary to specify the collation:

```
set @test = 'test' collate 'utf8mb4_0900_ai_ci';
select * from table where col_name = @test;
```

Execute this query using pymysql. Since the default charset used by pymysql is `utf8mb4_general_ci`, you'll get the error mentioned above.

**Expected behavior**

The query should either work because the default collation used by pymysql matches the default collation of mysql, or it should be possible to specify the collation (or encoding) when connecting.

The current behavior in the code is to use the default: https://github.com/PyMySQL/PyMySQL/blob/main/pymysql/connections.py#L307-L310

**Environment**
 - Server and version: 8.0.27-18.1 - Percona XtraDB Cluster
 - PyMySQL version: 0.7.4

**Comment by methane** [comment]
After #1119, we send `SET NAMES utf8mb4` on every new connection.
The default collation for utf8mb4 of the server (utf8mb4_0900_ai_ci on MySQL 8.0, utf8mb4_general_ci on MySQL 5.7 and MariaDB) are chosen by the server.

See this comment for more background.
https://github.com/PyMySQL/PyMySQL/pull/1119/files#diff-cceee545e98e58817fb5df3b7892efed08c0c68c0fd72f1fbb42df5010a62cf3R666-R679
