### ISSUE TITLE
1.0.3rc1build is missing `constants` directory

### ISSUE THREAD

**Issue by elip-OE** [PyMySQL/PyMySQL#1095]
**Describe the bug**
The build in pypi lack the constants directory, causing the module to be unusable

**To Reproduce**
Complete steps to reproduce the behavior:
install pymysql 1.0.3rc1

Code:

```py
>>> import pymysql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymysql/__init__.py", line 26, in <module>
    from .constants import FIELD_TYPE
ModuleNotFoundError: No module named 'pymysql.constants'

```

**Expected behavior**
import succeed

**Environment**
 - OS: linux
 - PyMySQL version: 1.0.3rc1

**Additional context**
N/A

**Comment by methane** [comment]
Thank you!
