### ISSUE TITLE
Compatibility with Django 4.2

### ISSUE THREAD

**Issue by fediev** [PyMySQL/PyMySQL#1100]
Like similar previous issues #790 or #610, this is not a bug actually. 

Django 4.2 needs mysqlclient 1.4.3 as minimum suppored version. Current PyMySQL has `1.4.0` as doctored version_info for MySQLdb compatibility. 

Is it possible for MySQLdb version to be bumped up? If so, it will be very helpful for me. Thanks.

ref. 
https://docs.djangoproject.com/en/4.2/releases/4.2/#miscellaneous
https://github.com/django/django/blob/main/django/db/backends/mysql/base.py#L33-L37

**Comment by MaartenUreel** [comment]
In the meantime, you can add this below your "install" line:
```
pymysql.install_as_MySQLdb()
pymysql.version_info = (1, 4, 3, "final", 0)
```
