### ISSUE TITLE
NameError: name 'Warning' isn't defined on Pico W

### ISSUE THREAD

**Issue by aliacn** [PyMySQL/PyMySQL#1101]
NameError: name 'Warning' isn't defined

In the project we developed with pico w, we get the following error. I try sample code on PyMysql page.

Schema:

REATE TABLE `users` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `email` varchar(255) COLLATE utf8_bin NOT NULL,
    `password` varchar(255) COLLATE utf8_bin NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
AUTO_INCREMENT=1 ;

Code:

import pymysql.cursors

# Connect to the database
connection = pymysql.connect(host='localhost',
                             user='user',
                             password='passwd',
                             database='db',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

with connection:
    with connection.cursor() as cursor:
        # Create a new record
        sql = "INSERT INTO `users` (`email`, `password`) VALUES (%s, %s)"
        cursor.execute(sql, ('webmaster@python.org', 'very-secret'))

    # connection is not autocommit by default. So you must commit to save
    # your changes.
    connection.commit()

    with connection.cursor() as cursor:
        # Read a single record
        sql = "SELECT `id`, `password` FROM `users` WHERE `email`=%s"
        cursor.execute(sql, ('webmaster@python.org',))
        result = cursor.fetchone()
        print(result)

**Expected behavior**

**Environment**
 - OS: [Raspberry Pico W]
 - Server and version: [phpMyAdmin 5.2.0]
 - PyMySQL version: 1.0.3

**Additional context**
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/lib/pymysql/__init__.py", line 27, in <module>
  File "/lib/pymysql/err.py", line 10, in <module>
NameError: name 'Warning' isn't defined

**Comment by methane** [comment]
I do not support MicroPython.
Warning is Python builtin. You need to get it by yourself.
