### ISSUE TITLE
Question related to the certificate format

### ISSUE THREAD

**Issue by SarEnderTarkanson** [PyMySQL/PyMySQL#1103]
Hi,

I would like to ask a question relevant to the SSL Certificate format.

Is it a prerequisite that the SSL certificate has to be in PEM format or can it be other than PEM?

**Comment by methane** [comment]
https://github.com/PyMySQL/PyMySQL/blob/885841f3fee416c222a75d83a81f74d3dcd71b51/pymysql/connections.py#L131
