### ISSUE TITLE
SSL Connection problem

### ISSUE THREAD

**Issue by hgoumner** [PyMySQL/PyMySQL#1106]
**Describe the bug**
I cannot establish a connection to the SQL database because of an ImportError related to a shared object library. I have tried with and without having SSL enabled.

Error message:

`ImportError: /home/hristo/miniconda3/envs/wbs_bootcamp/lib/python3.11/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: EC_POINT_get_affine_coordinates_GF2m, version OPENSSL_1_1_0`

Note: I asked someone to run the same code on a Windows machine, and it ran without errors.

**To Reproduce**
Import the pymysql module and set up a connection to the SQL server.

Schema:
No schema selected.

Code:

```py
import pymysql

USER     = 'root'
PASSWORD = open('/home/hristo/mysql_pass.txt', 'r').read()
HOST     = 'localhost'
PORT     = 3306

con = pymysql.connect(user=USER, password=PASSWORD, host=HOST, port=PORT)
# con = pymysql.connect(user=USER, password=PASSWORD, host=HOST, port=PORT, ssl_disable=True)
```

**Expected behavior**
I expect to successfully establish a connection to the database.

**Environment**
 - OS: Fedora 38, x86_64 GNU/Linux
 - Server and version: mysql  Ver 8.0.33 for Linux on x86_64 (MySQL Community Server - GPL)
 - PyMySQL version: 1.0.2

**Additional context**
Here is the full traceback:

![image](https://user-images.githubusercontent.com/11947421/235676547-84e011d0-2083-4191-b9e3-69ee712a9822.png)

**Comment by methane** [comment]
https://github.com/pyca/cryptography/issues/6712
