### ISSUE TITLE
Insert dict data that item value contain list of dict will throw TypeError.   

### ISSUE THREAD

**Issue by wil-wu** [PyMySQL/PyMySQL#1107]
**Describe the bug**
Insert dict data that item value contain list of dict will throw "TypeError: sequence item 0: expected str instance, dict found". but i don't use that item

**To Reproduce**

Schema:

```
CREATE DATABASE test;
USE test;
CREATE TABLE `test`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  PRIMARY KEY (`id`));
```

Code:

```
import pymysql

conn = pymysql.connect(host='localhost', user='root', password='123456', database='test')
cursor = conn.cursor()

data = [
    {'username': 'jack', 'age': 18, 'something': [{}, {}]},
    {'username': 'lucy', 'age': 18, 'something': [{}, {}]},
]

cursor.executemany('insert into user (username, age) values (%(username)s, %(age)s)', data)
cursor.close()
conn.close()

```

**Expected behavior**
It will not throw the TypeError.

**Environment**
 - OS: Windows
 - Server and version:  MySQL 8.0.19
 - PyMySQL version: 1.0.3

**Additional context**
Why dict item value can't be list of dict, even i don't use that item. i change value of key 'something' to "[1, 2]" , it works.

**Comment by methane** [comment]
This is intended behavior. You shouldn't pass that values you don't use in the SQL.
