### ISSUE TITLE
Duplicate Entry Error during INSERT Operation after Deleting Existing Entries

### ISSUE THREAD

**Issue by kyogom** [PyMySQL/PyMySQL#1135]
**Describe the bug**

My code below is used as part of a Flask application and handles approximately 40,000 requests per day. There is a delete_and_insert_debtors function that performs DELETE and INSERT operations. However, an issue arises during the INSERT operation where a pymysql.err.IntegrityError occurs, indicating a duplicate entry problem. The error message specifically points to a duplicated value in the debtor.PRIMARY key.

I will provide the reproduction steps, although it's important to note that this issue is not consistently reproducible. Out of the 40,000 requests, the error occurred in only 4 instances.

About the synchronization of the DELETE and INSERT statements when executed consecutively, could you confirm if they are processed synchronously?

**To Reproduce**
Complete steps to reproduce the behavior:

Schema:

```
CREATE TABLE debtors (payment_id VARCHAR(32), debtor_id VARCHAR(32), PRIMARY KEY(payment_id, debtor_id));
INSERT INTO debtors VALUES('1111','2222');
```

Code:

```py
import pymysql.cursors
from dbutils.persistent_db import PersistentDB

def get_db():
    """Return connection"""
    return PersistentDB(
            creator=pymysql,
            host="db",
            user="root",
            database="test",
            password="root",
            port=3306,
            charset='utf8mb4',
            cursorclass=pymysql.cursors.DictCursor,
            autocommit=True,
        ).connection()

def delete_and_insert_debtors(
    payment_id, debtor_ids
):
    """
        1. delete debtors 
        2. insert debtors

        NOTE: 
        CREATE TABLE debtors (payment_id VARCHAR(32), debtor_id VARCHAR(32), PRIMARY KEY(payment_id, debtor_id))
    """
    conn = get_db()
    conn.begin()
    try:
        with conn.cursor() as cursor:
            sql = """
                DELETE FROM
                    `debtors`
                WHERE
                    payment_id = %s
            """
            cursor.execute(sql, (payment_id))

            values = [[payment_id, debtor_id] for debtor_id in debtor_ids]
            sql = """
                    INSERT INTO `debtors` (
                        payment_id,
                        debtor_id
                    ) VALUES (%s, %s)
                """
            cursor.executemany(sql, values)
    except Exception as e:
        conn.rollback()
        raise e # pymysql.err.IntegrityError: (1062, "Duplicate entry '4309966-7167665' for key 'debtor.PRIMARY'")
    conn.commit()
    conn.close()
    return


def main():
    delete_and_insert_debtors('1111', ['2222']) # NOTE: Example value

if __name__ == "__main__":
    main()
```

**Expected behavior**

**Environment**
 - OS: [e.g. Windows, Linux]
   - Ubuntu 20.04.6 LTS
 - Server and version: [e.g. MySQL 8.0.19, MariaDB]
   - MySQL 8.0.28 on Amazon RDS
 - PyMySQL version: 
   - 1.0.3

**Comment by methane** [comment]
I can not reproduce it with your example. No evidence that PyMySQL bug cause your error.
Doubt your code and data. If you believe its bug of PyMySQL, make it reproducible for me.

**Comment by kyogom** [comment]
helpful.
