### ISSUE TITLE
Autocommit not functioning properly

### ISSUE THREAD

**Issue by mell0** [PyMySQL/PyMySQL#1155]
Hi,

A little prequel. I have one strange problem with this module using AWS RDS Aurora newest version 3.05.1. It has autocommit enabled by default and is almost identical ot InnoDB as you probably know.

Now the problem is that out of nowhere my process which using autocommit=True when creating a connection actually is not commiting anything when update/insert/delete or even change the database state after select. I checked and "autocommit_mode" seems to be set just right, but it's not working as intended. Even if I set the autocommit after the connection creation: con.autocommit(True) it still doesn't work as it should. When I force it using the method "_send_autocommit_mode" from "Connection" class immediately after "connect" method it starts working properly. I also found that that if I put string, instead of bool like autocommit="true" it works also, because in the method "autocommit" in "Connection" class it compares passed autocommit value vs server value and then calls "_send_autocommit_mode" and hence string will always be different to bool, it works properly.

Honestly I have used this module for quite long and never had any problem with this, but seems like new Mysql 8 versions might actually have break this functionality. 

Edit:
Checked further and autocommit on the server is set to "OFF", but the "server_status" "Connection" class variable which is assigned when calling "_get_server_information" actually returns 2 all the time even if the autocommit on the server is "OFF" by default.

**Comment by methane** [comment]
Unless you can reproduce it with Docker MySQL, it is Aurora specific issue.
Please ask support for AWS support team.

Resubmit issue if AWS support team investigate what is happning and there is something to do in PyMySQL side.

**Comment by mell0** [comment]
I already submitted issue to AWS support, just wanted to also submit issue here in case someone encounters such problem. It's rare nowadays someone to have autocommit set to OFF as default, but I guess it may happen. I will take more time and try to test if I can reproduce with docker MySQL. Thanks.
