### ISSUE TITLE
Display log exception when MySQL throws Too many connections exception.

### ISSUE THREAD

**Issue by lpe234** [PyMySQL/PyMySQL#1156]
**Describe the bug**
Display log exception when MySQL throws `Too many connections exception`.

The log:  `pymysql.err.OperationalError: (1040, 'ny connections')`

**To Reproduce**

MySQL Server
--
Product: | MySQL Community Server (GPL)
Version: | 5.7.23-log

![image](https://github.com/PyMySQL/PyMySQL/assets/7112305/ecdbe475-378d-4fd0-8184-bff36972795b)

**Comment by methane** [comment]
thank you. confirmed.
