### ISSUE TITLE
update with conditional value is impacted by pass in params

### ISSUE THREAD

**Issue by guangyuxu** [PyMySQL/PyMySQL#1161]
**Describe the bug**
update ... set short_link_update_dt = (case when short_link = 'gavin2025' then short_link_update_dt else now() end)
the condition value in the SQL is updated or cached before the SQL running

The different order of set columns causes different results.
PyMySQL==1.1.0

**To Reproduce**
data in table:
	title = 'Gavin2021'
        id=181

params: 
	{'id': 181, 'title': 'Gavin2025'}

SQL1: 
  UPDATE channel 
      SET title=%(title)s, 
         title_update_dt = (case when title = 'Gavin2025' then title_update_dt else now() end)
   WHERE id=%(id)s

  Result1: title_update_dt WAS NOT NOT NOT updated to now()

SQL2: 
  UPDATE channel 
      SET title_update_dt = (case when title = 'Gavin2025' then title_update_dt else now() end),
          title=%(title)s
   WHERE id=%(id)s

  Result2: title_update_dt WAS updated to now()

Schema:

```
CREATE DATABASE ...
CREATE TABLE ...
```

Code:

```py
import pymysql
con = pymysql.connect(...)
```

**Expected behavior**

**Environment**
 - OS: [e.g. Windows, Linux]
 - Server and version: [e.g. MySQL 8.0.19, MariaDB]
 - PyMySQL version: 

**Additional context**

**Comment by methane** [comment]
Why do you file an issue here?
Do you think it is a bug of the driver? Why do you think so?
Did you try same query from the `mysql` cli?

**Comment by methane** [comment]
no response.
