### ISSUE TITLE
AUR PKGBUILD calls for setup.py

### ISSUE THREAD

**Issue by tijko** [PyMySQL/PyMySQL#1162]
I've been running `yay -S pymysql` to install the  Arch User Repository package manager `PKGBUILD`.

Now I understand that this is downstream with their build recipe but I was looking to get some insight here.  Was there a point in time when this project used a `setup.py` file?

**Comment by methane** [comment]
I don't know. This is not a place to ask such question.

**Comment by tijko** [comment]
> This is not a place to ask such a question.

Really?  I plainly and simply asked if this project has changed its install method?  Being able to answer whether or not a `setup.py` file was used at some point in time is very reasonable question and given the context it very much tracks with "this place".

I will find my answers by other means as you appear incapable of answering basic questions not to mention minimal amount of courtesy.
