### ISSUE TITLE
pymysql.connect mistakenly throws a cryptography dependency missing error when given an incorrect sha256 password

### ISSUE THREAD

**Issue by benjaminkz** [PyMySQL/PyMySQL#1168]
**Describe the bug**

I already have pymysql[rsa] and cryptography installed in my environment. With a correct sha256 password, pymysql has no problem to build a connection to MySQL. However, it will throw a misleading dependency missing error if an incorrect sha256 password is given, instead of an OperationalError which is expected.

I rotate my mysql password periodically, and sometimes I would like to test if a previous or pending password has already been set in my codes. That's where an incorrect password might be given in my case and where I run into the above issue.

**To Reproduce**

```python
pymysql.connect(host='<host>', user='<an user with sha256_password or caching_sha2_password enabled>', password='<an incorrect sha256 password>', database='<database>')
```

```python
[ERROR] RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
Traceback (most recent call last):
  File "/var/task/mysql_rotation_multi_user.py", line 94, in lambda_handler
    set_secret(service_client, arn, token)
  File "/var/task/mysql_rotation_multi_user.py", line 202, in set_secret
    conn = get_connection(pending_dict)
  File "/var/task/mysql_rotation_multi_user.py", line 472, in get_connection
    return connect_and_authenticate(secret_dict, port, dbname, False)
  File "/var/task/mysql_rotation_multi_user.py", line 541, in connect_and_authenticate
    conn = pymysql.connect(
  File "/var/task/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/var/task/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/var/task/pymysql/connections.py", line 968, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "/var/task/pymysql/connections.py", line 1001, in _process_auth
    return _auth.caching_sha2_password_auth(self, auth_packet)
  File "/var/task/pymysql/_auth.py", line 266, in caching_sha2_password_auth
    data = sha2_rsa_encrypt(conn.password, conn.salt, conn.server_public_key)
  File "/var/task/pymysql/_auth.py", line 143, in sha2_rsa_encrypt
    raise RuntimeError(
```

**Expected behavior**
Throw an OperationalError if wrong password is given.

**Environment**
 - OS: Linux
 - Server and version: MySQL 8.0.35
 - PyMySQL version: 1.1.0

**Additional context**
This problem was also mentioned in [this stackoverflow](https://stackoverflow.com/questions/54477829/cryptography-is-required-for-sha256-password-or-caching-sha2-password) and [this issue](https://github.com/PyMySQL/PyMySQL/issues/1079).

**Comment by methane** [comment]
> I already have pymysql[rsa] and cryptography installed in my environment. With a correct sha256 password, pymysql has no problem to build a connection to MySQL. However, it will throw a misleading dependency missing error if an incorrect sha256 password is given, instead of an OperationalError which is expected.

Did you **REALLY** comfirm it? If so, please provide **COMPLETE** step to reproduce. Not one line code.

**Comment by methane** [comment]
I can not believe PyMySQL raise this error depends on password is incorrect.
PyMySQL is OSS, and you are Python programmer. Seeing this code is much faster than discussing in English.

```py
try:
    from cryptography.hazmat.backends import default_backend
    from cryptography.hazmat.primitives import serialization, hashes
    from cryptography.hazmat.primitives.asymmetric import padding


    _have_cryptography = True
except ImportError:
    _have_cryptography = False

...

    if not _have_cryptography:
        raise RuntimeError(
            "'cryptography' package is required for sha256_password or"
            + " caching_sha2_password auth methods"
        )
```

**Comment by benjaminkz** [comment]
I have pymysql[rsa] and cryptography installed. For some reasons, I can't reproduce my own problem in a fresh ubuntu environment I just created. The problem only occurs in my aws lambda environment, and with sha256 enabled, incorrect password and ssl set to none. I'm looking into it, and will let you know how it goes.

**Comment by benjaminkz** [comment]
The root cause is cryptography contains complied codes, and by default, pip will only download and compile the dependency for the architecture of the local machine. I pip installed pymysql and cryptography on my local Mac, packed them with my source codes and then deployed them in aws lambda, which is a Linux environment. That didn't work. For my use case, I should pip install cryptography with flag `--platform=manylinux2014_x86_64` and `only-binary=:all:`.
