### ISSUE TITLE
Insert uuid.uuid4()  bug

### ISSUE THREAD

**Issue by jiaohu** [PyMySQL/PyMySQL#1175]
**Describe the bug**
Here, a table with column str, and I insert `uuid` to it. it insert success. but in `mysql-connector-python` it report the error.

**To Reproduce**
Complete steps to reproduce the behavior:

Schema:

```
CREATE DATABASE test
CREATE TABLE `exp_data` (
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `filename` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `filedir` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'id',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'update time',
  `deleted_at` int DEFAULT '0' COMMENT 'deleted timestamp',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

```

Code:

```py
from repository.base import BaseModel
from repository.exp_data import ExpData
from repository.seg_data import SegData
from repository.sim_data import SimData
from repository.smooth_data import SmoothData


class NDBConn(object):
    _instance = None

    def __new__(cls, *args, **kwargs):
        if cls._instance is None:
            cls._instance = super(NDBConn, cls).__new__(cls)
        return cls._instance

    def __init__(self) -> None:
        self._engine = None
        self._config = None
        self.Session = None


    def set_mysql(self, mysql: dict):
        if self._engine is None:
            self._engine = create_engine(
                f"mysql+pymysql://{mysql['user']}:{mysql['password']}@{mysql['dbhost']}/{mysql['dbname']}?charset=utf8mb4"
            )
            BaseModel.metadata.create_all(self._engine,
                                          tables=[ExpData.__table__, SmoothData.__table__, SegData.__table__,
                                                  SimData.__table__])
            self.Session = sessionmaker(bind=self._engine)

    def session(self):
        return self.Session()


_db_cnn: NDBConn = None


def get_db() -> NDBConn:
    global _db_cnn
    if _db_cnn is None:
        _db_cnn = NDBConn()
    return _db_cnn
    
# exp_data.py
import time
from typing import Type

from sqlalchemy import Column, String, Text, func, asc
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

from repository.base import BaseModel


class ExpData(BaseModel):
    __tablename__ = "exp_data"
    uuid = Column(String(255))
    filename = Column(String(255), nullable=False, default='')
    content = Column(Text, nullable=False, default='')
    filedir = Column(String(255), nullable=False, default='')

    @classmethod
    def find_by_uuid(cls, session: Session, uuid_str: str) -> list[Type["ExpData"]]:
        """

        @param session:
        @param uuid_str:
        @return:
        """
        try:
            return session.query(cls).filter_by(uuid=uuid_str, deleted_at=0).all()
        except Exception as e:
            raise e    
    
# workform.py
class WorkForm(Ui_WorkForm, QtWidgets.QWidget):
    # send_project_widget = QtCore.Signal(CreateProjectParams)
    def __init__(self, param: CreateProjectParams, env_cfg=None, parent=None):
        super().__init__(parent)
    def remove_and_load_csv(self):
        session = get_db().session()
        print("on_start_pretreatment", session)
        try:
            ok = ExpData.exist_by_uuid_and_direct(session, self.params.get_uuid(),
                                                  self.trajectoryFileLineEdit.text())
            if ok is True:
                ExpData.delete_before(session, self.params.get_uuid())
                SmoothData.delete_before(session, self.params.get_uuid())
                SegData.delete_before(session, self.params.get_uuid())

            csv_files: list[str] = [file for file in os.listdir(self.trajectoryFileLineEdit.text()) if
                                    file.endswith('.csv')]
            exp_datas = []
            for csv_file in csv_files:
                file = QFile(os.path.join(self.trajectoryFileLineEdit.text(), csv_file))
                file.open(QIODevice.OpenModeFlag.ReadOnly)
                exp_data = ExpData(
                    uuid=self.params.get_uuid(),
                    filename=csv_file,
                    content=file.readAll().data(),
                    filedir=self.trajectoryFileLineEdit.text()
                )
                exp_datas.append(exp_data)
            session.add_all(exp_datas)
            session.commit()
            temp2 = ExpData.find_by_uuid(session, self.params.get_uuid())
            print("innner", temp2)
        except Exception as e:
            session.rollback()
            QMessageBox.critical(self, "error", f"Error during database operation: {e}")
            return
        finally:
            session.close()
    def on_start_pretreatment(self):
        self.startBtn.setEnabled(False)
        self.remove_and_load_csv()
```

**Expected behavior**
When I click the `start` button, it will execute `on_start_pretreatment` and then I insert batch data to mysql. After insert, I query them Immediately. I expected to get what I inserted.

**Environment**
 - OS: MacOs
 - Server and version: Ver 14.14 Distrib 5.7.24, for osx10.9 (x86_64) using  EditLine wrapper
 - PyMySQL version:  Immediately

**Additional context**
I found this problem in my project, and I  switch connect tool to find it. detail in [here](https://github.com/sqlalchemy/sqlalchemy/discussions/11568)

**Comment by methane** [comment]
Your code is not minimum and not runnable.
And this project is not mysql-connector-python.

**Comment by jiaohu** [comment]
> Your code is not minimum and not runnable. And this project is not mysql-connector-python.

but you have the fault compare to mysql-connector-python.

**Comment by jiaohu** [comment]
> Your code is not minimum and not runnable. And this project is not mysql-connector-python.

I have add two test, you can run it

**Comment by methane** [comment]
> but you have the fault compare to mysql-connector-python.

I don't understand this.
Again, this project is not mysql-connector-python. Do not report issue of it.

> I have add two test, you can run it.

No. Reproducible example includes:

1. Start container
2. Start MySQL in container
3. Create virtual environment
4. Install minimum dependencies (SQLAlchemy shouldn't be needed)
5. Write all code

And you should reproduce it from scratch by reading report you wrote to confirm it is really reproducible. (e.g. `from repository.base import BaseModel` without `repository.py`.)

**Comment by jiaohu** [comment]
This issue is only want to report that PyMsql insert UUID ok , but when I query with same object, It can not search the results.
And I check it with mysql-connector-python, it report error when i want to insert the object UUID.

Don't you think it's strange？ If you can insert UUID, why can not search with it?

**Comment by methane** [comment]
> Don't you think it's strange？

Don't. PyMySQL doesn't support UUID.

> If you can insert UUID, why can not search with it?

Why don't you investigate it by yourself?

* What records in the table after insert?
* What query SQLAlchemy execute?

You can check them.

**Comment by jiaohu** [comment]
I execute, It insert ok , but when I query it Immediately，i get an empty result
![image](https://github.com/PyMySQL/PyMySQL/assets/13608671/06a8ca0c-8cda-482a-bf3d-a3372088c810)

<img width="879" alt="image" src="https://github.com/PyMySQL/PyMySQL/assets/13608671/0849d46e-a2eb-4e7b-afa5-928398c8ecb1">

**Comment by methane** [comment]
You don't check what SQL is executed here.

```py
        row = ExpData.find_by_uuid(self.session, tttt)
```

**Comment by methane** [comment]
You should add `echo=True` option to create_engine().

https://docs.sqlalchemy.org/en/20/core/engines.html#engine-creation-api

**Comment by jiaohu** [comment]
ok, I find the fault. But why not report error when insert UUID?
I think it may be a good way. 
Or other method to avoid this mistake
![image](https://github.com/PyMySQL/PyMySQL/assets/13608671/b14f1e3c-4043-4453-8ad4-06bcd17085fc)

**Comment by jiaohu** [comment]
for when people insert ok，it is generally to think that can get result with same object

**Comment by methane** [comment]
Note that the issue is caused by your misuse of SQLAlchemy.
There is no problem at PyMySQL side. If you didn't use SQLAlchemy, you will get what you expected.
