### ISSUE TITLE
pyMySQL Error (no module called PyMySQL)

### ISSUE THREAD

**Issue by alanmathew671** [PyMySQL/PyMySQL#187]
While running test scripts via Robot Framework Ride Tool, it was unable to connect to database as there was an error occuring called "no module called PyMySQL". 
This issue occured when PyMySQL 0.6 was installed.

In order to the resolve the issue, version 0.6 was uninstaled and version 0.5 PyMySQL was installed though:

pip install PyMySQL==0.5

**Comment by pjandrews** [comment]
I'm seeing the problem with Anaconda and python 3. I think it can be resolved by restarting the computer. But then it comes back a few days later. I'm using windows 7.

(p3) c:\python_scripts\GRAMR\2>python GRAMR.py
Traceback (most recent call last):
  File "C:\python_scripts\GRAMR\2\Create_Index_MTP_auto.py", line 11, in <module>
    import pymysql
ImportError: No module named pymysql
  File "C:\python_scripts\GRAMR\2\Compile_report.py", line 294
    print("Missing {} column, cannot process VC data for {} {}".format(column,build,op), file = text_file)
                                                                                              ^
SyntaxError: invalid syntax

(p3) c:\python_scripts\GRAMR\2>python -m pip install --upgrade pymysql
Collecting pymysql
  Downloading PyMySQL-0.7.7-py3-none-any.whl (77kB)
    100% |################################| 81kB 5.3MB/s
Installing collected packages: pymysql
  Found existing installation: PyMySQL 0.7.6
    Uninstalling PyMySQL-0.7.6:
      Successfully uninstalled PyMySQL-0.7.6
Successfully installed pymysql-0.7.7

(p3) c:\python_scripts\GRAMR\2>python GRAMR.py
Traceback (most recent call last):
  File "C:\python_scripts\GRAMR\2\Create_Index_MTP_auto.py", line 11, in <module>
    import pymysql
ImportError: No module named pymysql
  File "C:\python_scripts\GRAMR\2\Compile_report.py", line 294
    print("Missing {} column, cannot process VC data for {} {}".format(column,build,op), file = text_file)
                                                                                              ^
SyntaxError: invalid syntax

(p3) c:\python_scripts\GRAMR\2>python
Python 3.5.1 |Continuum Analytics, Inc.| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymysql
>>> quit()

(p3) c:\python_scripts\GRAMR\2>python GRAMR.py
Traceback (most recent call last):
  File "C:\python_scripts\GRAMR\2\Create_Index_MTP_auto.py", line 11, in <module>
    import pymysql
ImportError: No module named pymysql
  File "C:\python_scripts\GRAMR\2\Compile_report.py", line 294
    print("Missing {} column, cannot process VC data for {} {}".format(column,build,op), file = text_file)
                                                                                              ^
SyntaxError: invalid syntax
