### ISSUE TITLE
converter for datetime objects doesn't handle timezones

### ISSUE THREAD

**Issue by exarkun** [PyMySQL/PyMySQL#219]
pymysql.converters.escape_datetime ignores the timezone of the datetime object passed to it.

The result is that two datetime instances that represent the same time but have different timezones end up looking like two different times instead.  For example:

```
>>> pymysql.converters.escape_datetime(datetime.datetime.now(pytz.timezone("US/Eastern")))
"'2014-03-07 11:16:07'"
>>> pymysql.converters.escape_datetime(datetime.datetime.now(pytz.timezone("UTC")))
"'2014-03-07 16:16:09'"
```

Though I only evaluated these two expressions two seconds apart the resulting values appear to be four hours and two seconds apart.

**Comment by methane** [comment]
Application should convert application's datetime with tz to database's (naive) datetime.
If you don't want to do it manually, you should use some wrapper.  Don't use this library directly.
