### ISSUE TITLE
how to deal with connections commit()/close()

### ISSUE THREAD

**Issue by bobgrigoryan** [PyMySQL/PyMySQL#237]
when trying to understand whether to use "autocommit=True" or call commit() manually
when "autocommit=False" I couldn't understand the following behavioral difference:
1. in case of manually creating/closing connections commit() should be called explicitly in the client application before connection.close().
2. in case of using connection in "with" statement commit() is always called, regardless of autocommit setting.

considering behavior (2) isn't it logical to call commit() inside connection.close() method? or maybe I haven't understand the overall commit logic well.

**Comment by methane** [comment]
@bobgrigoryan Yes. If application handles commit/rollback, `with` should not be used.
