### ISSUE TITLE
Check if results exist after execute() without having to call fetch____()

### ISSUE THREAD

**Issue by NucleaPeon** [PyMySQL/PyMySQL#239]
My problem is as follows.

I am retriving the row results like this:

    cursor.execute(sql)
    for field1, field2, field3 in cursor.fetchall():
        # do things here

The problem is when fetchall() returns no rows, meaning I get a None result. None is not iterable.

The same issue can be repeated by running this in a python interpreter:

    a, b, c = None

Could you implement an official method such as hasResults() that returns True if the execute() will return a non-NoneType value? 
Does this clash with standards or is it better to use a try/except clause?
I don't like the idea of caching values or calling the query more than once.

Let me know if this is plausible, maybe I'm doing it wrong. Thanks!

**Comment by methane** [comment]
cursor object is iterable, already.
