### ISSUE TITLE
"Client does not support authentication protocol requested by server; consider upgrading MySQL client" when attempting to authenticate over sockets

### ISSUE THREAD

**Issue by oconnore** [PyMySQL/PyMySQL#243]
Using: http://dev.mysql.com/doc/mysql-security-excerpt/5.5/en/socket-authentication-plugin.html

**Comment by grooverdan** [comment]
fixed in #353

**Comment by nicklasb** [comment]
The PR has not been merged yet, so this might be a bit premature.

**Comment by grooverdan** [comment]
its merged now.

**Comment by nicklasb** [comment]
Good stuff!
