### ISSUE TITLE
cursor.callproc response is slowly

### ISSUE THREAD

**Issue by zhizhongzhiwai** [PyMySQL/PyMySQL#249]
when i call cursor.callproc('proc_register', username, password, ip, deviceid, parent, default_coins) , the server response is so slowly.
i think the mysql set variable operation waste time.
can you fix it: set @proc_name_variable; @proc_name_variable2 ....

zhizhongzhiwai@126.com hesen

**Comment by methane** [comment]
Close since no reply for long time.
