### ISSUE TITLE
AttributeError: 'Connection' object has no attribute 'store_result'

### ISSUE THREAD

**Issue by dnozay** [PyMySQL/PyMySQL#251]
I'm trying to use `pymsql` as a drop-in replacement for `MySQLdb`
see http://mysql-python.sourceforge.net/MySQLdb.html

```python
from pymysql import install_as_MySQLdb
# install_as_MySQLdb() # fails.
db = MySQLdb.connect(db='test')
db.query("""SELECT spam, eggs, sausage FROM breakfast
         WHERE price < 5""")
res = db.store_result()
rows = res.fetch_row(how=1, maxrows=0)
```

however, i'm getting tracebacks in `db.store_result()`

**Comment by astawiarski** [comment]
I agree with @dnozay - this library doesn't seem to be fully compatible, drop-in replaced for MySQLdb. I tried using it as replacement in Trac and the same error occurred: `AttributeError: 'Connection' object has no attribute 'store_result'`

This should either be highlighted in documentation or, even better, made compatible.

**Comment by methane** [comment]
> this library doesn't seem to be fully compatible,

Yes.  No one says "fully".

> drop-in replaced for MySQLdb.

PyMySQL is drop-in replacement when you use APIs defined in DB API 2.0 (PEP 294).
For example, using same placeholder and provides `DictCursor`.

> I tried using it as replacement in Trac and the same error occurred

Why don't you report issue to Trac?

> This should either be highlighted in documentation 

I'll do it.

> or, even better, made compatible.

No, I won't.  I wan't to **reduce** supported API and keep simple.  Don't want to make it more complicated.

**Comment by KipIngram** [comment]
The store_result method seems like a pretty darn fundamental part of using MySQL to me.  I just ran into the same problem.
