### ISSUE TITLE
Multiprocessing pool - multiple cursor limitation

### ISSUE THREAD

**Issue by iamtennislover** [PyMySQL/PyMySQL#267]
Question:

From the http://legacy.python.org/dev/peps/pep-0249/#threadsafety, I want to know first is pymysql threadsafe = 3 (Threads may share the module, connections and cursors)?

Also, if I try to run multiple cursors in parallel (using multiprocessing.Pool) for one connection, what is the limitation of the no. of cursors or is it dependent upon the server?

**Comment by kadnan** [comment]
@methane can you give example how to use it?

**Comment by methane** [comment]
Here is issue tracker, not forum.
I'm neither free tech support or teacher.
