### ISSUE TITLE
Can't connect to MySQL server Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by zappjones** [PyMySQL/PyMySQL#269]
I've been having an issue recently with hiccups on the MySQL server that is eventually causing this error.

```
(2003, 'Can\'t connect to MySQL server on \'<connection>\' ((2013, "Lost connection to MySQL server during query (error(104, \'Connection reset by peer\'))"))')
Callstack:
    File "/usr/lib64/python2.7/site-packages/pymysql/connections.py", line 818, in _connect
        2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e))
    File "/usr/lib64/python2.7/site-packages/pymysql/connections.py", line 626, in __init__
        self._connect()
```

It looks like the error is generated from the tcp keep alive time since it always happens after 7200 seconds but I'm wondering why the connection isn't able to connect?

Is there any variables I should look at on the unix box or the MySQL server that could help the debugging process?

Thanks!

**Comment by michalgasek** [comment]
I'm experiencing this mysterious issue as well occasionally. PyMySQL is however connecting to SphinxSearch, not MySQL server.

![screen shot 2015-01-16 at 18 33 18](https://cloud.githubusercontent.com/assets/1117361/5780886/5e047f78-9dae-11e4-9834-dd388078f34a.png)

**Comment by michalgasek** [comment]
@zappjones Do you use any connection pooling to MySQL or possibly patch PyMySQL with Gevent/Eventlet?

**Comment by bloodywing** [comment]
Yes what I did was using Circuits Timer class with a callback function that simply sends the SELECT 1 query. https://gist.github.com/bloodywing/83c4bfa38c8ce5724fb2 see my example. I'm pretty sure this is possible in Gevent or Eventlet too. But can't give you an example for it Except for this: http://stackoverflow.com/questions/13206798/somethig-like-cron-timer-in-gevent

**Comment by zappjones** [comment]
Hey all -

I was able to track down my issue with the help of amazon engineers.
We use an RDS as our backend MySQL server and we were sending too many connections for the RDS to handle.

The default somaxconn value for an amazon RDS instance is 128 and they bumped it up to 1024 for us.

After the change we've been good.

Here's a little bit more explanation:

> /proc/sys/net/core/somaxconn: Limit of socket listen() backlog, known in userspace as SOMAXCONN. Defaults to 128. The value should be raised substantially to support bursts of request. For example, to support a burst of 1024 requests, set somaxconn to 1024.

https://computing.llnl.gov/linux/slurm/high_throughput.html
