### ISSUE TITLE
gevent killed greenlet causes pymysql to continue on the broken connection

### ISSUE THREAD

**Issue by lxyu** [PyMySQL/PyMySQL#275]
Bug reported in the sqlalchmey issue tracker but from @zzzeek's point of view, it's pymysql side bug.

This will cause a serious bug "transaction partial succeeding" when greenlet timed out and killed by gevent.

Original issue here: https://bitbucket.org/zzzeek/sqlalchemy/issue/3258/a-gevent-killed-greenlet-causes-pymysql

Reproduce script:
- https://gist.github.com/lxyu/4e14021e4bae7bc26da7
- https://gist.github.com/zzzeek/947337f44d70fac537be

**Comment by wooparadog** [comment]
After some experiment, the reason this happens is that `gevent.Timeout` is actually a `BaseException` which is not so often handled by any libraries. 

The temporary fix is very simple: https://gist.github.com/a9755c0a5f256cd533c590dd5369ae1e

with this modified version of pymysql, the problem won't happen with the reproduction script listed in the issue description.

**Comment by Jsmilemsj** [comment]
> After some experiment, the reason this happens is that `gevent.Timeout` is actually a `BaseException` which is not so often handled by any libraries.
> 
> The temporary fix is very simple: https://gist.github.com/a9755c0a5f256cd533c590dd5369ae1e
> 
> with this modified version of pymysql, the problem won't happen with the reproduction script listed in the issue description.
> 
> edit:
> 
> There should be a nicer way to handle this exception. But the cause is `gevent.Timeout` being a `BaseException`.

The link has failed, could you update it?
