### ISSUE TITLE
Allow executemany to cache results from multiple selects

### ISSUE THREAD

**Issue by csojinb-picwell** [PyMySQL/PyMySQL#281]
Currently, the results are just overwritten by the next `execute`. It would be nice to be able to run several similar selects and fetch the results from them all together.

**Comment by methane** [comment]
`.executemany()` is for building insert statement like "INSERT .. INTO .. VALUES (a1, b1), (a2, b2), ...(an, bn)"

When you want query multiple select statement, Python loop is enough.

```python
results = []
for p in params:
    cur.execute(query, p)
    results.extend(cur.fetchall())
```
