### ISSUE TITLE
KeyboardInterrupt exception forces finishing of query

### ISSUE THREAD

**Issue by mathieulongtin** [PyMySQL/PyMySQL#287]
When you hit ctrl-C in the middle of a query, the cursor's `__del__` method calls cursor.close(), which tries to finish the current query. So if you hit ctrl-C in the middle of a long query, it tries to grab all the results from that query rather than killing it.

**Comment by mathieulongtin** [comment]
I'm not sure how to handle that. I think maybe removing the __del__ that are all over the place. If someone drops an unfinished cursor, they shouldn't have any guarantee that the connection will keep working. The only thing is the connection should probably send a COM_QUIT before closing the socket just to be polite.

**Comment by zzzeek** [comment]
it's very standard and largely expected that when a Python object is GC'ed, it leaves the program in a stable state and that remaining, non-GC'ed objects continue to work correctly (all DBAPIs do this)   If the connection is still present, it definitely should still be in a working state.   If your program is trapping ctrl-C and is allowing the connection to remain usable, it doesn't have much option here.   OTOH, if your program is exiting out, the connection itself will be closed and there wont be anything left to read by the cursor (I suppose if that's not happening, PyMySQL could replace the use of __del__ with weakref callbacks, which are much more controllable).

Maybe you need to catch KeyboardInterrupt and call connection.close(), if you're wanting the program to catch ctrl-C and continue executing without any delay.

**Comment by mathieulongtin** [comment]
That's the problem, I do catch the exception, but my catcher never gets executed, it's stuck in the close method of the cursor. 

—
Mathieu Longtin
514-803-8977

**Comment by zzzeek** [comment]
and its the `__del__()`?  like, if you refer to the cursor in the KeyboardInterrupt, the reference stays, `__del__()` doesn't get called, and it completes quickly?  this doesn't really sound like a possible thing.  Have any test code illustrating this?

**Comment by mathieulongtin** [comment]
Ok, let me qualify that. This is only an issue with `SSCursor`. Default `Cursor` behaves as expected.

I created some sort of test bed for the various combinations here: https://gist.github.com/mathieulongtin/7ad1227285ebaa35a70e. Just change the SQL to something slow.

If I run the code with just --stream, and I hit ctrl-C after a few seconds, I get this:

```
$ python ./pymysql_ctrlc_testbed.py --stream
Got 1081 rows Caught: KeyboardInterrupt()
Did exception get caught?
Got 1081 rows
^CException KeyboardInterrupt in <bound method SSCursor.__del__ of <pymysql.cursors.SSCursor object at 0xb73d50>> ignored
Done
```

Note that I hit ctrl-C once more between `Got 1081 rows` and `Done`. Otherwise, it would have downloaded a few million rows into /dev/null before finishing.

By contrast, if you close the db before the cursor is cleaned up, you get this:

```
$ python ./pymysql_ctrlc_testbed.py --stream --close-db
Got 1771 rows Caught: KeyboardInterrupt()
Did exception get caught?
Got 1771 rows
Closing db
Exception AttributeError: AttributeError("'NoneType' object has no attribute 'read'",) in <bound method SSCursor.__del__ of <pymysql.cursors.SSCursor object at 0x1041d50>> ignored
Done
```

**Comment by zzzeek** [comment]
so from a MySQL protocol perspective, as far as what MySQLdb would do, this is equivalent to a [mysql_use_result](http://dev.mysql.com/doc/refman/5.0/en/mysql-use-result.html):

> When using mysql_use_result(), you must execute mysql_fetch_row() until a NULL value is returned, otherwise, the unfetched rows are returned as part of the result set for your next query. The C API gives the error Commands out of sync; you can't run this command now if you forget to do this! 

So pretty much, in order to keep the connection valid, all the remaining rows have to be fetched.   if you want to kill it off, you should maintain the reference to the cursor in the keyboardinterrupt and close the connection.

**Comment by zzzeek** [comment]
OK so yes the GC on my end isn't in the "catch", its when the program is actually trying to exit.   it seems like cursor.__del__ is happening before connection.__del__.  and if you do actually call connection.close() in the catch, then you get this:

    Exception AttributeError: AttributeError("'NoneType' object has no attribute 'read'",) in <bound method SSCursor.__del__ of <pymysql.cursors.SSCursor object at 0x1021cca50>> ignored

so there is definitely some sloppy cleanup happening here.   i want to see if i can use a different cleanup routine here.

**Comment by mathieulongtin** [comment]
That's probably a decent solution. In fact, I think that's what MySQLdb does.
