### ISSUE TITLE
What about threatsafety?

### ISSUE THREAD

**Issue by byaka** [PyMySQL/PyMySQL#289]
original mysqldb implement only level 1 and cant share connections over threads. Creating connection for every thread it's massive overhead. Using Pool for this - hard thing when working over jsonrpclib.
What about this module?

**Comment by zzzeek** [comment]
have you tried threading.Lock ?  why force the overhead of mutexing on everyone?

**Comment by byaka** [comment]
For example we have server, and some his methods use mysql queries. Clients work with this server over rpc protocol.
Threading.lock, when many (i'm say only about 5-10 clients per second) work with him, transform him to turn-based strategy :( and it's break all profit..

**Comment by zzzeek** [comment]
the PyMySQL connection uses a single socket.   concurrent access across threads on this socket would have to be mutexed by threading.Lock (if that's what you mean by "turn-based", then yes, this is "turn-based").    It could be provided via wrappers for Connection and Cursor, but IMO they would be optional, and you can of course make these yourself ahead of time (subclass and/or wrap Connection / Cursor and supply cursorclass to the Connection).

**Comment by byaka** [comment]
Thx for ansver.
What about Greenlet-safely?

**Comment by methane** [comment]
I believe gevent is same to threading:  You cannot use single connection from multiple greenlet without synchronization like `gevent.lock.RLock`.

**Comment by methane** [comment]
@byaka May I close this issue?
If you have another question, please post it to [PyMySQL Users Group](https://groups.google.com/forum/#!forum/pymysql-users)
