### ISSUE TITLE
Drop Python 2.6 support

### ISSUE THREAD

**Issue by methane** [PyMySQL/PyMySQL#301]
* Remove unittest2 dependency
* Remove [this code](https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L63-L79)

**Comment by pdunnigan** [comment]
what is the reasoning behind dropping py2.6 support? 
it's the default python version on the RHEL/CentOS 6.x based linux which is still in a lot of enterprises.

**Comment by methane** [comment]
Python core developers doesn't support Python 2.6 anymore.
If you want to use PyMySQL from PyPI, why don't you install Python 2.7 from source, pyenv, pythonz or miniconda?  It should be very easy.

Many Python projects are disturbed from "Support Python 2.x because it is supported in RHEL/CentOS 5.x/6.x".  It is one reason why moving Python 3 is so slow. 

I think default Python of Debian/RHEL/CentOS is for software distributed by their repository.
New version of software on PyPI should not be restrict from too old Python.

**Comment by pdunnigan** [comment]
Well old but prevalent in enterprises still.

That is fine we can make our version dependencies different for those 
platforms.

**Comment by methane** [comment]
Honestly saying, it's easy to keep Python 2.6 support.

* Instead of removing unittest2, I can use unittest2 on every Python versions.
* [There are only 20 lines](https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L63-L83) for Python 2.6 other than tests.

So I'll keep Python  2.6 support as is for 0.7.

But I don't recommend using Python 2.6 since it's not secure without distribution specific customize, and I don't run tests on CentOS 6 or other old distributions.

When an issue on CentOS 6 is posted, I may ignore it if I can't reproduce it on newest Ubuntu LTS.
