### ISSUE TITLE
'module' object has no attribute 'wrap_self'

### ISSUE THREAD

**Issue by arprasad** [PyMySQL/PyMySQL#308]
I was using Python2.7.5 and tried to connect to MySql5.6 using ssl_ca authentication.
pymysql.connect(host=HOST,user=USERNAME,passwd=PASSWORD,db=SCHEMA, ssl={'ca':ssl_file})

This has given the following exception:
 File "PATH\pymysql\connections.py", line 832, in _send_authentication
   self.socket = ssl.wrap_self.socketet(self.socket, keyfile=self.key,
AttributeError: 'module' object has no attribute 'wrap_self'

I could fix it by replacing the call to ssl.wrap_self.socketet by ssl.wrap_socket

Hope you fix the same.

**Comment by methane** [comment]
What version do you use?

https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L995

https://github.com/PyMySQL/PyMySQL/commit/a6fad0fd467d0d7eabca41c848384b4851ec7b48
