### ISSUE TITLE
problem with connect

### ISSUE THREAD

**Issue by byaka** [PyMySQL/PyMySQL#311]
I'm try to replace mysqldb in my project with this cool implementation.
but when i'm try, i have strange error.
I'm only change import and when i'm try to connect to db, i have this
```python
  File "/var/python/libs/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/var/python/libs/pymysql/connections.py", line 644, in __init__
    self._connect()
  File "/var/python/libs/pymysql/connections.py", line 866, in _connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
```

when i'm change import back (to mysqldb) all work fine.

**Comment by methane** [comment]
What version do you use?
Could you try '127.0.0.1' instead of 'localhost'? (since IPv6 may be problem).

**Comment by byaka** [comment]
So strange. When i change localhost to 127.0.0.1, i have this error (111 connection refused) on both libs (pymysql and mysqldb).
Any ideas?

**Comment by cactus** [comment]
@byaka mysqldb was likely using a local unix socket in that case (it tries automatically when host string is "localhost").

You need to make your server listen on a tcp socket.

**Comment by byaka** [comment]
@cactus big thx!
Sorry for this stupid ticket
