### ISSUE TITLE
With Django and .cnf files, testing empties non-testing database

### ISSUE THREAD

**Issue by RossBrunton** [PyMySQL/PyMySQL#312]
Steps to reproduce:
- Create a virtualenv (I used python 3.4)
- Install pymysql and django into this virtualenv
- Create a django project (django-admin.py startproject myproject)
- Add the following to myproject/myproject/__init__.py:
```python
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except:
    pass
```
- Change the database settings in myproject/myproject/settings.py to the following:
```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS':{
            'read_default_file': './db.cnf',
        },
    }
}
```
- Create a db.cnf file in myproject, I used the following:
```
[client]
database = some_database
user = some_user
default-character-set = utf8
```
- Create a super user (manage.py createsuperuser)
- Use manage.py dbshell to verify that the auth_user table isn't empty
- Run tests (manage.py test)
- Check auth_user isn't empty again

Testing is supposed to use a different database, which is then deleted after the tests are complete, I'd imagine that using the config file stops however Django is switching to the test database.

If I don't use the read_default_file, it works fine.

**Comment by methane** [comment]
> Testing is supposed to use a different database

Which database?

>  I'd imagine that using the config file stops however Django is switching to the test database.

I can't parse this English sentence.
Please write down like talking to five age kid knowing Python and MySQL protocol.

**Comment by RossBrunton** [comment]
When doing tests, it creates a database named "test_whatevertheproddatabaseis" and switches to that. Details are on https://docs.djangoproject.com/en/1.9/topics/testing/overview/#the-test-database

And yeah, that sentence is really bad. I meant that switching the database has no effect when the credentials are specified by a config file.

For the record, the sentence was supposed to be read like "I'd imagine that using the config file stops (however Django is switching to the test database.)". Which is very confusing, sorry!

**Comment by methane** [comment]
> I meant that switching the database has no effect when the credentials are specified by a config file.

Which is credential?

```
[client]
database = some_database
user = some_user
default-character-set = utf8
```

**Comment by methane** [comment]
Since I'm not a Django user, I still don't understand what's the problem of PyMySQL.
Any small example program without Django which describe your problem?

**Comment by RossBrunton** [comment]
I just tried to reproduce it using a new Django project, both using the latest and the one originally used, and the error doesn't seem to occur any more. I think the updates over the past year probably fixed it, so I'll just close this issue.
