### ISSUE TITLE
TypeError: %i format: a number is required, not str

### ISSUE THREAD

**Issue by MartinThoma** [PyMySQL/PyMySQL#329]
The code

```python
import pymysql
connection = pymysql.connect(host='localhost',
                             user='user',
                             passwd='passwd',
                             db='db')
cursor = connection.cursor()

sql = ("UPDATE `users` SET `email`= 'maxmustermann@email.de' "
       "WHERE `id` = %i LIMIT 1")

try:
    cursor.execute(sql, 42)
    connection.commit()
finally:
    connection.close()
```

gives

```text
Traceback (most recent call last):
  File "/home/moose/GitHub/PyMySQL/test.py", line 12, in <module>
    cursor.execute(sql, 42)
  File "/home/moose/GitHub/PyMySQL/pymysql/cursors.py", line 132, in execute
    query = query % self._escape_args(args, conn)
TypeError: %i format: a number is required, not str
```

This should not happen, as 42 is obviously an integer, not a string.

**Comment by methane** [comment]
PyMySQL convert all objects including integer to formatted and quoted string.
You can use only `%s` or `%(name)s` as placeholder.

**Comment by tomkcook** [comment]
Is there some solid thinking behind this?  How are you supposed to do queries like this one:

     select * from users limit %d;

It seems its not possible - `limit` won't accept a string and there's no way to use a number as a placeholder.  Why exactly is it necessary to sanitize numbers before they go into the query?

**Comment by methane** [comment]
Since Python is not PHP.
Python distinguish string and integer values.

**Comment by methane** [comment]
php:
```
php > var_dump(sprintf("%d", "42"));
string(2) "42"
```

Python
```
>>> "%d" % ("42",)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: %d format: a number is required, not str
```

I prefer Python over PHP.

**Comment by tomkcook** [comment]
Well, quite.  I'm not exactly sure why PHP is relevant here?  My question is, why does pymysql insist on converting everything to a string before it goes into the query?  You might well prefer Python; this is not exactly Pythonish behaviour.

There are some places, such as the example I gave above, where a string is not acceptable in the query.  How can I do this sort of query with pymysql?  It seems the only way is this:

    sql = 'select * from users limit %d' % (10,)
    cursor.execute(sql)

But that's encouraging exactly the sort of sql-injection-vulnerable code that parameterised queries are supposed to avoid.

**Comment by methane** [comment]
> Well, quite. I'm not exactly sure why PHP is relevant here?

Sorry, I may misunderstand what you said.
`cursor.execute("SELECT * FROM users limit %s", (10,))` is valid way.

**Comment by tomkcook** [comment]
I see.  Thanks.

**Comment by ExplodingCabbage** [comment]
> `cursor.execute("SELECT * FROM users limit %s", (10,))` is valid way.

No it isn't; MySQL won't accept a quoted limit, which this approach produces.

PyMySQL should allow the `%i` placeholder to be used in order to make this limitation less irritating.

**Comment by methane** [comment]
TRY BEFORE CLAIM!!!!

**Comment by methane** [comment]
> No it isn't; MySQL won't accept a quoted limit, which this approach produces.

`cursor.execute("limit %s", (10,))` produces `"limit 10"`.
You must notice that if you tried.

When saying "No" to someone, you should check yourself before.

**Comment by ExplodingCabbage** [comment]
You're correct; I must've had some stupid other bug in the code where I thought I'd observed this. Apologies.
