### ISSUE TITLE
TypeError: unsupport operand type(s) for %: 'bytes' and 'tuple'

### ISSUE THREAD

**Issue by spieled** [PyMySQL/PyMySQL#335]
TypeError: unsupport operand type(s) for %: 'bytes' and 'tuple'

PyMySQL version 0.6.6
file: cursors.py
line: 132
code: query = query % self._escape_args(args, conn)

When I check the value of query, it is b"SHOW VARIABLES LIKE 'sql_mode'".
When I check the value of args, it is ().
Actually, query is bytes from the begining of this function.

And I Use python-3.3.6, flask and SQLAlchemy

**Comment by methane** [comment]
You should use unicode string for query.

**Comment by spieled** [comment]
when use PyMySQL@0.6.6 with python3, maybe there is a problem in cursors.py line 132.
I solve this problem by change
"""
query = query % self._escape_args(args, conn)
"""
to
"""
if type(query) == bytes:
    query = query.decode() % self._escape_args(args, conn)
else:
    query = query % self._escape_args(args, conn)
"""

**Comment by spieled** [comment]
not good,
so change to
"""
try:
    query = query % self._escape_args(args, conn)
except:
    query = query.decode() % self._escape_args(args, conn)
"""

and now , it handle py2 and py3, as well as b'' or u''

**Comment by methane** [comment]
Why don't you unicode query?

**Comment by methane** [comment]
"It works for me" doesn't means "It's right design".
PyMySQL accepts string as query.
On Python 2, string is both of bytes and unicode.
On Python 3, only str (unicode) is string.

**Comment by spieled** [comment]
Thank you! I am so shamed. I've handled my problem use unicode.
