### ISSUE TITLE
constants.CR is missing

### ISSUE THREAD

**Issue by maxtepkeev** [PyMySQL/PyMySQL#336]
Hi,

[constants.CR](https://github.com/farcepest/MySQLdb1/blob/master/MySQLdb/constants/CR.py) module is missing in pymysql, while it exists in MySQLdb.

That makes some libraries, e.g. [SQLObject](http://www.sqlobject.org), unusable with pymysql.

**Comment by methane** [comment]
I want to copy it from MySQL or MySQL-python.
But PyMySQL is under MIT and both of MySQL and MySQL-python are under GPL.
Please wait...
