### ISSUE TITLE
connect() hangs indefinitely if MySQL server opens socket connection but doesn't respond.

### ISSUE THREAD

**Issue by ic3man5** [PyMySQL/PyMySQL#338]
connect() hangs indefinitely if MySQL server opens socket connection but doesn't respond.

Nothing seems to work besides commenting out the following line (831) in connections.py:

Hang happens in ``` self._get_server_information() ```

working:
```
            #sock.settimeout(None)
            sock.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)
            if self.no_delay:
                sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
            self.socket = sock
            self._rfile = _makefile(sock, 'rb')
            self._get_server_information()
```

Program returns:
```
2013: Lost connection to MySQL server during query (timed out) 

Exception Type: <class 'pymysql.err.OperationalError'>
```

not working:
```
            sock.settimeout(None)
            sock.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)
            if self.no_delay:
                sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
            self.socket = sock
            self._rfile = _makefile(sock, 'rb')
            self._get_server_information()
```

Same thing happens with my ssh connection (ssh is also hanging) unless I specify the -o ConnectTimeout option for SSH.

**Comment by ic3man5** [comment]
Addition information:

Tried:
``` socket.setdefaulttimeout(5) ```
and
``` connect_timeout=5 kwarg in connect() ```

```
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.


DATA
    BINARY = DBAPISet({249, 250, 251, 252})
    DATE = DBAPISet({10, 14})
    NULL = 'NULL'
    NUMBER = DBAPISet({0, 1, 3, 4, 5, 8, 9, 13})
    ROWID = DBAPISet()
    STRING = DBAPISet({253, 254, 247})
    TIME = DBAPISet({11})
    TIMESTAMP = DBAPISet({12, 7})
    __all__ = ['BINARY', 'Binary', 'Connect', 'Connection', 'DATE', 'Date'...
    apilevel = '2.0'
    paramstyle = 'format'
    threadsafety = 1
    version_info = (1, 2, 2, 'final', 0)

VERSION
    0.6.6.None

FILE
    c:\python34\lib\site-packages\pymysql\__init__.py
```

**Comment by methane** [comment]
> connect() hangs indefinitely if MySQL server opens socket connection but doesn't respond.

Why this happens?

**Comment by ic3man5** [comment]
I'm not 100% sure, I believe since the server is a VM under virtualbox its sometimes crashing. I believe I fixed it server side but it takes a long time to resurface (up to a month or more).

Is there a reason for ``` sock.settimeout(None) ``` ? Seems like this code serves no purpose but to cause blocking IO (socket read/write) to hang forever.

Only thing I found regarding this is https://github.com/PyMySQL/PyMySQL/issues/136

**Comment by methane** [comment]
Since query may take several hours.
For example, libmysql's default read timeout is one year!
https://github.com/mysql/mysql-server/blob/7e58ce8e69de5a4e941d913999cbbf905fe8f444/include/mysql.h#L69

**Comment by ic3man5** [comment]
IMO I would recommend setting this after ``` self._get_server_information() ``` then and only set to None if connect_timeout kwarg isn't set. I doubt ``` _get_server_information() ``` queries should ever take longer than a few seconds. This would allow proper error handling if the server can't respond but the socket is being opened (due to firewalls or NAT or some other stupid reason).

**Comment by methane** [comment]
I prefer following libmysqlclient behavior.
It set read-timeout right after connection made, not after handshake.
I'll add read_timeout option. But I'll not change when set read-timeout.

**Comment by methane** [comment]
read_timeout is implemented.
