### ISSUE TITLE
pymysql.connect ignores host, connects to the machine's IP

### ISSUE THREAD

**Issue by nemobis** [PyMySQL/PyMySQL#339]
```
>>> pymysql.connect(host='10.64.37.5', db="meta_p", read_default_file='~/.my.cnf')Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nemobis/.local/lib/python3.4/site-packages/PyMySQL-0.6.6-py3.4.egg/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/home/nemobis/.local/lib/python3.4/site-packages/PyMySQL-0.6.6-py3.4.egg/pymysql/connections.py", line 644, in __init__
    self._connect()
  File "/home/nemobis/.local/lib/python3.4/site-packages/PyMySQL-0.6.6-py3.4.egg/pymysql/connections.py", line 838, in _connect
    self._request_authentication()
  File "/home/nemobis/.local/lib/python3.4/site-packages/PyMySQL-0.6.6-py3.4.egg/pymysql/connections.py", line 1021, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/nemobis/.local/lib/python3.4/site-packages/PyMySQL-0.6.6-py3.4.egg/pymysql/connections.py", line 893, in _read_packet
    packet.check_error()
  File "/home/nemobis/.local/lib/python3.4/site-packages/PyMySQL-0.6.6-py3.4.egg/pymysql/connections.py", line 369, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/nemobis/.local/lib/python3.4/site-packages/PyMySQL-0.6.6-py3.4.egg/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/home/nemobis/.local/lib/python3.4/site-packages/PyMySQL-0.6.6-py3.4.egg/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
pymysql.err.OperationalError: (1045, "Access denied for user 'u2179'@'10.68.17.228' (using password: YES)")
```
I specified 10.64.37.5, but it tried to connect to 10.68.17.228 which is not the database server but my current machine. Originally I tried "s3.labsdb" which is the alias to the IP:
```
$ grep 10.64.37.5 /etc/hosts
10.64.37.5 s3.labsdb
```

https://github.com/PyMySQL/PyMySQL/issues/311#issuecomment-76492834 says the server needs to listen on a TCP socket, I don't know if it does.

Version:
```
$ easy_install3 --user pymysql
Searching for pymysql
Best match: PyMySQL 0.6.6
Processing PyMySQL-0.6.6-py3.4.egg
PyMySQL 0.6.6 is already the active version in easy-install.pth
```

**Comment by jettify** [comment]
Looks like your have mysql host defined in your ``~/.my.cnf``. If host defined in ``read_default_file``, original ``host`` argument is not used, see[1]

https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L602-L608

**Comment by nemobis** [comment]
Nikolay Novik, 26/04/2015 17:03:
> Looks like your have mysql host defined in your |~/.my.cnf|. If host
> defined in |read_default_file|, original |host| argument is not used, see[1]

The default file only contains user and password.

**Comment by methane** [comment]
@nemobis Can you connect MySQL via normal MySQL client?
It looks like you hasn't register user properly.
https://dev.mysql.com/doc/refman/5.1/en/account-names.html

**Comment by nemobis** [comment]
INADA Naoki, 27/04/2015 03:08:
> @nemobis <https://github.com/nemobis> Can you connect MySQL via normal
> MySQL client?
> It looks like you hasn't register user properly.

Connection works correctly with MySQLdb module. Maybe PyMySQL is trying 
to ping hosts or other things which are forbidden by firewalls on this 
cluster?

**Comment by methane** [comment]
>> pymysql.err.OperationalError: (1045, "Access denied for user 'u2179'@'10.68.17.228' (using password: YES)")
> I specified 10.64.37.5, but it tried to connect to 10.68.17.228 which is not the database server but my current machine.

10.68.17.228 is client address.
MySQL server's auth is based on user@host and password.
Your error says you connected to MySQL on TCP level and denied by auth.

> Connection works correctly with MySQLdb module.

From same machine?

**Comment by nemobis** [comment]
INADA Naoki, 27/04/2015 08:41:
>  From same machine?

Yes

**Comment by methane** [comment]
>   From same machine?
> Yes

And same user and password?
Could you try without `read_default_file`?

**Comment by nemobis** [comment]
INADA Naoki, 27/04/2015 08:54:
> And same user and password?

Yes, same code and everything, I only changed import.

> Could you try without |read_default_file|?

Hm, I think I did and that didn't work either. I will try again later 
today but of course it's only for testing, I need to publish the code 
and there can't be passwords.

**Comment by nemobis** [comment]
@halfak solved the mystery. It doesn't work if the default file has quotes around the password or user.

**Comment by methane** [comment]
Close this issue since issue title is far from cause.
Continues on #345.

**Comment by a2902793** [comment]
I am facing this issue again and I cannot solve this.
Version: 1.0.2
