### ISSUE TITLE
What's the difference between PyMySQL and mysqlclient-python?

### ISSUE THREAD

**Issue by elad661** [PyMySQL/PyMySQL#342]
PyMySQL and mysqlclient-python seem to be very similar: Both aim to be a mysql connector to python that aims to maintain compatibility with MySQLdb.

I know there's a difference in the implementation details (PyMySQL being pure python), but it's unclear to me which one I should use, and which implementation is superior.

**Comment by methane** [comment]
mysqlclient-python is much faster than PyMySQL.
When to use PyMySQL is:

* You can't use libmysqlclient for some reason
* You want to use monkeypatched socket of gevent or eventlet
* You wan't to hack mysql protocol

**Comment by radzhome** [comment]
PyMySQL also looks faster under PyPy vs mysqlclient - https://gist.github.com/methane/90ec97dda7fa9c7c4ef1

**Comment by lufangfan** [comment]
it is very nice!
