### ISSUE TITLE
Cursor.rowcount is not matched_rows but affected_rows, which may be less

### ISSUE THREAD

**Issue by johnlxi** [PyMySQL/PyMySQL#347]
Currently the Cursor.rowcount is not matched_rows found by WHERE

Not like suggected here (  https://www.python.org/dev/peps/pep-0249/#id48  )

"Database module authors should try to implement the more common interpretation of returning the total number of rows found by the WHERE clause, or clearly document a different interpretation of the .rowcount attribute"

Acutally the matched_rows is really useful in many situations, will anyone make it supported, please.

^_^

**Comment by johnlxi** [comment]
After think it again, I believe current implementation is pretty reasonable

**Comment by terrisgit** [comment]
I would like to get matched_rows in order to tell the difference between a bug or weirdness versus nothing in a row was changed

**Comment by methane** [comment]
There are two ways to know matched rows count.

1. passing client flag

```
from pymysql.constants import CLIENT

conn = pymysql.connect(..., client_flag=CLIENT.FOUND_ROWS)
```

In this case, `rowcount` is rows matched with WHERE clause.
(But you can't know rows changed)

2. info

After executed query, you can show text message by `print(cursor._result.message)`.

It's same to mysql command line client shows.
https://dev.mysql.com/doc/refman/5.7/en/mysql-info.html
