### ISSUE TITLE
literal works differently as MySQLdb

### ISSUE THREAD

**Issue by JulienPalard** [PyMySQL/PyMySQL#356]
The readme states that PyMySQL is a dropin replacement for MySQLdb but I found a difference that broke my code:
```
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import MySQLdb
>>> db = MySQLdb.connect(...) # redacted parameters
>>> db.literal(["yolo", 42])
("'yolo'", '42')
```

vs
```
Python 3.2.3 (default, Feb 20 2013, 14:44:27) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymysql
>>> db = pymysql.connect(...) # redacted parameters
>>> db.literal(["yolo", 42])
"('yolo',42)"
```

MySQLdb returns a typle of escaped strings, and PyMySQL returns a string containing parenthesis.

It breaks my code as I used it this way:

```
insert_values = re.compile(r"\svalues\s*(\(((?<!\\)'.*?\).*(?<!\\)?'|.)+?\))",
                           re.IGNORECASE)

def prepare_multiple(db, query, args):
    m = insert_values.search(query)
    if not m:
        raise Exception("Can't find VALUE part of query")
    p = m.start(1)
    e = m.end(1)
    qv = m.group(1)
    q = [qv % db.literal(a) for a in args]
    return '\n'.join([query[:p], ',\n'.join(q), query[e:]])
```

To forge multiple insert statements.

Beware that's probably not the cleanest way to do it, as far as I remember, I did not write it myself, but parsing and editing the SQL query client side is tricky, using a regex seems a bad idea to parse SQL, and the regex is probably not the best possible one ^-^

**Comment by methane** [comment]
The MySQLdb behavior you mention is changed in MySQLdb 1.2.5.
https://github.com/farcepest/MySQLdb1/commit/87d1145c0d6ee4f5a8ecf6d5c62d2479b9cf27ea#commitcomment-6819475

And @farcepest said he will revert the commit in 1.2.6
https://github.com/farcepest/MySQLdb1/issues/49#issuecomment-32502230

So connection.literal() is unstable for tuple for now.  Don't relay to the behavior.
Instead, you can use Cursor.executemany() for bulk insert.

**Comment by JulienPalard** [comment]
Ok.
