### ISSUE TITLE
socketio is slower than MySQLdb

### ISSUE THREAD

**Issue by jheld** [PyMySQL/PyMySQL#360]
My company was mocking out using this library over the more traditional python-mysql package, which we use for our other code bases. However, under this use case, we have to bring up many connections, very fast, and send down lots of queries/executes. My coworker mentioned that the socketio used in this library (python-based) is the reason why this is much slower than the c-based python-mysql. Is this true? It looks like this library uses a backported version of the py3 code. Can anything be remedied? We want to *at some point* hit py3....and this is one road block that will incur a penalty in that endeavor.

If I'm not being detailed enough, or you want clarifications/data, please let me know. This is not intended to spark a flame war or anything. We're grateful for this project, and I'm trying to do my due diligence in seeing what our options are for the short and long term.

**Comment by methane** [comment]
I used SocketIO to avoid large amount of small IO.
It improves performance.  Especially, PyPy performance is very improved.

Most common bottleneck of PyMySQL is parsing packet.
mysqlclient (aka MySQLdb) uses libmysqlclient to IO and parsing packet. And libmysqlclient is implemented in C/C++.
PyMySQL uses pure Python parser.

When you use massive query (thousands queries per second) which fetches small amount of rows, IO is bottleneck and performance difference between mysqlclient and PyMySQL is small.

When you use relative small number query (~hundreds queries per second) fetches large amount of rows, packet parsing is bottleneck and performance difference between them is huge.
In this case, you should use mysqlclient or PyPy.
