### ISSUE TITLE
UnicodeDecodeError in executemany with mixed str/bytes arguments

### ISSUE THREAD

**Issue by hannosch** [PyMySQL/PyMySQL#364]
There is workaround code for mixed str/bytes arguments in the execute (single) path, but this is missing from the executemany code.

PR with test to follow shortly.

**Comment by grooverdan** [comment]
@hannosch 

I'm working on adding tests for mysql-5.6/5.7 (https://github.com/grooverdan/PyMySQL/tree/mysql56_57_tests) and get the following error with this test in py34 and mysql-5.7.

If you have any suggestions on fixing the test/implementation I'm keen to hear it

https://travis-ci.org/grooverdan/PyMySQL/jobs/77274309
<pre>
======================================================================
ERROR: test_issue_364 (pymysql.tests.test_issues.TestGitHubIssues)
Test mixed unicode/binary arguments in executemany.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/grooverdan/PyMySQL/pymysql/tests/test_issues.py", line 421, in test_issue_364
    cur.execute(sql, args=values)
  File "/home/travis/build/grooverdan/PyMySQL/pymysql/cursors.py", line 146, in execute
    result = self._query(query)
  File "/home/travis/build/grooverdan/PyMySQL/pymysql/cursors.py", line 297, in _query
    self._do_get_result()
  File "/home/travis/build/grooverdan/PyMySQL/pymysql/cursors.py", line 312, in _do_get_result
    self._show_warnings(conn)
  File "/home/travis/build/grooverdan/PyMySQL/pymysql/cursors.py", line 325, in _show_warnings
    warnings.warn(str(msg), err.Warning, 4)
pymysql.err.Warning: Invalid utf8 character string: 'FF00'
</pre>

**Comment by hannosch** [comment]
@grooverdan I have no real idea. I've been able to reproduce the warning though. That is locally on OS X with MySQL 5.7 under Python 2.7.10. So it seems it's not just a Python 3 issue.

Ran out of time for now, will look into this more but don't know when I'll find the time.

**Comment by grooverdan** [comment]
ok. No problem. for now I've caught the warning as expected for mysql-5.7

**Comment by methane** [comment]
mysqlclient-python uses libmysqlclient.

```python
In [4]: import MySQLdb.connections
In [8]: conn = MySQLdb.connect(charset='utf8mb4')
In [13]: for i in range(0, 256, 16):
   ....:     print(conn.escape_string(bytes(range(i, i+16))))
   ....:
b'\\0\x01\x02\x03\x04\x05\x06\x07\x08\t\\n\x0b\x0c\\r\x0e\x0f'
b'\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\\Z\x1b\x1c\x1d\x1e\x1f'
b' !\\"#$%&\\\'()*+,-./'
b'0123456789:;<=>?'
b'@ABCDEFGHIJKLMNO'
b'PQRSTUVWXYZ[\\\\]^_'
b'`abcdefghijklmno'
b'pqrstuvwxyz{|}~\x7f'
b'\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f'
b'\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9a\x9b\x9c\x9d\x9e\x9f'
b'\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf'
b'\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf'
b'\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf'
b'\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf'
b'\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef'
b'\xf0\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff'

In [14]: conn = MySQLdb.connect(charset='utf8mb4', sql_mode='NO_BACKSLASH_ESCAPES')

In [15]: for i in range(0, 256, 16):
    print(conn.escape_string(bytes(range(i, i+16))))
   ....:
b'\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f'
b'\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f'
b' !"#$%&\'\'()*+,-./'
b'0123456789:;<=>?'
b'@ABCDEFGHIJKLMNO'
b'PQRSTUVWXYZ[\\]^_'
b'`abcdefghijklmno'
b'pqrstuvwxyz{|}~\x7f'
b'\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f'
b'\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9a\x9b\x9c\x9d\x9e\x9f'
b'\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf'
b'\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf'
b'\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf'
b'\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf'
b'\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef'
b'\xf0\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff'
```

**Comment by methane** [comment]
How about this?
`cur.execute("SELECT _binary%s", (bytes(range(256)),))`

**Comment by grooverdan** [comment]
thanks @methane , added to #369
