### ISSUE TITLE
SQLAlchemy connection.execute throws an error in `pymysql/cursors.py`

### ISSUE THREAD

**Issue by rawrgulmuffins** [PyMySQL/PyMySQL#367]
I'm trying to run a simple query against a mysql server using sqlalchemy.

    import sqlalchemy as sa

    connection_string = 'mysql+pymysql://test_results:ab@eng-sea-db01-rep.west.isilon.com'
    engine = sa.create_engine(connection_string)
    connection = engine.connect()

    query = """
        select distinct n.listname, n.notes
        from notes n 
        join run r on n.start = r.start
        where r.branch = 'B_HEAD' 
        and r.start > '2015-08-01' 
        and n.notes like '%ug%';"""
    result = connection.execute(query)
    for row in result:
        print("listname: {} | notes: {}".format(row['listname'], row["notes"]))

This program throws an exception on the `execute(query)` line.

    Traceback (most recent call last):
    File "db_test.py", line 19, in <module>
        result = connection.execute(query)
    File "/home/alord/.virtualenvs/regression_failures/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 906, in execute
        return self._execute_text(object, multiparams, params)
    File "/home/alord/.virtualenvs/regression_failures/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text
        statement, parameters
    File "/home/alord/.virtualenvs/regression_failures/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
        context)
    File "/home/alord/.virtualenvs/regression_failures/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1344, in _handle_dbapi_exception
        util.reraise(*exc_info)
    File "/home/alord/.virtualenvs/regression_failures/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 182, in reraise
        raise value
    File "/home/alord/.virtualenvs/regression_failures/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
        context)
    File "/home/alord/.virtualenvs/regression_failures/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
        cursor.execute(statement, parameters)
    File "/home/alord/.virtualenvs/regression_failures/lib/python3.4/site-packages/pymysql/cursors.py", line 132, in execute
        query = query % self._escape_args(args, conn)
    TypeError: not enough arguments for format string

I'm using the latest PyMySQL and SQLAlchemy version.

    Flask==0.10.1
    Flask-SQLAlchemy==2.0
    itsdangerous==0.24
    Jinja2==2.8
    MarkupSafe==0.23
    PyMySQL==0.6.6
    SQLAlchemy==1.0.8
    Werkzeug==0.10.4

Not sure what's going on yet. Preliminary report.

**Comment by methane** [comment]
`%ug%` should be `%%ug%%`.

```
In [1]: "%%" % ()
Out[1]: '%'
```

**Comment by rawrgulmuffins** [comment]
hmmm, so I with PyMySQL I shouldn't expect to be able to use sql queries that I got working in the mysql console program first?

**Comment by methane** [comment]
Yes, in rare cases.

**Comment by rawrgulmuffins** [comment]
How feasible is it to raise a custom exception explaining what's happened in those rare cases?

**Comment by methane** [comment]
Pythonistas are familiar with error raised from invalid `%` operation.
Custom error may hide what is real problem.

At least, I can specify your case without reproducible code.
I may can't solve your problem easily if I wrap real error with custom error.

**Comment by rawrgulmuffins** [comment]
I could accept that argument if the application code wasn't using the % formatter correctly but in this case it's caused by a custom requirement of PyMySQL. =P

**Comment by methane** [comment]
* Traceback shows `%` formatter is used clearly.
* query can use `%(limit)s` style format. User should know `%` format is used internally.
* If PyMySQL wrap the error with custom error, real problem will be hidden or traceback will be very long garbage.

**Comment by methane** [comment]
"not enough arguments for format string" is clear than "your query is wrong".

**Comment by methane** [comment]
Without wrapping:
```
In [1]: "select %i" % ("10",)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-709d37d46944> in <module>()
----> 1 "select %i" % ("10",)

TypeError: %i format: a number is required, not str
```

With wrapping:
```
In [3]: class CustomError(Exception):
   ...:     pass
   ...:

In [4]: try:
   ...:     "select %i" % ("10",)
   ...: except Exception:
   ...:     raise CustomError("your query is wrong")
   ...:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-778c9b8085cc> in <module>()
      1 try:
----> 2     "select %i" % ("10",)
      3 except Exception:

TypeError: %i format: a number is required, not str

During handling of the above exception, another exception occurred:

CustomError                               Traceback (most recent call last)
<ipython-input-4-778c9b8085cc> in <module>()
      2     "select %i" % ("10",)
      3 except Exception:
----> 4     raise CustomError("your query is wrong")
      5

CustomError: your query is wrong
```

**Comment by methane** [comment]
OK, there is Exception for wrapping such errors.
https://www.python.org/dev/peps/pep-0249/#programmingerror
I'll use it for here.
