### ISSUE TITLE
Do not trim the string in result set

### ISSUE THREAD

**Issue by Ting-y** [PyMySQL/PyMySQL#371]
What files should i look at to if i want to modify the return result set?

**Comment by grooverdan** [comment]
connections.py and cursors.py.

Do you have a test case that shows string trimming?

**Comment by Ting-y** [comment]
I have added a test case in my folk repository. What should i do next if i want to modify the result set

https://github.com/Ting-y/PyMySQL/commit/5aeea8fc5ea6f05913ea69c124a06c37e0d0cea4

**Comment by methane** [comment]
I can't reproduce it...

```python
In [8]: cur.execute("CREATE TABLE test (data varchar(10))")
Out[8]: 0

In [9]: cur.execute("insert into test (data) values " "('string'), ('string   ')")
Out[9]: 2

In [10]: cur.execute("select data from test")
Out[10]: 2

In [11]: cur.fetchall()
Out[11]: (('string',), ('string   ',))

In [12]: cur.execute("select data from test")
Out[12]: 2

In [13]: cur.fetchone()
Out[13]: ('string',)

In [14]: cur.fetchone()
Out[14]: ('string   ',)
```

**Comment by methane** [comment]
@Ting-y Could you send pull request for the test?
Travis-CI will run your test on some environments.

**Comment by methane** [comment]
One MySQL pitfall is VARCHAR column ignores trailing spaces when comparison.

```python
In [15]: cur.execute("SELECT count(1) FROM test WHERE data='string'")
Out[15]: 1

In [16]: cur.fetchone()
Out[16]: (2,)
```

**Comment by Ting-y** [comment]
Should I trim the space after fetch the result?

**Comment by methane** [comment]
No.
Please send me a failing test.

2015年8月28日(金) 23:33 Ting Yang <notifications@github.com>:
