### ISSUE TITLE
0.6.7 egg

### ISSUE THREAD

**Issue by papachoco** [PyMySQL/PyMySQL#383]
Hello,

Could we have the 0.6.7 distribution egg  on pypi.python.org ? This is would be for buildout based installations.

Thanks

Carlos

**Comment by methane** [comment]
I forgot to put sdist to PyPI.
I hope buildout can use sdist.
Since I forget about egg and I don't want to learn such legacy format again.

**Comment by papachoco** [comment]
the tar.gz source would suffice too

**Comment by methane** [comment]
I've uploaded source package.
