### ISSUE TITLE
Connection through SSL

### ISSUE THREAD

**Issue by barnettjacob** [PyMySQL/PyMySQL#386]
Sorry if this is a daft question but I can't see an example in the docs!

What does my connection string need to look like for an SSL connection, specifically how do I reference my certificate? For other purposes I use a .my.cnf file that contains all my credentials.

Thanks in advance.
Jacob

**Comment by methane** [comment]
What is "connection string"?

**Comment by barnettjacob** [comment]
Ha. Sorry. I'm talking about the string that I use to connect to the database that contains my credentials e.g:  `dbconn = pymysql.connect(user = 'user', database = 'mydb', host = 'host', password = 'password')

I also need to be able to add the path to my SSL certificate to this but can't work out how to do it.

The ideal solution would be to read all of this information from an option file (https://dev.mysql.com/doc/refman/5.1/en/option-files.html) which contains credentials for a number of databases where all I do is specify the group I want to use e.g

```[db1]
database=db1
user=me
host=mydb1.com
password=xxxxxxxxx
ssl-ca=/xxx/xxx/xxx.pem

[db2]
database=db2
user=me
host=mydb2.com
password=xxxxxxxxx
ssl-ca=/xxx/xxx/xxx.pem```

Thanks!

**Comment by methane** [comment]
Personally, I never used TLS for MySQL.

https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L535-L537
`connect(..., ssl={'ca': '/xxx/xxx/xxx.pem'})` may work.

**Comment by ferlatte** [comment]
We do use TLS for MySQL.

The above connection does work. the 'ca' argument path should ideally be to your system's CA bundle (which you should add appropriate CA certs to if needed for things like AWS services).

On RHEL, it's /etc/pki/tls/certs/ca-bundle.crt, on Ubuntu /etc/ssl/certs/ca-certificates.crt.

So, assuming Ubuntu:

`connect(..., ssl={'ca': '/etc/ssl/certs/ca-certificates.crt')`

and then you'll have TLS to your MySQL server, assuming it's configured correctly.

**Comment by methane** [comment]
@barnettjacob Could you close this issue?
Or do you have more question?

**Comment by barnettjacob** [comment]
Thanks. Closed.
