### ISSUE TITLE
connection prefers localhost over mysql config file

### ISSUE THREAD

**Issue by rassilon42** [PyMySQL/PyMySQL#389]
If I use the following example code:

    import pymysql
    pymysql.install_as_MySQLdb()
    ...
    class Database(object)

        def __init__(self, *args, **kwargs):
            """
            just delegate to the mysql library
            """
            self.handle = MySQLdb.connect(*args, **kwargs)
       ....

    Database(read_default_file=MY_CNF)  

PyMySQL connects with host=localhost instead of the one provided in the my.cnf file.
it only happens with newer versions of PyMySQL and seems to be related to the following commit 

    ddc9a86cb8b1360610d2d7a475172c6894f7499c
    -> Prefer arg to config
-
      def _config(key, arg):
                 if arg:
                    return arg
                 try:
                     return cfg.get(read_default_group, key)
                 except Exception:
                     return arg

if i comment out the the if condition it works as expected and the connection uses
the host from the my.cnf, otherwise it defaults to localhost.

              # if arg:
              #    return arg

I couldn't find any discussion regarding this or couldn't make out why this is the case.
Is this intended and why ?

sorry if I'm missing something here

**Comment by methane** [comment]
PyMySQL behavior should be same to MySQL-python (using libmysqlclient aka MySQL Connector/C) as possible.
So I don't discuss about "which is better".  Unreasonable difference from MySQL-python is a bug.
I'll check which [mysql_real_connect](https://dev.mysql.com/doc/refman/5.7/en/mysql-real-connect.html) prefer.

**Comment by methane** [comment]
But I believe `default_file` specify **default** options and passed arguments overrides defaults.

**Comment by methane** [comment]
So the real problem is default argument of Connection.
https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L502

Currently, `host='localhost',`, but it should be `host=None`.

**Comment by rassilon42** [comment]
cool , so I can look forward to a fix ? :)
thanks
