### ISSUE TITLE
PyMSQL should patch _mysql_exceptions

### ISSUE THREAD

**Issue by avaitla** [PyMySQL/PyMySQL#392]
Not sure if this is a bug or expected behavior, but should install_as_MySQLdb also patch the _mysql_exceptions file?

Here is some sample code that doesn't work as I expected initially:

    import pymysql
    pymysql.install_as_MySQLdb()
    from _mysql_exceptions import IntegrityError

    if __name__ == "__main__":
        assert IntegrityError.__module__ == "pymysql.err"

**Comment by methane** [comment]
No.
PyMySQL only compatible with MySQL-python's public, DB-API 2.0 based API.
PyMySQL doesn't support private or low-level API not based on DB-API 2.0.

You should import Exceptions from `MySQLdb` module. (ref: https://www.python.org/dev/peps/pep-0249/#exceptions)

```python
import pymysql
pymysql.install_as_MySQLdb()
from MySQLdb import IntegrityError
```
