### ISSUE TITLE
Support read_timeout or write_timeout in PyMySQL

### ISSUE THREAD

**Issue by avaitla** [PyMySQL/PyMySQL#393]
I think currently this option is not part of DBAPI, but MySQLdb supports read_timeout. Any plan in the roadmap to add this?

**Comment by methane** [comment]
While there are no plans, I will do it.

>  this option is not part of DBAPI

`dbapi_module.connect()` is API defined by DB-API.
So PyMySQL should compatible with MySQL-python's `connect()` as possible and reasonable.

**Comment by paladini** [comment]
I need a feature like that too. 

I don't get your answer, @methane , sorry. What should I do in order to change read_timeout/write_timeout while we don't have a feature like that in PyMySQL? Should I pass an argument to connect()? If so, which?

Thanks.
