### ISSUE TITLE
No self.close() in __exit__ method of connection?

### ISSUE THREAD

**Issue by sepus** [PyMySQL/PyMySQL#396]
Is it possible (or sensible) to use the context handler for the connection, e.g.:

```
connection = pymysql.connect(host='localhost',
                             user='user',
                             password='passwd',
                             db='db',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)
with connection as cursor:
    ... # do something
# proceed
```

Precisely: Is the connection closed after the with-block? I ask, because

1. the example given on https://github.com/PyMySQL/PyMySQL doesn't use the context handler for the connection but for the cursor;
2. the __exit__ method of the connection object is

```
def __exit__(self, exc, value, traceback):
    """On successful exit, commit. On exception, rollback"""
    if exc:
        self.rollback()
    else:
        self.commit()
```

and not

```
def __exit__(self, exc, value, traceback):
    """On successful exit, commit. On exception, rollback"""
    if exc:
        self.rollback()
    else:
        self.commit()
    self.close()
```

**Comment by methane** [comment]
> Is it possible (or sensible) to use the context handler for the connection

No. DB-API 2.0 doesn't define context manager API.

> Precisely: Is the connection closed after the with-block? 

No, as you can see.

Currently, connection's contextmanager is for managing transaction.
For compatibility with MySQL-python, I can't change the behavior easily.
