### ISSUE TITLE
pymysql.err.InternalError: Packet sequence number wrong - got 1 expected 2

### ISSUE THREAD

**Issue by Windfarer** [PyMySQL/PyMySQL#414]
got this error in PyMySQL version 0.7.0, but in version 0.6.7 everything is ok, I have no idea about this problem

**Comment by methane** [comment]
Could you provide reproducible code?

**Comment by Windfarer** [comment]
I use this package https://github.com/noplay/python-mysql-replication, it depends on PyMySQL, and works fine in PyMySQL==0.6.7, but raise that error in 0.7.0, and I didn't change that package's version.

**Comment by Windfarer** [comment]
What are the changes in 0.7.0? I have no idea.

**Comment by methane** [comment]
No breaking changes in **public / supported** API.
I added check for sequence number internally.

I suppose python-mysql-replication uses PyMySQL not in normal way and hit
internal changes.
Please provide script to reproduce, or stacktrace at least.

I'm not an esper.  I don't use every packages on PyPI.
I don't want to learn new package I haven't used (and I won't use it in the future).

**Comment by Windfarer** [comment]
ok, wait a minute, and I will collect the information

**Comment by methane** [comment]
ref noplay/python-mysql-replication#138

**Comment by Windfarer** [comment]
oh, thanks for your patient, i have found out that sourcecode just now. I really appreciate for your help.

**Comment by Windfarer** [comment]
I think I should close this issue.

**Comment by mamdosein97** [comment]
hello. thanks for your helpful library
I have this problem as same. what should i do?

**Comment by jkklee** [comment]
@mamdosein97  this is not a problem of pymysql, this may caused by use a pymysql connection object with multiple threads/processes, I had faced this problem and I implate a litle library based on pymysql that focus on this problem, which you can use almost as same as pymysql. [pymysql-connpool](https://github.com/jkklee/pymysql-connpool)
