### ISSUE TITLE
Broken unicode to Binary conversion

### ISSUE THREAD

**Issue by lgrech** [PyMySQL/PyMySQL#416]
After upgrade to pymysql 0.7 there's an error when initializing Binary from unicode. We're using Python 2.7 with SqlAlchemy (which is converitng LargeBinary to pymysql Binary). 

```
".../lib/python2.7/site-packages/sqlalchemy/util/compat.py", 
line 200, in raise_from_cause
     reraise(type(exception), exception, tb=exc_tb)
   File 
".../lib/python2.7/site-packages/sqlalchemy/engine/base.py", 
line 1073, in _execute_context
     context = constructor(dialect, self, conn, *args)
   File 
".../lib/python2.7/site-packages/sqlalchemy/engine/default.py", 
line 608, in _init_compiled
     for key in compiled_params
   File 
".../lib/python2.7/site-packages/sqlalchemy/engine/default.py", 
line 608, in <genexpr>
     for key in compiled_params
   File 
".../lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py", line 
834, in process
     return DBAPIBinary(value)
   File 
".../lib/python2.7/site-packages/pymysql/__init__.py", line 
77, in Binary
     return bytearray(x)
StatementError: (exceptions.TypeError) unicode argument without an 
encoding 
```

For Python 2.7 Binary constructor is now using bytearray() to initialize value but it does not provide any encoding (which is required for unicode).

This can be easily reproduced with following example:

```
>>> from pymysql import Binary
>>> Binary('aaa')
bytearray(b'aaa')
>>> Binary(u'aaa')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pymysql/__init__.py", line 77, in Binary
    return bytearray(x)
TypeError: unicode argument without an encoding
```

**Comment by methane** [comment]
Why do you use unicode for binary data?

**Comment by lgrech** [comment]
Well, this how this column is initialized in our code. We send some unicode data via REST API and then store it in DB (in BLOB). It's out legacy solution which was working with previous version on pymysql. I'm not saying this is the best design choice however bytearray() supports unicode and Binary supports strings. Question is why it doesn't support unicode anymore?

**Comment by methane** [comment]
Since I was surprised `Binary(unicode)` doesn't raise TypeError and I thought it was unexpected behavior.
I've sent mail to db-sig ML to make a consensus about should Binary accept unicode string or not.

**Comment by lgrech** [comment]
Ok, thanks

**Comment by hannosch** [comment]
I think it makes a lot of sense to raise an exception if you try to store unicode data in a binary column. A binary column by definition doesn't have an encoding, so how should it decide to encode the given unicode data and on the return trip decode it again?

I think MySQL has been very forgiving here in the past and raised no warning about this, probably falling back to the connections, tables or default database encoding. If you change any one of them it might have unexpected results and break your code.

But with MySQL 5.6.27 and 5.7 it now raises warnings each time you try to send non-binary data to a binary column, so PyMySQL had to be a bit more explicit about this as well. The changelog entry for MySQL 5.6.27 is: "MySQL sometimes produced no warning when it was unable to interpret a character in a given character set. (Bug #20238729)".

It doesn't help that in Python 2 most people have been very lax in dealing with the unicode/bytes split and the bytes type is just an alias for str, which makes it rather hard to know if something is truly a binary type or not. I think SQLAlchemy has therefor chosen to explicitly demand any text type to be of type unicode in Python 2, to properly distinguish it from str/bytes, but that isn't true for all other users.

**Comment by lgrech** [comment]
Ok then, let's say I'm convinced;) Storing char data in binary column is not recommended (which is no supprise;)) so we'll try to fix it in a "correct" way in our product. My doubt is coming from a fact that MySQL allows you to store unicode in binary column while pymysql doesn't and since it's "just" a client it can be seen as limitation (which I hope I can live with). Regards. Lukasz

**Comment by nicholasknight** [comment]
This has also broken working code for us running against MariaDB 10. We've reverted to 0.6.7.

Does the PyMySQL project have any official policy with regard to maintaining compatibility with existing code? Where can I find it?

It would have been nice if the changelog had at least warned that this was a compatibility-breaking change...

**Comment by methane** [comment]
Writing English is far harder than writing Python to me.
You can contribute by improving changelog.

At least, I couldn't imagine who use unicode type for storing binary data.
That's why there are no warn in changelog.

**Comment by nicholasknight** [comment]
A changelog note like this would help a lot:

> Compatibility warning: As of 0.7.0, attempting to insert unicode strings into (VAR)BINARY columns will now raise a TypeError. Code that does not make the necessary conversions may break, for example when inserting strings deserialized using the standard `json` library. See issue #416.

Note that we're not _deliberately_ using unicode types. It's just very easy to end up with a unicode object without really wanting one in some cases. Consider, for example, any sort of case-sensitive data that gets passed in JSON:

```
>>> json.loads('{"apiToken": "AbCd1234"}')
{u'apiToken': u'AbCd1234'}
>>> 
```

API tokens are usually case-sensitive ASCII alphanumerics. They fit fine in both JSON strings and (VAR)BINARY columns. But `json.loads()` drops a unicode object on you by default, and you have to specifically take action to get a (byte) string.

We had a similar issue with some object IDs coming into some glue code between Oracle and MariaDB (either cx_Oracle or SQLAlchemy gave us a unicode object that we didn't really want/need, but it had never been a problem before).

Storing a unicode object in a BINARY column is certainly not "correct", but the 90% case (maybe 99%) is that the developer wanted the data to be encoded to UTF-8 or at least ASCII. Until a few weeks ago, that's what happened for many years, making this mistake so easy that I doubt Lukasz and I will be the only people it bites.

(I would personally prefer the old behavior be temporarily returned with some sort of warning logged during a deprecation period, but I recognize I'm very conservative about API changes and don't really expect that to happen here.)

**Comment by methane** [comment]
> Compatibility warning: As of 0.7.0, attempting to insert unicode strings into (VAR)BINARY columns will now raise a TypeError. 

It's not correct.  PyMySQL doesn't know about column type.

**Comment by methane** [comment]
In Python 2, str type is used for both of text and binary data.
You can use `pymysql.Binary()` to tell "this str is binary data" to PyMySQL.
So passing unicode to `pymysql.Binary()` doesn't make sense.

PyMySQL 0.6 doesn't allow it intentionally.

**Comment by nicholasknight** [comment]
I appreciate your time and candor. Since the policies of the PyMySQL project towards breaking changes are fundamentally at odds with its use in a production setting, I'll just fork off 0.6.7 internally so I don't have to bother you further.
