### ISSUE TITLE
Connection oddness in a class

### ISSUE THREAD

**Issue by Bobspadger** [PyMySQL/PyMySQL#421]
http://stackoverflow.com/questions/34288213/python-and-mysql-connections-in-a-class-db-open-and-close-strange-behaviour

Am I doing something wrong or is this a bug ?

**Comment by methane** [comment]
Please write a real code which can reproduce the issue, instead of buggy pseudo code.

**Comment by Bobspadger** [comment]
Ok - here is some working code (everything is ok)




__author__ = 'alexhellier'

import newrelic.agent
import pymysql
import pymysql.cursors

class mysqlHelpers:
	@newrelic.agent.background_task()
	def get_new_jobs(self, call):
		"""
		Get all the new products to update or create to the web
		:param call:  - create or update
		:param limit: - integer for how many records to get
		:return: rows
		"""

		db = pymysql.connect(host='host.mydomain.com', user='username', passwd='mypassword', db='magento_api',
		                     charset='utf8', )
		mysqlcursor = db.cursor(pymysql.cursors.DictCursor)
		sql = """
				SELECT `description short html`, `magento html`, `magento Tax class id`, `Magento URL key`,
 				`Magento_categories`, `Magento_ProductID`, `price`, `Magento_shipping_weight`,
 				`magento_status`, `Magento_Stock_data_is_in_stock`, `Magento_visibility`, `magento_WEBSITE_ID`,
 				`Meta description`, `Meta Keywords`, `Offer expire date`, `Offer start date`, `Product Name Magento`,
				`product name web3`, `sales inc Naughty`, `special_price`, `call_type`, `attributes`,
				`call_status`, `tiered_price`, `sku`, `attribute_set`, `StoreID`, `product_options_header`,
				 `product_options_values`,
				  `id`, meta_title, stock_for_sale_qty FROM mage_product_create_update WHERE (call_type = "%s" AND call_status = 0)
				"""
		# print(sql % (call))
		mysqlcursor.execute(sql % (call))
		rows = mysqlcursor.fetchall()
		mysqlcursor.close()
		return rows

	def get_new_jobs_debug_sku(self, call, sku):
		"""
		Get all the new products to update or create to the web
		:param call:  - create or update
		:param limit: - integer for how many records to get
		:return: rows
		"""

		db = pymysql.connect(host='host.mydomain.com', user='username', passwd='mypassword', db='magento_api',
		                     charset='utf8', )
		mysqlcursor = db.cursor(pymysql.cursors.DictCursor)
		sql = """
				SELECT `description short html`, `magento html`, `magento Tax class id`, `Magento URL key`,
 				`Magento_categories`, `Magento_ProductID`, `price`, `Magento_shipping_weight`,
 				`magento_status`, `Magento_Stock_data_is_in_stock`, `Magento_visibility`, `magento_WEBSITE_ID`,
 				`Meta description`, `Meta Keywords`, `Offer expire date`, `Offer start date`, `Product Name Magento`,
				`product name web3`, `sales inc Naughty`, `special_price`, `call_type`, `attributes`,
				`call_status`, `tiered_price`, `sku`, `attribute_set`, `StoreID`, `product_options_header`,
				 `product_options_values`,
				  `id`, meta_title, stock_for_sale_qty FROM mage_product_create_update WHERE (call_type = "%s" AND sku = "%s" )
				"""
		# print(sql % (call))
		mysqlcursor.execute(sql % (call, sku))
		rows = mysqlcursor.fetchall()
		mysqlcursor.close()
		return rows

	def get_new_jobs_debug_id(self, call, db_id):
		"""
		Get all the new products to update or create to the web
		:param call:  - create or update
		:param limit: - integer for how many records to get
		:return: rows
		"""

		db = pymysql.connect(host='host.mydomain.com', user='username', passwd='mypassword', db='magento_api',
		                     charset='utf8', )
		mysqlcursor = db.cursor(pymysql.cursors.DictCursor)
		sql = """
				SELECT `description short html`, `magento html`, `magento Tax class id`, `Magento URL key`,
 				`Magento_categories`, `Magento_ProductID`, `price`, `Magento_shipping_weight`,
 				`magento_status`, `Magento_Stock_data_is_in_stock`, `Magento_visibility`, `magento_WEBSITE_ID`,
 				`Meta description`, `Meta Keywords`, `Offer expire date`, `Offer start date`, `Product Name Magento`,
				`product name web3`, `sales inc Naughty`, `special_price`, `call_type`, `attributes`,
				`call_status`, `tiered_price`, `sku`, `attribute_set`, `StoreID`, `product_options_header`,
				 `product_options_values`,
				  `id`, meta_title, stock_for_sale_qty FROM mage_product_create_update WHERE (call_type = "%s" AND id = "%s" )
				"""
		# print(sql % (call))
		mysqlcursor.execute(sql % (call, db_id))
		rows = mysqlcursor.fetchall()
		mysqlcursor.close()
		return rows






	@newrelic.agent.background_task()
	def write_call_result(self, rowid, status, result):
		"""
		Write back to the db the resultant call result so we know not to do it again.
		:param db_id: the row ID
		:param status: 0 = not done, 10 = complete, x = to be decided
		:param result: the text output so we can see any errors logged
		:return:
		"""
		db = pymysql.connect(host='host.mydomain.com', user='username', passwd='mypassword', db='magento_api',
		                     charset='utf8')
		mysqlcursor = db.cursor()
		sql = """
				UPDATE mage_product_create_update SET call_status = "%s", call_result = "%s" WHERE id = "%s"
				"""
		mysqlcursor.execute(sql % (status, result, rowid))
		mysqlcursor.close()
		db.commit()

	@newrelic.agent.background_task()
	def clear_old_jobs(self, start_date):
		"""

		:param days: number of days to keep
		:return:
		"""
		db = pymysql.connect(host='host.mydomain.com', user='username', passwd='mypassword', db='magento_api',
		                     charset='utf8')
		sql = """
			DELETE FROM mage_product_create_update WHERE call_status != 0 AND CREATION < '%s'
					"""
		mysqlcursor = db.cursor()
		mysqlcursor.execute(sql % (start_date))
		mysqlcursor.close()
		db.commit()

**Comment by Bobspadger** [comment]
Non Working
__author__ = 'alexhellier'

import newrelic.agent
import pymysql
import pymysql.cursors

class mysqlHelpers:
	db = None

	def __init__(self):
		self.db = pymysql.connect(host='mysqlserver', user='myusername', passwd='mypassword',
		                          db='mydatabase',
		                          charset='utf8')

	@newrelic.agent.background_task()
	def get_new_jobs(self, call):
		"""
		Get all the new products to update or create to the web
		:param call:  - create or update
		:param limit: - integer for how many records to get
		:return: rows
		"""

		mysqlcursor = self.db.cursor(pymysql.cursors.DictCursor)
		sql = """
				SELECT `description short html`, `magento html`, `magento Tax class id`, `Magento URL key`,
 				`Magento_categories`, `Magento_ProductID`, `price`, `Magento_shipping_weight`,
 				`magento_status`, `Magento_Stock_data_is_in_stock`, `Magento_visibility`, `magento_WEBSITE_ID`,
 				`Meta description`, `Meta Keywords`, `Offer expire date`, `Offer start date`, `Product Name Magento`,
				`product name web3`, `sales inc Naughty`, `special_price`, `call_type`, `attributes`,
				`call_status`, `tiered_price`, `sku`, `attribute_set`, `StoreID`, `product_options_header`,
				 `product_options_values`,
				  `id`, meta_title, stock_for_sale_qty FROM mage_product_create_update WHERE (call_type = "%s" AND call_status = 0)
				"""
		# print(sql % (call))
		mysqlcursor.execute(sql % (call))
		rows = mysqlcursor.fetchall()
		mysqlcursor.close()
		return rows

	@newrelic.agent.background_task()
	def write_call_result(self, rowid, status, result):
		"""
		Write back to the db the resultant call result so we know not to do it again.
		:param db_id: the row ID
		:param status: 0 = not done, 10 = complete, x = to be decided
		:param result: the text output so we can see any errors logged
		:return:
		"""
		mysqlcursor = self.db.cursor()
		sql = """
				UPDATE mage_product_create_update SET call_status = "%s", call_result = "%s" WHERE id = "%s"
				"""
		mysqlcursor.execute(sql % (status, result, rowid))
		mysqlcursor.close()
		self.db.commit()

	@newrelic.agent.background_task()
	def clear_old_jobs(self, start_date):
		"""

		:param days: number of days to keep
		:return:
		"""
		sql = """
			DELETE FROM mage_product_create_update WHERE call_status != 0 AND CREATION < '%s'
					"""
		mysqlcursor = self.db.cursor()
		mysqlcursor.execute(sql % (start_date))
		mysqlcursor.close()
		self.db.commit()

	def __del__(self):
		self.db.close()

**Comment by Bobspadger** [comment]
Its worth noting that the FIRST run through of the db stuff works, but any follow on call fails (but does not error just whizzes through with no changes to the db or selects returning data)

So an example would be:

while True:
    get_new_jobs(create)

This would find items to do on the first iteration, and all requests after fail to return any rows, even though they are there in the DB

**Comment by methane** [comment]
What version of PyMySQL do you use?

**Comment by Bobspadger** [comment]
PyMySQL==0.6.6

**Comment by snower** [comment]
I also found this problem, you must commit after each query, and perhaps related autocommit.

**Comment by Bobspadger** [comment]
so even after a SELECT you need a db.commit() ?

**Comment by snower** [comment]
I was doing this, I found the right.

**Comment by Bobspadger** [comment]
Ok, still not working as expected.

I've written a small test:

MySQL table - just an id and two fields which we increment with some integers

```
CREATE TABLE `test` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `field1` int(11) DEFAULT NULL,
  `field2` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8;
```

model.py - the db stuff

```
import pymysql

db = pymysql.connect(host='mysql02.local',
                     user='username',
                     passwd='password',
                     db='test',
                     charset='utf8')

class Models:
	def get_data(self):
		cur = db.cursor()
		sql = 'SELECT * FROM test WHERE field1 IS NOT NULL'
		cur.execute(sql)
		rows = cur.fetchall()
		cur.close()
		db.commit()
		return rows
		pass


	def post_data(self, field1, field2):
		cur = db.cursor()
		sql = "INSERT INTO test(field1, field2) VALUES('%s', '%s')"
		cur.execute(sql %(field1, field2))
		cur.close()
		db.commit()

		pass

	def update_data(self,field1, field2):
		cur = db.cursor()
		sql = "UPDATE test SET field2='%s' WHERE field1='%s'"
		cur.execute(sql %(field1, field2))
		print(cur._result.message)
		cur.close()
		db.commit()


		pass


```

Then the test to just run around and update some numbers with out constantly openeing and closing db connections

```
import model

mysql = model.Models()

def main():

	#do stuff
	for i in range(0, 100):
		mysql.post_data(i, i)
	input('Carry on - please check we have 100 rows in the db')

	for x in range(0, 10):
		returneddata = mysql.get_data()
		for row in returneddata:
			print(row)
			updated_number = row[1] + 10
			mysql.update_data(row[0], updated_number)

		input('ive run, check mysql to see if field2 has incremented by 10')




if __name__ == "__main__":
	main()
```



I get that rows have been affected, but nothing is changing in the DB.

Thanks

Alex

**Comment by methane** [comment]
```
mysql> CREATE TABLE `test` (
    ->   `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    ->   `field1` int(11) DEFAULT NULL,
    ->   `field2` int(11) DEFAULT NULL,
    ->   PRIMARY KEY (`id`)
    -> ) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8;
Query OK, 0 rows affected (0.02 sec)
```

```
$ cat > model.py
(paste your code, and modify user and password)
$ cat > main.py
(paste your code)
```

```
$ pip install pymysql==0.6.6
$ python main.py
Carry on - please check we have 100 rows in the db
```

Start another terminal and mysql cli

```
mysql> select * from test;
+-----+--------+--------+
| id  | field1 | field2 |
+-----+--------+--------+
| 101 |      0 |      0 |
| 102 |      1 |      1 |
| 103 |      2 |      2 |
...
| 198 |     97 |     97 |
| 199 |     98 |     98 |
| 200 |     99 |     99 |
+-----+--------+--------+
100 rows in set (0.00 sec)
```

Everything is OK.
