### ISSUE TITLE
(pymysql.err.InternalError) Packet sequence number wrong - got 0 expected 1 

### ISSUE THREAD

**Issue by cmzz** [PyMySQL/PyMySQL#423]
pymysql version: 0.7.1

`  File "/Users/zyxcba/PycharmProjects/lanqq_server/venv/lib/python2.7/site-packages/pymysql/connections.py", line 952, in _read_packet
    (packet_number, self._next_seq_id))
InternalError: (pymysql.err.InternalError) Packet sequence number wrong - got 1 expected 22 `

The same error in 0.7.0.

**Comment by methane** [comment]
See #422 .
This error is happen when your usage of PyMySQL is wrong, especially multi threading.

If your usage of PyMySQL is correct, it's a bug of PyMySQL.
So I need reproducible example code.

**Comment by cmzz** [comment]
I used PyMySQL with SQLAlchemy (V1.0.11) and multi threading..

code :
models.py
`def get_session():
    connect_string = "mysql+pymysql://root:root@127.0.0.1:3306/test?charset=utf8"
    engine = create_engine(connect_string , echo=True, encoding="utf8")
    DBSession = sessionmaker(bind=engine)
    DB = DBSession()
    return DB

DB = get_session()`


message_manage.py:
`import threading
from models import DB

from user_event import UserEvent

class MessageManager(threading.Thread):
...
def app_info(self):
    # Here is ok
    app = DB.query(App).filter_by(qun_id=self.qid).first()

    # Another thread
    UserEvent(message, app, msg_type).start()
`


user_event.py:
`from models import DB
import threading
class UserEvent(threading.Thread):
	...
	def user_info(self):
		# Here..  
		user = DB.query(GroupMember).filter_by(qq=self.fromQQ).first()
`

**Comment by methane** [comment]
You should use scoped_session.
Read this page carefully: http://docs.sqlalchemy.org/en/latest/orm/contextual.html

**Comment by EaconTang** [comment]
Thanks for the issue, I finally fix my problem which fucked me these days!

**Comment by pvilas** [comment]
Same problem here . It was the encoding="utf-8" part.
