### ISSUE TITLE
mysql CURDATE() not expanding properly

### ISSUE THREAD

**Issue by zachsis** [PyMySQL/PyMySQL#424]
When running the following python code below:

```
import pymysql
from pprint import pprint

conn = pymysql.connect(.....)

cur = conn.cursor()

build_select = "SELECT CURDATE();"
cur.execute(build_select)
results = cur.fetchall()
pprint(results)

```
outputs:

`((datetime.date(2016, 2, 2),),)`

whereas when running the same query in a MySQL console, you get the following output?

```
mysql> SELECT CURDATE();
+------------+
| CURDATE()  |
+------------+
| 2016-02-02 |
+------------+
1 row in set (0.00 sec)

```

**Comment by methane** [comment]
PyMySQL converts query result to Python types.
For example, when you query `SELECT 1+2`, you will get integer `3`, not string `'3'`.
In your case, PyMySQL converts date string to Python's `datetime.date` type.
