### ISSUE TITLE
Packet sequence number wrong - got 1 expected 2

### ISSUE THREAD

**Issue by ulugbekrozimboyev** [PyMySQL/PyMySQL#425]
My project keep getting error : mysql error sql: Packet sequence number wrong - got 1 expected 2
for this sql query:
```
sql = """
	SELECT n.name
	FROM %s n
	WHERE n.ID = %s """ % (globals.tbl_notification_type, str(notificationTypeID))
```
env: python 3.4 & PyMySQL 0.7.1

**Comment by methane** [comment]
See #414, #422 and #423.
This exception is happen when PyMySQL is used in wrong way.

**Comment by methane** [comment]
If you think this exception is a bug of PyMySQL, please reproducible example code.

**Comment by ulugbekrozimboyev** [comment]
my app uses multi thread, it seems this library works differently on single and multi thread. can you tell me about difference or give me some link to documentation

**Comment by methane** [comment]
PyMySQL's threadsafety is 1.
https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/__init__.py#L37

It is defined in PEP 249
https://www.python.org/dev/peps/pep-0249/#threadsafety

> Threads may share the module, but not connections.

**Comment by teknogeek** [comment]
So how do you recommend people get around this problem then? I implement this in a project that makes many queries very frequently and it would make no sense for it to open a new connection each time. The way it was set up with `MySQLdb` was to allow everything to access a single connection and run all the queries over it...

**Comment by methane** [comment]
I use SQLAlchemy's pool.
Another way is threadpool. Each worker thread can have own connection.

Please don't use this issue tracker for ask a question.
Writing English takes much energy than writing Python for me.
Stackoverflow or ML is better place.
