### ISSUE TITLE
Cursor.lastrowid issue

### ISSUE THREAD

**Issue by Labouh** [PyMySQL/PyMySQL#429]
Hi,
I think there is an issue regarding compliance with PEP0249:
https://www.python.org/dev/peps/pep-0249/#lastrowid

We got an exception when retrieving latrowid after an insert on a table without a rowid.
AttributeError: 'Cursor' object has no attribute 'lastrowid'

But reading PEP0249 we can see that it should return None and not raise an exception!

Regards

**Comment by methane** [comment]
PyMySQL suports `lastrowid`:
https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/cursors.py#L308

Can you provide reproducible code with schema?

**Comment by Labouh** [comment]
Sorry 
I check the code and it is in the case of an executemany with multiple rows
PEP0249 is clear on the subject: 
The semantics of  .lastrowid  are undefined in case the last executed statement modified more than one row, e.g. when using  INSERT  with  .executemany()  .

And in your case it throw an execution...

**Comment by methane** [comment]
OK.  While the exception helps you to find your bug, preferred behavior is to return None.
