### ISSUE TITLE
main script is executed twice when import pymysql

### ISSUE THREAD

**Issue by opencookie** [PyMySQL/PyMySQL#437]
Hi, All.

I'm using
win7
python 3.5.1
MariaDB 10.1
PyMySQL 0.7.2

My main python script is executed twice when import pymysql.
When I import sqlite3, no problem.
What should i do?

**Comment by methane** [comment]
> What should i do?

I think you should read this thread. :-)
https://mail.python.org/pipermail/python-ideas/2016-January/038165.html

**Comment by opencookie** [comment]
I changed names variously.(now, wh_server.py)

**Comment by opencookie** [comment]
Sorry, It's a problem about Flask and PyCharm.
