### ISSUE TITLE
Error：AttributeError: 'SocketIO' object has no attribute '_checkClosed'

### ISSUE THREAD

**Issue by HanWenfang** [PyMySQL/PyMySQL#438]
Please Help!! Python 2.7 ! When ran the first sql, I met this exception! How to solve this exception!! 

**AttributeError: 'SocketIO' object has no attribute '_checkClosed'**

**Comment by methane** [comment]
Which Python 2.7?

SocketIO inherits io.RawIOBase and io.RawIOBase has _checkClosed.

**Comment by HanWenfang** [comment]
Python 2.7.3 (f66246c46ca30b26a5c73e4cc95dd6235c966b8f, Jul 30 2013, 09:27:06)
[PyPy 2.0.2 with GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2

**Comment by HanWenfang** [comment]
I found it doesn't have it. 

>>>> dir(io.RawIOBase)
['__abstractmethods__', '__class__', '__delattr__', '__dict__', '__doc__', '__enter__', '__exit__', '__format__', '__getattribute__', '__hash__', '__init__', '__iter__', '__metaclass__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_checkReadable', '_checkSeekable', '_checkWritable', 'close', 'closed', 'flush', 'isatty', 'next', 'read', 'readable', 'readall', 'readline', 'readlines', 'seekable', 'tell', 'writable', 'writelines']

**Comment by HanWenfang** [comment]
I find it didn't have it.

>>>> dir(io.RawIOBase)
['__abstractmethods__', '__class__', '__delattr__', '__dict__', '__doc__', '__enter__', '__exit__', '__format__', '__getattribute__', '__hash__', '__init__', '__iter__', '__metaclass__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_checkReadable', '_checkSeekable', '_checkWritable', 'close', 'closed', 'flush', 'isatty', 'next', 'read', 'readable', 'readall', 'readline', 'readlines', 'seekable', 'tell', 'writable', 'writelines']

**Comment by methane** [comment]
Your PyPy is too old.
Try PyPy 5.0.1

**Comment by HanWenfang** [comment]
I am using the Centos, its Version is too old, but I cannot update it now. Can you fix it? Please help!

**Comment by methane** [comment]
Try this: https://github.com/squeaky-pl/portable-pypy

There are many bugs (including security issue) fixed after Python 2.7.3.
I won't pay any effort to support such a version.

**Comment by HanWenfang** [comment]
Thanks for your help! @methane

**Comment by methane** [comment]
I recommend you to use new PyPy.
Using old software is dangerous as using IE6 on WinXP to browse web.

But, if you run your software on closed network, you may be able to modify PyMySQL to work.
I give you a hint.
https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L48-L83

There is a code for Python 2.6 (while PyMySQL doesn't support Python 2.6 officially).
You can modify this file to use code for Python 2.6.
