### ISSUE TITLE
Readme file says the dict key is "password" but really it's "passwd"

### ISSUE THREAD

**Issue by consolibyte** [PyMySQL/PyMySQL#440]
In the readme it says to use this to connect: 

```
connection = pymysql.connect(host='localhost',
                             user='user',
                             password='passwd',
                             db='db',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)
```

This isn't actually correct. The `password` key should be `passwd`. It should be: 

```
connection = pymysql.connect(host='localhost',
                             user='user',
                             passwd='passwd',
                             db='db',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)
```

**Comment by methane** [comment]
Have you read the docstring or code?

**Comment by consolibyte** [comment]
Yes, the example and docstring works fine. The actual library works fine. 

But your readme file is incorrect. So, if someone copy/pastes from your readme file, they get an error. 

The actual code is perfectly fine and I got it to work. I was just trying to let you know that your readme file is misleading people...

**Comment by methane** [comment]
> But your readme file is incorrect. So, if someone copy/pastes from your readme file, they get an error.

Could you paste the error?

**Comment by methane** [comment]
> Yes, the example and docstring works fine. The actual library works fine.

docstring says:

```
        password: Password to use.
...
        passwd: Alias for password. (for compatibility to MySQLdb)
```

Is it fine?  What's the issue?

**Comment by methane** [comment]
Please don't file an issue before you actually confirm the problem.
I have some projects and little daughter.  My time is not cheap.
