### ISSUE TITLE
pymysql.connect   KeyError: 224

### ISSUE THREAD

**Issue by haveNoName** [PyMySQL/PyMySQL#442]
```pytb
  File "build/bdist.macosx-10.10-intel/egg/pymysql/__init__.py", line 93, in Connect
    return Connection(*args, **kwargs)
  File "build/bdist.macosx-10.10-intel/egg/pymysql/connections.py", line 510, in __init__
    self._connect()
  File "build/bdist.macosx-10.10-intel/egg/pymysql/connections.py", line 676, in _connect
    self._get_server_information()
  File "build/bdist.macosx-10.10-intel/egg/pymysql/connections.py", line 830, in _get_server_information
    self.server_charset = charset_by_id(self.server_language).name
  File "build/bdist.macosx-10.10-intel/egg/pymysql/charset.py", line 173, in charset_by_id
    return _charsets.by_id(id)
  File "build/bdist.macosx-10.10-intel/egg/pymysql/charset.py", line 21, in by_id
    return self._by_id[id]
KeyError: 224
```

**Comment by methane** [comment]
Python version?
MySQL version?
Code?

**Comment by haveNoName** [comment]
mysql> status;
--------------
mysql  Ver 14.14 Distrib 5.5.43, for osx10.8 (i386) using readline 5.1


Python 2.7.6

conn = pymysql.connect(host="xxx", port=5002, user="xx",passwd="xx",db="xx",charset="utf8")

mysql> SHOW VARIABLES LIKE 'character%'
    -> ;
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | utf8mb4                    |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+

**Comment by methane** [comment]
PyMySQL version?

PyMySQL knows charset id 224.
https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/charset.py#L232

Your charset.py is same to above?

**Comment by haveNoName** [comment]
I saw three PyMySQL in python dir. Delete PyMySQL-0.6.6-py2.7.egg  PyMySQL3-0.5-py2.7.egg   
left PyMySQL-0.7.2-py2.7.egg.
It's OK .
Thanks a lot.
