### ISSUE TITLE
Confusing context manager

### ISSUE THREAD

**Issue by cthoyt** [PyMySQL/PyMySQL#446]
On line 799 of connections.py, the `__enter__` method returns `self.cursor()` rather than `self`. 

While this isn't a bug, I think it makes more sense to return `self` so as to adhere to the example below, which is a common pattern shared by most python connectors. This also allows more user flexibility while still taking advantage of the power of context managers.

```python
with pymysql.connect() as conn:
    with conn.cursor() as cur:
        print(cur)
```

Unfortunately I realize making a change like this might cause a lot of code to break, and must be carefully considered.

**Comment by methane** [comment]
> Unfortunately I realize making a change like this might cause a lot of code to break, and must be carefully considered.

Yes.  And current behavior is came from MySQL-python.
There are no choice for now.

**Comment by cthoyt** [comment]
Thanks for the insight, I appreciate it.

**Comment by kostix** [comment]
See also: #396

**Comment by evertrol** [comment]
I would think the (correct) behaviour can be achieved by setting a configuration parameter.
This can be either passed as argument to e.g. `connect()` or `Connection()`, or set at the package level itself (or even both: then the former should override the latter).

While backwards compatibility is something worth, in this case it is really unexpected, and the behaviour should at some point in the future be changed. Using a configuration parameter can ease that transition.

**Comment by methane** [comment]
There is no correct behavior.  DB-API 2.0 doesn't have `__enter__` definition.
So you should prefer code without context manager, or you should use convenient wrapper.

I dislike configuration.  There are too many options already.  Many people asks
questions without reading docstring.  When transition, I'll use normal deprecation process.

But problem is not **backward** compatibility.
Main problem is compatibility with well used but not maintained library: MySQL-python.

See also: PyMySQL/mysqlclient-python#44 and https://sourceforge.net/p/pypi/support-requests/553/

After it solved, I'll think about backward incompatible API changes with normal deprecation process.

**Comment by kostix** [comment]
I concur.  The behaviour of the context manager was surprising to me but what it needs is better documentation, not another configuration knob.  I solved that for me with a custom (and very simple) wrapper which explicitly implements whatever policy I wanted it to.
