### ISSUE TITLE
cursor.executemany() does not handle percent signs correctly vs. execute()

### ISSUE THREAD

**Issue by zzzeek** [PyMySQL/PyMySQL#449]
see also similar mysqlclient issue at https://github.com/PyMySQL/mysqlclient-python/issues/80

Below, a statement with percent signs succeeds for cursor.execute(), but fails for cursor.executemany() with:

    pymysql.err.InternalError: (1054, u"Unknown column 'A%%' in 'field list'")

oddly, adding a preceding space to the statement resolves it. 

    def run_test(conn):
        cursor = conn.cursor()
        cursor.execute("""
            DROP TABLE IF EXISTS percent_test
        """)
        cursor.execute("""
            CREATE TABLE percent_test (
            `A%` INTEGER,
            `B%` INTEGER
        )
        """)
        cursor.execute("SHOW CREATE TABLE percent_test")
        print cursor.fetchall()

        stmt = "INSERT INTO percent_test (`A%%`, `B%%`) VALUES (%s, %s)"

        # passes
        cursor.execute(stmt, (1, 2))

        # ?!!? passes ?!?!
        cursor.executemany(" " + stmt, [(3, 4), (5, 6)])

        # fails
        cursor.executemany(stmt, [(3, 4), (5, 6)])

        cursor.close()
        conn.commit()

    import pymysql
    conn = pymysql.connect(user="scott", passwd="tiger", db="test")

    run_test(conn)

**Comment by methane** [comment]
> oddly, adding a preceding space to the statement resolves it.

It's because this pattern doesn't allow preceding spaces.
https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/cursors.py#L15-L16

So executemany fallbacks to execute.
