### ISSUE TITLE
Working with gevent

### ISSUE THREAD

**Issue by byaka** [PyMySQL/PyMySQL#451]
I try to use pymysql with gevent. But seems like ```gevent.monkey.patch_all()```  don't affected pymysql.
Gevent and pymysql all latest versions.

```python
import gevent.monkey
gevent.monkey.patch_all()

import flask
import pymysql.cursors
from gevent.pywsgi import WSGIServer

app = flask.Flask(__name__)
app.debug = False

@app.route('/test1')
def test1():
    tArr={'host': '', 'password': '', 'db': '', 'user': ''}
    # q='SELECT SLEEP(5)' # with this request server not blocked
    q='SELECT pageId FROM siteParser3.sitePages WHERE siteId=52495' #some heavy and long request

    print '>> before pymysql'
    connection = pymysql.connect(**tArr)
    cursor=connection.cursor()
    cursor.execute(q)
    s=cursor.fetchall()
    connection.close()
    print '>> after pymysql'

    return 'ok'

@app.route('/hi')
def hi():
    print '<< hi'
    return 'hello world'

if __name__ == '__main__':
    WSGIServer(('0.0.0.0', 7001), app, log='default').serve_forever()
    # app.run(debug=False, host='0.0.0.0', port=7001, threaded=True)

```

One strange thing. With query like `SELECT SLEEP(5)` all work fine. But with real heavy and slow query, server will be blocked until request not end.

**Comment by methane** [comment]
> With query like SELECT SLEEP(5) all work fine.

This means PyMySQL works nice with gevent.

> But with real heavy and slow query, server will be blocked until request not end.

Isn't your machine is just overloaded unresponsive?

**Comment by byaka** [comment]
> Isn't your machine is just overloaded unresponsive?
No. Please try this example with any query, that return large pack of rows.

**Comment by methane** [comment]
> that return large pack of rows.

It can easily overload your gevent app.
gevent (or asyncio or tornado) is suitable for handling massive idle connections.
Receiving and parsing large data can't be non blocking.
