### ISSUE TITLE
execute encoded sql statement occurs ProgrammingError

### ISSUE THREAD

**Issue by lasteye** [PyMySQL/PyMySQL#452]
Hi, when executing following SQLsatatement, PyMySQL raises ProgramingError.
`insert into test.test_0 values (14, '\xb4\\')`
`\xb4\\` (encoding gb18030)

**Comment by methane** [comment]
Too few information and I don't want to pay time to ask "What is your XXX" for you.
How about go Q&A site?
If no one resolve the issue, please write all information you asked there.
(Or you can write a link to the thread if discussion is in English).

**Comment by lasteye** [comment]
@methane Thanks for your reply. Let me show you the context:
 #!/usr/bin/python2
#coding:utf8

import pymysql

cnn = pymysql.connect(user='root',host='localhost',password='password')
cur = cnn.cursor()
sql = 'insert into test.test_0 values (1, "{0}")'

try:
    cur.execute(sql.format('\xb4\\'))
except Exception,e:
    print(str(e))
finally:
    cur.close()
    cnn.close()

Following ouput when executing above script: 
> (1064, u'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'"\ufffd\\")\' at line 1')

the table structure of **test.test_0** is:
`mysql> show create table test.test_0\G
*************************** 1. row ***************************
       Table: test_0
Create Table: CREATE TABLE `test_0` (
  `id` int(11) NOT NULL,
  `name` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
1 row in set (0.00 sec)
`

**Comment by methane** [comment]
Do you know escaping?  It seems general question about SQL.
I think you should study about how to construct SQL safely.
I'm not free tech support or your teacher.
Please ask your colleague or ML instead filing issue.
