### ISSUE TITLE
ON DUPLICATE with executemany

### ISSUE THREAD

**Issue by bemeurer** [PyMySQL/PyMySQL#462]
I'm attempting to do the following
```
# Executes query for each dictionary in member.
cursor.executemany("INSERT INTO `citizens` (`handle`,`org`,`role`, "
                                 "`rank`,`visibility`,`stars`,`type`) VALUES "
                                 "(%(handle)s,%(sid)s,%(roles)s,%(rank)s,"
                                 "%(visibility)s,%(stars)s,%(type)s) ON DUPLICATE"
                                 " KEY UPDATE `org`=concat(ifnull(`org`, ''), "
                                 " ', ', %(sid)s);", member)
# Commits changes to the database.
conn.commit()
```
However when running said code the following happens:
```
There was a problem inserting member(s): (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%(sid)s)' at line 1")
```
And if I print the failed query it looks like [this](https://gist.github.com/bemeurer/b483cd66d52ee7518d16897875f5084d). The variable `member` is a list composed of dictionaries with identical keys, as shown [here](https://gist.github.com/bemeurer/5068fd9569c2f980e36a5bbf87c57c8d).

The code is being run on Python 3.5.1 with PyMySQL 0.7.3
on Arch x64 with the latest updates. The database is running MySQL 5.6.30.

**Comment by methane** [comment]
What is `%(sid)s` ???
It can't be executemany.

**Comment by methane** [comment]
executemany is utility for building query like "... VALUES (row1), (row2), (row3), ... ".
So `ON DUPLICATE KEY` clause can't include placeholder.
You should `.execute()` repeatedly.
