### ISSUE TITLE
Request failover and high availability awareness

### ISSUE THREAD

**Issue by destinymedia** [PyMySQL/PyMySQL#470]
It is increasingly common to maintain a cluster of MySQL instances with the ability to failover. Switching is left to either the application or the hosting environment, yet our drivers could share the responsibility with the cluster. 

Some cluster implementations such as aws-rds update a dns entry to point to the new master, but local dns caching causes an unnecessary delay in a time sensitive failover event. Readonly queries could be redirected a slave instance to balance the load on the cluster, but knowing which instance to connect to becomes the applications responsibility.

Cluster structures can be discoverable. The aws-aurora cluster for example can provide details about the cluster layout and failover events allowing the driver to know if the master has changed and gain a list of all the slaves. Alternatives could be the connection options identifying a list of slaves.

The mariadb connector added failover and high availability awareness to the Java connector recently and is worth reviewing for ideas. The Amazon Aurora team has been working with them on adding cluster aware features into the connector.
https://mariadb.com/kb/en/mariadb/failover-and-high-availability-with-mariadb-connector-j/

My interest is with Aurora clusters, but there is a general feature here.

By identifying the cluster, the driver can switch to another instance immediately if the cluster reports a failover, or balance the load using a round robin or randomizer. This also allows readonly SQL activities to be automatically sent to a readonly instances (slaves) in the cluster where all writing (master) SQL activities remain with the writing instance (master) in the cluster.

**Aurora** failover management steps:
1. Instance A is in write replication mode, instance B and C are in read replication mode.
2. Instance A fails.
3. Cluster detects A failure, and promote instance B in write mode. Instance C will change its master to use B.
4. Cluster end-point will change to instance B end-point.
5. Instance A will recover and be in read replication mode. 

**Sequential** failover management steps:
1. identify all instances in the cluster (ex: host1, host2, host3)
2. attempt to connect to a host in order listed in connection settings

**Comment by methane** [comment]
Sorry, but I don't want to implement such feature in this project.
Such a feature should be implemented in "connection pool", and this project focus on "connection".

You can build connection pool on top of this project.
Having higher level connection pool allows user can select low level driver.  For example, mysqlclient and PyMySQL.
