### ISSUE TITLE
Python3 slow query execution

### ISSUE THREAD

**Issue by paulfantom** [PyMySQL/PyMySQL#475]
I am creating mysql plugin for grabbing "GLOBAL STATUS" data for [netdata](https://github.com/firehol/netdata). It executes one query ("SHOW GLOBAL STATUS") every second which doesn't carry very much data. However I found that your implementation of `cursor.execute(query)` is sluggish. It takes about 2-3x more time than MySQLdb implementation. After some investigation I think that the main reason behind it is usage of `socket.makefile()` which has some well known performance issues (https://bugs.python.org/issue18329)

**Comment by methane** [comment]
https://bugs.python.org/issue18329 is about `for line in fileobj`.
PyMySQL doesn't uses it.

I measured performance again and again.  I believe performance bottleneck is parsing packet, not reading.

> After some investigation

Results?

**Comment by methane** [comment]
When loading large number of records, I think bottleneck is here:
https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L1399-L1428

MySQLdb uses C implementation.  3x slower than MySQLdb is good enough for current PyMySQL.

**Comment by paulfantom** [comment]
All times are measured on old PC with intel Atom and populated mysql database.
I am using time() from python time library.
Results:
```
sql = "SHOW GLOBAL STATUS"
cursor.execute(sql):
PyMySQL: ~0.0397s
MySQLdb: ~0.0082s
```

I have checked you suspicions and you are right:
```
_read_result_packet(first_packet): ~0.0332s

average of one iteration of while loop in _read_rowdata_packet: ~0.00007s
average of self.connection._read_packet() in _read_rowdata_packet: ~0.00004s
while loop iterates 446 times
```

Do you have any recommendations how can I speed it up other than using MySQLdb? (google didn't help much)

**Comment by methane** [comment]
How about CyMySQL?
https://github.com/nakagami/CyMySQL/

I'm closing this issue since there is #297 already.

**Comment by paulfantom** [comment]
Ok, thanks.
