### ISSUE TITLE
Test failures with MySQL 5.7 in Ubuntu Xenial and Yakkety

### ISSUE THREAD

**Issue by ltangvald** [PyMySQL/PyMySQL#478]
At https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/tests/test_issues.py#L460 (and 470)
the test checks for python version > 3.2 and MySQL version to see if it should expect the deprecation warning 5.7 will give for the statement. However, this warning is also thrown when running the test with python 2.7, causing the test to fail when building the python-pymysql package in Ubuntu Xenial and Yakkety.
Ubuntu Launchpad bug: https://bugs.launchpad.net/ubuntu/+source/python-pymysql/+bug/1592664

## Suggested fix ##
Simply removing the check on python version seems to fix the issue.

**Comment by methane** [comment]
thanks

**Comment by ltangvald** [comment]
The code on line 470 has the same issue, though (AsText and AsBinary are both deprecated)

**Comment by methane** [comment]
@ltangvald I'm sorry about it.
Do you really need release?

I don't want to make a new release only for test failure on certain environment,
without real bugfix in library code.

**Comment by ltangvald** [comment]
@methane For the Ubuntu package we can fix it with a patch in the packaging scripts (which refers to this bug so we can keep track of when it's fixed upstream), so you don't need to rush it :)
