### ISSUE TITLE
PyMySQL custom converters reset to default / not used

### ISSUE THREAD

**Issue by aavanian** [PyMySQL/PyMySQL#499]
When creating a mysql engine with pymysql and custom converters, the converters dict passed in parameter is taken in account in the pymysql connection object but during a commit, it seems encoders revert to the default ones. See below some sample code.
The error "AttributeError: 'Timestamp' object has no attribute 'translate'" occurs when pymysql cannot find a converter for the type of the value passed. Dropping in debugger confirms that the encoders are the default ones and the value is of type pandas.Timestamp.

## Expected Behavior
it should execute without error
## Current Behavior
fails with AttributeError: 'Timestamp' object has no attribute 'translate'

## Executable script to reproduce (for bugs)

```
import pymysql
from pymysql.converters import conversions, escape_datetime
from pandas import Timestamp
from datetime import datetime

assert escape_datetime(Timestamp('2016-08-12 08:45:00')) == escape_datetime(datetime(2016, 8, 12, 8, 45))
conversions[Timestamp] = escape_datetime

conn = pymysql.connect(user='scott', passwd='tiger', host='localhost', db='test', conv=conversions )
cursor = conn.cursor()

cursor.execute("create table if not exists stuff (data datetime)")

cursor.execute("insert into stuff (data) values (%s)", (Timestamp('2016-08-12 08:45:00')))
```

## Tracebacks (for bugs)

```
Traceback (most recent call last):
  File "C:\Users\alexandre.avanian\AppData\Local\Continuum\Anaconda3\envs\vol_tools\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-4ebb3d89c226>", line 15, in <module>
    cursor.execute("insert into stuff (data) values (%s)", (Timestamp('2016-08-12 08:45:00')))
  File "C:\Users\alexandre.avanian\AppData\Local\Continuum\Anaconda3\envs\vol_tools\lib\site-packages\pymysql\cursors.py", line 165, in execute
    query = self.mogrify(query, args)
  File "C:\Users\alexandre.avanian\AppData\Local\Continuum\Anaconda3\envs\vol_tools\lib\site-packages\pymysql\cursors.py", line 144, in mogrify
    query = query % self._escape_args(args, conn)
  File "C:\Users\alexandre.avanian\AppData\Local\Continuum\Anaconda3\envs\vol_tools\lib\site-packages\pymysql\cursors.py", line 130, in _escape_args
    return conn.escape(args)
  File "C:\Users\alexandre.avanian\AppData\Local\Continuum\Anaconda3\envs\vol_tools\lib\site-packages\pymysql\connections.py", line 794, in escape
    return escape_item(obj, self.charset, mapping=mapping)
  File "C:\Users\alexandre.avanian\AppData\Local\Continuum\Anaconda3\envs\vol_tools\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "C:\Users\alexandre.avanian\AppData\Local\Continuum\Anaconda3\envs\vol_tools\lib\site-packages\pymysql\converters.py", line 110, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "C:\Users\alexandre.avanian\AppData\Local\Continuum\Anaconda3\envs\vol_tools\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Timestamp' object has no attribute 'translate'
```

## Your Environment
* Operating System and version: Windows 10
* Python version and build: Python 3.4.4 |Continuum Analytics, Inc.| (default, Feb 16 2016, 09:54:04) [MSC v.1600 64 bit (AMD64)]
* PyMySQL Version used: 0.7.6

**Comment by methane** [comment]
It's not a bug. It's a design.
And I don't recommend to use conv.  You can convert values before passing it to cursor.

**Comment by aavanian** [comment]
Ok, fair enough, a few follow-up questions:
* May I ask why:
 * conv will only change connection behavior but not cursor? It actually seems conv will be ignored for everything but literal (that's from a quick browse of the code, I may be wrong: the converters.escape functions always refers to the default global encoders and are called with mapping = None for everything but literal)
 * you don't recommend using conv?
* Shouldn't this be documented?

I thought handling value conversion at the end point would be the best solution

**Comment by methane** [comment]
>
> May I ask why:
>
> conv will only change connection behavior but not cursor? It actually seems conv will be ignored for everything but literal (that's from a quick browse of the code, I may be wrong: the converters.escape functions always refers to the default global encoders and are called with mapping = None for everything but literal)

You're right.  It's a long living bug.  But I'm happy about no one use it.

> you don't recommend using conv?

No, I don't recommend using conv. The reason is (1) API is somewhat
broken, (2) too difficult for normal users.

For example, Encoders and decoders are executed in different layer.
Normal users may be surprised about it.
But it has reason.  Encoders are for creating SQL. But decoders are
not for parsing SQL.

And when I support another protocol (e.g. x protocol or prepared
statement), all of converters are broken.

Even for current text protocol, decoders can't use enough information
(connection encoding and column flags)
and encoders can't know about connection encoding and how to escape properly.


>
> Shouldn't this be documented?
>

Contribution welcome.
I'm not good at reading and writing English.  English is 1000x
difficult than Python and 100x difficult than C.

> I thought handling value conversion at the end point would be the best solution
>

Endpoint is layered.  For example, NIC is endpoint. I believe you
agree that NIC firmware is not good place for
converting user-defined Python types.

conv is lower level layer too.  It is bound to MySQL protocol.
Higher level conversion should be done in upper layer: ORM.

-- 
INADA Naoki  <songofacandy@gmail.com>
