### ISSUE TITLE
Field containing a data larger than 59K causes an error

### ISSUE THREAD

**Issue by ahmetax** [PyMySQL/PyMySQL#500]
Any mediumtext or largetext fields containing a data larger than 59K, fires an error: pymysql.err.Error: (<class 'TypeError'>, TypeError("a bytes-like object is required, not 'int'",)).
Problem occurs when cursor.execute(query) is called. Charset is utf8.
When the existing data is made shorter than 59K, problem is solved. 

## Executable script to reproduce (for bugs)

code:
```python
import pymysql.cursors

# Connect to the database
connection = pymysql.connect(host='localhost',
                             user='user',
                             password='passwd',
                             db='db',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

try:
    with connection.cursor() as cursor:
        # Create a new record
        sql = "INSERT INTO `users` (`email`, `password`) VALUES (%s, %s)"
        cursor.execute(sql, ('webmaster@python.org', 'very-secret'))

    # connection is not autocommit by default. So you must commit to save
    # your changes.
    connection.commit()

    with connection.cursor() as cursor:
        # Read a single record
        sql = "SELECT `id`, `password` FROM `users` WHERE `email`=%s"
        cursor.execute(sql, ('webmaster@python.org',))
        result = cursor.fetchone()
        print(result)
finally:
    connection.close()
```

schema:
```sql
CREATE TABLE `users` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `email` varchar(255) COLLATE utf8_bin NOT NULL,
    `password` varchar(255) COLLATE utf8_bin NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
AUTO_INCREMENT=1 ;
```

## Tracebacks (for bugs)

```
paste here
```

## Your Environment

* Operating System and version: Ubuntu 16.04
* Python version and build (cygwin, python.org, homebrew, pyenv, Linux distribution's package, PyPy etc...) Python 3.5.1
* PyMySQL Version used: 0.5
* my.cnf if possible.  If you don't have it, related system variables like [connection encoding](https://dev.mysql.com/doc/refman/5.6/en/charset-connection.html).

**Comment by methane** [comment]
> PyMySQL Version used: 0.5

It's too old. Can you reproduce it with 0.7.6?

**Comment by ahmetax** [comment]
Thank you. I will try it.

**Comment by ahmetax** [comment]
I installed version 0.7.6, and the problem is resolved.

Thank you very much.
