### ISSUE TITLE
How to get rows affected in a UPDATE statement.

### ISSUE THREAD

**Issue by Xie-Zhibin** [PyMySQL/PyMySQL#502]
## See the title, how can i know the number of affected rows affected, Thx.

**Comment by methane** [comment]
**[You must not ask a question on issue tracker](https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde#.hdf6lpk11)**

**Comment by Xie-Zhibin** [comment]
Oh, I'm very sorry.
