### ISSUE TITLE
0.7.7 breaks 'show slave status' output

### ISSUE THREAD

**Issue by jasonvangundy** [PyMySQL/PyMySQL#510]
using version >= 0.7.7, after executing "show slave status" sql, calling cursor.fetch* returns None.  I have rolled back to version 0.7.6 and confirmed it's working fine.

**Comment by methane** [comment]
I don't have develop environment using replication setup.
Could you try this?

```py
import pymysql
pymysql.connections.debug = True
conn = pymysql.connect(...)
cursor = conn.cursor()
cursor.execute("SHOW SLAVE STATUS")
print(cursor.fetchall())
```

**Comment by methane** [comment]
#513 may fix this.  Can you try 0.7.9?
