### ISSUE TITLE
Query doesn't return all results

### ISSUE THREAD

**Issue by joshusre** [PyMySQL/PyMySQL#518]
If I loop this query:
 sql = "select timestamp from log_message.message_bundle where timestamp between {t} and {n} order by timestamp desc;".format(n=timestampfornow, t=timestampforhalfanhourago)
I recieve less results than are actually present in my db.  I believe it also propagates exponentially, as the result become more and more incorrect as I run the loop.

## Expected Behavior
Return all rows in db that fit query.

## Current Behavior
It doesn't

current stamps then 1475160162 now 1475158362
select timestamp from log_message.message_bundle where timestamp between 1475158362 and 1475160162 order by timestamp desc;
results 1228 (actual 1228)
current stamps then 1475160172 now 1475158372
select timestamp from log_message.message_bundle where timestamp between 1475158372 and 1475160172 order by timestamp desc;
results 1228 (actual 1276) 
current stamps then 1475160182 now 1475158382
select timestamp from log_message.message_bundle where timestamp between 1475158382 and 1475160182 order by timestamp desc;
results 1227(actual 1279)

from a while loop that calls the function over and over.  Results eventually drops to 0.

## Executable script to reproduce (for bugs)

code:
```python

def get_conn(config_dict):
    return pymysql.connect(host=config_dict["sql"]["ip"],
                           port=int(config_dict["sql"]["port"]),
                           user=config_dict["sql"]["user"],
                           passwd=config_dict["sql"]["pw"],
                           db='mysql')

def get_message_proc_rate(conn):
    rightnow = int(time.time())
    halfhourago = int(time.time() - 1800)
    print "current stamps then{} now {}".format(rightnow, halfhourago)
    cur = conn.cursor(pymysql.cursors.DictCursor)
    sql = "select timestamp from log_message.message_bundle where timestamp between {t} and {n} order by timestamp desc;".format(n=rightnow,
                                                                                                  t=halfhourago)
    print sql
    cur.execute(sql)
    data = cur.fetchall()
    print "results {}".format(len(data))

sqlite_conn = mysql_lib.get_conn([login_params)

while True:
    mysql_lib.get_message_proc_rate(sqlite_conn)
    time.sleep(5)

**Comment by methane** [comment]
Google "repeatable read".

**Comment by joshusre** [comment]
You're right.  Sorry for bothering you and thank you for helping me.
Apologies.
