### ISSUE TITLE
DictCursor fetchall() return type is inconsistent - usually a list, but a tuple if there are no results

### ISSUE THREAD

**Issue by ExplodingCabbage** [PyMySQL/PyMySQL#521]
## Expected Behavior
`DictCursor`'s `fetchall()` method should always return a list

## Current Behavior
When the result set is empty, `DictCursor`'s `fetchall()` returns an empty tuple; otherwise, it returns a list. This creates annoying traps like concatenating together the results from `fetchall()` with `+` failing in the special case that any of the results are empty unless the programmer using the library knows to coerce the result to a list first.

## REPL output demonstrating bug

```
>>> cur = conn.cursor(pymysql.cursors.DictCursor)
>>> cur.execute('create table foo (bar int)')
0
>>> cur.execute('insert into foo values (1),(2),(3)')
3
>>> cur.execute('select * from foo')
3
>>> cur.fetchall()
[{'bar': 1}, {'bar': 2}, {'bar': 3}]
>>> cur.execute('select * from foo where false')
0
>>> cur.fetchall()
()
```

I don't have time to provide more info while at work, but will check things like version numbers  when I have the chance.

**Comment by methane** [comment]
DB-API 2.0 says only "a sequence of sequences".

Although I agree that inconsistency is annoying, MySQL-python has this behavior from
many years ago.  And some code tightly depends actual type returned.  (e.g. `== ()`)

I can't change the behavior in foreseeable future.
