### ISSUE TITLE
Permission for publication of PyMySQL stubs in typeshed

### ISSUE THREAD

**Issue by ghagerer** [PyMySQL/PyMySQL#524]
I started to generate stubs for PyMySQL, which I uploaded to [this repo](https://github.com/ghagerer/pymysql_stubs).

I want to commit all this as third party stubs to the [typeshed repo](https://github.com/python/typeshed) as I stated it in [an issue there](https://github.com/python/typeshed/issues/631). According to the guidelines of typeshed and [PEP484](https://www.python.org/dev/peps/pep-0484/#the-typeshed-repo) respectively, the official permission from the regarding project for which the stubs are generated is necessary.

So, does the PyMySQL project agree that stubs generated for this project are published as third party stubs as part of the typeshed project?

Thanks in advance!

**Comment by methane** [comment]
Thanks, go ahead!

One point:
https://github.com/ghagerer/pymysql_stubs/blob/master/__init__.pyi#L30-L33

```
def Connect(*args, **kwargs) -> Connection: ...
def get_client_info() -> str: ...

connect = ...  # type: Any
```

`connect` should be defined as function which signature is same to `Connect`.
`Connect` is only for backward compatibility. `connect` is standard (defined in DB-API 2.0) API.

**Comment by ghagerer** [comment]
Thanks! I will include the connect issue in future.
