### ISSUE TITLE
converters._escape_unicode() should explicitly call unicode()

### ISSUE THREAD

**Issue by pczerkas** [PyMySQL/PyMySQL#525]
converters._escape_unicode() should explicitly call unicode() on the value, before calling .translate() on it. Custom objects can be passed as parameters to SQL query, but in case of unknown object type (in encoders dict) pymysql should let such value to leverage Python protocol methods (__str__, __unicode__)

Problem manifests itself e.g. when using Django GEO/GIS GeometryField() model field.

## Expected Behavior

def _escape_unicode(value, mapping=None):
    """escapes *value* without adding quote.

    Value should be unicode
    """
    return unicode(value).translate(_escape_table)

## Current Behavior

def _escape_unicode(value, mapping=None):
    """escapes *value* without adding quote.

    Value should be unicode
    """
    return value.translate(_escape_table)

## Executable script to reproduce (for bugs)

code:
```python
import pymysql.cursors

# Connect to the database
connection = pymysql.connect(host='localhost',
                             user='user',
                             password='passwd',
                             db='db',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

try:
    with connection.cursor() as cursor:
        # Create a new record
        sql = "INSERT INTO `users` (`email`, `password`) VALUES (%s, %s)"
        cursor.execute(sql, ('webmaster@python.org', 'very-secret'))

    # connection is not autocommit by default. So you must commit to save
    # your changes.
    connection.commit()

    with connection.cursor() as cursor:
        # Read a single record
        sql = "SELECT `id`, `password` FROM `users` WHERE `email`=%s"
        cursor.execute(sql, ('webmaster@python.org',))
        result = cursor.fetchone()
        print(result)
finally:
    connection.close()
```

schema:
```sql
CREATE TABLE `users` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `email` varchar(255) COLLATE utf8_bin NOT NULL,
    `password` varchar(255) COLLATE utf8_bin NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
AUTO_INCREMENT=1 ;
```

## Tracebacks (for bugs)

```
paste here
```

## Your Environment

* Operating System and version:
* Python version and build (cygwin, python.org, homebrew, pyenv, Linux distribution's package, PyPy etc...)
* PyMySQL Version used:
* my.cnf if possible.  If you don't have it, related system variables like [connection encoding](https://dev.mysql.com/doc/refman/5.6/en/charset-connection.html).

**Comment by methane** [comment]
Please write "Expected Behavior" and "Current Behavior" with code using public API,
not private API.
It doesn't help I understand what is the problem.

**Comment by methane** [comment]
And please remove sample code from issue template if you cannot provide it.

**Comment by methane** [comment]
ping

**Comment by methane** [comment]
Close since no reply for long time.

**Comment by tuky** [comment]
I stumbled upon this very exact same issue and others had it before: https://stackoverflow.com/questions/43502086/django-geo-mysql-query-error-wktadapter-object-has-no-attribute-translate/.

Django by default uses the `mysqlclient` package, but usage of `PyMySQL` is possible by running `pymysql.install_as_MySQLdb()`. So I would argue, that both should behave the same. Django sends very simple `WKTAdapter` objects to the connection. `WKTAdapter` implements an `__str__` method so it can be escaped. Now comes the difference:

- `literal` from `mysqlclient` (https://github.com/PyMySQL/mysqlclient-python/blob/e52812fd15084344910d4eb55b4a6d3b12ef1baf/MySQLdb/connections.py#L238) works for `WKTAdapter`
- `literal` from `PyMySQL` https://github.com/PyMySQL/PyMySQL/blob/3674bc6fd064bf88524e839c07690e8c35223709/pymysql/connections.py#L462 does not work with `WKTAdapter`.
