### ISSUE TITLE
Object cursor.execute(mySQLCommand) throws AttributeError exception

### ISSUE THREAD

**Issue by onvav** [PyMySQL/PyMySQL#527]
Object cursor.execute(mySQLCommand) throws AttributeError exception

## Expected Behavior
Database connection is lost, then program calls:
```
with database.cursor() as cur:
    cur.execute(sqlCmd)
    result = cur.fetchall()
```

Then pymysql.Error exception is raised.

## Current Behavior
Database connection is lost, then program calls:
```
with database.cursor() as cur:
    cur.execute(sqlCmd)
    result = cur.fetchall()
```

Then AttributeError exception is raised instead expected pymysql.Error.

## Possible Solution
It is necessary use workaround and catch pymysql.Error and AttributeError too.
Maybe self._rfile should be checked before using it?

## Tracebacks (for bugs)
```
....
  File "/home/pi/TraceScripter/trcscr/trcscr.py", line 935, in getTagStatusFromDB
    cur.execute(sqlCmd)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 835, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 1019, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 1302, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 961, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 988, in _read_bytes
    data = self._rfile.read(num_bytes)
AttributeError: 'NoneType' object has no attribute 'read'
```

* Operating System and version: Raspbian Jessie, Raspberry Pi 3
* Python: Python 3.4 (python.org)
* PyMySQL Version used: 0.7.9

**Comment by methane** [comment]
Did you use closed connection????

**Comment by onvav** [comment]
Thank you for your quick response. Now I have more detailed information and you are right. It will be somehow connected with closed connection. Because:
1. the connection is established by the script
2. Ethernet cable is disconnected, so no connection with database server. Script has no clue about it.
3. First query atempt => throws pymysql exception, the scripts just passed it and continues without explicit closing connection. So correct and expected behavior.
4. Second query atempt in same statement =>throws AttributeError exception

If the connection had been closed in 3.step, then atempt in 4. step was used with closed connection.
But still, I am not sure whether AttributeException is appropriately descriptive.
Is it necessary to check connection.open before cursor.execute to prevent AttributeError?

**Comment by methane** [comment]
> Is it necessary to check connection.open before cursor.execute to prevent AttributeError?

Explicitly close the connection and create new connection when you catch pymysql exception.

**Comment by onvav** [comment]
Thanks for advice!
