### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by ftrotter** [PyMySQL/PyMySQL#530]
## Expected Behavior
I read the documentation and I understand what the various implications are for your configuration and setup calls.

## Current Behavior
I read your documentation and I see the arguments listed, but not explained. 

## Possible Solution
improve the quality of your documentation

## Executable script to reproduce (for bugs)
not a code bug

## Context
Specifically I am getting a timeout, and i want to know what valid parameters to connect_timeout and what the implications of passing 'None' in are. This information should be available for every setup parameter, either by reference into mysql documentation or inline.

## Your Environment
n/a

* Operating System and version: 
n/a
* Python version and build (cygwin, python.org, homebrew, pyenv, Linux distribution's package, PyPy etc...)
n/a
* PyMySQL Version used:
n/a
* my.cnf if possible.  If you don't have it, related system variables like [connection encoding](https://dev.mysql.com/doc/refman/5.6/en/charset-connection.html).
n/a
,

**Comment by methane** [comment]
I'm bad at English writing.
I won't fix this issue.  But contribution is welcome.

**Comment by methane** [comment]
#541 fixed specific issue about `connect_timeout`.

In general, I won't fix.  Contribution is welcome.
I close this issue, because I don't want to miss more real issues.
