### ISSUE TITLE
Selecting data in loop returns not all records

### ISSUE THREAD

**Issue by tomasrasymas** [PyMySQL/PyMySQL#533]
Hello,

1. xxx table contains one record id = 1
2. I am starting script
```
import pymysql
import time
connection = pymysql.connect(host="127.0.0.1",
                                           port=3306,
                                           user="xxx",
                                           passwd="xxx",
                                           db="station",
                                           charset='utf8',
                                           cursorclass=pymysql.cursors.DictCursor)

while True:
    with connection.cursor() as cursor:
        sql = "select * from xxx"
        cursor.execute(sql)
        result = cursor.fetchall()
        print result

    time.sleep(5)

connection.close()
```

3. While my script is running  i open MySQLWorkbench and insert new record to xxx table, etc. id = 2
4. Problem: my script can not select new inserted record. 

If i restart my script then it selects new inserted record id=2, but if then i insert another record from MySQLWorkbench it does not find it (unless i restart my script)

Can you explain how to retrieve all records from database in loop?

**Comment by methane** [comment]
https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde#.jpghtkuhf
