### ISSUE TITLE
Incorrect string value

### ISSUE THREAD

**Issue by seanmars** [PyMySQL/PyMySQL#536]
## Tracebacks (for bugs)

```
site-packages\pymysql\cursors.py:166: Warning: (1366, "Incorrect string value: '\\xA5x\\xA5_\\xBC\\xD0...' for column 'VARIABLE_VALUE' at row 480")
```

## Context
When i use the alembic, and just use command : alembic current

## Your Environment
* Operating System and version: Windows 10
* Python version and build (cygwin, python.org, homebrew, pyenv, Linux distribution's package, PyPy etc...): Python 3.5.2
* PyMySQL Version used: 0.8.9
* my.cnf:

```
[client]
default-character-set = utf8mb4
[mysql]
default-character-set = utf8mb4
[mysqld]
skip-character-set-client-handshake
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
```

**Comment by methane** [comment]
i can't reproduce.
too few and incomplete report.

**Comment by seanmars** [comment]
## env
Windows 10 + MySQL 5.7 + Python 3.5.2
## pip list:
```
alembic        0.8.9
Mako           1.0.6
MarkupSafe     0.23
pip            9.0.1
PyMySQL        0.7.9
python-editor  1.0.3
setuptools     32.1.2
SQLAlchemy     1.1.4
wheel          0.29.0
```

## Step

Just use alembic's command "current" to check the revision, then i got that warning message.

## my alembic.ini

```
# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migration

# template used to generate migration files
file_template = %%(year)d%%(month).2d%%(day).2d-%%(hour).2d%%(minute).2d%%(second).2d_%%(rev)s_%%(slug)s

# max length of characters to apply to the
# "slug" field
truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
sourceless = false

# version location specification; this defaults
# to migration/versions.  When using multiple version
# directories, initial revisions must be specified with --version-path
# version_locations = %(here)s/bar %(here)s/bat migration/versions

# the output encoding used when revision files
# are written from script.py.mako
output_encoding = utf-8

sqlalchemy.url = mysql+pymysql://user:passwd@localhost:3306/stock?charset=utf8mb4


# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
```

**Comment by methane** [comment]
```
$ pip install alembic==0.8.9 Mako==1.0.6 MarkupSafe==0.23 PyMySQL==0.7.9 python-editor==1.0.3 SQLAlchemy==1.1.4
...
Successfully installed Mako-1.0.6 MarkupSafe-0.23 PyMySQL-0.7.9 SQLAlchemy-1.1.4 alembic-0.8.9 python-editor-1.0.3
$ cat > alembic.ini
(copy and paset)
$ alembic current
  FAILED: Path doesn't exist: 'migration'.  Please use the 'init' command to create a new scripts folder.
```

Please try do in clean environment to make it "reproducible".
For example, Is it reproducible without creating any databases and tables?

**Comment by methane** [comment]
> `for column 'VARIABLE_VALUE'`

I can't find `VARIABLE_VALUE` in alembic.

**Comment by methane** [comment]
Please google "1366 Incorrect string value MySQL" before reporting issue.
I'm not free MySQL support.
Don't file an issue until you're sure this is a bug of PyMySQL.

**Comment by seanmars** [comment]
I'm so sorry for that, i'm really not sure this bug is PyMySQL or not.
Because i got the message from pymsql.

This is my test repository: https://github.com/seanmars/test.git

Just create the user 'test' with password 'test', and create the test database named 'test' with  utf8mb4_unicode_ci

```
pip install -r requirements.txt
alembic current
```

**Comment by methane** [comment]
```
$ alembic current -v
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
```

Did you really try it with **clean** database????

I think your database have non utf-8 data in utf8mb4 column. But I'm not sure.
It's not my business.

**Comment by seanmars** [comment]
Your mysql is installed on Windows 10 ?

**Comment by methane** [comment]
No, on Mac.

But your error message said: `for column 'VARIABLE_VALUE' at row 480")`
Does MySQL on Windows create table with VARIABLE_VALUE column and insert 480th row automatically?
I can't believe it.

**Comment by methane** [comment]
It is a warning message, not an error.
The message comes from MySQL server. PyMySQL just show it for you.

Why PyMySQL developer should investigate your MySQL server?

**Comment by seanmars** [comment]
Ok, i'll find another way to clean is issue.
Very thanks your help, and I'm sorry to bother you.

**Comment by seanmars** [comment]
Hi, i had try to test some situation.
MySQL's config is same => https://github.com/PyMySQL/PyMySQL/issues/536#issuecomment-268442972
Use the repository => https://github.com/seanmars/test

The Database are clean and just create a empty database named "test".
### Env A

Windows 10 + MySQL 5.7 + Python 3.4  + SQLAlchemy 1.1.4 + alembic 0.8.9 + ***PyMySQL 0.7.9***

### Env B

Windows 10 + MySQL 5.7 + Python 3.4  + SQLAlchemy 1.1.4 + alembic 0.8.9 + ***mysql-connector 2.1.4***

The Env A will got the warning message.

```
e:\pyvirtualenv\py34\lib\site-packages\pymysql\cursors.py:166: Warning: (1366, "Incorrect string value: '\\xA5x\\xA5_\\xBC\\xD0...' for column 'VARIABLE_VALUE' at row 480")
```

But the Evn B has no warning.

I know maybe this issue is not the PyMySQL's issue, just for your information.

**Comment by methane** [comment]
Yes, pymysql show warning for you.
mysql-connector doesn't do it by default.

https://dev.mysql.com/doc/connector-python/en/connector-python-connectargs.html

2016/12/22 午前2:12 "Mars" <notifications@github.com>:

**Comment by seanmars** [comment]
I know, so I had setting the get_warnings=true, and get nothing warning too.

**Comment by methane** [comment]
get_warning doesn't show warning.
You need fetchwarnings() and print manually.

https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursor-fetchwarnings.html

2016/12/22 午前10:17 "Mars" <notifications@github.com>:

**Comment by methane** [comment]
https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlconnection-raise-on-warnings.html

2016/12/22 午前10:33 "INADA Naoki" <notifications@github.com>:

**Comment by thorstenkampe** [comment]
The issue comes from `SQLAlchemy` (`Alembic` uses `SQLAlchemy` under the hood). When `SQLAlchemy` first connects, it issues `SHOW VARIABLES LIKE 'sql_mode'`. If any of the MySQL server's variables contain non ASCII data, the warning is returned. In my and @seanmars case, I suspect a localized timezone name on the server side.

The [corresponding Bug](https://bugs.mysql.com/bug.php?id=74429) has been open upstream since 2014.
`mysqlclient` and `mysql-connector-python` apparently don't show warnings by default. Is it possible to disable warnings for a connection in PyMySQL?
