### ISSUE TITLE
Use `contextlib.closing` instead of `try/finally` in README example

### ISSUE THREAD

**Issue by bbkane** [PyMySQL/PyMySQL#537]
Whenever I use pymysql, I copy and modify the code in the README. I switch the
`try/finally` block to a [`contextlib.closing`](https://docs.python.org/3/library/contextlib.html#contextlib.closing) call so my code is cleaner and so
I don't have to remember closing it after I make my modifications.

I'd appreciate it if the default code in the README also used
`contextlib.closing` I'd be happy to make a pull request to do this if you'd accept it.

Advantages:

- Just as portable- it's in the standard library for both Python2 and Python3.
- More readable
- A tiny bit shorter (1 line)
- No need for an outer `try` block who's purpose (to close the connection) might get confused with any
  inner `try` blocks with different purposes
- No need for a `final` block that might get lost in the copy/paste/modify cycle

Disadvantages:

- People might not recognize what the `closing` context manager does (it's a
  quick web search away and learning it gives the user another tool for anything
  that needs unconditional closing)

I've pasted the original code and my proposed change code below.

Original

```python
import pymysql.cursors

# Connect to the database
connection = pymysql.connect(host='localhost',
                             user='user',
                             password='passwd',
                             db='db',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

try:
    with connection.cursor() as cursor:
        # Create a new record
        sql = "INSERT INTO `users` (`email`, `password`) VALUES (%s, %s)"
        cursor.execute(sql, ('webmaster@python.org', 'very-secret'))

    # connection is not autocommit by default. So you must commit to save
    # your changes.
    connection.commit()

    with connection.cursor() as cursor:
        # Read a single record
        sql = "SELECT `id`, `password` FROM `users` WHERE `email`=%s"
        cursor.execute(sql, ('webmaster@python.org',))
        result = cursor.fetchone()
        print(result)
finally:
    connection.close()
```

contextlib.closing version

```python
import contextlib
import pymysql.cursors


# Connect to the database
connection = pymysql.connect(host='localhost',
                             user='user',
                             password='passwd',
                             db='db',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

with contextlib.closing(connection):
    with connection.cursor() as cursor:
        # Create a new record
        sql = "INSERT INTO `users` (`email`, `password`) VALUES (%s, %s)"
        cursor.execute(sql, ('webmaster@python.org', 'very-secret'))

    # connection is not autocommit by default. So you must commit to save
    # your changes.
    connection.commit()

    with connection.cursor() as cursor:
        # Read a single record
        sql = "SELECT `id`, `password` FROM `users` WHERE `email`=%s"
        cursor.execute(sql, ('webmaster@python.org',))
        result = cursor.fetchone()
        print(result)
```

**Comment by methane** [comment]
> Just as portable- it's in the standard library for both Python2 and Python3.

It isn't advantage: try-finally is portable for both Python 2 and Python 3 too.

And there is a huge disadvantage: It requires more knowledge to read example.

**Comment by bbkane** [comment]
Fair enough. Thanks for making/maintaining the library!
