### ISSUE TITLE
Improve config parser

### ISSUE THREAD

**Issue by mbaldessari** [PyMySQL/PyMySQL#548]
Currently when we create a Connection object with option read_default_file=/etc/my.cnf, the setup of the object may fail due due to inability to recognize a few lines which are pretty common in mariadb installations. Namely, we error out like this:
ConfigParser.ParsingError: File contains parsing errors: /etc/my.cnf
        [line 19]: '!includedir /etc/my.cnf.d\n'

Or like this:
ConfigParser.ParsingError: File contains parsing errors: /etc/my.cnf.d/galera.cnf
        [line 30]: 'skip-external-locking\n'
        [line 77]: 'quick\n'
        [line 78]: 'quote-names\n'

We are thinking of two approaches here:
A) We just ignore any parsing error
B) We try and make it robust enough to cover at least the two above use cases

Which direction would you like us to take in a pull request that tries to improve this?

Thanks

**Comment by methane** [comment]
I appreciate to pull request to support it, but it should be

* small, easy to read and maintain
* no additional dependency
* with test

Otherwise, I don't want to pay my time and energy to read, test, and maintain it.

**Comment by mbaldessari** [comment]
Sounds fair enough, thanks. I'll try a couple of approaches and we'll see what makes more sense in terms of maintainability.

**Comment by methane** [comment]
ref: #588

**Comment by irufus** [comment]
Does this issue still need help?

**Comment by methane** [comment]
I don't know.  Who cares what?

**Comment by BjoernT** [comment]
This issue is still present ```ConfigParser.ParsingError: File contains parsing errors: /etc/my.cnf
[line 19]: '!includedir /etc/my.cnf.d\n'``` if not worked round but it's actually happening inside the standard python config parser:

```
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
``` 
which can justify to close the issue here and address it somewhere else.
Alternatively you can merge the files rather than including them, which also makes sure that you have the original file included at the time of backup.
What do you think?

**Comment by methane** [comment]
I don't have motivation for supporting include directive.
"Supporting" includes maintain, not only implement.
