### ISSUE TITLE
TypeError("a bytes-like object is required, not 'int'",)

### ISSUE THREAD

**Issue by lt82654993** [PyMySQL/PyMySQL#550]
I use python3.5 and  mysql 5.1 or 5.6, both have this problem（use MYISAM engine）. . Data can insert mysql,But have a TypeError. 
So, I real confuse. why pymysql insert data auto increment id about 66000 above report a typeError that means id <=60000 is normal.
I used pyspider frame to crawl data into mysql database.
I hope you can resolve my confues, thanks!

**Comment by methane** [comment]
**[You must not ask a question on issue tracker](https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde#.hdf6lpk11)**

**Comment by lt82654993** [comment]
I am thinking this problem maybe a bug. Where can i ask a question solving my confuse? Can you help me?

**Comment by methane** [comment]
Have you really read the article???

```
FAQ
Q. I don’t know is this a bug or my usage is wrong
A. Until you have confidence it’s a bug, it’s a question, not a bug report.
Ask in forum, and if it seems bug after discussion, file a bug report to
issue tracker with URL and summary of the discussion.
```

**Comment by methane** [comment]
And ISSUE_TEMPLATE said:

> If you're sure it's PyMySQL's issue, report the complete steps to reproduce, from creating database.

Why do you expect I pay my time and energy for you, while you didn't pay your energy only
for reading ISSUE TEMPLATE?
Please go stackoverflow, until you can write good issue report.
