### ISSUE TITLE
Executemany fails when ON DUPLICATE KEY is used

### ISSUE THREAD

**Issue by Erfa** [PyMySQL/PyMySQL#554]
There appears to be an issue when you want to send query parameters in the `ON DUPLICATE KEY UPDATE` part of a query, if you execute it using `executemany`. For example this:

```python
sql = '''
      INSERT INTO users (name, age) VALUES (%s, %s)
      ON DUPLICATE KEY UPDATE name = %s, age = %s
      '''

parameters = [
    ['Mary', 35] * 2,
    ['Steve', 21] * 2,
]

cursor.executemany(sql, parameters)
```

Will cause the following trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 196, in executemany
    self._get_db().encoding)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 214, in _do_execute_many
    v = values % escape(next(args), conn)
TypeError: not all arguments converted during string formatting
```

I know that `executemany` is not supposed to support all types of queries, so perhaps this is intended. If so, maybe a better error message would be useful?

**Comment by methane** [comment]
If you can implement friendly error for **all** possible errors, without any regression (including performance regression) and increasing maintenance cost, please send pull request.

I prefer simple.
I fear "frindly error" hides unintentional, more difficult errors.
Especially, execitemany is "expert only". Detailed error won't disterb experts. they can read code and point it out soon like you.

**Comment by Akuli** [comment]
Does someone know an SQL library that can efficiently insert many things like that? I'm having trouble finding one.

**Comment by Akuli** [comment]
I found a solution, adding a link here to hopefully save some time from someone else https://stackoverflow.com/a/26372066
