### ISSUE TITLE
fetchall returns empty if query result is just one row

### ISSUE THREAD

**Issue by balves** [PyMySQL/PyMySQL#559]
If you use fetchall, or fetchone, on a query that only returns one result ( row ) it will return an empty result incorrectly.  
```
 def fetchall(self):
        """Fetch all the rows"""
        self._check_executed()
        if self._rows is None:
            return ()
        if self.rownumber:
            result = self._rows[self.rownumber:]
        else:
            result = self._rows
        self.rownumber = len(self._rows)
        return result
```

if self.rownumber is 1
_rows[1] doesn't exist as it only contains one element which is index 0

this causes the result to incorrectly return empty

**Comment by methane** [comment]
> if self.rownumber is 1

Why is this happen???

As I wrote in ISSUE_TEMPLATE,  **If you're sure it's PyMySQL's issue, report the complete steps to reproduce, from creating database.**

**Comment by methane** [comment]
BTW, https://www.python.org/dev/peps/pep-0249/#fetchall says:

> Fetch all (remaining) rows of a query result

**Comment by balves** [comment]
My apologies for the missing data. To be honest I thought I wouldn't get a reply.

Create database with the following table:
CREATE database users;
CREATE TABLE `token` (
  `id` bigint(20) unsigned NOT NULL,
  `token` varchar(767) CHARACTER SET ascii NOT NULL,
  `principal_rid` bigint(20) unsigned NOT NULL,
  `valid_until` datetime NOT NULL)

INSERT INTO token (id, token, principal_rid, valid_until) VALUES (0, 'example_token', 3, CURTIME());

def get_token_fromdb():
    #db = MySQLdb.connect(host="localhost", port=3306, db="users", user="root")
    db = pymysql.connect(host="localhost", port=3306, db="users", user="root")
    db.autocommit(True)
    cursor = db.cursor()
    cursor.execute("select token from token WHERE principal_rid=3")
    token = cursor.fetchall()  #fetchone has the same behaviour
    cursor.close()
    db.close()
    return token

token gets back empty because in the cursor _rownumber is 1. 

I've used MySQLdb with the exact same code and it works fine. hence opening this issue. 
I may be doing something stupid but I can't really see where.

Thank you for the time spent reading this.

**Comment by methane** [comment]
```
In [1]: import pymysql
In [2]: db = pymysql.connect(host="127.0.0.1", port=3306, db="test", user="root")
In [3]: db.autocommit(True)
In [4]: cursor = db.cursor()
In [5]: cursor.execute("select token from token WHERE principal_rid=3")
   ...:
Out[5]: 1
In [6]: token = cursor.fetchall()
In [7]: token
Out[7]: (('example_token',),)
```

**Comment by methane** [comment]
Did you used newest PyMySQL?

**Comment by balves** [comment]
Yes. PyMySQL (0.7.10).

I won't make you lose more time. I'll be happy for this to be closed. I will try this in another environment and see i something i have in mine is conflicting or something of that sort.

Thanks anyway

**Comment by xin053** [comment]
I found the same problem.When I debug the code,
```
with connection.cursor() as cursor:
        # Read a single record
        sql = "SELECT `logtime` FROM `logs` order by `logtime` limit 1"
        cursor.execute(sql)
        result = cursor.fetchone()
        print(result)
```
from the debug window,the `result` is `None`
But when I just run the code,not in debug mode,it works fine.
I just can not understand why this happened.
By the way,I debug the python code with vscode with the python extension.

**Comment by methane** [comment]
@xin053 Why can't you read this message in this thread???
https://github.com/PyMySQL/PyMySQL/issues/559#issuecomment-287025154
