### ISSUE TITLE
Empty `args` is not handled properly in execute() method

### ISSUE THREAD

**Issue by nehemiahjacob** [PyMySQL/PyMySQL#562]
I guess this code is problematic https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/cursors.py#L143

On this snippet:
```
            if args is not None:
                query = query % self._escape_args(args, conn)
```

Django causes a problem by passing `args` as empty tuple instead of `None`. So the correct code should be something like

```
            if args:
                query = query % self._escape_args(args, conn)
```

Exception Received: `TypeError: not enough arguments for format string`

Steps to reproduce:
In any django queryset, use the `extra()` hook and pass the below raw SQL statement with modulo operator `%`

`qs = qs.extra(where=['my_col % 10'])`. 

Ideally, this has to be reported as a Django bug, but the fix makes more sense here in this project. If the `args` is empty list/tuple/None the behavior should be similar.

Let me know if would require a pull request. The current workaround is to use `mod` keyword instead of `%` for MySQL: like this `qs = qs.extra(where=['my_col mod 10'])`

**Comment by methane** [comment]
You should use `%%` instead.
