### ISSUE TITLE
Import Error: No module name pymysql

### ISSUE THREAD

**Issue by mayurpande** [PyMySQL/PyMySQL#564]
I have installed `virtualenv` and `python3-pip`. However whenever I try to run my code I keep getting the error `ImportError: No module name pymysql`

This is on a live ubuntu server 16.04.
When I was installed on my local ubuntu desktop it worked fine with the installation like so;

```
sudo apt-get install python3-pymysql

```

However I have tried installing with `pip`,`pip3` and `apt-get` on the live server but it doesn't work.

When I run `pip list` it shows (same for `pip3 list`;

```
appdirs (1.4.3)
packaging (16.8)
pip (9.0.1)
pkg-resources (0.0.0)
pyparsing (2.2.0)
setuptools (34.3.3)
six (1.10.0)
wheel (0.30.0a0)
```

However each time I try and install it says requirement already statisfied

**Comment by methane** [comment]
It's definitely not a PyMySQL issue.
Don't consult me about your environment issue.
