### ISSUE TITLE
Linking to MySQLdb documentation

### ISSUE THREAD

**Issue by millerbryan** [PyMySQL/PyMySQL#565]
I recommend, in the interest of efficiency, that we link to the MySQLdb docs.  I can do that if you approve the action.  Newcomers are very likely to be puzzled by the very brief example page and not realized that the API is actually very large and expressive.

**Comment by methane** [comment]
There are no MySQLdb docs written for Python 3.

**Comment by millerbryan** [comment]
Yes, that is unfortunate.  However, I have been successfully using the MySQLdb docs for Python 2.x with Python 3.6, PyMySQL 0.7.11, and MySQL 5.7 with excellent success.  Other than the usual Python 2 VS 3 syntax differences I have not encountered any serious differences.

**Comment by methane** [comment]
What do you talking about? [this](http://mysqlclient.readthedocs.io/)?

**Comment by millerbryan** [comment]
Actually, I was talking about [this](http://mysql-python.sourceforge.net/MySQLdb.html) but believe they are the same.  The formatting is different.

**Comment by UserName011** [comment]
One of the reasons that I find it hard to move to PyMySQL is that it's not easy to modify all the functions and scripts which use MySQLdb. It would be easier if there was a documentation which maps the function name in MySQLdb to it's name in PyMySQL.

**Comment by methane** [comment]
@mikemill It is old, unmaintained version.
But there are some difference between PyMySQL and mysqlclient (or MySQL-python).
Please send pull request to PyMySQL document instead.

**Comment by methane** [comment]
@UserName011 Both of mysqlclient and PyMySQL regards DB-API 2.0.  Read it.
In other words, 1:1 for public (higher level) methods.  Both have same class / method name unless you use private APIs which is not documented in DB-API 2.0

**Comment by millerbryan** [comment]
@methane  Thank you.  I was not aware that PyMySQL followed the DB-API 2.0 standard.
