### ISSUE TITLE
Memoryview support in PyMySQL

### ISSUE THREAD

**Issue by groutr** [PyMySQL/PyMySQL#568]
In reference to this comment:
https://github.com/PyMySQL/PyMySQL/issues/233#issuecomment-45332944

Your code snippet leads me to believe that you didn't quite understand how to use memoryviews.

I'm curious to know if you've experiemented with this any further or have given it more thought.  I want to experiment with the possibility of using memoryviews.  Would this be something you'd be willing to consider if I open a PR?

My guiding source on the benefits of memoryviews comes from: http://eli.thegreenplace.net/2011/11/28/less-copies-in-python-with-the-buffer-protocol-and-memoryviews

**Comment by methane** [comment]
Using memoryview is very complex than you thought.
At least, your entry doesn't care about memoryview.release().
(see also: https://bugs.python.org/msg284954)

Additionally, memoryview may not be buffer or bytes.
It can be n-D array of 64bit-integer.  It makes code supporting memoryview complex.

I don't want to introduce more complexity.
Reducing one copy is negligible optimization in case of MySQL client.
