### ISSUE TITLE
pymysql.err.InternalError: (9007, 'Unsupported distributed transaction'),how to fix it

### ISSUE THREAD

**Issue by 2014QING** [PyMySQL/PyMySQL#569]
when I use python3.6 try to connect sharing table,but it said"pymysql.err.InternalError: (9007, 'Unsupported distributed transaction')".I want to konw how to fix it

**Comment by methane** [comment]
Google with error number and message.

**Comment by 2014QING** [comment]
I can't find the solution. Could you tell me ?

**Comment by methane** [comment]
No.
Here is neither user forum nor Q&A site.
I'm not free user support for you.

2017/05/14 午後1:00 "2014QING" <notifications@github.com>:
