### ISSUE TITLE
Out of date API docs

### ISSUE THREAD

**Issue by smitchell556** [PyMySQL/PyMySQL#571]
The API docs seem to be out of date for `connections.py` and `cursors.py` and don't include connection and cursor properties or function definitions.

It looks like the documentation started from #199 but didn't quite get finished.

**Comment by methane** [comment]
I won't work on it.  But contribution is welcome.

**Comment by smitchell556** [comment]
Do you prefer just class level documentation as it currently is? I think adding class members would be beneficial.

**Comment by methane** [comment]
Do you know [PEP 249](https://www.python.org/dev/peps/pep-0249/)?

Keyword arguments of connection constructor is PyMySQL specific.  So they are documented.
On the other hand, most methods are based on PEP 249.
And most methods not specified in PEP 249 is implementation detail.

**Comment by smitchell556** [comment]
I am familiar with it. I know the PEP is referenced in the user guide, but adding it to the main API reference page is a good idea.

The arguments accepted by the connection constructor could be moved into the class docstring so they would show up in the pages generated on readthedocs. As it stands sphinx doesn't use the __init__ docstring if there is a class level docstring. There are also some public members that aren't PEP 249 specific, like connection.open which I think would be beneficial to document. I'll submit a PR and we can go from there.
