### ISSUE TITLE
Add support for handling expired passwords

### ISSUE THREAD

**Issue by tsroten** [PyMySQL/PyMySQL#572]
It would be helpful for PyMySQL to support a sandbox mode where users with expired passwords can set their password. This is covered in [the MySQL docs](https://dev.mysql.com/doc/refman/5.7/en/password-expiration-sandbox-mode.html).

The [`pymysql.constants.CLIENT.HANDLE_EXPIRED_PASSWORDS`](https://github.com/PyMySQL/PyMySQL/blob/40f6a706144a9b65baa123e6d5d89d23558646ac/pymysql/constants/CLIENT.py#L29) constant has a comment "Not done yet".

Currently, if a user logs into a MySQL server via PyMySQL with an expired password, they receive error 1862:
```
Your password has expired. To log in you must change it using a client that supports expired passwords.
```

**Comment by UserName011** [comment]
+1 for that

**Comment by methane** [comment]
Pass `client_flag=CLIENT.HANDLE_EXPIRED_PASSWORDS` explicitly.
