### ISSUE TITLE
How to connect using a string?

### ISSUE THREAD

**Issue by UserName011** [PyMySQL/PyMySQL#581]
This is the example from manual:
```
connection = pymysql.connect(host='localhost',
                             user='user',
                             password='passwd',
                             db='db',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)
```

In my case I'm connecting between two databases.
The connection details are saved in a table so I need to retrieve the information from there using SQL query.
Basically the query gives me

`connectionstr = host="a",user="b",password="c",db="d"`

What I wanted to do is:
`connectionstr + =""",charset='utf8mb4',cursorclass=pymysql.cursors.DictCursor """`

and then do:

`connection = pymysql.connect(connectionstr)`

But this does not work. How can I make it work?
I can not hard codded my connection settings.

**Comment by methane** [comment]
serialize kwargs via json

**Comment by UserName011** [comment]
@methane Why not support the connection as string like MySQLDB does?

**Comment by bbbmurry** [comment]
It is unfortunate we cannot supply a valid connection URI:
https://dev.mysql.com/doc/refman/8.0/en/mysql-shell-connection-using-uri.html

This could simplify application configuration.
