### ISSUE TITLE
Misleading exception information

### ISSUE THREAD

**Issue by zhulongcheng** [PyMySQL/PyMySQL#586]
```
sql = "SELECT `id`, `password` FROM `users` WHERE `id`=%s"
cursor.execute(sql, {'id': object()})

# 
# AttributeError: 'object' object has no attribute 'translate'
```

When I see the above exception, it is difficult to think of a parameter error.
Maybe an obvious parameter TypeError  would be better.

https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/converters.py#L20
https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/converters.py#L68-L73

**Comment by methane** [comment]
Why `mapping[text_type]` raise KeyError?

It's not parameter error.  It's just an abuse and your report is too incomplete.

**Comment by methane** [comment]
Sorry I was wrong.  But I won't fix.
This part is complicated.  If I try to fix one non-bug, I may produce two bugs.
I don't have motivation at all.

**Comment by methane** [comment]
It's too complicated to maintain.
But it can't be simplify for backward compatibility.

**Comment by zhulongcheng** [comment]
Check value type and raise early？

If `escape_item` can not escape item successfully, raise a `EscapeError`, rather than raise a unstable error.

**Comment by methane** [comment]
It's not easy as you thought.
I need to read MySQL-python and PyMySQL code carefully to find what's the right way.
And I don't have energy and time to describe it.

**Comment by methane** [comment]
Anyway, your code has other bug.  If you want to use dict, you should use `%(id)s`, not `%s`.
And I don't want to check all possible foolish errors.  It increase maintenance cost and decrease performance.  And I don't have motivation.

I'm very busy at least one year.  I'll fix only serious bugs which makes PyMySQL tottaly unusable.
