### ISSUE TITLE
MULTI_STATEMENTS & MULTI_RESULTS always enabled in client_flag in Connection

### ISSUE THREAD

**Issue by mjmaenpaa** [PyMySQL/PyMySQL#590]
MULTI_STATEMENTS & MULTI_RESULTS are always enabled in Connection client_flag and there is no way to disable them. client_flag parameter is always bitwise or'd with constants.CLIENT.CAPABILITIES which includes MULTI_STATEMENTS & MULTI_RESULTS.
In connections.py: `client_flag |= CLIENT.CAPABILITIES`

Small example to demonstrate issue:

    from __future__ import print_function

    import pymysql
    from pymysql.constants.CLIENT import MULTI_STATEMENTS

    db_prefix = "bugtest_"
    host = "127.0.0.1"
    port = 3306
    user = "root"
    password = None

    def create_db(client_flag):
        try:
            connection = pymysql.connect(user=user, host=host, port=port, passwd=password, client_flag=client_flag)
            cursor = connection.cursor()

            db1 = db_prefix + "1"
            db2 = db_prefix + "2"
            sql = 'CREATE DATABASE IF NOT EXISTS {0:s}; CREATE DATABASE IF NOT EXISTS {1:s};'.format(db1, db2)
            print('  ' + sql)
            cursor.execute(sql)
            cursor.execute("SHOW DATABASES LIKE 'bugtest_%'")
            results = cursor.fetchall()
            for result in results:
                print('  ' + result[0])
        finally:
            cursor.execute('DROP DATABASE IF EXISTS {0:s}'.format(db1))
            cursor.execute('DROP DATABASE IF EXISTS {0:s}'.format(db2))
            connection.close()

    print('This query should go okay.')
    create_db(MULTI_STATEMENTS)        
            
    print('This should give database error')
    create_db(0)

And what happens currently:

    This query should go okay.
      CREATE DATABASE IF NOT EXISTS bugtest_1; CREATE DATABASE IF NOT EXISTS bugtest_2;
      bugtest_1
      bugtest_2
    This should give database error
      CREATE DATABASE IF NOT EXISTS bugtest_1; CREATE DATABASE IF NOT EXISTS bugtest_2;
      bugtest_1
      bugtest_2

And what happens if MULTI_STATEMENTS is removed from CAPABILITIES:

    This query should go okay.
      CREATE DATABASE IF NOT EXISTS bugtest_1; CREATE DATABASE IF NOT EXISTS bugtest_2;
      bugtest_1
      bugtest_2
    This should give database error
      CREATE DATABASE IF NOT EXISTS bugtest_1; CREATE DATABASE IF NOT EXISTS bugtest_2;
    C:\Python27\lib\site-packages\pymysql\cursors.py:166: Warning: (1008, "Can't drop database 'bugtest_1'; database doesn't exist")
      result = self._query(query)
    C:\Python27\lib\site-packages\pymysql\cursors.py:166: Warning: (1008, "Can't drop database 'bugtest_2'; database doesn't exist")
      result = self._query(query)
    Traceback (most recent call last):
      File "bug.py", line 35, in <module>
        create_db(0)
      File "bug.py", line 21, in create_db
        cursor.execute(sql)
      File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 166, in execute
        result = self._query(query)
      File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 322, in _query
        conn.query(q)
      File "C:\Python27\lib\site-packages\pymysql\connections.py", line 862, in query
        self._affected_rows = self._read_query_result(unbuffered=unbuffered)
      File "C:\Python27\lib\site-packages\pymysql\connections.py", line 1063, in _read_query_result
        result.read()
      File "C:\Python27\lib\site-packages\pymysql\connections.py", line 1346, in read
        first_packet = self.connection._read_packet()
      File "C:\Python27\lib\site-packages\pymysql\connections.py", line 1020, in _read_packet
        packet.check_error()
      File "C:\Python27\lib\site-packages\pymysql\connections.py", line 393, in check_error
        err.raise_mysql_exception(self._data)
      File "C:\Python27\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
        raise errorclass(errno, errval)
    pymysql.err.ProgrammingError: (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CREATE DATABASE IF NOT EXISTS bugtest_2' at line 1")

**Comment by elemount** [comment]
Hi @mjmaenpaa , what's your scenario on the MULTI_STATEMENTS & MULTI_RESULTS, why you need to disable it? It is not usual to disable it? Could you describe your scenario?

**Comment by mjmaenpaa** [comment]
Hi,

main reason I needed to disable them was because I was doing security testing for my application and simplest way to detect multi statement sql injection was to simply disable multi statement support in connection.

But I managed to disable it by monkey patching before creating connection:

    orig_capabilities = pymysql.constants.CLIENT.CAPABILITIES
    pymysql.constants.CLIENT.CAPABILITIES ^= pymysql.constants.CLIENT.MULTI_STATEMENTS
    conn = pymysql.connect()
    pymysql.constants.CLIENT.CAPABILITIES = orig_capabilities

**Comment by elemount** [comment]
@mjmaenpaa , I would suggest you just set
```python
conn = pymysql.connect(defer_connect=True)
conn.client_flag &= ~pymysql.constants.CLIENT.MULTI_STATEMENTS
conn.connect()
```
This is a perfect way to do it by set per connections.

**Comment by elemount** [comment]
@mjmaenpaa , and I do not think we can modify `client_flag` parameter behavior. @methane , what is your idea?

**Comment by methane** [comment]
I think default should be same to MySQL Connector/C

2017/08/10 午後2:35 "Alex Lee" <notifications@github.com>:

**Comment by elemount** [comment]
@methane , In MySQL Connector/C, the `MULTI_STATEMENTS` attribute is disabled by default, so it can be opened by set `client_flag`. Refer [mysql-real-connect API](https://dev.mysql.com/doc/refman/5.6/en/mysql-real-connect.html). 
I do not think this attribute can be disabled in PyMySQL, which may broke so may existing program using PyMySQL.

Or should we put 
```python
conn = pymysql.connect(defer_connect=True)
conn.client_flag &= ~pymysql.constants.CLIENT.MULTI_STATEMENTS
conn.connect()
```
as FAQ about how to disable this attributes?

**Comment by methane** [comment]
> I do not think this attribute can be disabled in PyMySQL, which may broke so may existing program using PyMySQL.

I will do it at 0.8.  Release note can have information about that.
While it may break existing program, it won't corrupt data, only show errors.
Users who see the error can fix the program.

**Comment by user2301** [comment]
**How to get number of rows affected / row count after multiple insert statement execution**

pymysql.connect(host, username, password, database, port, client_flag= CLIENT.MULTI_STATEMENTS|CLIENT.MULTI_RESULTS)
insert_statement= "INSERT INTO demo VALUES ('$SYS/publish/messages/received',0,1515580086025);
INSERT INTO demo VALUES ('$SYS/publish/messages/sent',0,1515580086025);
INSERT INTO demo VALUES ('$SYS/publish/messages/sent',3,1515580094997);
INSERT INTO demo VALUES ('$SYS/publish/messages/sent',4,1515580105983);"

row_count = cursor.execute(insert_statement)
print (row_count) -> #always prints 1 (but actually 4 rows are inserted as per insert_statement)

print (cursor.rowcount) -> #always prints 1 (but actually 4 rows are inserted as per insert_statement)

**Comment by methane** [comment]
**[You must not ask a question on issue tracker](https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde#.hdf6lpk11)**
