### ISSUE TITLE
change DEFAULT_CHARSET = 'latin1'    to  DEFAULT_CHARSET = 'utf8'  ?!

### ISSUE THREAD

**Issue by tonyzeng2016** [PyMySQL/PyMySQL#594]
why the default charset is "latin1" ? what will happen if it changed to 'utf8'?

**Comment by methane** [comment]
> why the default charset is "latin1" ?

To consistency with MySQL Connector/C

> what will happen if it changed to 'utf8'?

I don't know.  File an issue on bugs.mysql.org.  Not here.
