### ISSUE TITLE
autoreconnect problem with mysqlobject using pysmysql as driver

### ISSUE THREAD

**Issue by shaileshkm** [PyMySQL/PyMySQL#601]
Recently I started using PyMySQL as mysql driver for SQLObject since I wanted a pure python driver.

Since then, every morning any sql causes exception  in SQLobject. I have couple of questions related to it. Yesterday I updated SQLObject to latest release. Still no luck.

Stack:

  File "/home/shailesh/AuthService/Server/AuthResources.py", line 307, in GetAuthType
    product_rec = ProductTable.Product.FindKnownId(caller_product[0])
  File "/home/shailesh/AuthService/DBLib/Product.py", line 69, in FindKnownId
    if ret.count():
  File "/home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/sresults.py", line 229, in count
    count = self.accumulate('COUNT(*)')
  File "/home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/sresults.py", line 211, in accumulate
    return conn.accumulateSelect(self, *exprs)
  File "/home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/dbconnection.py", line 501, in accumulateSelect
    val = self.queryOne(q)
  File "/home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/dbconnection.py", line 476, in queryOne
    return self._runWithConnection(self._queryOne, s)
  File "/home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/dbconnection.py", line 342, in _runWithConnection
    val = meth(conn, *args)
  File "/home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/dbconnection.py", line 469, in _queryOne
    self._executeRetry(conn, c, s)
  File "/home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/mysql/mysqlconnection.py", line 258, in _executeRetry
    raise dberrors.InterfaceError(ErrorMessage(e))
  File "/home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/mysql/mysqlconnection.py", line 10, in __new__

1. The exception is coming from a constructor of ErrorMessage in sqlobject code.
Found couple of threads on this topic which I need to follow up with.
https://www.mail-archive.com/sqlobject-discuss@lists.sourceforge.net/msg01213.html
http://www.boduch.ca/2009/03/ecp-and-sqlobject.html?m=0

2. What is the exception raised  in first place.
After some trial and error, found this.
 6/ERROR   :  sqlobject: **** Error in /home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/mysql/mysqlconnection.py
 6/ERROR   :  query=SELECT COUNT(*) FROM product WHERE ((product.known_id) = (8193)), sqlobject error:(0, '')
 1/ERROR   :  (2006, "MySQL server has gone away (error(32, 'Broken pipe'))")

The mysql default idle connection timeout is 8 hours (wait_timeout).
So looks like, overnight, the connection from sqlobject times out.

However, this is such a basic issue to manage for ORM layer which manages connection pool. Also, never faced this  issue with mysqldb which I've been testing with for more than 4 months.

From sqlobject code, found this.
method makeConnection

                conn = self.module.connect(
                    host=self.host, port=self.port, db=self.db,
                    user=self.user, passwd=self.password, **self.kw)
                if self.driver != 'oursql':
                    # Attempt to reconnect. This setting is persistent.
                    conn.ping(True)

Found this comment in _executeRetry
	# When a server connection is lost and a query is attempted, most of
        # the time the query will raise a SERVER_LOST exception, then at the
        # second attempt to execute it, the mysql lib will reconnect and
        # succeed. However is a few cases, the first attempt raises the
        # SERVER_GONE exception, the second attempt the SERVER_LOST exception
        # and only the third succeeds. Thus the 3 in the loop count.
        # If it doesn't reconnect even after 3 attempts, while the database is
        # up and running, it is because a 5.0.3 (or newer) server is used
        # which no longer permits autoreconnects by default. In that case a
        # reconnect flag must be set when making the connection to indicate
        # that autoreconnecting is desired. In MySQLdb 1.2.2 or newer this is
        # done by calling ping(True) on the connection.

Once this exception occurs, nothing works. I have to bounce my server.
Before bouncing the server, from database I see this.

At the time of exception
MySQL [(none)]> SHOW FULL PROCESSLIST;
+-----+------+---------------------+------+---------+------+----------+-----------------------+
| Id  | User | Host                | db   | Command | Time | State    | Info
            |
+-----+------+---------------------+------+---------+------+----------+-----------------------+
| 932 | root | 172.16.100.69:53108 | NULL | Query   |    0 | starting | SHOW FULL
PROCESSLIST |
+-----+------+---------------------+------+---------+------+----------+-----------------------+

So looks like sqlobject is unable to reconnect even if it has logic to do so.

**Comment by shaileshkm** [comment]
Here's what I've found so far.
- SQLObject, when creating connection, calls ping(True) on connection.
- connection has been idle for long time to have reached mysql's wait_timeout
- SQLObject issues a request
- Connection._execute_command calls Connction._write_bytes which catches exception
  - calls _force_close which closes the _sock object
  - throws OperationalError(2006, ""MySQL server has gone away")
- SQLObject catches OperationError. If one of 2006 or 2013, it reattempts query execution one more time.
- Connection._execute_command first checks if _sock object is open. If not, it throws InterfaceError.
- SQLObject has no retry logic for InterfaceError and gets tangled up when processing arg[1] (which is absent).

It looks to me, SQLObject assumption is once ping(True) is set on connection, the reconnection should be handled transparently by the driver (PyMySQL in this case). I certainly hasn't seen reconnection problem with MySQLDb (mysql python) driver.

I tried doing following explicitly when handling InterfaceError in SQLObject
- Call ping again on connection
- Retry one more time

This logic did the trick.

I'm not sure if SQLObject's assumption about auto reconnect is valid or not. I guess it would be trickier doing it in db driver because, besides auto reconnect, it does not know other fact whether to do auto commit, what's the encoding etc.

**Comment by methane** [comment]
I don't have time now.  And I never use SQLObject.

Anyway, you must not rely on autoreconnect + retry.
When error happend while reading, there are no way to know sent query is executed or not.
You may execute same query twice or more.

When you use pooling, you must not reuse connection longer than wait_timeout.

**Comment by methane** [comment]
https://github.com/PyMySQL/PyMySQL/blob/0408bf4a588b8d8934fd9c1fa03e736c8f93f38c/pymysql/connections.py#L872-L888

ping reconnects transparency.
If not, please issue new report.

**Comment by toien** [comment]
is it considerable to add an `auto_ping` param when construct `Connection`?
and if it is True, in Cursor's `_get_db` function do a ping op like:
`    def _get_db(self):
        if not self.connection:
            raise err.ProgrammingError("Cursor closed")
        if self.connection.auto_ping:
            self.connection.ping()
        return self.connection`
