### ISSUE TITLE
mariadb 10.2 enforces CHECK constraints; PyMySQL should raise OperationalError, not InternalError

### ISSUE THREAD

**Issue by zzzeek** [PyMySQL/PyMySQL#607]
You need MariaDB 10.2 to try this out.    mysqlclient raises OperationalError when the CHECK constraint is hit, PyMySQL raises InternalError probably because it does not expect this.     

```
import pymysql
import MySQLdb

def run_for_dbapi(dbapi):
    print("RUNNING DBAPI: %s" % dbapi)
    conn = dbapi.connect(user='scott', passwd='tiger', host='mariadb102', db='test')
    cursor = conn.cursor()
    cursor.execute("DROP TABLE IF EXISTS ck_test")
    cursor.execute(
        "CREATE TABLE ck_test "
        "(x integer, CHECK (x > 5)) engine=InnoDB")
    try:
        cursor.execute("INSERT INTO ck_test (x) VALUES (%s)", (3, ))
        print("DBAPI FAILED TO RAISE!")
    except Exception as e:
        print("DBAPI SUCCESSFULLY RAISED: %r" % e)

    finally:
        cursor.close()
        conn.close()


run_for_dbapi(MySQLdb)
run_for_dbapi(pymysql)

```

output:

```
RUNNING DBAPI: <module 'MySQLdb' from '/home/classic/.venv/lib/python2.7/site-packages/MySQLdb/__init__.pyc'>
DBAPI SUCCESSFULLY RAISED: OperationalError(4025, 'CONSTRAINT `CONSTRAINT_1` failed for `test`.`ck_test`')
RUNNING DBAPI: <module 'pymysql' from '/home/classic/.venv/lib/python2.7/site-packages/pymysql/__init__.pyc'>
DBAPI SUCCESSFULLY RAISED: InternalError(4025, u'CONSTRAINT `CONSTRAINT_1` failed for `test`.`ck_test`')

```

This just came up while I was getting my tests running on 10.2.  I don't need this fix on my end for anything, I can work around it.

**Comment by methane** [comment]
Hmm, where the error numbers defined?

I can't find 4025 in here:
https://mariadb.com/kb/en/library/mariadb-error-codes/#mariadb-specific-error-codes

**Comment by zzzeek** [comment]
bah....ive already had two mariadb jiras fixed for this CHECK constraint thing.   Their error codes are all under 2000 so I have no idea where they get 4025 from, I'd need to grep the source.  How does mysqlclient get OperationalError ?

**Comment by zzzeek** [comment]
welp this is the only place it's anywhere:  https://github.com/MariaDB/mariadb-connector-c/blob/ba8310e82dac659482f04cd2e270e666da072f95/include/mysqld_error.h#L1076   and there are lots of codes in there that aren't anywhere.

**Comment by mont5piques** [comment]
This happend to me beacause I tried to put a big integer on a field that was not big enough. It's like you want put a 300 character long string into a 50 field.
