### ISSUE TITLE
Add connection's read_timeout and write_timeout to parameters in documentation

### ISSUE THREAD

**Issue by ju-kreber** [PyMySQL/PyMySQL#612]
Currently, these two are only listed in the complete bunch of arguments the constructor takes, but do not appear in the parameter list with description.
This really is a minor issue, but I spent some time going through code to find out what I needed was already there. :)

**Comment by methane** [comment]
I'm not native English.  My English is broken and I'm not good at writing document.
Contribution is welcome.
