### ISSUE TITLE
transaction_isolation was added in MySQL 5.7.20 as an alias for tx_isolation, which is now deprecated and is removed in MySQL 8.0. Applications should be adjusted to use transaction_isolation in preference to tx_isolation.

### ISSUE THREAD

**Issue by iROCKBUNNY** [PyMySQL/PyMySQL#614]
`transaction_isolation` was added in MySQL 5.7.20 as an alias for `tx_isolation`, which is now deprecated and is removed in MySQL 8.0. Applications should be adjusted to use `transaction_isolation` in preference to tx_isolation.

```
/venv/local/lib/python2.7/site-packages/pymysql/cursors.py:166: Warning: (1287, u"'@@tx_isolation' is deprecated and will be removed in a future release. Please use '@@transaction_isolation' instead")
  result = self._query(query)
```
See also: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_tx_isolation

**Comment by methane** [comment]
PyMySQL doesn't use both.  You pass it to PyMySQL.

**Comment by mcauto** [comment]
mysql-server 8.0
CentOS 7
PyMySQL 0.9.3
sqlalchemy 1.1.0

![image](https://user-images.githubusercontent.com/15080806/76926926-f811af80-6920-11ea-930a-d1be92c82d87.png)

**Comment by methane** [comment]
It's not issue of this project.

**Comment by mcauto** [comment]
It's sqlalchemy issue.

https://github.com/sqlalchemy/sqlalchemy/issues/5161
