### ISSUE TITLE
tx_isolation depricated in mysql, causing warnings while using pymysql

### ISSUE THREAD

**Issue by schemanen** [PyMySQL/PyMySQL#616]
In POST execution using pymysql you get a warning due to a faulty use of the parameter tx_isolation that is deprecated in MySQL 5.7. You can see the error bellow.  

/python3.5/site-packages/pymysql/cursors.py:166: Warning: (1287, "'@@tx_isolation' is deprecated anâ99 rows in set (0.00 sec)
d will be removed in a future release. Please use '@@transaction_isolation' instead")

Since the error is causing errors while using for example SQLAlchemy you have to add a lot of checks to handle the issue so the impact is big. Please let me know if I can help you or provide more information. 

BR Kim

**Comment by eddwinn** [comment]
Could we atleast get an option to stop/suppress the warning from pymysql?  Much scripting has gone it to finding a way around this warning for my project.

**Comment by methane** [comment]
https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings
