### ISSUE TITLE
Pymysql complains of 1287, "'@@tx_isolation' is deprecated and will be removed in a future release. Please use '@@transaction_isolation' instead"

### ISSUE THREAD

**Issue by eddwinn** [PyMySQL/PyMySQL#617]
mysql 5.6

mysql> show variables like "tx_isolation";
+---------------+-----------------+
| Variable_name | Value           |
+---------------+-----------------+
| tx_isolation  | REPEATABLE-READ |
+---------------+-----------------+
1 row in set (0.00 sec)

under 5.7
mysql> show variables like "transaction_isolation";
+-----------------------+-----------------+
| Variable_name         | Value           |
+-----------------------+-----------------+
| transaction_isolation | REPEATABLE-READ |
+-----------------------+-----------------+
1 row in set (0.00 sec)

**Comment by methane** [comment]
So what????
MySQL complains.  PyMySQL just report it to you.  No problem other than your usage.
