### ISSUE TITLE
 (pymysql.err.IntegrityError) (1215, 'Cannot add foreign key constraint')

### ISSUE THREAD

**Issue by tirupathiraop** [PyMySQL/PyMySQL#618]
Recently we upgraded our project code from python2 to python3.
In this process we had to change mysqldb with pymysql. (as mysqldb is no longer supported by python3).

So after this change we are facing so many issues related to foreign keys.

```
  raise errorclass(errno, errorvalue)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1215, 'Cannot add foreign key constraint')
```
 The same code used to work fine with mysqldb.
Any help would be appreciated.

**Comment by methane** [comment]
> In this process we had to change mysqldb with pymysql. (as mysqldb is no longer supported by python3).

There is fork supporting Python 3: https://github.com/PyMySQL/mysqlclient-python

> So after this change we are facing so many issues related to foreign keys.
> The same code used to work fine with mysqldb.

It's not enough information.  Error looks it's your fault.
Complete and minimum step to reproduce is required.
