### ISSUE TITLE
SSL clarity for connecting to cloud mysql as a service

### ISSUE THREAD

**Issue by ftrotter** [PyMySQL/PyMySQL#619]
Hello, 
        Thank you for the excellent project. 

Your documentation currently documents the ssl only as "similar to mysql_ssl_set's parameters" it would be nice to have these more clearly spelled out. I am not really sure what mysql_ssl_set is.

I am also looking for a way to turn of the hostname checking in the ssl implementation as per:
https://stackoverflow.com/questions/22758031/how-to-disable-hostname-checking-in-requests-python

but as an option to the ssl parameter on PyMySQL. 

I am trying to leverage the certificates that are auto-generated by Google's MySql cloud project, and it generates certs with its internal entity names as the hostname on the certs. This does make some sense, give that the platform has the capacity to swap IP addresses so simply. 

But it does mean that I need to ignore the strict relationship between the certificate entity name and the hostname. Given the growing popularity of MySQL-as-a-service having this library support the SSL outputs that Google's service delivers would be very helpful. 

This is clearly a feature request, one for the documentation and likely another for the code. I can understand that this might not get attention depending on how many people are dealing with the issue... But I had the problem and I am sure I am not entirely alone. 

In any case. Thank you for providing a much needed abstraction layer. 

Regards,
-FT

**Comment by methane** [comment]
What PyMySQL should do is follow [what MySQL does](https://dev.mysql.com/doc/refman/5.7/en/using-encrypted-connections.html#using-encrypted-connections-client-side-configuration).

Main problem is *I* don't know TLS well.  Since this is relating to security, I need to
study before implementing it.
English is not my mother language, so please don't try to teach me in English.
It doesn't help me.  Daily massive emails from github steals my time. (This is not only my project).
When I have time, I'll survey.  Until then, you need to patch PyMySQL by yourself.

**Comment by methane** [comment]
BTW, where is concrete step about connecting CloudSQL via mysql commandline client
(or bindings using libmysqlclient.so)?
There should be "right way" to use IP address and SSL.

**Comment by ftrotter** [comment]
Thank you for the quick response. 

I will try to find the time to follow you instructions and do a pull request ...

-ft

**Comment by methane** [comment]
I read CloudSQL document.  But I still don't know what cert CloudSQL server sends.
Should client verify IP address or host name?

**Comment by elemount** [comment]
@methane , The option in libmysqlclient is [MySQL options](https://dev.mysql.com/doc/refman/5.7/en/mysql-options.html) section `MYSQL_OPT_SSL_MODE`. 

PyMySQL always use the most strict value `SSL_MODE_VERIFY_IDENTITY`, but CloudSQL can accept `SSL_MODE_VETIFY_CA`

**Comment by methane** [comment]
Thanks.  So current PyMySQL support it.
