### ISSUE TITLE
pymysql does not support  "LOAD DATA LOCAL" ?

### ISSUE THREAD

**Issue by petehunt** [PyMySQL/PyMySQL#62]
Originally filed by fla.sam on 2011-04-29T08:58:02

What steps will reproduce the problem?
1. I try to load a local data from a csv format file into remote mysql-server"
LOAD DATA LOCAL INFILE 'a_csv_file' 
            INTO TABLE some_table_name
            FIELDS 
                TERMINATED BY ','
                ENCLOSED BY '"'
            LINES 
                TERMINATED BY '\n'
            IGNORE 1 LINES
            (field1, field2)
" 

What is the expected output? What do you see instead?
  File "/home/sam/workspace/lqjh2/lqjh2_admin_srv/pre_data/load_pre_data.py", line 62, in main
    cursor.execute(sql)
  File "/home/sam/PY_ENV/lq2_ENV/lib/python2.7/site-packages/django/db/backends/util.py", line 15, in execute
    return self.cursor.execute(sql, params)
  File "/home/sam/PY_ENV/lq2_ENV/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 86, in execute
    return self.cursor.execute(query, args)
  File "/home/sam/PY_ENV/lq2_ENV/lib/python2.7/site-packages/pymysql/cursors.py", line 108, in execute
    self.errorhandler(self, exc, value)
  File "/home/sam/PY_ENV/lq2_ENV/lib/python2.7/site-packages/pymysql/connections.py", line 184, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.DatabaseError: (1148, u'The used command is not allowed with this MySQL version')

but when i switch to "MySQL-python" it's everything fine.

What version of the product are you using? On what operating system?
0.4

**Comment by jakebruemmer** [comment]
I'm currently running into this issue with pymysql version `0.6.7` on Windows. I have set `local-infile=1` in my `my-default.ini` file but it's still throwing the error that this type of operation isn't permitted. Has 0.6 been tested for Windows computers? I'm wondering if I've updated the correct configuration file.

Thanks

**Comment by methane** [comment]
@jakebruemmer PyMySQL may not read your `my-default.ini`.  Use `local_infile=True` option of `connect()` function.

**Comment by jakebruemmer** [comment]
I switched to another Python connector, but I will try this if I use `pymysql` again. Thank you for responding.

**Comment by powerkx** [comment]
Works fine with below setup.

CentOS7, mysql5.6.40，Python3.6.1, PyMySQL 0.8.1
1. /etc/my.cnf
[mysqld]
secure_file_priv=''
local-infile
[mysql]
local-infile

2. in your python scripts:
conn = pymysql.connect(host=host, user=user, passwd=passwd, port=3306, charset='utf8', connect_timeout=10, db='testtest', local_infile=1)
