### ISSUE TITLE
pymysql.connections.Connection object's db attribute's value and type

### ISSUE THREAD

**Issue by jkklee** [PyMySQL/PyMySQL#630]
pymysql version: 0.7.9
example:
```
>>> conn = pymysql.connect(host='x.x.x.x', user='xxxx', password='xxxx', database='test', charset='utf8')
>>> conn.db
b'test'    ### Here is a bytes type
>>> conn.charset
'utf8'     ### But here is a str type, I think is better to keep these attributes have the same type(str type)

### And additional about select_db() method
>>> conn.select_db('user')    ### This indeed  take effect
>>> conn.db
b'test'    ### But here not change
```

**Comment by methane** [comment]
It's not bug.  It is not public API, while it's starts with underscore.
public API are:

* APIs defined in DB-API 2.0
* Documented API.

**Comment by jkklee** [comment]
Dose the `db` attribute and `select_db()` method start with  underscore? 😛

**Comment by methane** [comment]
`db` isn't start underscore by historical reason, and `select_db()` is public API, you can use.

Anyway, you shouldn't expect anything about `connection.db`.
It's semantics is not documented and guaranteed.
Currently, it mirrors constructor's argument.  But no guarantee in the future.
