### ISSUE TITLE
MySQLResult choking on un-decodable data

### ISSUE THREAD

**Issue by zougloub** [PyMySQL/PyMySQL#631]
Hi,

I have a table using the utf8 charset but contains data which, for some reason, cannot be decoded by Python (invalid utf-8), but nevertheless I'd like to access the data; the best thing I found to do was to monkey-patch `pymysql.connections.MySQLResult._read_row_from_packet()` so that `data = data.decode(encoding)` is replaced by something that doesn't raise exceptions (in certain cases).

Since PyMySQL has pluggable converters, I was wondering if it would be a welcome idea to also have pluggable encoders/decoders, instead of using inflexible bytes.decode() or str.encode().

Moreover, there might be a mixup between MySQL charsets and Python encodings, as trying to use eg. the "binary" charset in the MySQL connection results in Python encoding/decoding errors as 'binary' is not a Python codec.

**Comment by methane** [comment]
Have you tried `use_unicode=False`?

**Comment by zougloub** [comment]
Hi, no I hadn't noticed the option; `MySQLResult` returns bytes when using this, and so it's not raising exceptions (then overriding `pymysql.converters.conversions` can re-convert to `str`/`unicode`), and this is less dirty than monkey-patching a class method... I think it's an acceptable solution.
I'll close the issue as I only make occasional use of PyMySQL. Thanks for the pointer!
