### ISSUE TITLE
PyMySQL regression in 0.8.0 on INSERT

### ISSUE THREAD

**Issue by sabexx** [PyMySQL/PyMySQL#632]
PyMySQL 0.8.0 fails in updating transactions that 0.7.11 would have allowed - the database server being  Mariadb v10.0.33.

I tried using PyMySQL v0.8.0 on both Python 3.4 and Python 3.6 on the Windows XP and Windows 8 platforms respectively.

INSERT style transactions fail with an exception that reports "(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near...<snip>"). However, when I copy the SQL statement sent from PyMySQL 0.8.0 to the MariaDB query log and execute it from mysqlclient, the query works unedited, meaning something else is afoot.

SELECT statements work in both 0.7.11 and 0.8.00.

Unfortunately, I can't post snippets due to the confidential nature of the work, and I opened this issue is to let you know that there may be an issue with v0.8.0.

Good luck and happy hunting.

**Comment by methane** [comment]
Have you read this?

https://github.com/PyMySQL/PyMySQL/blob/0305541132b134047eb4ba70fc9acbc9be603d05/CHANGELOG#L7-L15



> SELECT statements work in both 0.7.11 and 0.8.00.

What do you mean?



> Unfortunately, I can't post snippets due to the confidential nature of the work, and I opened this issue is to let you know that there may be an issue with v0.8.0.

I can't do anything without reproducing example.
