### ISSUE TITLE
Feature request: Dumps

### ISSUE THREAD

**Issue by johnnybubonic** [PyMySQL/PyMySQL#635]
It'd be great if PyMySQL had a built-in method for dumping a database or table. It's something that was sorely missing from the original mysql connector.

[this](https://stackoverflow.com/a/10566474) could be a good approach, though it'd have to have a way to determine if it's a table or an entire database being dumped.

for completion's sake, [this](https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#mysqldump-option-summary) is a list of arguments/switches for the mysqldump command itself, though i imagine this could all/mostly be implemented natively.

**Comment by methane** [comment]
My goal is just providing DB-API 2.0 driver.
Additional features can be implemented split libraries using this project.
