### ISSUE TITLE
Execute sql statement error

### ISSUE THREAD

**Issue by succeed0924** [PyMySQL/PyMySQL#646]
I originally used the 0.7.11 version, and then upgraded to the 0.8.0 version, has been reported 1064 error, rollback version to solve the problem.

**Comment by methane** [comment]
Have you read changelog?

Anyway, complete reproducible example is needed.
Your message is not issue report, just a spam mail.
Don't send spam to me.

**Comment by succeed0924** [comment]
I was updating directly on linux, because I had not found any problems until I found it on the old machine. It was indeed my fault to submit the problem without reading the update instructions. I am sorry.
