### ISSUE TITLE
The password is missing

### ISSUE THREAD

**Issue by WaterZhai** [PyMySQL/PyMySQL#650]
![image](https://user-images.githubusercontent.com/28179670/39082914-6b70b64c-458d-11e8-8206-099613f6735e.png)

![image](https://user-images.githubusercontent.com/28179670/39082918-76dcefdc-458d-11e8-94b4-cb02e9f88f42.png)

![image](https://user-images.githubusercontent.com/28179670/39082924-8aab2dc6-458d-11e8-8f10-f54b407d1efe.png)

![image](https://user-images.githubusercontent.com/28179670/39082946-cfc49276-458d-11e8-8132-7a39d20bbcb6.png)

我调试了一下午。找不出什么问题。其他的各种方面都考虑了，最终得出一个结论，密码，不见了。当然，也有可能是其他的问题，我是个新手。刚开始学python，之前学了两年java。
so，我不知道该怎么办了。你给看看。

**Comment by grooverdan** [comment]
This looks like a lack of support for caching_sha2_password plugin. This is the default in MySQL-8.0.

@WaterZhai, please show output from the SQL; `SHOW CREATE USER water`; in mysql prompt to verify.

Algorithm for development: https://jira.mariadb.org/browse/CONC-312

**Comment by WaterZhai** [comment]
![fxcywm o vap83 ycb0wl8](https://user-images.githubusercontent.com/28179670/39090562-c25b8810-4614-11e8-8897-bca015518233.jpg)

这个是什么？

**Comment by methane** [comment]
Don't use Chinese here.
Here is issue tracker for maintainer.
Not forum for users.

**Comment by grooverdan** [comment]
@WaterZhai I can't read Chinese. Your output confirms my theory that caching_sha2_password is required. Thankyou. This is now a feature request in #651.

@methane, its a rather larger feature request. I can help. Like, #583, it seems hard to avoid an extra dependency.
