### ISSUE TITLE
caching_sha2_password authentication plugin support (MySQL-8.0)

### ISSUE THREAD

**Issue by grooverdan** [PyMySQL/PyMySQL#651]
PyMySQL doesn't implement the default MySQL-8.0 authentication protocol

https://dev.mysql.com/doc/dev/mysql-server/latest/page_caching_sha2_authentication_exchanges.html

Will require fix for #532 as basis for some paths of the implementation.

**Comment by luhuan97** [comment]
I also encountered this problem and hope to solve it as soon as possible。

**Comment by 646420882** [comment]
不支持mysql8.0   期待作者的更新

**Comment by zzzeek** [comment]
as a workaround, recommend folks use mysql_native_password (https://dev.mysql.com/doc/refman/8.0/en/native-pluggable-authentication.html) :

```
[mysqld]
# brand new server before any users are created
default-authentication-plugin=mysql_native_password

```
it's good enough for mariadb so it's good enough for Oracle
