### ISSUE TITLE
Wrong user variable values

### ISSUE THREAD

**Issue by ArdaOzupek** [PyMySQL/PyMySQL#673]
Hi,

I'm following [that pattern](http://www.sqlines.com/mysql/how-to/get_top_n_each_group) to get top N rows per each group.

This is my table:
```
CREATE TABLE cities
   (
      city VARCHAR(80),
      country VARCHAR(80),
      population INT
   );
 
   INSERT INTO cities VALUES ('New York', 'United States', 8175133); 
   INSERT INTO cities VALUES ('Los Angeles', 'United States', 3792621); 
   INSERT INTO cities VALUES ('Chicago', 'United States', 2695598); 
 
   INSERT INTO cities VALUES ('Paris', 'France', 2181000);
   INSERT INTO cities VALUES ('Marseille', 'France', 808000);
   INSERT INTO cities VALUES ('Lyon', 'France', 422000);
 
   INSERT INTO cities VALUES ('London', 'United Kingdom',	7825300);
   INSERT INTO cities VALUES ('Birmingham', 'United Kingdom', 1016800);
   INSERT INTO cities VALUES ('Leeds', 'United Kingdom', 770800);
```

And this is the sql statement that I'm executing:
```
SELECT city, country, population, 
       @country_rank := IF(@current_country = country, @country_rank + 1, 1) AS country_rank,
       @current_country := country 
  FROM cities
  ORDER BY country, population DESC
```

If I execute this statement from MySQLWorkbench, It works as excepted. I can get the rows with the incremented integer values of country_rank. But when I execute the same statement from PyMySQL, It just returns 1.0 float data for all the rows.

I'm using _Python 2.7_ with _MySQL version 5.7.12_. And my cursor class is _pymysql.cursors.DictCursor_

Did anyone face this issue?

**Comment by methane** [comment]
https://dev.mysql.com/doc/refman/5.7/en/user-variables.html

"However, the order of evaluation for expressions involving user variables is undefined."

**Comment by methane** [comment]
`mysql` CLI behaves same to PyMySQL.
https://gist.github.com/methane/c1f5977e37f5b1b513493f374f752a2f

It is unlikely PyMySQL's bug.
You should research how MySQL workbench works by yourself, or post question to StackOverflow.

I know MySQL C/S protocol, but I'm not MySQL behavior well.
