### ISSUE TITLE
Error la instalar requirements.txt

### ISSUE THREAD

**Issue by jesusUgaz** [PyMySQL/PyMySQL#675]
**Estoy utilizando :** 

- ***Virtualenv***
- ***Python 2.7***
- ***Homebrew -> contiene mariadb***

----------

**Lo que contiene requirements.txt**

----------

    amqp==1.0.11
    anyjson==0.3.3
    backports.ssl-match-hostname==3.4.0.2
    billiard==2.7.3.28
    celery==3.0.19
    certifi==2015.4.28
    docopt==0.4.0
    ecdsa==0.10
    Fabric==1.8.0
    html5lib==0.999
    Jinja2==2.6
    kombu==2.5.10
    lxml==3.4.4
    MySQL-python==1.2.5
    paramiko==1.12.0
    Pillow==2.4.0
    pycrypto==2.6.1
    pyes==0.99.5
    PyPDF2==1.22
    python-dateutil==2.1
    reportlab==3.2.0
    requests==2.7.0
    six==1.9.0
    sparkpost==1.2.0
    SQLAlchemy==0.8.0
    suds==0.4
    tornado==3.0.1
    urllib3==1.10.4
    wheel==0.24.0
    WTForms==1.0.3
    xhtml2pdf==0.0.6

----------
***Al ejecutar el comando:*** 

***pip install -r requirements.txt*** 

***me sale el siguiente error:***

----------

    (pasarela) 09:49:02 jugaz ~/Worked/FrontEnd/pasarela [master !] $
    pip install -r requirements.txt
    Collecting amqp==1.0.11 (from -r requirements.txt (line 1))
    Collecting anyjson==0.3.3 (from -r requirements.txt (line 2))
    Collecting backports.ssl-match-hostname==3.4.0.2 (from -r requirements.txt (line 3))
    Collecting billiard==2.7.3.28 (from -r requirements.txt (line 4))
    Collecting celery==3.0.19 (from -r requirements.txt (line 5))
    Collecting certifi==2015.4.28 (from -r requirements.txt (line 6))
      Using cached https://files.pythonhosted.org/packages/86/35/9758a67004a266047c779ae40a3d937869bfc6fc3422f6c606b8afbc9d23/certifi-2015.04.28-py2.py3-none-any.whl
    Collecting docopt==0.4.0 (from -r requirements.txt (line 7))
    Collecting ecdsa==0.10 (from -r requirements.txt (line 8))
    Collecting Fabric==1.8.0 (from -r requirements.txt (line 9))
    Collecting html5lib==0.999 (from -r requirements.txt (line 10))
    Collecting Jinja2==2.6 (from -r requirements.txt (line 11))
    Collecting kombu==2.5.10 (from -r requirements.txt (line 12))
    Collecting lxml==3.4.4 (from -r requirements.txt (line 13))
    Collecting MySQL-python==1.2.5 (from -r requirements.txt (line 14))
      Using cached https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip
    Collecting paramiko==1.12.0 (from -r requirements.txt (line 15))
    Collecting Pillow==2.4.0 (from -r requirements.txt (line 16))
    Collecting pycrypto==2.6.1 (from -r requirements.txt (line 17))
    Collecting pyes==0.99.5 (from -r requirements.txt (line 18))
    Collecting PyPDF2==1.22 (from -r requirements.txt (line 19))
    Collecting python-dateutil==2.1 (from -r requirements.txt (line 20))
    Collecting reportlab==3.2.0 (from -r requirements.txt (line 21))
    Collecting requests==2.7.0 (from -r requirements.txt (line 22))
      Using cached https://files.pythonhosted.org/packages/26/ff/c71b3943bebdd9f7ceb9e137296370587eb0b33fe2eb3732ae168bc45204/requests-2.7.0-py2.py3-none-any.whl
    Collecting six==1.9.0 (from -r requirements.txt (line 23))
      Using cached https://files.pythonhosted.org/packages/10/e3/a7f8eea80a9fa8358c1cd89ef489bc03675e69e54ed2982cd6f2a28d8295/six-1.9.0-py2.py3-none-any.whl
    Collecting sparkpost==1.2.0 (from -r requirements.txt (line 24))
      Using cached https://files.pythonhosted.org/packages/74/29/4fe828495a2c14e781a829429e33228c788c89f981ba0b5aea18ee464189/sparkpost-1.2.0-py2.py3-none-any.whl
    Collecting SQLAlchemy==0.8.0 (from -r requirements.txt (line 25))
    Collecting suds==0.4 (from -r requirements.txt (line 26))
    Collecting tornado==3.0.1 (from -r requirements.txt (line 27))
    Collecting urllib3==1.10.4 (from -r requirements.txt (line 28))
      Using cached https://files.pythonhosted.org/packages/92/b7/37eabe93db6e719a69f9515c911ada4399afb88ea08b2cbfa864d846e5b7/urllib3-1.10.4-py2-none-any.whl
    Collecting wheel==0.24.0 (from -r requirements.txt (line 29))
      Using cached https://files.pythonhosted.org/packages/e8/14/eaaac12b0432c984a27ad0050a5a0bedc6135df35a0f5f1f35228faf12d4/wheel-0.24.0-py2.py3-none-any.whl
    Collecting WTForms==1.0.3 (from -r requirements.txt (line 30))
    Collecting xhtml2pdf==0.0.6 (from -r requirements.txt (line 31))
    Requirement already satisfied: setuptools>=2.2 in ./lib/python2.7/site-packages (from reportlab==3.2.0->-r requirements.txt (line 21)) (39.2.0)
    Requirement already satisfied: pip>=1.4.1 in ./lib/python2.7/site-packages (from reportlab==3.2.0->-r requirements.txt (line 21)) (10.0.1)
    Installing collected packages: amqp, anyjson, backports.ssl-match-hostname, billiard, six, python-dateutil, kombu, celery, certifi, docopt, ecdsa, pycrypto, paramiko, Fabric, html5lib, Jinja2, lxml, MySQL-python, Pillow, urllib3, pyes, PyPDF2, reportlab, requests, sparkpost, SQLAlchemy, suds, tornado, wheel, WTForms, xhtml2pdf
      Running setup.py install for MySQL-python ... error
        Complete output from command /Users/jugaz/Worked/FrontEnd/pasarela/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/kw/89nh94pd6td8bz3_dq9yjphr0000gp/T/pip-install-n8xmdk/MySQL-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/kw/89nh94pd6td8bz3_dq9yjphr0000gp/T/pip-record-9kXxLo/install-record.txt --single-version-externally-managed --compile --install-headers /Users/jugaz/Worked/FrontEnd/pasarela/bin/../include/site/python2.7/MySQL-python:
        running install
        running build
        running build_py
        creating build
        creating build/lib.macosx-10.12-x86_64-2.7
        copying _mysql_exceptions.py -> build/lib.macosx-10.12-x86_64-2.7
        creating build/lib.macosx-10.12-x86_64-2.7/MySQLdb
        copying MySQLdb/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/MySQLdb
        copying MySQLdb/converters.py -> build/lib.macosx-10.12-x86_64-2.7/MySQLdb
        copying MySQLdb/connections.py -> build/lib.macosx-10.12-x86_64-2.7/MySQLdb
        copying MySQLdb/cursors.py -> build/lib.macosx-10.12-x86_64-2.7/MySQLdb
        copying MySQLdb/release.py -> build/lib.macosx-10.12-x86_64-2.7/MySQLdb
        copying MySQLdb/times.py -> build/lib.macosx-10.12-x86_64-2.7/MySQLdb
        creating build/lib.macosx-10.12-x86_64-2.7/MySQLdb/constants
        copying MySQLdb/constants/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/MySQLdb/constants
        copying MySQLdb/constants/CR.py -> build/lib.macosx-10.12-x86_64-2.7/MySQLdb/constants
        copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.macosx-10.12-x86_64-2.7/MySQLdb/constants
        copying MySQLdb/constants/ER.py -> build/lib.macosx-10.12-x86_64-2.7/MySQLdb/constants
        copying MySQLdb/constants/FLAG.py -> build/lib.macosx-10.12-x86_64-2.7/MySQLdb/constants
        copying MySQLdb/constants/REFRESH.py -> build/lib.macosx-10.12-x86_64-2.7/MySQLdb/constants
        copying MySQLdb/constants/CLIENT.py -> build/lib.macosx-10.12-x86_64-2.7/MySQLdb/constants
        running build_ext
        building '_mysql' extension
        creating build/temp.macosx-10.12-x86_64-2.7
        clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/opt/openssl/include -Dversion_info=(1,2,5,'final',1) -D__version__=1.2.5 -I/usr/local/Cellar/mariadb/10.2.15/include/mysql -I/usr/local/Cellar/mariadb/10.2.15/include/mysql/.. -I/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _mysql.c -o build/temp.macosx-10.12-x86_64-2.7/_mysql.o
        In file included from _mysql.c:44:
        /usr/local/Cellar/mariadb/10.2.15/include/mysql/my_config.h:3:2: warning: This file should not be included by clients, include only <mysql.h> [-W#warnings]
        #warning This file should not be included by clients, include only <mysql.h>
         ^
        In file included from _mysql.c:46:
        /usr/local/Cellar/mariadb/10.2.15/include/mysql/mysql.h:440:3: warning: this function declaration is not a prototype [-Wstrict-prototypes]
          MYSQL_CLIENT_PLUGIN_HEADER
          ^
        /usr/local/Cellar/mariadb/10.2.15/include/mysql/mysql.h:436:16: note: expanded from macro 'MYSQL_CLIENT_PLUGIN_HEADER'
          int (*deinit)();                                      \
                       ^
        _mysql.c:1589:10: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
                if (how < 0 || how >= sizeof(row_converters)) {
                    ~~~ ^ ~
        _mysql.c:2005:42: error: no member named 'reconnect' in 'struct st_mysql'
                if ( reconnect != -1 ) self->connection.reconnect = reconnect;
                                       ~~~~~~~~~~~~~~~~ ^
        3 warnings and 1 error generated.
        error: command 'clang' failed with exit status 1
    
        ----------------------------------------
    Command "/Users/jugaz/Worked/FrontEnd/pasarela/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/kw/89nh94pd6td8bz3_dq9yjphr0000gp/T/pip-install-n8xmdk/MySQL-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/kw/89nh94pd6td8bz3_dq9yjphr0000gp/T/pip-record-9kXxLo/install-record.txt --single-version-externally-managed --compile --install-headers /Users/jugaz/Worked/FrontEnd/pasarela/bin/../include/site/python2.7/MySQL-python" failed with error code 1 in /private/var/folders/kw/89nh94pd6td8bz3_dq9yjphr0000gp/T/pip-install-n8xmdk/MySQL-python/

**Comment by groutr** [comment]
How does this relate to PyMySQL?
