### ISSUE TITLE
Bad deadlock handling in MariaDB 10.2.XX

### ISSUE THREAD

**Issue by dduuch** [PyMySQL/PyMySQL#681]
Executing multiple operations that have been done from different DB hosts causes following error:

> (pymysql.err.InternalError) (1213, u'Deadlock: wsrep aborted transaction')

DBError should be returned instead of InternalError.

My Galera cluster is based on MariaDB 10.2.13 (on 10.2.14 is the same problem).

**Comment by methane** [comment]
> DBError should be returned instead of InternalError.

What is DBError?  There is not DBError in DB-API 2.0.

Do you mean DatabaseError?  InternalError is subclass of DatabaseError.

```
In [2]: issubclass(pymysql.InternalError, pymysql.DatabaseError)
Out[2]: True
```
