### ISSUE TITLE
Table not exists caused by a space

### ISSUE THREAD

**Issue by Antisunny** [PyMySQL/PyMySQL#685]
Python3.6.3

both `0.8.0` and `0.8.1`

pymysql.err.ProgrammingError: (1146, "Table 'informat ion_schema.tables' doesn't exist")

There is a space in the database name 'informat ion'

the code raises the Exception

```python
for item in data:
    print(json.dumps(item, ensure_ascii=False, indent=4), file=sys.stderr)
    with conn.cursor() as cur:
        cur.execute("""
            INSERT INTO `onco_reference` 
            (`pubmed_id`, `url`, `publication_year`, `title`, `journal`, `note`) 
            VALUES (%(pubmed_id)s, %(url)s, %(publication_year)s, %(title)s, %(journal)s, %(note)s)""", item)
    # conn.commit()
```

**Comment by methane** [comment]
PyMySQL just passes error from MySQL to you.
You need to fix your database.

Or if you have enough evidence this is PyMySQL's issue, please report complete information.
