### ISSUE TITLE
Invalid warning triggered when executing "create database IF NOT EXISTS mydatabase"

### ISSUE THREAD

**Issue by bagage** [PyMySQL/PyMySQL#688]
When running the following code:

```python3
#!/usr/bin/env python3

import pymysql

db = pymysql.connect("localhost", "root", "root")
cursor = db.cursor()
cursor.execute("create database IF NOT EXISTS mydatabase")
cursor.execute("create database IF NOT EXISTS mydatabase") # invalid warning triggered here
```

I get a warning in the console output:

```
/home/user/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1007, "Can't create database 'PROD'; database exists")
  result = self._query(query)
```

I believe it should not show up thanks to the `IF NOT EXISTS` condition. And there seems to be no way to ignore that warning?

PyMSQL version 0.8.1 with python 3.6.3.

**Comment by methane** [comment]
I believe you should not post such opinion and question here.
You must consult with MySQL team or stackoverflow.

**Comment by bagage** [comment]
I do not believe it's an issue with MySQL - the same request executed via `mysql-client` is running just fine with no warning.
There is no way, via pymsql, to remove that warning anyway. That's my issue.

**Comment by methane** [comment]
You just missed the warning with MySQL client.
PyMySQL doesn't raise such warning.
PyMySQL just send query and receive results, errors, and warnings.

**Comment by bagage** [comment]
Still, if anyone wants to get rid of this message when using PyMysql, the simplest solution is to workaround by adding:

```
cursor._defer_warnings = ignore_warning
```

**Comment by methane** [comment]
It ignores *all* warnings from MySQL, not only *this* warning.

I may add option to not show warnings in future version, but I'm not sure.

**Comment by methane** [comment]
BTW, mysql client has `--show-warnings` option which automatically show warnings, like PyMySQL.
https://dev.mysql.com/doc/refman/8.0/en/mysql-command-options.html#option_mysql_show-warnings

Without this option, mysql client shows only count of warnings, and you need to execute `SHOW WARNINGS` to see the warning.

```
mysql> create database IF NOT EXISTS mydatabase;
Query OK, 1 row affected (0.03 sec)

mysql> create database IF NOT EXISTS mydatabase;
Query OK, 1 row affected, 1 warning (0.01 sec)

mysql> show warnings;
+-------+------+-----------------------------------------------------+
| Level | Code | Message                                             |
+-------+------+-----------------------------------------------------+
| Note  | 1007 | Can't create database 'mydatabase'; database exists |
+-------+------+-----------------------------------------------------+
1 row in set (0.00 sec)
```

It's **very** basic knowledge.  You must ask on Stackoverflow, before assuming it's PyMySQL issue.

**Comment by bagage** [comment]
I know that mysqsl has `--show-warnings`, but again this is not the default value when you use `mysql-client` binary directly, while pymsql always forces it without any possibility to disable it.

I do not care about any mysql warnings for this particular request (eg: I know what I'm doing), so I just wanted pymsql to stop warning me here.

I know that setting deferred warnings to true will remove all warnings what-so-ever but again, I know what I'm doing, thank you.

**Comment by methane** [comment]
> I know that mysqsl has --show-warnings, but again this is not the default value when you use mysql-client binary directly, while pymsql always forces it without any possibility to disable it.
> 
> I do not care about any mysql warnings for this particular request (eg: I know what I'm doing), so I just wanted pymsql to stop warning me here.

Huh!  You should read the issue you wrote.

"Invalid warning triggered" --- Why you said "Invalid warning" if you didn't care?

"I believe it should not show up thanks to the IF NOT EXISTS condition." -- Why "thanks to"?

Your issue was about suppressing particular warning which MySQL raises.  Not about disabling show warning by default.

**Comment by devblueray** [comment]
I realize you don't think this is a pymysql issue and you may be correct.  However, I can issue both CREATE IF NOT EXISTS dbname and DELETE IF EXISTS dbname in the mysql client and it works without issue (no errors and it creates/deletes the database as instructed).  However, when I attempt the same commands in pymysql, it appears to ignore the IF EXISTS/IF NOT EXISTS part.  I took this to the mysql people and they told me that it's an issue with pymsql because it works in the mysql client.

**Comment by methane** [comment]
Have you read above discussion?

```
mysql> create database IF NOT EXISTS mydatabase;
Query OK, 1 row affected, 1 warning (0.01 sec)

mysql> show warnings;
+-------+------+-----------------------------------------------------+
| Level | Code | Message                                             |
+-------+------+-----------------------------------------------------+
| Note  | 1007 | Can't create database 'mydatabase'; database exists |
+-------+------+-----------------------------------------------------+
1 row in set (0.00 sec)
```

**mysql cli reports same warning**.
