### ISSUE TITLE
#682 broke the Python2 support

### ISSUE THREAD

**Issue by stamparm** [PyMySQL/PyMySQL#700]
https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/_auth.py#L175-L192 is incompatible with Python 2 (not reviewed the rest of `_auth`). Introduced the following issue: https://github.com/sqlmapproject/sqlmap/issues/3168.

Snippet as a proof:

```
import hashlib
password = u"foo".encode("utf8")
nonce = u"bar".encode("utf8")
p1 = hashlib.sha256(password).digest()
p2 = hashlib.sha256(p1).digest()
p3 = hashlib.sha256(p2 + nonce).digest()
res = bytearray(p1)
res[0] ^= p3[0]
```

results with the following error (on Python 2.7.12):

```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    res[0] ^= p3[0]
TypeError: unsupported operand type(s) for ^=: 'int' and 'str'
```

p.s. `hashlib`'s `digest()` returns `str` on Python2, while returning `bytes` on Python3

**Comment by methane** [comment]
Actually, it doesn't break Python 2, because older version didn't support caching_sha2.
But it's a bug of course.  Thanks.

**Comment by stamparm** [comment]
Can I then disable `caching_sha2` inside Python2? Currently module doesn't seem to be usable in Python2 or maybe I am wrong. I just want to find a way to bypass this Issue

**Comment by methane** [comment]
https://mysqlserverteam.com/upgrading-to-mysql-8-0-default-authentication-plugin-considerations/

But I think downgrading to older version is better workaround.

**Comment by stamparm** [comment]
So, basically, I'll be able to patch my Issue by forcing users to downgrade PyMySQL (https://github.com/sqlmapproject/sqlmap/issues/3168)?

**Comment by stamparm** [comment]
"Fixed" (https://github.com/sqlmapproject/sqlmap/commit/a424e4ab599cd80fd6ea54e828f2d72c7c4f2a9d). New message presented to the users:

```
please downgrade the 'PyMySQL' package (=< 0.8.1) (Reference: https://github.com/PyMySQL/PyMySQL/issues/700)
```

Thank you for your support. Closing this down. Sorry for bothering
