### ISSUE TITLE
Use Python's logging capability for debug output

### ISSUE THREAD

**Issue by dmiyakawa** [PyMySQL/PyMySQL#703]
From 0.9.0, it seems PyMySQL started to print debug information from pymsql._auth by default.

https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/_auth.py

```
DEBUG = True
...
    if n == 3:
        if DEBUG:
            print("caching sha2: succeeded by fast path.")
...
```

It is alright for the module to enable debug logging by default, especially during your heavy development, while as a user, I expect there should be a public and stable way to disable it (as part of an open API, or something similar).

I understand setting pymysql._auth.DEBUG to False works, but it is probably not "guaranteed" to be "stable" in the future release (may be removed, renamed, or ignored), as the module name implies (modifying a variable in a module starting with a underscore seems not "public").

A few suggestions:

 * It may be better to move DEBUG flag to the module that look more "public", like `pymsql.__init__.py`. Mentioning it in the document may also help, and the keep the flag kept for future releases.
    * Or, explicitly comment in _auth.py that why DEBUG is set to True and whether the flag will be kept in later release or just a tentative flag we (users) should not heavily rely on. In that case I think using `_DEV_DEBUG` for the name might be better, as it strongly implies "this flag is for development!!", which wouldn't confuse me.
 * Using Python's logging mechanism may be better than using `print()`. As a user, calling `getLoger('pymysql')` and configure its log level feels much more natural.

Thank you for your hard work. I really appreciate it.

**Comment by methane** [comment]
I just missed to disabled it.  And I don't want to use logging.

**Comment by methane** [comment]
And I don't want to increase API surface.  I don't want to guarantee more backward compatibility.
So I won't document more APIs.
