### ISSUE TITLE
Latest release (v0.9.1) installs `tests` as a top-level library

### ISSUE THREAD

**Issue by campadrenalin** [PyMySQL/PyMySQL#705]
This is kind of a subtle issue. The pymysql `tests` dir is installed as a top level package. So you could presumably reproduce this by:

1. Install pymysql globally or in a virtualenv.
2. Make sure the current directory doesn't have a `tests` dir.
3. Open a python prompt.
4. `import tests/test_auth` and see if it works.

This seems to come from a quirk of `PyMySQL-0.9.1.dist-info/top_level.txt`:
```
pymysql
tests
```

Most people won't notice. If you want to know the details of my workflow and why it affects me, I will include them below, but it doesn't really relate to fixing the packaging bug, and I know your time is valuable.

I use a tool called Serverless to deploy Python-based applications on AWS Lambda. Part of the build process is installing all Python dependencies to `.serverless/requirements/...`, and then symlinking those into the root of my project repository temporarily. It's failing because my repo has a `tests` dir, so when Serverless tries to symlink the `tests` dependency, the two collide. I have several different workaround options, including pinning to a previous version of PyMySQL. But I think this issue is worth fixing upstream for everybody, and any workarounds on my end would ideally be temporary.

**Comment by methane** [comment]
Fixed via fa43bf7

**Comment by campadrenalin** [comment]
Thank you so much for your quick response and resolution! It genuinely means a lot to us.
