### ISSUE TITLE
Specify pip3 in installation documentation please.

### ISSUE THREAD

**Issue by okridgway** [PyMySQL/PyMySQL#707]
Installation instructions from the [PyMySQL docs](https://pymysql.readthedocs.io/en/latest/user/installation.html) throw an error when not specifically run with pip3. Please consider updating them to reflect the github page. 

Thank you, 

(hope your wife gets better)

**Comment by methane** [comment]
Fixed via c3becee5e94223fac50d3fcfe8a3b157d76bbea7
