### ISSUE TITLE
PyMySQL with Flask: %d format: a number is required, not str with stored procedure

### ISSUE THREAD

**Issue by SeppPenner** [PyMySQL/PyMySQL#708]
Hi, I'm trying to use the cursors from PyMySQL together with stored procedures. As far as I understood, I can use the cursor as it's described in the documentation: http://pymysql.readthedocs.io/en/latest/modules/cursors.html

However, when I call the callproc method:

```python
cursor.callproc('storingSystemCreateCategory', args)
```

I get the following error: 

> %d format: a number is required, not str

My stored procedure is a simple one using only one IN parameter:

```mysql
DELIMITER //
CREATE PROCEDURE storingSystemCreateCategory(IN name VARCHAR(255))
 BEGIN
 INSERT INTO StoringSystem.Category(`createdAt`, `updatedAt`, `deleted`, `name`)
 VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, False, name);
 END //
DELIMITER ;
```

Is there a way to get this to work without the issue? I mean, the sense of stored procedures is to prevent SQL injections. So I would most likely want to use the validation on database side if possible.

Before you ask: Yes, the database access in general works. I use another project called [Flask-MySQL](http://flask-mysql.readthedocs.io/en/latest/) which basically only [simplifies the database initialization and connection](https://github.com/cyberdelia/flask-mysql/blob/master/flaskext/mysql.py#L3) from PyMySQL:

The issue is on stackoverflow, too: https://stackoverflow.com/questions/51176160/pymysql-with-flask-d-format-a-number-is-required-not-str-with-stored-procedu

**Comment by methane** [comment]
Why don't you paste traceback?

**Comment by SeppPenner** [comment]
`Why don't you paste traceback?`
Hi @methane. Let's just say it was too late in the evening when I posted the issue. I will provide more details on my setup and the traceback from the client soon.

**Comment by methane** [comment]
Yes.  Stacktrace tells everything I need:

```
  File "C:\Program Files (x86)\Python\lib\site-packages\pymysql\connections.py", line 964, in connect
    self.host_info = "socket %s:%d" % (self.host, self.port)
TypeError: %d format: a number is required, not str
```

You passed string for `port` argument, but it must be integer.

```
app.config['MYSQL_DATABASE_PORT'] = '3306'
```

This should be `3306`, not `'3306'`

**Comment by SeppPenner** [comment]
@methane Thanks. I will change this and try again.

**Comment by SeppPenner** [comment]
Hi @methane: This issue is fixed, thank you 👍
