### ISSUE TITLE
General question about reconnect

### ISSUE THREAD

**Issue by test24853** [PyMySQL/PyMySQL#711]
Was anyone able to "use" the reconnect feature proper? The example code in the docs are not able to do that. ping(true) neither. Since I switched from MySQLdb to pymysql I am haunted by not being able to reconnect issues. Can anyone guide me into the right direction? Also overwriting core lib methods does not seem the right way for something simple like a reconnect.

Thanks a lot for everyone who takes the time to read that.

`db = pymysql.connect(host="***", user="***", passwd="***", db="***", use_unicode=True, hharset='utf8mb4', cursorclass=pymysql.cursors.DictCursor)`
`db.autocommit(True)`
`db.ping(True)`

Other people also seem to have the issue after they switched from MySQLdb to pymysql:

https://github.com/PyMySQL/PyMySQL/issues/601

**Comment by Schokobecher** [comment]
+1 this, it's really annoying and makes me consider switching libs again...

**Comment by methane** [comment]
Read https://github.com/PyMySQL/PyMySQL/issues/601#issuecomment-330798537 and https://github.com/PyMySQL/PyMySQL/issues/601#issuecomment-352754547

**Comment by test24853** [comment]
@methane thank you for your feedback.

So you are saying I need to run cur.ping() before every single query? Did I understand that correctly?

I am not long pooling anything. I am using flask and Gunicorn. But also on all my other py3 scripts that do jobs that last longer then wait_timeout I encounter those issues.

@methane I do understand that you are a really skilled and busy individual. But so many people - including me - struggle with this. Take a look at the stackoverflow questions about this topic its crazy. I do understand that this might cause huge problems with transactions, but is there no way to add a parameter for this behavior? **You would save people thousands of hours troubleshooting and finding and writing their own dirty solutions to this problem.** Even if you won't respond to this, I still appreciate your work and your library.

**Comment by methane** [comment]
> So you are saying I need to run cur.ping() before every single query? Did I understand that correctly?

No.  Have you read my two comments, really?

> I am not long pooling anything. I am using flask and Gunicorn. But also on all my other py3 scripts that do jobs that last longer then wait_timeout I encounter those issues.

auto reconnect is bad way to dealing with wait_timeout.
You must refresh DB connection frequently, before it is closed from server.
For example, SQLAlchemy has `pool_recycle` option.
http://docs.sqlalchemy.org/en/latest/core/pooling.html#setting-pool-recycle
(While I think "3600" in the example is too long... 1min~10min is enough.)

> Take a look at the stackoverflow questions about this topic its crazy.

What is "the stackoverflow questions"?

> You would save people thousands of hours troubleshooting and finding and writing their own dirty solutions to this problem. 

No. auto reconnect must not help them.  It's a bad feature in most cases.
Connection must be closed from client side, not server side.  Otherwise, you cannot know
your query is executed or not executed.

**Comment by test24853** [comment]
Hello @methane ,

I know some time has passed but recently I am working in an environment again where roughly every 3rd connection has a timeout. What is the proper way of handling such an issue? Asking you because you seem to be a really experienced person and there must be a way how professionals solve this in an elegant way.

All the "solutions" I found was overwriting your library via classes. Right now I am doing a .ping(True) before every query, but since this environment has a 33% timeout ratio that does not do the job anymore sadly. I do not do transactions by the way. Just regular UPDATE, SELECT, DELETE.

It feels like a wrong approach to write 8 additional lines of python code for every SELECT query. (While, Exception, etc). Thank you so much for your time and hope for a response :)

**Comment by methane** [comment]
The only solution is fix your environment.  There are no way to use MySQL safely on such environment.

When connection is closed during you're executing query like "UPDATE" or "DELETE", there are
no way to know the query is executed or not.
Even if you're using transaction, `db.commit()` can be failed.  So your query is executed or not.
This is fundamental problem of distributed system.  No one can solve it.

So you need to fix your environment.  Such accidental connection close must not be happened 99.9999% time.

**Comment by Schokobecher** [comment]
I've been watching this issue and must say: Come down your high horse @methane ...

I find it astonishing how you can be that blind to an issue and just tell somebody "you can't use MySQL" for whatever reason?

> The only solution is fix your environment
>There are no way to use MySQL safely on such environment.

It not up to you to decide which use-case of an environment is fit for MySQL - If somebody wants to run MySQL client on a toaster they can do it and you should not let your ideology artificially limit the possibilities. According to you I can't run a MySQL client on a RPI with an LTE connection or run it at my home connection in a typical developing country, where high latency and package loss is more common than you might imagine.

So maybe label your project with some "Idealist ideas only" or "Only useable with packet loss below XY%"

You inherited a lot of users from the MySQL-python, I know that for a fact. That library ignored your "safety concerns" if you wanted it to, and let the dev handle the safekeeping like a program should have the option for.

> So you need to fix your environment.

Sure, want me to redirect a call with my local ISPs (Wired and non-wired) to you? So you can explain to them why they are bad and my 3rd world country can go to hell and MySQL is not suitable for anything?

Ridiculous and very saddening. 0% compromising or even trying to understand an issue/request and 100% basing with **THAT'S NOT WHAT I WANT** - At least offer an option if you think others can't handle a change.

Cheers.

**Comment by methane** [comment]
@Schokobecher Did you read the comment correctly?
I asked "the proper way of handling such an issue".  So I must say there are no such way, by computer science.  I described why it's impossible.

> Sure, want me to redirect a call with my local ISPs (Wired and non-wired) to you? So you can explain to them why they are bad and my 3rd world country can go to hell and MySQL is not suitable for anything?

I use laptop and I use suspend heavily.  But it's not problem.  I run Python program on remote machine (e.g. EC2) with ssh + tmux.  Or you can even run MySQL local and send dump file to remote.

Without reliable connection, no one can use MySQL in reliable way.  "UPDATE a=a+1" will or will not be executed.  If you retry, it will be executed 0~(max retry count) times.  It's computer science.

> Ridiculous and very saddening. 0% compromising or even trying to understand an issue/request and 100% basing with **THAT'S NOT WHAT I WANT** - At least offer an option if you think others can't handle a change.

I use issue tracker for tracking issues of OSSes I maintain.  Not for communicating users.
Read this article: https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde
