### ISSUE TITLE
two problems while using this library

### ISSUE THREAD

**Issue by hiwjcn** [PyMySQL/PyMySQL#717]
### problem1:
in this way,cursor raise a exception,says that cursor do'nt has a function named cursor()
``` python
with connection.cursor() as cursor:
        # Create a new record
        sql = "INSERT INTO `users` (`email`, `password`) VALUES (%s, %s)"
        cursor.execute(sql, ('webmaster@python.org', 'very-secret'))
```
i should use pymysql like this way.it works ,but its different from the doc.
``` python
def check_exist(m):
    with connection() as con:
        con.execute('select * from car_zone where no=%s and update_time=%s limit 1', (m['no'], m['update_time']))
        return len(con.fetchall()) > 0
```
### problem2
when i pass a number arg with %d placeholder in sql,pymysql raise a exception that %d only recieve number argument,but got str.i indeed pass an number arg in my code.
this confused me

## in the end
`thanks for your contribute`

**Comment by methane** [comment]
Both are not problem.  That's spec.
You must go Stackoverflow before stealing OSS maintainer time and energy.
