### ISSUE TITLE
Deprecate old password

### ISSUE THREAD

**Issue by methane** [PyMySQL/PyMySQL#718]
Old password is not recommended for all version of MySQL which PyMySQL supports.

I don't test it.  I don't use it.  I don't want support it.  And existing code is ugly.
Deprecate it in next version, and remove it eventually.

**Comment by joelthelion** [comment]
So how does one use the new password? I looked at the docs trying to understand what I am doing wrong, but couldn't figure it out (I'm using the password= keyword argument in the pymysql.connect function, is this no longer correct?).

PS: I arrived here from https://github.com/PyMySQL/PyMySQL/pull/713, wondering why the fix hadn't been pushed to pypi yet).

**Comment by methane** [comment]
> So how does one use the new password?

Why should I google instead of you?  Why don't you google by yourself instead of annoying maintainer?
Read "Upgrading Accounts from mysql_old_password to mysql_native_password" section in https://dev.mysql.com/doc/refman/5.6/en/account-upgrades.html


> PS: I arrived here from #713, wondering why the fix hadn't been pushed to pypi yet).

Because make new release take my time and energy.
And there is far better solution: upgrading password.

Note that old password is Pre-4.1 format.  MySQL 4.1 is released 2003!
MySQL 5.7 CLI dropped old password support already.

**Comment by joelthelion** [comment]
Believe it or not, I did google, but I was under the assumption that "new password" was a pymysql concept, not a server setting. I absolutely respect your time and realize that you are under no obligation to answer my questions.

That said, I cannot upgrade a 20 year old system like that. So if you stop supporting it, I'll have to use a different package.

**Comment by blodter** [comment]
@joelthelion - I'm in the same situation. @methane, why would you remove backwards-compatible support? Users should have the option to use less secure methods if they so choose - not everyone is able to upgrade older systems as @joelthelion already pointed out.

**Comment by methane** [comment]
> why would you remove backwards-compatible support?

I don't want to maintain it.  I don't use 20 year old MySQL.  That's enough reason.

> Users should have the option to use less secure methods if they so choose - not everyone is able to upgrade older systems as @joelthelion already pointed out.

Huh.  You have option to use old version of PyMySQL, or fork this project.
Don't forget this is not Oracle's project: I maintain this project almost as a volunteer.

Or do you want to donate $10/month for maintain old password?

**Comment by methane** [comment]
One more note: Even Oracle (MySQL owner) removed old password support form MySQL client library.
Why do you think one volunteer maintainer should support 20-year-old legacy feature longer than owner company?

**Comment by scotloach** [comment]
This is really unfortunate.  I have a project that needs to connect to an old server that doesn't use new password yet.  I can't force the server maintainer to update it, I just need it to work.  Backwards compatibility would have been nice, I'll have to find an alternative library to use.

**Comment by methane** [comment]
You can use old PyMySQL like you are using old password, old MySQL cli, etc.

**Comment by scotloach** [comment]
I wonder if something else is going on then, because the command-line client works fine for the DB I'm connecting to, but I get the same error from the client.  Is there a way to tell (with restricted rights on the DB) what's happening?

**Comment by methane** [comment]
Don't bother me anymore.
MySQL already **removed** (not only deprecated) it.
I haven't test it for long years.  I don't want to test and maintain it anymore.
I'm tired to maintain this project and I must reduce maintenance cost of this project.
