### ISSUE TITLE
How to use user-defined variables?

### ISSUE THREAD

**Issue by markuman** [PyMySQL/PyMySQL#723]
```python
import pymysql.cursors

# Connect to the database
connection = pymysql.connect(host='127.0.0.1',
                             user='root',
                             password='password',
                             db='somedb',
                             port=3306,
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)


with connection.cursor() as cursor:
    sql = """
    SET @bla = 1; 
    select @bla;"""
    cursor.executemany  (sql, ('webmaster@python.org',))
    result = cursor.fetchone()
    print(result)
```

While that sql file

```sql
SET @bla = 1; 
select @bla;
```

works with mysql-cli, dbeaver, mysql-workbench, I don't get it to work with PyMySQL. Splitting the statements will results in an empty result for the 2nd statement.  
Is it not possible to work with user-defined variables inside the statements or am I stupid?

**Comment by methane** [comment]
https://github.com/PyMySQL/PyMySQL/blob/55e195cdf2f19c3f36007b72c1a9093dd9b0ebdb/CHANGELOG#L55-L58

**Comment by NiDHanWang** [comment]
> https://github.com/PyMySQL/PyMySQL/blob/55e195cdf2f19c3f36007b72c1a9093dd9b0ebdb/CHANGELOG#L55-L58

Query works well with **client_flag** set to **CLIENT.MULTI_STATEMENTS**, but no data returns.
While the same query does return data when I run it with Navicat, what could be the possible reason for this?

Here's an example of my code:
```python
import pymysql
from pymysql.constants import CLIENT

sql_query = '''
set @a:=0;
select order_id,@a:=@a+1
from yu_saler_order
where success_time>='2021-05-18 00:00:00';
'''
conn = pymysql.connect(
    host = 'XXXXXX',
    port = XXXX,
    user = 'XXX',
    passwd = 'XXXXXX',
    db = 'XXXXX',
    charset = 'utf8',
    client_flag= CLIENT.MULTI_STATEMENTS
)
cur = conn.cursor()
cur.execute(sql_test)
```
