### ISSUE TITLE
Queries after Exception on connection return previous result

### ISSUE THREAD

**Issue by adamchainz** [PyMySQL/PyMySQL#724]
I'm chasing a problem with my application, which uses an exception deriving from `BaseException` to do some control flow to exit when a condition is met, much like `KeyboardInterrupt` or `SystemExit`. I'm seeing the wrong result come back a context manager that does a queries in its `__exit__` block (specifically it's a user lock, [source](https://github.com/adamchainz/django-mysql/blob/master/django_mysql/locks.py#L47)).

I've simplified this down into a reproducible test script - run it, and then immediately hit Ctrl-C to kill it:

```python
import pymysql


def main():
    cursor = pymysql.connect().cursor()
    try:
        for _ in range(10):
            cursor.execute('select sleep(0.5)')  # simulate doing work, returns 0

    finally:
        cursor.execute("select 1")
        assert cursor.fetchone()[0] == 1, "Wrong result"  # on Ctrl-C, gets 0 from sleep


if __name__ == '__main__':
    main()

```

And of course one doesn't hit Ctrl-C, the right result is returned and the assertion passes.

I think the behaviour is due to an `except:` instead of `except Exception:` within PyMySQL's source, perhaps [this one](https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L721), meaning it's interpreting the `BaseException` as if it was due to a problem in communications with MySQL, instead of part of 'control flow' exiting the program. Potentially related to #275.

**Comment by adamchainz** [comment]
Actually I'm not sure `BaseException` handling is to blame, here's a second test script that more closely emulates my application by using the POSIX alarm signal to trigger a random exception after 1 second:

```python
import signal

import pymysql


def main():
    def raise_exception(signal_num, stack_frame):
        raise Exception('death')

    signal.signal(signal.SIGALRM, raise_exception)
    signal.alarm(1)

    cursor = pymysql.connect().cursor()
    try:
        cursor.execute('select sleep(3)')  # simulate doing work, returns 0

    finally:
        cursor.execute("select 1")
        assert cursor.fetchone()[0] == 1, "Wrong result"


if __name__ == '__main__':
    main()
```

`Exception('death')` can be swapped for `KeyboardInterrupt` to properly match the previous behaviour.

I think a better explanation is: on exception, pymysql assumes the connection won't be reused, and it can be left in a state where results are pending. Raising special exceptions like `KeyboardInterrupt` can actually trigger more queries in context managers / `except` clauses, and these end up fetching previous queries' results. Probably cleanup behaviour can be added when a new query is issued to see if a previous one was interrupted by an exception.

**Comment by methane** [comment]
> an exception during query execution, pymysql assumes the connection won't be reused, and it can be left in a state where results are pending.

Yes, it's by design.  You must not reuse the connection.
Fetching previous query is complex than you think; for example, how much timeout should be used?
When result is very large and it takes much time or memory, Ctrl-C should be able to stop receiving.

I recover from error only when it's really mandatory.
In this case, you should just use new connection.

**Comment by adamchainz** [comment]
What do you think of adding guards against the current behaviour, which is basically a silent failure? It took me quite some time to debug the cause.

**Comment by methane** [comment]
No thoughts until I see PR.
If it's robust, easy to maintain, robust, and negligible overhead, I may merge.

**Comment by silverriver** [comment]
@adamchainz 
Exactly same issue. It takes me an entire afternoon debuging my code.
Having some kinds of warning for this issue is nice. 
Seem I need to check how to use pymysql in a more appropriate way.
