### ISSUE TITLE
Writing one DataFrame to Mysql

### ISSUE THREAD

**Issue by lugq1990** [PyMySQL/PyMySQL#732]
Dear, all,
  I want to use python to write a DataFrame to Mysql, I have already create table in Mysql. But I did not find a good way to do this.  I have found by using df.to_sql(), but this doesn't work for me. 
  Please tell me how to do this fast?
  Thank you!

**Comment by methane** [comment]
Here is issue tracker, not user forum.
Use Stackoverflow.

(Hint: Use csv and "LOAD LOCAL INFILE" query)
