### ISSUE TITLE
AttributeError: '[class]' object has no attribute 'translate' on execute with extra args

### ISSUE THREAD

**Issue by neirbowj** [PyMySQL/PyMySQL#734]
Thank you for the work you do on this software.

# Expected behavior

`Cursor.execute` only attempts to process arguments that are referenced by the query string.

# Observed behavior

`Cursor.execute` attempts to process all arguments, and raises `AttributeError` if an argument cannot be escaped.

Sample traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/neirbowj/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/home/neirbowj/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/home/neirbowj/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 127, in _escape_args
    return dict((key, conn.literal(val)) for (key, val) in args.items())
  File "/home/neirbowj/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 127, in <genexpr>
    return dict((key, conn.literal(val)) for (key, val) in args.items())
  File "/home/neirbowj/venv/lib/python3.6/site-packages/pymysql/connections.py", line 469, in literal
    return self.escape(obj, self.encoders)
  File "/home/neirbowj/venv/lib/python3.6/site-packages/pymysql/connections.py", line 462, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/home/neirbowj/venv/lib/python3.6/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/home/neirbowj/venv/lib/python3.6/site-packages/pymysql/converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/home/neirbowj/venv/lib/python3.6/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Eggs' object has no attribute 'translate'

```

# Steps to reproduce

```python
import pymysql
class Eggs():
    pass
conn = pymysql.connect(user='user', password='secret', host='localhost')
cur = conn.cursor()
cur.execute('SELECT %(spam)s', dict(spam=3, eggs=Eggs()))
```

# Environment

```
$ python --version
Python 3.6.7
$ pip list
Package      Version
------------ -------
asn1crypto   0.24.0
cffi         1.11.5
cryptography 2.3.1
idna         2.7
pip          18.1
pycparser    2.19
PyMySQL      0.9.2
setuptools   40.4.3
six          1.11.0
$ cat /etc/system-release
Red Hat Enterprise Linux Server release 6.10 (Santiago)
 $ mysql --version
mysql  Ver 14.14 Distrib 5.7.23, for Linux (x86_64) using  EditLine wrapper
```

**Comment by neirbowj** [comment]
Arguments that are not referenced by the query string should be of no concern to PyMySQL because they do not need to be encoded and bound to query parameters. I've checked some other database drivers (MySQLdb 1.3.13, psycopg2 2.7.5, pg8000 1.12.3, sqlite3) and they all ignore unneeded arguments as I expected they would. That behavior is also consistent with common patterns in Python more generally.

Will you consider this as an enhancement request?

**Comment by methane** [comment]
> I've checked some other database drivers (MySQLdb 1.3.13, psycopg2 2.7.5, pg8000 1.12.3, sqlite3) and they all ignore unneeded arguments as I expected they would. 

Really?  I'm a mysqlclient (MySQLdb) maintainer.  It escapes *all* items in passed dict.

https://github.com/PyMySQL/mysqlclient-python/blob/9fb618806bf638fa67f40b9cc3dafc4779237b63/MySQLdb/cursors.py#L112-L116

pysqlite uses just `?`.  They don't use dict, do they?

Unlike psycopg or pg8000, MySQLdb used `str % dict` from long time ago, before I start maintain.
I don't want to break backward compatibility.

> Will you consider this as an enhancement request?

No.  I don't know any way to list which `%(name)s` are used in the string in zero cost.
