### ISSUE TITLE
With + Connection - returns cursor rather than the connection, doesn't close connection on exit

### ISSUE THREAD

**Issue by greghoop** [PyMySQL/PyMySQL#735]
By returning a cursor rather than a connection, extra code needs to be written to handle exceptions and close the connection. Why not return a connection object, then a user can use a second nested with to get a cursor object. This way, wherever an error occurs, the cursors/connections will be neatly closed, and tracebacks will nicely propagate.

I noticed this was a problem when using SSH, and the tunnel wasn't getting decommissioned because the DB connection was still active. Other users also having this problem:

https://stackoverflow.com/questions/31214658/can-i-use-pymysql-connect-with-with-statement

Relevant lines in the code:

https://github.com/PyMySQL/PyMySQL/blob/09040abb0a8153b68b76113539632e7eaa53ce69/pymysql/connections.py#L494

https://github.com/PyMySQL/PyMySQL/blob/09040abb0a8153b68b76113539632e7eaa53ce69/pymysql/connections.py#L498

**Comment by methane** [comment]
These APIs are added for compatibility with mysqlclient.
And these APIs are deprecated in mysqlclient later.

https://github.com/PyMySQL/mysqlclient-python/blob/9fb618806bf638fa67f40b9cc3dafc4779237b63/MySQLdb/connections.py#L278-L290

But I forgot to deprecate these API in PyMySQL.
Wait at least two years:  one year for deprecation, next one year for removal.

**Comment by mark-schaal** [comment]
Glad to know I'm not alone in seeing this, and +1 to @greghoop link to https://stackoverflow.com/questions/31214658/can-i-use-pymysql-connect-with-with-statement.

The context manager is a good interim workaround if you do not want to assign the connection to a variable manually.

**Comment by halezmo** [comment]
I also got this strange issue, will this be solved soon?
