### ISSUE TITLE
Canot cath invalid charset on connection

### ISSUE THREAD

**Issue by WHK102** [PyMySQL/PyMySQL#737]
Example:

    pymysql.connect(
        unix_socket='/var/lib/mysql/mysql.sock',
        charset       ='utf-8'
    )

Says:

    'NoneType' object has no attribute 'encoding'
    ...
    File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 284, in __init__
      self.encoding = charset_by_name(self.charset).encoding

In the documentation: https://pymysql.readthedocs.io/en/latest/modules/connections.html the `charset` attribute does not specific the object type or charsets supported.

> charset – Charset you want to use.

Any charset?, i set the string `'utf-8'` but have a exception.

In MySQL the `utf-8` is `utf8`, but in all other develop language like as java, php, etc is `utf-8` and the ISO standard declare the name as `utf-8`.

Please, add in the documentation: The charset string supported are same the MySQL supported, like as `utf8` and not the python literal supported.

Add a switch with the supported mysql charsets: https://dev.mysql.com/doc/refman/5.5/en/charset-charsets.html , and call a trow if the charset is not present in the list.

**Comment by methane** [comment]
Google "MySQL charset"

If you want to use utf-8, charset is "utf8mb4"

2018年10月27日(土) 10:37 WHK <notifications@github.com>:

**Comment by WHK102** [comment]
Thanks @methane but what I want is for you to control the parameters delivered.

**Comment by methane** [comment]
I can not understand what you meaning.
I am not good English reader/writer.  You shouldn't expect me to write document for MySQL beginners.
There are many information on the internet.  Google is your friend.
