### ISSUE TITLE
Canot use int as param in execute()

### ISSUE THREAD

**Issue by WHK102** [PyMySQL/PyMySQL#738]
By example:

    handler = pymysql.connect(...)
    cursor = handler.cursor()
    cursor.execute('''
                INSERT INTO tablename (col_int, col_str)
                VALUES (%d, %s)
            ''', (int(value_int), str(value_str)))

The error says:

    %d format: a number is required, not str.
    File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 168, in execute
      query = self.mogrify(query, args)
    File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 147, in mogrify
      query = query % self._escape_args(args, conn)

**Comment by methane** [comment]
You can not use %s because PyMySQL convert all arguments to strong suitable to embed in SQL.
