### ISSUE TITLE
unable get real last insert id from execute()

### ISSUE THREAD

**Issue by WHK102** [PyMySQL/PyMySQL#740]
For example: make a custom insert into table if record not exist:

    INSERT INTO tablename (column_value)
    SELECT * FROM (SELECT %s) AS to_insert
    WHERE NOT EXISTS (
        SELECT id
        FROM   tablename
        WHERE
            column_value = %s
        ) LIMIT 1

If the record not exist, the `cursor.lastrowid` return the row inserted, but if the row is duplicated, the value returned is `0`.

From mysql query using `LAST_INSERT_ID()` return the key id if record exist and is duplicated.

Please, when the record is duplicated using `cursor.lastrowid`,  return the duplicated record id like as mysql server.

**Comment by methane** [comment]
It's not driver's job.  You should ask to bugs.mysql.com.
