### ISSUE TITLE
When will #713 be pushed into pypi?

### ISSUE THREAD

**Issue by arccoder** [PyMySQL/PyMySQL#741]
_Originally posted by @Anthonyjmartin in https://github.com/PyMySQL/PyMySQL/pull/713#issuecomment-413525898_

The PyMySQL 0.9.2 version does not seem to have the #713 change.
Please merge this change to pypi.

**Comment by methane** [comment]
See https://github.com/PyMySQL/PyMySQL/pull/713#issuecomment-414264904
