### ISSUE TITLE
Need to install pymysql on servers without web access

### ISSUE THREAD

**Issue by zappfinger** [PyMySQL/PyMySQL#745]
On my job, I need to install pymysql on several secured servers. They do not allow internet access, so I can not use pip. I did download the pymysql egg, but this requires cryprography. So I downloaded the cryptography wheel, but when running pip install on that it tries to get additional data from the web.
I'm using python3.7. Any way to get the whole pymysql package including all dependencies off line?

**Comment by methane** [comment]
**[You must not ask a question on issue tracker](https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde#.hdf6lpk11)**
