### ISSUE TITLE
decode error when using a chinese program name like '特征工程.py'

### ISSUE THREAD

**Issue by lhdgriver** [PyMySQL/PyMySQL#747]
pymysql/connections.py line 847 v = v.encode('utf8') 'ascii' codec can't decode
I see the code here around line 318

`

        if program_name is None:
            argv = getattr(sys, "argv")
            if argv:
                program_name = argv[0]
        if program_name:
            self._connect_attrs["program_name"] = program_name
`

and here around line  852, which encode the 'program_name' which is in chinese... and failed.
`
v = v.encode('utf8')
`

I use a english program name, and then it fixed. But i think there may be a more 'right' way to do it.

**Comment by methane** [comment]
Oh! Do you use Python 2?

**Comment by methane** [comment]
@lhdgriver Would you try #748?

**Comment by lhdgriver** [comment]
Yes. I have to use python2. #748 fix the problem.
But the way, I see in _compat.py, you use range_type to make it compatible. But a better way is to use six, [https://pythonhosted.org/six/](url),

**Comment by methane** [comment]
I know six of course.
I don't want to add external dependency only for 6 items.
