### ISSUE TITLE
pymysql reads returning mysql query cache results

### ISSUE THREAD

**Issue by yashh** [PyMySQL/PyMySQL#76]
Just hit a weird case. I am using pymysql with connection pooling. So I pull of a connection object from a queue create a cursor and perform read and close the cursor and put back the connection object into the queue

```
with get_mysql_cursor() as cursor:
    cursor.execute("Select count(*) from items")
    data = cursor.fetchall()
```

Now when you insert / delete from items using a different connection (or) even using mysql client, the above code will still show the old count.  I thought pymysql was caching the results but I traced it back to the Connection.wfile.write()... and found out that mysql was actually being queried. Then after some googling I hit this bug on mysql (http://bugs.mysql.com/bug.php?id=42197)

So after creating the connection I set the .autocommit(True) and then that fixed my problems. I never knew that set autocommit=1; by passes the mysql query cache.. But it is pretty surprising.  Were you able to reproduce this behaviour.

**Comment by wangyangkobe** [comment]
@methane You are my hero, thanks a lot.

**Comment by BetterAutomations** [comment]
I don't understand why I had to set autocommit(True) to see current data when I am in fact committing. This was seeing cached changes on this table until I set that.

```
mysql> REPLACE INTO `door_notifications` (`username`, `value`) VALUES ('ByteMe@Example.com', 'false'); COMMIT;
Query OK, 2 rows affected (0.01 sec)

Query OK, 0 rows affected (0.00 sec)

mysql>
```

With the above command, you can see I am performing a commit. But pymysql in another shell still sees 'true'. So I added conn.autocommit(True), restarted the script, and now toggling the command above between true and false does in fact change the value seen by pymysql. What might cause this behavior?

Here's the columns. The `ts` column is unused and probably will be dropped.
```
mysql> SHOW COLUMNS FROM `door_notifications`;
+----------+-------------+------+-----+-------------------+-----------------------------------------------+
| Field    | Type        | Null | Key | Default           | Extra                                         |
+----------+-------------+------+-----+-------------------+-----------------------------------------------+
| ts       | timestamp   | YES  |     | CURRENT_TIMESTAMP | DEFAULT_GENERATED on update CURRENT_TIMESTAMP |
| username | varchar(60) | NO   | PRI | NULL              |                                               |
| value    | json        | NO   |     | NULL              |                                               |
+----------+-------------+------+-----+-------------------+-----------------------------------------------+
3 rows in set (0.00 sec)

mysql>
```

**Comment by methane** [comment]
You should learn "transaction" and "repeatable read".
