### ISSUE TITLE
Improve helpfulness of error message when cryptography is required

### ISSUE THREAD

**Issue by srcole** [PyMySQL/PyMySQL#768]
I just downloaded mysql (v8.0.13) and pymysql (v0.9.3) on my Mac (OS v10.14). This newest version of mysql now suggests encrypting passwords with SHA256 by default.

I was trying to connect to a database in mysql using:
```
import pymysql
con = pymysql.connect('localhost', 'testuser', 'testpw', 'testdb')
```

And got the error: `RuntimeError: cryptography is required for sha256_password or caching_sha2_password`

It took me 10 minutes or so on Google, and going to where this error was encoded on this github, to figure out that "cryptography" is just a package I need to pip install.

This could have been much easier if the error was worded just a little differently, e.g.:

```
RuntimeError: The python package, cryptography, is required for sha256_password or caching_sha2_password. Obtain this package by running `pip install cryptography` and retry.
```

This is a trivial PR, so I'm gonna go ahead and submit it. I think this could trip up others too.

**Comment by methane** [comment]
Your suggestion looks too long.
If you can google based on current error message, it's enough.

**Comment by chimziie** [comment]
I also struggled with this one for a while! Please implement this fix.

**Comment by kumanoit** [comment]
I too struggled with this for long time. Googling this error leads to various unhelpful links.
Its better to add a line like "pip install cryptography". This can save a lot of time.

**Comment by hurjinhyuk1** [comment]
Thank you for your help.
Really in cmd, pip install cryptography works !!

**Comment by lacortes** [comment]
Thank you so much!!! Was having issues overall using SQLAlchemy to connect to MYSQL and someone recommended I use pymysql and then this error came out next. You have saved me hours of headaches!

**Comment by RakeshNagarajan** [comment]
> 
> 
> I too struggled with this for long time. Googling this error leads to various unhelpful links.
> Its better to add a line like "pip install cryptography". This can save a lot of time.

Thanks.. it worked :)

**Comment by lcalmbach** [comment]
I struggled with this as well, that would be a great fix!
