### ISSUE TITLE
Syntax error when using semi colons in query

### ISSUE THREAD

**Issue by bagerard** [PyMySQL/PyMySQL#770]
Hi, First of all thanks for the great library!
We recently upgraded pymysql version (0.7.9 --> 0.9.2) in our application (python 3.6.5) and noticed that queries with semi colons started failing. See below:
```
import pymysql
connection = pymysql.connect(host='127.0.0.1',
                             user='cptest',
                             password='*****',
                             db='test',
                             charset='utf8',
                             cursorclass=pymysql.cursors.DictCursor)
with connection.cursor() as cursor:
    sql = "DROP TABLE IF EXISTS `odm_AuditRecord`;DROP TABLE IF EXISTS `odm_AuditRecord2`;"
    cursor.execute(sql)

(...)
~/.pyenv/versions/3.6.5/envs/cpconn/lib/python3.6/site-packages/pymysql/err.py in raise_mysql_exception(data)
    107         errval = data[3:].decode('utf-8', 'replace')
    108     errorclass = error_map.get(errno, InternalError)
--> 109     raise errorclass(errno, errval)

ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DROP TABLE IF EXISTS odm_AuditRecord2' at line 1")
```
Am I doing something wrong or is this a bug?
Thanks in advance for the support!

**Comment by methane** [comment]
> Am I doing something wrong or is this a bug?

You didn't read the changelog.

https://github.com/PyMySQL/PyMySQL/blob/a3c06319791009436315eb9387ca3fa00bfd4b17/CHANGELOG#L66-L69

>  Thanks in advance for the support!

I'm a volunteer OSS maintainer, but not a free tech support for every user.
Use Stackoverflow or some other place to get **community** support.
