### ISSUE TITLE
sum and avg seem not to work

### ISSUE THREAD

**Issue by Feano** [PyMySQL/PyMySQL#771]
Hello, 
I try to execute a sum command:

with conn.cursor(pymysql.cursors.DictCursor) as cur:
        cur.execute("SELECT sum(aID) FROM userAnswers")
        conn.commit()
        ranking = cur.fetchall()

Sum always returns null, while count returns the correct count. AVG also returns null, min and max return the correct result. Sorry if this is an error on my side, however, I do not have an explanation and found nothing on the internet. Tested with python 2.7 & 3.6 and pymysql 0.9.3 & 0.9.2

**Comment by Feano** [comment]
Maybe an addition: if I run the same command in MySQL Workbench the correct result is returned. If I leave the sum completely pymysql returns:

**Comment by Feano** [comment]
{\"aID\": 6}, {\"aID\": 5}, {\"aID\": 3}, {\"aID\": 9}, {\"aID\": 9}]}

**Comment by methane** [comment]
This is issue tracker, and I'm not free tech support.
You should use other community like Stackoverflow.

**Comment by andrewortman** [comment]
Btw, I am hitting this problem as well. SUM aggregations seem to always be null.
