### ISSUE TITLE
Warning: (1292, "Truncated incorrect DOUBLE value: )

### ISSUE THREAD

**Issue by lingdavid** [PyMySQL/PyMySQL#775]
` sqid="'"+sqid+"'"`
` search_sql = "select * from {} where c_sq_id={}".format('question_answer', sqid)`

when I execute the code,it report some warning:

`D:\Anaconda3\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'aa9659ab04f4eb65cabiahdbbbeafbehhf46cea'")
  result = self._query(query)`

how can i fix it?

**Comment by methane** [comment]
Google error number and message.
