### ISSUE TITLE
Can you add "-A, --no-auto-rehash" client flag support?

### ISSUE THREAD

**Issue by phaibin** [PyMySQL/PyMySQL#776]
The "-A, --no-auto-rehash" flag will dramatically reduce the connection time for MySQL. But I can't find a corresponding value in constants/CLIENT.py. Can you add one more constant to support this attribute?

**Comment by methane** [comment]
Auto rehash is MySQL CLI's feature.  Since this project is just a library, not CLI application, it doesn't provide auto rehash from first.
