### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by gaborantal** [PyMySQL/PyMySQL#777]
Hey!

After installing requirements-dev, tests cannot be run on a freshly installed Ubuntu 18.10. As there are no other description on how to run tests/measure coverage data or so.

I am familiar with tox, pytest and so on. Are there any tutorial which I was unable to find? 

______________________________________________________________________________________________
ERROR:   py36: could not install deps [coverage pytest]; v = InvocationError('/home/abcdef/projects/PyMySQL/.tox/py36/bin/pip install coverage pytest (see /home/abcdef/projects/PyMySQL/.tox/py36/log/py36-1.log)', 1)

This is the error I got. However both deps are installed already.

**Comment by methane** [comment]
OK, this is tutorial:

1. Read the error message.
1. Think
1. Read the source.
1. Think.

> ERROR: py36: could not install deps [coverage pytest]; v = InvocationError('/home/abcdef/projects/PyMySQL/.tox/py36/bin/pip install coverage pytest (see /home/abcdef/projects/PyMySQL/.tox/py36/log/py36-1.log)', 1)
> 
> This is the error I got. However both deps are installed already.

Read the error message.  Have you checked `/home/abcdef/projects/PyMySQL/.tox/py36/log/py36-1.log`?
