### ISSUE TITLE
Cursor.lastrowid does not return ID on update

### ISSUE THREAD

**Issue by rmills** [PyMySQL/PyMySQL#778]
cursor.execute('UPDATE the_table SET checked = 1 WHERE checked = 0 LIMIT 1')
mysql.commit()
id = cursor.lastrowid
print(id) #returns 0 not last id
   
The table has two columns `id` (unique, auto increment) `checked` (int). The row does update as expected but the *cursor.lastrowid* is always 0 *cursor.rowcount* returns 1. Checking the database shows a single row affected.  The docs say "This read-only property returns the value generated for an AUTO_INCREMENT column by the previous INSERT or UPDATE statement". It works correctly on insert, but UPDATE always returns 0.

**Comment by methane** [comment]
In your case, there are no "value generated for an AUTO_INCREMENT".

**Comment by rmills** [comment]
In what case would an update generate a AUTO_INCREMENT?

**Comment by methane** [comment]
https://dev.mysql.com/doc/refman/5.6/en/mysql-insert-id.html
