### ISSUE TITLE
ExecuteMany -- No batch insert if fixed values are present

### ISSUE THREAD

**Issue by himanshu-pro** [PyMySQL/PyMySQL#781]
With table as below:
```
CREATE TABLE person(
  id int NOT NULL AUTO_INCREMENT,
  name varchar(255),
  father varchar(255)
);
```

Following code makes 3 roundtrips instead of batching the queries into 1 roundtrip.
```
query = "INSERT into person (name, father) VALUES (%s, 'Darth Vader')"
cursor.executemany(query, ['himanshu', 'methane', 'grooverdan'])
```

Reason: The regex used to check if the query can be batched does not account for fixed values. 'Darth Vader' in the above example.

**Comment by methane** [comment]
It's not a bug, it is intended limitation.
There are no plan to add real SQL parser.  I don't want to make regex complicated.

You need to build batched query manually.
