### ISSUE TITLE
Why it raise an internal error when I just sending an 'count-distinct' query?

### ISSUE THREAD

**Issue by zifeiYv** [PyMySQL/PyMySQL#788]
There is my code:
```
connection = pymysql.connect(...)
cr = connection.cursor()
cr.execute('select count(distinct my_field) from my_db.my_table')
```
and it raise the error:
> pymysql.err.InternalError:(9002, 'MySQLNormalMergeNode receive packets larger than config size')

There are about 110,000 rows in `my_table` and the `max_allowed_packet` is 16777216.
I am really confused about that and need some help.

**Comment by methane** [comment]
Ask it on MySQL community.  It's not client issue.
