### ISSUE TITLE
Minor SSL issue

### ISSUE THREAD

**Issue by guzman-raphael** [PyMySQL/PyMySQL#797]
This is related to a SSL behavior that I came across while testing. 
Will open a PR for your review if you agree.

To put it simply, if you instantiate the Connection class with this example:

`Connection(host='localhost', user='root', password='simple', port=3306, ssl={})`

Then it will connect successfully without SSL rather than using the `ssl` module to determine the appropriate paths.

**Comment by methane** [comment]
Why do you think it's a bug?

I didn't care about empty dict.  In other words, there are no defined behavior,
and any behavior is not a bug.

**Comment by guzman-raphael** [comment]
Hi @methane,

It was just my opinion. Updated my description above to remove the term bug.

My thought was, if an argument is passed with a value other than `None` for `ssl`, it implies that a user is trying to utilize `ssl`. However, currently if `ssl` receives a values of `{}`, then it will not use `ssl` as it will be skipped. Consider the following values for `ssl` if passed:

- `{'ca': 'path/to/ssl', ...}`
- `{'ssl': {}}`
- `{'nothing': {}}`
- `{'anything': {}}`

All the above will trigger `ssl` on the connection. 
My suggestion is simply if it makes sense to add:

- `{}`

**Comment by njgrisafi** [comment]
I agree with @guzman-raphael on the minor issue. I struggled to realize my dict I was passing in was not valid. However, `{'ssl': 'ANYTHING'}` is the only option that works for me, so I'm curious why that is.

I first found this dict format here: https://stackoverflow.com/questions/44207063/python-mysql-ssl-connections

**Comment by swchoi727** [comment]
hm, makes me think that the expression `not ssl` gets evaluated to determine whether or not to enable SSL, for which an empty dict evaluates to False.

**Comment by methane** [comment]
I don't think `ssl={}` implies use want to use TLS.
User need to pass any SSL option to enable TLS.

I think adding `ssl["mode"]` option is much better. (see [ssl_mode](https://dev.mysql.com/doc/refman/8.0/en/connection-options.html#option_general_ssl-mode) option.)
