### ISSUE TITLE
pymysql cannot execute sql with regex string and no error info,but mysql-client ok

### ISSUE THREAD

**Issue by Duanexiao** [PyMySQL/PyMySQL#801]
sql cmd: update db_name.table_name set `var1_regex` = '"ping.*."', `var2_regex` = '{"ip": "(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"}' where `id` = 674133820625866;

Looking for your reply, thank you

**Comment by methane** [comment]
I don't know.
