### ISSUE TITLE
Same Query - Always Same Result

### ISSUE THREAD

**Issue by Mushoz** [PyMySQL/PyMySQL#802]
When I execute a simple query such as "SELECT * FROM live", it always returns the exact same result. This happens, despite me adding new data to the live table in between the first and second query. Is this a bug or by design? I would like my query to always return an up-to-date result rather than reusing an old outdated result. Is there some way I can accomplish this?

**Comment by Mushoz** [comment]
Setting auto commit to True fixes it. No idea why autocommits are required for SELECT statements, because the other process that is writing data does properly commit the changes, but it does.

More details here in case other people stumble on this: https://stackoverflow.com/questions/20485332/pymysql-insert-into-not-working

**Comment by methane** [comment]
Google "repeatable read".
