### ISSUE TITLE
OperationalError: 1045 on login if password has non ascii characters

### ISSUE THREAD

**Issue by Zincr0** [PyMySQL/PyMySQL#804]
OperationalError: 1045 on login if password has non ascii characters

- Using python 3.5

Step to reproduce:

1.- Install PyMySQL[rsa] and cryptography.

2.- Create a mysql 8 instance

`docker run --name some-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=my-sécrét-pw -e MYSQL_DATABASE=dbase -d mysql:8.0`

3.- Wait like 10 seconds to the container fully starts.

4.- Try to connect

```python
import pymysql.cursors
connection = pymysql.connect(host='127.0.0.1',
                             user='root',
                             password='my-sécrét-pw',
                             db='dbase')
```
It will fail with 
`
OperationalError: (1045, "Access denied for user 'root'@'172.17.0.1' (using password: YES)")
`

However, if you use an ascii password like "my-secret-pw", it will work just fine.

**Comment by methane** [comment]
This is not a bug because MySQL protocol doesn't define which encoding is used to encode password.  So library can't guarantee login is succeeded when password is non-ASCII unicode.
You can manually encode your password and pass the binary password to PyMySQL.

**Comment by Zincr0** [comment]
I will leave here a working example for everyone, since there is no documentation about this "not a bug" thing that affects only this library:

```python
import pymysql.cursors
connection = pymysql.connect(host='127.0.0.1',
                             user='root',
                             password=bytes('my-sécrét-pw', 'utf-8') ,
                             db='dbase')
```
