### ISSUE TITLE
'charmap' codec can't encode character '\ufffd' in position 2249: character maps to <undefined>

### ISSUE THREAD

**Issue by acujl** [PyMySQL/PyMySQL#805]
I'm trying to fetchall a portuguese (Not brazilial portuguese) database, can't see the portuguese enconding on the code...

If you're sure it's PyMySQL's issue, report the complete steps to reproduce, from creating database.

I don't have time to investigate your issue from an incomplete code snippet.

**Comment by methane** [comment]
This is issue tracker, not a user forum.  I am maintainer, just a free tech support.
