### ISSUE TITLE
Multi Query aka execute script

### ISSUE THREAD

**Issue by t-abraham** [PyMySQL/PyMySQL#809]
Hi,

I am tring to use the multi query method to delete/add tables in the database using pymysql but it is generating error. Can you please help me out?

`
tahasanul@754abff4f690:/home/script$ python3 ./initialize_DB_Tables.py
/usr/lib/python3/dist-packages/pymysql/cursors.py:165: Warning: (1007, "Can't create database 'CLIENT01'; database exists")
  result = self._query(query)
Traceback (most recent call last):
  File "./initialize_DB_Tables.py", line 46, in <module>
    curs.execute_script(TableSchema)
AttributeError: 'Cursor' object has no attribute 'execute_script'
`

the py code is 

```
import pymysql

# MySQL  DB Name
conn =  pymysql.connect(
                        host="sandbox.skynode.link",    # your host, usually localhost
                        user="tahasanul",                       # your username
                        passwd="tahasanul")                     # your password
                        #db="CLIENT01")                         # name of the data base

# MySQL  DB Table Schema
TableSchema="""
drop table if exists CLIENT01_Location01_Temperature_Data;

create table CLIENT01_Location01_Temperature_Data(
  id INT AUTO_INCREMENT PRIMARY KEY,
  SensorID VARCHAR(255),
  Date_n_Time VARCHAR(255),
  Temperature VARCHAR(255)
);

drop table if exists CLIENT01_Location01_Humidity_Data;
create table CLIENT01_Location01_Humidity_Data(
  id INT AUTO_INCREMENT PRIMARY KEY,
  SensorID VARCHAR(255),
  Date_n_Time VARCHAR(255),
  Humidity VARCHAR(255)
);
"""

#Connect or Create DB File
#conn = pymysql.connect(DB_Name)
curs = conn.cursor()
curs.execute("CREATE DATABASE IF NOT EXISTS CLIENT01")
conn.select_db("CLIENT01")

#Create Tables
#curs = conn.cursor()
curs.execute_script(TableSchema)


#Close DB
curs.close()
conn.close()

```

**Comment by methane** [comment]
* There is no `execute_script` method.  Why do you use it?
* See https://github.com/PyMySQL/PyMySQL/blob/383c0438fe74464ad65b9850bd13f310de7a878e/CHANGELOG#L66-L69

**Comment by whmmm** [comment]
Thanks a lot .....
