### ISSUE TITLE
do pymsql support sql sentences like 'get_json_string' in pymysql? tried but failed

### ISSUE THREAD

**Issue by CeciliaPYY** [PyMySQL/PyMySQL#815]
Sorry to interrupt such a busy person, but still got a question to ask.

I test my sql sentences like following, it works out fine.
![E1C80A99-E8AC-405D-8C14-0AD439C42E2E](https://user-images.githubusercontent.com/30582437/65825784-b9723500-e2ad-11e9-9b8a-88b68780815c.JPG)

However when I test it in pymysql, it works like this.
![0D588AFE-714D-43CA-A688-7630654EC73D](https://user-images.githubusercontent.com/30582437/65825818-140b9100-e2ae-11e9-820c-46e07068dc7f.JPG)

After I delete 'get_json_string', it works fine as it was before.
Can you help me figure this out? Thanks!!!

**Comment by methane** [comment]
Issue tracker is not place to ask a question.
And PyMySQL is not MySQL.  You should ask such question in MySQL community.
