### ISSUE TITLE
AttributeError: module 're' has no attribute 'compile'

### ISSUE THREAD

**Issue by karezi** [PyMySQL/PyMySQL#819]
I cannot import pymysql.

- Operation System: MacOS Catalina v10.15
- Python Version: 3.7.3
- PyMySQL Version: 0.9.3

```
>>> import pymysql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/karezi/nlpre/lib/python3.7/site-packages/pymysql/__init__.py", line 28, in <module>
    from .converters import escape_dict, escape_sequence, escape_string
  File "/Users/karezi/nlpre/lib/python3.7/site-packages/pymysql/converters.py", line 164, in <module>
    DATETIME_RE = re.compile(r"(\d{1,4})-(\d{1,2})-(\d{1,2})[T ](\d{1,2}):(\d{1,2}):(\d{1,2})(?:.(\d{1,6}))?")
AttributeError: module 're' has no attribute 'compile'
```

**Comment by methane** [comment]
Do you have `re.py`?

Anyway, it is not an issue of this project.  It is your environment issue.

**Comment by karezi** [comment]
I just used PyCharm to install PyMySQL to virtual env and imported pymysql failed. I don't know why. If I use normal environment to install, I imported it successfully. Maybe there are some mistakes with my virtual environment. Thanks for your help.

**Comment by karezi** [comment]
I have found the mistake. I have a module named re...I changed the module name and imported pymysql successfully.
