### ISSUE TITLE
* You shouldn't use the issue tracker to ask about the error you saw.  **OSS maintainers are not free tech support!!**  People like you are killing OSS which maintained by volunteers.  Read [this article](https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde)

### ISSUE THREAD

**Issue by Behinder** [PyMySQL/PyMySQL#829]
Yes I should because errors persists:
Because I was attacked ad personam my reply is here:
Why not? I was desperate to try find the cause of suddenly crashing the tool I must rely on and you attack me personally which is kinda pathetic.
OSS Maintainers should better learn to read with understanding! And yes they are tech support, and yes because the software is free tech support also should be free.If you release software you take responsibility. Such idiots like you should never be maintainers to anything.

I report error I saw because this important to me and other people that relies on scripts given by Apple.
And before I reported I spent 6 days lookin deeply in the code and the problem.

1. Installing mysqlclient is not solution to the problem! ERROR PERSIST!
MySQLdb still works because it connects properly user to database.
2.I must install MySQL-python because Apple in their tool requires to do so. Their tool is not dead therefore any project that is forced to use it shouldn't be  considered "dead"
3. It is not you what decide which tool I should use or not. Maybe I should say "You shouln't use python, switch to Ruby"?

If OSS not provide correct solution then better be dead. 
If you are not helping solve the errors then better say nothing.
If you do not have time to deeply dig into problem instead of saying not-working solutions then you should change your job.

_Originally posted by @methane in https://github.com/PyMySQL/PyMySQL/issues/676#issuecomment-558859095_

**Comment by methane** [comment]
Have you read the issue template?
Have you read [the article](https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde)?

**Comment by methane** [comment]
#676 was trouble while installing **MySQL-python**.
But **this project is not MySQL-python**.  Do you understand?

Additionally, solving user trouble is not part of maintaining OSS.

Be careful when writing a comment or opening the issues.
Although you didn't mean it, you are sending spam to OSS maintainer.
