### ISSUE TITLE
Select query returns some values as None when present in the DB

### ISSUE THREAD

**Issue by Med-All** [PyMySQL/PyMySQL#831]
I have a query which looks like:

```
    cursor = db.cursor()
    sql = "SELECT * FROM users WHERE userID = '%s'" % (userID)
    cursor.execute(sql)
    rowCount = cursor.rowcount
    result = cursor.fetchone()
    
    print(result)
```

after few good queries response will return result which looks like:

```
    (1584, None, None, '1316911449', 'Erik', 'C', 'Tester', '', 'V', '0', '', datetime.datetime(2019, 12, 4, 2, 13, 14), datetime.datetime(2019, 12, 4, 2, 13, 13), datetime.datetime(2019, 12, 4, 2, 13, 14))
```

when the DB contains values for second and third column as hashes

```
    1584	0dcfa75b5ed837cb9446891022eb6465	0dcfa75b5ed837cb9446891022eb6465	1316911449	Erik	C	Tester		V	0		2019-12-04 14:03:40	2019-12-04 02:13:13	2019-12-04 14:03:40
```

Any clue why those values are getting dropped on a select query after few good rounds?

PS.
It looks like it always is getting dropped after the row #1585 from the DB

**Comment by methane** [comment]
Schema?
Server?
Connect opens?

**Comment by Med-All** [comment]
Schema:

CREATE TABLE `users` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `userUID` varchar(80) DEFAULT NULL,
  `userHash` varchar(32) DEFAULT NULL,
  `userID` varchar(20) DEFAULT NULL,
  `userFName` varchar(100) DEFAULT NULL,
  `userMName` varchar(60) DEFAULT NULL,
  `userLName` varchar(100) DEFAULT NULL,
  `userSuffix` varchar(20) DEFAULT NULL,
  `status` varchar(2) NOT NULL DEFAULT 'X' COMMENT 'V = Valid, N = Not Valid, X = Never Checked',
  `failureCode` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `failureMessage` varchar(80) DEFAULT NULL,
  `lastLoginTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `userID_UNIQUE` (`userID`),
  UNIQUE KEY `userUID_UNIQUE` (`userUID`),
  UNIQUE KEY `userHash_UNIQUE` (`userHash`),
  KEY `userLName_INDEX` (`userLName`),
  KEY `userFName_INDEX` (`userFName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

Server:
- MySQL 8.0.15

Connect opens:
- at the beginning of the script as

```
    db = pymysql.connect(dbHost, port=dbPort, db=db, user=dbUser, passwd=dbPassword, charset='utf8mb4')
    warnings.filterwarnings('ignore', category=pymysql.Warning)     #ignore (do not raise) DB warnings in the logs
```

**Comment by methane** [comment]
Can you create a reproducible example, or provide packet capture?

**Comment by Med-All** [comment]
I can't as I'm getting that problem on large amount of data (prod) but wasn't present during the development process (small test data).

As I have stated before - data got dropped when it will pas row #1585 in the table.

**Comment by methane** [comment]
If it is not reproducible in small environment, it is not an isssue of PyMySQL.
PyMySQL are not affected by your data size.

* Some other process on your prod system really update the column to NULL, or
* Bug of MySQL.

Try the latest MySQL.  8.0.15 is not the latest.

**Comment by Med-All** [comment]
OK, I will update MySQL.
