### ISSUE TITLE
symbol '%' are explained internally in cursors.py causing python grammar error: "ValueError: unsupported format"

### ISSUE THREAD

**Issue by kbxu** [PyMySQL/PyMySQL#834]
the bug happens when I'm using LIKE in mysql query
(PyMySQL ver. 0.9.3, Python ver 3.6)

for example:
db = create_engine('mysql+pymysql://xx:xx@localhost/dbname')
pd.read_sql("SELECT * FROM tablename WHERE var0='%s' AND var1 LIKE 'abc%%';" % somestring, db)

the query then becomes
"SELECT * FROM tablename WHERE var0='somestring' AND var1 LIKE 'abc%';"
and will be sent to pd.read_sql, which is also ok for sql

**however at line 147 of `pymysql/cursors.py`**
the query with **'abc%;'** is explained again by
**query % self._escape_args(args, conn)**

and it will cause a python grammar error
**ValueError: unsupported format character**
because of **'%;' % somestr** 

so I have to use four % so that there's one % in the final query which won't cause python grammar error

**should there be somewhere that the % is replaced by %% before line 147 of cursors.py?**

**Comment by methane** [comment]
No.
