### ISSUE TITLE
help

### ISSUE THREAD

**Issue by DeveYassineBaghdadi** [PyMySQL/PyMySQL#836]
I built an desktop application by python ("pyqt5")
so i wanna use mySQL db 
for example:

there are 3 computer (pc1, pc2, pc3)
i want to put the mysql db on pc1 and work on it from pc2 and pc3 at the same time , by LAN (local area network)
i actually dont know how do this

**Comment by methane** [comment]
The is tracker is not used forum.
OSS maintainers are not free tech support.
Please don't use is tracker to ask help.
