### ISSUE TITLE
feature request: establish connection string via DSN?

### ISSUE THREAD

**Issue by bayesfactor** [PyMySQL/PyMySQL#839]
It would be very convenient to allow connection strings via DSN. For example, MS-SQL + pyodbc allows connections via DSN.

https://docs.sqlalchemy.org/en/13/core/engines.html#microsoft-sql-server

desired behavior is that the following snippet establishes a connection to the database specified by "mydsnname"
```
eng = create_engine("mysql+pymysql://@mydsnname")
conn = eng.connect()
```

**Comment by methane** [comment]
ODBC has DSN but MySQL doesn't have DSN.  I don't create original DSN.

You can use SQLAlchemy DSN anyway.  If you don't want to use SQLAlchemy too, you can use json (e.g.  `pymysql.connect(**json.decode(json_encoded_connection_string))`) instead.
