### ISSUE TITLE
Syntax error after upgrading from 0.7.11 to 0.9.3

### ISSUE THREAD

**Issue by yrdeboer** [PyMySQL/PyMySQL#841]
Hi,

Great software, we have been using it for a more than 3 years already!
Today we upgraded from 0.7.11 to 0.9.3 and immediately we are getting syntax errors.

Turns out that we no longer can concatenate multiple SQL queries and separate them using a semi-colon ...

However, this is officially supported (https://dev.mysql.com/doc/refman/8.0/en/c-api-multiple-queries.html):

"MySQL also supports the execution of a string containing multiple statements separated by semicolon (;) characters."

Therefore, we think that raising a SYNTAX error would be a bug, because there is nothing wrong with the syntax per-se (althoug the error comes from the DB it self, it is not issued when we only change the PyMySQL version).

So we are wondering, how should we proceed? Is it performant to loop over the queries and issue them on the same cursor and after the cursor is closed issue the commit?

We're worried about a performance hit obviously :)

---------------------------

This code below runs fine when the only thing we have changed is the version of pymysql from 0.9.3 to 0.7.11. Running with 0.9.3 gives the output below (ending in a SYNTAX error from the DB itself):

> Going to execute: DELETE FROM orders_current_buy WHERE id IN (96902760,97048222);
Done.

Going to execute: UPDATE orders_current_buy SET   uuid="8a368b8d-e6f2-43ff-bce9-05cc83f2d2f8",  price=413.0,  quantity=0.01666391,  quantity_surplus=0.0,  commission_paid=0.01720548,  status="In progress",  ts_\
opened_utc="2018-08-02T10:16:03.634000",ts_closed_utc="2018-08-02T10:17:33.170000",  linked_sell_order_uuid="7e534bfc-fd96-45c4-bcfd-bcb7aa023ee7" WHERE   id=9605652;
Done.

Going to execute: DELETE FROM orders_current_buy WHERE id IN (96902760,97048222);UPDATE orders_current_buy SET   uuid="8a368b8d-e6f2-43ff-bce9-05cc83f2d2f8",  price=413.0,  quantity=0.01666391,  quantity_surplu\
s=0.0,  commission_paid=0.01720548,  status="In progress",  ts_opened_utc="2018-08-02T10:16:03.634000",ts_closed_utc="2018-08-02T10:17:33.170000",  linked_sell_order_uuid="7e534bfc-fd96-45c4-bcfd-bcb7aa023ee7" \
WHERE   id=9605652;
Error in DB IO: DB=b'gsmg' DB user=b'trade_engine' exception=<class 'pymysql.err.ProgrammingError'> exception=(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server\
 version for the right syntax to use near \'UPDATE orders_current_buy SET   uuid="8a368b8d-e6f2-43ff-bce9-05cc83f2d2f8",  pr\' at line 1'). SQL query=DELETE FROM orders_current_buy WHERE id IN (96902760,9704822\
2);UPDATE orders_current_buy SET   uuid="8a368b8d-e6f2-43ff-bce9-05cc83f2d2f8",  price=413.0,  quantity=0.01666391,  quantity_surplus=0.0,  commission_paid=0.01720548,  status="In progress",  ts_opened_utc="201\
8-08-02T10:16:03.634000",ts_closed_utc="2018-08-02T10:17:33.170000",  linked_sell_order_uuid="7e534bfc-fd96-45c4-bcfd-bcb7aa023ee7" WHERE   id=9605652;

**Comment by methane** [comment]
When you updated the library version and get trouble, you must check changelog at least backward incompatible changes.

https://github.com/PyMySQL/PyMySQL/blob/9f1b8569032ec7eaff36fe9ef5e40f82c47260b2/CHANGELOG#L66-L69

**Comment by yrdeboer** [comment]
Thanks!
