### ISSUE TITLE
Add support for SSL/TLS verify_mode

### ISSUE THREAD

**Issue by moomindani** [PyMySQL/PyMySQL#842]
Currently PyMySQL determines SSL/TLS verify_mode automatically here. https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L337

Related issues: (it is not a PyMySQL bug.) https://github.com/PyMySQL/PyMySQL/issues/430

My suggestion is to add configuration so that users can specify any of the verify_mode (ssl.CERT_NONE, ssl.CERT_OPTIONAL, ssl.CERT_REQUIRED) defined in ssl.py.
https://docs.python.org/3/library/ssl.html

It would be good to support `ssl-mode` explained here.
https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#option_general_ssl-mode

**Comment by dgm** [comment]
Also, in https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L239-L245   if it is reading from a config file, it should read ssl-mode=DISABLED     

If I read this right,  if reading from a file is used, it creates a ssl dict object, and automatically sets self.ssl = True  without regard to ssl-mode being disabled.

**Comment by kwatsen** [comment]
+1 to the OP.

Especially hoping for VERIFY_CA and VERIFY_IDENTITY support.
