### ISSUE TITLE
Packet sequence number wrong - got 102 expected 3

### ISSUE THREAD

**Issue by hirocsingh** [PyMySQL/PyMySQL#845]
This issue is back in PYMYSQL, even though after using `pymysql.connect()` for each thread I am getting this error for two threads in my API call

**Comment by methane** [comment]
Please provide preproducible example.  Without it, I assume it's issue of your application or environment.

**Comment by hirocsingh** [comment]
1. Have a bunch or controller. 
<img width="197" alt="1" src="https://user-images.githubusercontent.com/21228750/76001895-d1408b80-5ed3-11ea-9b41-93bd88a13d46.png">

2. Give each controller their own connection i.e `pymysql.connect(<connection string>)`
3. In my case I am using the API calls from my Angular app. 

You will get the mentioned error in some of the APIs where the return data is huge. 

The same API call which throws this error returns the results in Postman but it fails from UI.
<img width="594" alt="2" src="https://user-images.githubusercontent.com/21228750/76001955-e61d1f00-5ed3-11ea-943e-158b00be713e.png">

UI Call:
<img width="336" alt="3" src="https://user-images.githubusercontent.com/21228750/76001969-ec130000-5ed3-11ea-8dfd-144fb68db1bf.png">


Error:
<img width="903" alt="4" src="https://user-images.githubusercontent.com/21228750/76001986-f208e100-5ed3-11ea-91d3-13e791aadd98.png">

**Comment by methane** [comment]
It is not "reproducible example".  I can not reproduce your issue.
And It doesn't prove the issue is not your bug.

Please provide a "complete step to reproduce".

**Comment by hirocsingh** [comment]
Issue cannot be resolved.
