### ISSUE TITLE
Feature request unescape string

### ISSUE THREAD

**Issue by flipchan** [PyMySQL/PyMySQL#848]
Would be nice to get a function that unescaped the select value that has been inserted with escape

**Comment by flipchan** [comment]
https://github.com/PyMySQL/PyMySQL/blob/c3c87a7e773dbb09def0b081c70dd55fe83b9633/pymysql/converters.py

unescape this:
_escape_table = [unichr(x) for x in range(128)]
_escape_table[0] = u'\\0'
_escape_table[ord('\\')] = u'\\\\'
_escape_table[ord('\n')] = u'\\n'
_escape_table[ord('\r')] = u'\\r'
_escape_table[ord('\032')] = u'\\Z'
_escape_table[ord('"')] = u'\\"'
_escape_table[ord("'")] = u"\\'"

def _escape_unicode(value, mapping=None):
    """escapes *value* without adding quote.
    Value should be unicode
    """
    return value.translate(_escape_table)

**Comment by flipchan** [comment]
```python
def un_escape(inputen):

```

**Comment by methane** [comment]
Why do you think it is worth not only for you but many PyMySQL users?

**Comment by flipchan** [comment]
because everyone has this problem? its a universal problem

**Comment by methane** [comment]
> because everyone has this problem? its a universal problem

Universal?  I never want this.  When people want this?

**Comment by flipchan** [comment]
because people who insert escaped data want to select unescaped data

**Comment by methane** [comment]
> because people who insert escaped data want to select unescaped data

1. People escape strings and insert it
2. MySQL unescape the string and insert it
3. People select unescaped strings.

No need to insert escaped data.

**Comment by flipchan** [comment]
mariadb does not unescape it

**Comment by flipchan** [comment]
@methane ^
