### ISSUE TITLE
How can I ignore UnicodeDecodeError when I use cursor.execute(sql);cursor.fetchall();

### ISSUE THREAD

**Issue by zhaoziming** [PyMySQL/PyMySQL#849]
**Describe the bug**

**To Reproduce**
Complete steps to reproduce the behavior:

Schema:

```
CREATE DATABASE ...
CREATE TABLE ...
```

Code:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 740: illegal multibyte sequence
----------------------------
When I get the result set, there are a small number of string encoding problems that cause the program to report errors. The solution is simple,
data = data.decode(encoding) =>data = data.decode(encoding,'ignore')
 but it's not a good idea to modify your code.

How can I set errorss='ignore' to pymysql 

**Expected behavior**

**Environment**
 - OS: [e.g. Windows, Linux]
 - Server and version: [e.g. MySQL 8.0.19, MariaDB]
 - PyMySQL version: the newest version

**Additional context**

**Comment by methane** [comment]
**[You must not ask a question on issue tracker](https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde#.hdf6lpk11)**
