### ISSUE TITLE
error  client_flag=pymysql.constants.CLIENT.MULTI_STATEMENTS

### ISSUE THREAD

**Issue by fedez** [PyMySQL/PyMySQL#850]
i have a problem with this when i try in: 
Name: Jhon',30); delete from persons; --
Years:30

pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '--', 20)' at line 1")

import pymysql
conn = pymysql.connect(
 host="localhost",
 user="user",
 passwd="user",
 db="l",
 client_flag=pymysql.constants.CLIENT.MULTI_STATEMENTS
)

cursor = conn.cursor()
try:
 cursor.execute("CREATE TABLE persons (nameVARCHAR(50), yearINT)")
except pymysql.err.InternalError:
 pass
name= input("Name: ")
years = int(input("Years: "))
cursor.execute(f"INSERT INTO persons VALUES ('{name}', {year})")
conn.commit()
print("succesful!")
conn.close()

i don't know what im doing wrong

**Comment by methane** [comment]
Read the error message.  You can not use `--` for comments.
