### ISSUE TITLE
Matching Charsets as Incorrect String 

### ISSUE THREAD

**Issue by alvare16** [PyMySQL/PyMySQL#852]
**Describe the bug**
MySQL error with the code 1366 mapped as incorrect string value.

**To Reproduce**
Set connection with charset: utf8mb4
Join two tables with different charsets, have at least one column containing letters with accents

When using to_sql:
(pymysql.err.InternalError) (1366, "Incorrect string value: '\\xC5\\x81asis...' for column 'client_last_name' at row 726")

Schema:

```
CREATE TABLE :
[SQL: INSERT INTO email_stats (`index`, email_id, client_id, email_address, date_sent, date_read, is_read, is_failed, retry_count, source, source_id, open_count, tracking_id, category_id, date_added, email_name, subject, template, email_utm, client_first_name, client_last_name, company, title, client_email, state, country, company_description, company_type, company_markets, category_alias, category_description) VALUES (%(index)s, %(email_id)s, %(client_id)s, %(email_address)s, %(date_sent)s, %(date_read)s, %(is_read)s, %(is_failed)s, %(retry_count)s, %(source)s, %(source_id)s, %(open_count)s, %(tracking_id)s, %(category_id)s, %(date_added)s, %(email_name)s, %(subject)s, %(template)s, %(email_utm)s, %(client_first_name)s, %(client_last_name)s, %(company)s, %(title)s, %(client_email)s, %(state)s, %(country)s, %(company_description)s, %(company_type)s, %(company_markets)s, 
```

Code:
```py
knowde = pymysql.connect(host='', 
                          user='', 
                          password='', 
                          db='',
                          charset="utf8mb4")

#engine connection
con = engine.connect()

#Importing full email clicks table into tableau schema in mysql-- no issues
full_clicks_email.to_sql("email_clicks", con, if_exists="replace")
```
**Expected behavior**
Since the tables from MySQL are either latin1 or utf8, I set char as utf8mb4. I expect to create table in SQL with no decoding problem.

**Environment**
 - OS: [Mac]
 - Server and version: [ MySQL 5.7.29]
 - PyMySQL version: 0.9.3

**Additional context**
The problem only occurs in the client_last_name column. Had problems only with accented characters.

**Comment by methane** [comment]
> MySQL error with the code 1366 mapped as incorrect string value.

It is mapped in MySQL, not in PyMySQL.

> When using to_sql:

to_sql is not PyMySQL method.

> Schema:
>
>    CREATE TABLE :
>    [SQL: INSERT INTO email_stats

It is not schema.

> Code:

It is not "reproducible" example.
Please write a reproducible example without using only PyMySQL.
