### ISSUE TITLE
Help executing SP in batch

### ISSUE THREAD

**Issue by flakobatako** [PyMySQL/PyMySQL#855]
Hi. 

I don't know if this is the most efficient way to call an SP in batch.

My SP is just an SP with no out parameters wich does some validations and then inserts in a table a string, and lastly it returns the number or rows inserted (wich always be 1) or (-1) if it didn't insert anythig. It's something like this (It's an example, because the original if big and do some weird validations):

```sql
CREATE PROCEDURE `OSF`.`test_insert`(IN p_request TEXT, IN p_queue_name VARCHAR(45))
BEGIN
  SET @var_AffectedRows = -1;
  SET @requestvalue = p_request;  
  SET @queuenamevalue = p_queue_name;

  // Do validations

  // IF validations are true
  INSERT INTO queue_table VALUES (@requestvalue, @queuenamevalue);
  // END IF

  SELECT ROW_COUNT() INTO @var_AffectedRows;
  SELECT @var_AffectedRows AS conteo;
END
```

When i call the SP it returns a 1 (rows inserted), or -1 (no rows inserted).

It calls the batch sql statement in less than a second, but the recovery of the results is slower.

This is what i could come up:

```python
def getPyMySQLConn():
    return pymysql.connect(host=mysql_url,
                           port=int(mysql_port),
                           user=mysql_user,
                           password=mysql_password,
                           db=mysql_db,
                           client_flag=CLIENT.MULTI_STATEMENTS,
                           autocommit=True,
                           cursorclass=pymysql.cursors.DictCursor
                           )

def insertBatchPyMysqlText():
    conn = getPyMySQLConn()

    try:
        resultlist = []
        sql = ''
        # Here i create the sql batch statement
        for i in range(1000):
            sql = sql + \
                "CALL OSF.test_insert('test', 'orderSync');"
        nextSet = True
        
        # Create the cursor
        with getPyMySQLConn().cursor() as cursor:
            # Execute the batch statement
            cursor.execute(sql)
            # Fetch the results (this is weird, the first iteration it yields a (), then the 
            # result of the sp, and it repeats until all the sets have been traversed)
            res = cursor.fetchall()
            # infinite loop to traverse every nextSet available until there's just 
            # empty () returned by fetchall()
            while nextSet:
                #save the result before calling nextset()
                old_res = res
                cursor.nextset()
                # Fetch the results
                res = cursor.fetchall()
                # if res is not an empty () then append it to the results
                if res is not ():
                    resultlist.append(res[0].get('count_insert'))
                # If at any given time there's 2 empty () consecutively returned, then 
                # change the flag and finally exit the loop or it will be stuck forever.
                if old_res is () and res is ():
                    nextSet = False
        # Close connection
        conn.close()
    except Exception as e:
        print(e)
```

**Explanation:** 
-First i create a string with the 1000 call stored procedure statements.
-Create a cursor and then execute the huge string (this takes less than 1 second i can even check the DB and there's the 1k new rows already inserted).
-Now to check the result of every statement call cursor.nextset() and then res = cursor.fetchall() in an infinite loop based in a flag do the same until theres no more results yielded, but pure ()'s (This part takes 10 seconds with 1000 records which is very slow for 1k results).
Done

So far this approach works (altough it's ugly AF) This is what i could come up with. I don't know if there's a better way to do the same thing.

-Other things i've tried: using executemany, a manual loop (df.itertuples), pandas calling the sp in a loop, sqlalchemy manual loop, and sqlalchemy executemany, but they are super slow. 

It's wrong what i'm doing? Is there a better way?

Thank you in advance.

**Comment by methane** [comment]
Maintainer is not free tech support.
Please use other sites like stackoverflow.
