### ISSUE TITLE
escape_string() escape ' / " maybe have some bugs

### ISSUE THREAD

**Issue by stanpao** [PyMySQL/PyMySQL#859]
Description:

By the purpose of escape_string(), automatically expand chars having ambious meaning .
But, ' or '' (\\' or \\") is not with the ambious meaning. Maybe the below code need to be commented out:
venv/Lib/site-packages/pymysql/converters.py
line 65 - 66
# _escape_table[ord('"')] = u'\\"'
# _escape_table[ord("'")] = u"\\'"

----------------------------------------------------------------------------------------------------
reproduce:
a = 'update x set y = "z";'

EXPECTED:
pymysql.escape_string(a) -> 'update x set  y = "z";'

ACTUALLY:
pymysql.escape_string(a) -> 'update x set y = \\"z\\";'

**Comment by methane** [comment]
You are totally misunderstanding it.  It is low level function and only experts should use it.

**Comment by stanpao** [comment]
Inada san：
Could you tell me more information about the purpose eascape_string()?
The brief is ok.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by methane** [comment]
See https://stackoverflow.com/questions/5741187/sql-injection-that-gets-around-mysql-real-escape-string

It is PHP, but the essence is same.

**Comment by methane** [comment]
You expected "automatically expand chars having ambious meaning ."
It is very very very dangerous.

I believe you should learn how to protect your application from SQL injection.  After learning it, you must know why there must not be "automatically expand chars having ambious meaning ."

**Comment by stanpao** [comment]
Thanks Inada San. Actually I’m not know much about sql injection.
Thanks you for your explanation.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
