### ISSUE TITLE
query same sql , change  table ,result is same

### ISSUE THREAD

**Issue by lyj0309** [PyMySQL/PyMySQL#861]
+ this is code 
```
db = pymysql.connect("localhost", "root", "xxxxxx", "xxxxx")
cursor = db.cursor()

def main():
    while True:
        sql = "SELECT * FROM work_ids WHERE is_in = -1"
        try:
            num = cursor.execute(sql)
            workIds = cursor.fetchall()
        except OSError as err:
            print(err)
            return
        print(num)
        time.sleep(3)
        continue
```
i change database when it run,the result is same

than i put ```cursor = db.cursor()``` behind ```while True:``` 

the result is same 

i put ```db = pymysql.connect("localhost", "root", "xxxxxx", "xxxxx")
cursor = db.cursor()``` behind  ``` while True:``` 

it's nornal

**Comment by methane** [comment]
>         print(num)


Shouldn't you print `workIds`?

Anyway, please don't use the issue tracker for asking question.
OSS maintainers are not free tech support.  You should ask newbie questions on other Python communities.
