### ISSUE TITLE
Incorrect behavior with mixing "%" symbol and prepared statemtnts

### ISSUE THREAD

**Issue by david-shiko** [PyMySQL/PyMySQL#863]
Incorrect behavior with mixing multiple "%" symbols and sql statement itself

**To Reproduce**
Just try the folowing queries:
case 1) cursor.execute('SELECT %s % %s', (5, 10))
case 2) cursor.execute('SELECT %s % 10', (5))

Schema:
```
No DDL need for bug reproduction
```

Code:

```py
import pymysql
con = pymysql.connect(...)
cursor = con.cursor()
cursor.execute('SELECT %s % %s', (5, 10))
photo = cursor.fetchone()
```

**Expected behavior**
5 % 10 == 5
case 1) I got: unsupported format character '%' (0x25) at index 12
case 2) ValueError: incomplete format

 - OS: Windows
 - Server and version: MySQL 8.0.19
 - PyMySQL version: 0.9.3

**Comment by methane** [comment]
See https://docs.python.org/3/library/stdtypes.html#printf-style-bytes-formatting

You need to use `%%` instead.

**Comment by david-shiko** [comment]
Thanks. I know about that solution, I just want to say, that it's emplicit behavior. Maybe better to refuse from it ?
