### ISSUE TITLE
Document differences between Oracle implementation and PyMySQL

### ISSUE THREAD

**Issue by montao** [PyMySQL/PyMySQL#864]
What are the features supported by mysql-connector-python that are not supported by PyMySQL?

I found that it is different ways to get a dict from a cursor and different ways to run multiple SQL statements, but the way I found it was by running my code. 

The background is that we have been using the mysql-connector-python but when trying to package it with Debian there occured build failure. Changing to PyMySQL then everything worked at once. Therefore I am investigating the possibilities of changing from the Oracle connector to PyMySQL for a large administrative task.

**Comment by methane** [comment]
I don't know much about mysql-connector-python and I can not maintain the diff.
Please write it in your blog.
