### ISSUE TITLE
"coverage unknown" readme badge

### ISSUE THREAD

**Issue by matkoniecz** [PyMySQL/PyMySQL#867]
**Describe the bug**
Readme badge shows "coverage unknown" instead of displaying coverage status

**To Reproduce**
Open https://github.com/PyMySQL/PyMySQL scroll to badges in header

**Expected behavior**
Badge is not present or shown some numeric value, probably in percents

**Environment**
 - OS: Linux, Lubuntu 20
 - Server and version: none
 - PyMySQL version: latest master 

**Additional context**
Badge image links to 404 page - https://coveralls.io/github/PyMySQL/PyMySQL?branch=master

**Comment by methane** [comment]
Thank you. It is fixed now.
