### ISSUE TITLE
Load data local infile works on windows but not on ubuntu

### ISSUE THREAD

**Issue by JizzFactoryEmployee** [PyMySQL/PyMySQL#868]
I wrote some code that pushes a CSV to a database using load data local infile, it worked on windows perfectly but for some reason it doesnt work on ubuntu. On ubuntu i can get information about the database but it seems like i cant add any data through load data local infile which is the main method that i intend to use.

I get no error messages as well. plz halp

**Comment by methane** [comment]
OSS maintainer is not free tech support. Please ask on MySQL or Python community.

**Comment by yx91490** [comment]
https://github.com/PyMySQL/PyMySQL/blob/6ccbecc1a0dfd04065b081950d2d35b1dac0aaa8/pymysql/connections.py#L138
