### ISSUE TITLE
threadsafety is 1？that is not a good ideal for pool conenct.

### ISSUE THREAD

**Issue by SchopenhauerZhang** [PyMySQL/PyMySQL#869]
you know threadsafety is 1, is not a good ideal . it can creat lock or long time to wait when mangy threads connect database.So pymysql is not support for pool connect?
```
threadsafety = 1
apilevel = "2.0"
paramstyle = "pyformat"


```
pymysql/__init__.py

**Comment by methane** [comment]
threadsafety=1 means you can not use single connection from multiple threads.
You can have one connection per thread anyway.
You can use connection pool supporting multi threading like SQLAlchemy's engine.
