### ISSUE TITLE
"You have an error in your SQL syntax" when running multiple queries

### ISSUE THREAD

**Issue by naclcaleb** [PyMySQL/PyMySQL#870]
**Describe the bug**
When running a SQL string with multiple queries (i.e. `SELECT * FROM table; DELETE FROM table;`), pymysql throws a `ProgrammingError` saying "You have an error in your SQL syntax".

**To Reproduce**
```
import pymysql
conn = pymysql.connect(host='host', user='user', password='password', database='database')
cursor = conn.cursor()
cursor.execute("""
SELECT * FROM table; 
DELETE FROM table;
""")
```

Schema:

```
CREATE DATABASE database;
CREATE TABLE table(id INTEGER PRIMARY KEY AUTO_INCREMENT);
```

**Expected behavior**
Both queries would be executed; the value retrieved from the cursor should be the one from the last statement to be executed.

**Environment**
 - OS: macOS Catalina
 - Server and version: MySQL 5.6
 - PyMySQL version: 0.9.3

**Comment by methane** [comment]
Semicolon in the query is usually used for SQL injection.
You need to enable it manually.

https://github.com/PyMySQL/PyMySQL/blob/d895719372d00378b17a42d60109d10b0d1a10ed/CHANGELOG#L66-L69

**Comment by naclcaleb** [comment]
Oh...good point. Now I need to think about how I'm going to do this...thanks for reminding me!
