### ISSUE TITLE
support --no-auto-rehash

### ISSUE THREAD

**Issue by doyou89** [PyMySQL/PyMySQL#871]
**Describe the bug**
When connecting to mysql, it takes some times to read tables because auto-rehash option is enabled by default.
If the db to be connected would big one, this may takes long time.

**Expected behavior**
auto-rehash should be disabled by default because this library may not use auto completion.

**Comment by methane** [comment]
This library doesn't have auto-rehash feature, because this library is not CLI and never support auto completion.
