### ISSUE TITLE
connection.encoding not set since version 0.10.0

### ISSUE THREAD

**Issue by bwinkel** [PyMySQL/PyMySQL#877]
Hi,

thanks a lot for maintaining this package!

I came across an issue with using a different charset (e.g., latin1) to store binary blobs of numbers in a data base. This used to work until v0.9.3, by setting the `charset` argument when creating the connection. However, with v0.10.0 I get an error:

```python
----> 1 cursor.execute(insertstring)

/opt/miniconda/envs/effbg_py3.7qt5/lib/python3.7/site-packages/pymysql/cursors.py in execute(self, query, args)
    161         query = self.mogrify(query, args)
    162 
--> 163         result = self._query(query)
    164         self._executed = query
    165         return result

/opt/miniconda/envs/effbg_py3.7qt5/lib/python3.7/site-packages/pymysql/cursors.py in _query(self, q)
    319         self._last_executed = q
    320         self._clear_result()
--> 321         conn.query(q)
    322         self._do_get_result()
    323         return self.rowcount

/opt/miniconda/envs/effbg_py3.7qt5/lib/python3.7/site-packages/pymysql/connections.py in query(self, sql, unbuffered)
    501                 sql = sql.encode(self.encoding)
    502             else:
--> 503                 sql = sql.encode(self.encoding, 'surrogateescape')
    504         self._execute_command(COMMAND.COM_QUERY, sql)
    505         self._affected_rows = self._read_query_result(unbuffered=unbuffered)

/opt/miniconda/envs/effbg_py3.7qt5/lib/python3.7/encodings/cp1252.py in encode(self, input, errors)
     10 
     11     def encode(self,input,errors='strict'):
---> 12         return codecs.charmap_encode(input,errors,encoding_table)
     13 
     14     def decode(self,input,errors='strict'):

UnicodeEncodeError: 'charmap' codec can't encode characters in position 120-121: character maps to <undefined>
```

I could trace this down to the point where the `encoding` attribute of the connection is having the value of `cp1252`. In previous pymysql versions, the `encoding` was the same as `charset`. In fact, if I manually override the encoding, it works again (as before).

I'm not sure, if `encoding` is meant to be an internal variable, only. There seems to be no argument in the create-connection function to set it.

**Comment by methane** [comment]
"not set" is wrong. It is set as `cp1252`. And it is intensional.

`charset` is MySQL term. And `latin1` charset in MySQL meant cp1252 actually. Old PyMySQL used latin1 Python encoding for latin1 MySQL charset but it was a bug. The bug is fixed for now.

But I strongly recommend you to use `charset="utf8mb4"`. I only test UTF-8.

**Comment by methane** [comment]
See PyMySQL/mysqlclient-python#390 for backgraound of this change.
