### ISSUE TITLE
Queries containing the '%' character lead to exceptions

### ISSUE THREAD

**Issue by Stannislav** [PyMySQL/PyMySQL#880]
**Describe the bug**
Some SQL queries may contain the '%' character. Whenever this is the case an exception is raised.

The exception occurs in line 147 in `pymysql/cursors.py`, which reads
```python
query = query % self._escape_args(args, conn)
```
The presence of the '%' character in 'query' triggers a substitution. Whenever `args = {}` this results in the statement `query % {}`, which can lead to various errors depending on which characters  follow the '%' character in `query`.

**To Reproduce**
Complete steps to reproduce the behavior:
- Set up a MySQL database
- Create a table named `my_table` with a text column named `text_column`.
- Run this code

```python
import pandas as pd
import sqlalchemy

db_engine = sqlalchemy.create_engine(f"mysql+pymysql://<database URI>")
query = "SELECT * FROM my_table WHERE text_column LIKE '%giraffe%'"
result = pd.read_sql(query, db_engine)
```
This results in
```shell
TypeError: must be real number, not dict
```

This is due to "%g" in the query, effectively leading to `"%g" % {}`.

**Expected behavior**
The query should go through without errors.

**Environment**
 - OS: MacOS
 - Server and version: MySQL
 - PyMySQL version: 0.9.3

**Comment by methane** [comment]
See https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting

You need to `%%`, or `%s` and move `'%giraffe%'` to argument.

**Comment by Stannislav** [comment]
Hi, could you explain what you mean by "move to argument"?

I know how string formatting works in Python, but is it intentional that an end-user who's just writing an SQL query should anticipate that internally this query will go through a string substitution and escape all percent signs by hand?

**Comment by methane** [comment]
> Hi, could you explain what you mean by "move to argument"?

```
cur.execute("SELECT * FROM my_table WHERE text_column LIKE %s", ("%giraffe%",))
```

> I know how string formatting works in Python, but is it intentional that an end-user who's just writing an SQL query should anticipate that internally this query will go through a string substitution and escape all percent signs by hand?

Yes it intentional. Read https://www.python.org/dev/peps/pep-0249/#paramstyle

**Comment by Stannislav** [comment]
Hi, I think you must have misunderstood me. I know how string substitution works in python, there's no need to link to the python docs.

What I was trying to say is that I don't ever call `cur.execute(...)` explicitely, see the description at the top. Here's the example from above again:

```python
import pandas as pd
import sqlalchemy


result = pd.read_sql(
    "SELECT * FROM my_table WHERE text_column LIKE '%giraffe%'",
    sqlalchemy.create_engine(f"mysql+pymysql://<database URI>")
)
```
How would you suggest altering this code so that it doesn't trip over the hidden string substitution?

**Comment by methane** [comment]
> Hi, I think you must have misunderstood me. I know how string substitution works in python, there's no need to link to the python docs.

I think you must misunderstood me. I know that you know Python string substitution. So I wrote a link to DB-API 2.0 specification, not Python doc.



> What I was trying to say is that I don't ever call `cur.execute(...)` explicitely, see the description at the top. Here's the example from above again:

If so, please report your opinion to Panda, not for me. This project never provide `pd.read_sql`. This project provides only `Cursor.execute()`.
