### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by richard-newman-rtap** [PyMySQL/PyMySQL#882]
The semantic versioning used to version this library was incorrect for version 0.10.0.
Since it contained breaking changes (removal of the context manager support from the connection class) it should have been increased by a major version not a minor version (which is intended for new functionality only and backwards compatible changes)

The incorrect use of semantic versioning could cause some package managers to automatically update and break code in unintended ways.
Please tag the version correctly as a major version change which introduces breaking changes.

**Comment by methane** [comment]
* Read this 100 times: https://semver.org/#spec-item-4. 0.10.0 doesn't conflict with semvar.
* Python and MySQL don't use semvar. And PyMySQL don't use it too. You must not force semvar.

**Comment by richard-newman-rtap** [comment]
Fair point about item 4, I hadn't considered that.
Thanks for your time.
