### ISSUE TITLE
How to preserve comments in statements?

### ISSUE THREAD

**Issue by tminglei** [PyMySQL/PyMySQL#884]
I need embed some info to statements to track it. 

So I did it like this,
```python
conn = pymysql.connect(..)
cur = conn.cursor()
cur.execute("select * from ... -- [some track code]")
...
```
But on mysql server side, I only got `select * from ...`. The `-- [some track code]` was missing.

As I know, `mysql` command provides an option of `--comments -c` to preserve comments.

Can I preserve comments with `pymysql`?

**Comment by methane** [comment]
PyMySQL doesn't strip comments.
What "mysql server side" mean?

**Comment by tminglei** [comment]
Well, `mysql server side` means the `SHOW FULL PROCESSLIST` results.
  
  
I checked it with `mysql` command as below,
```
# mysql -u kf_yangyunxia -p******** --host=172.16.150.119 --port=4000 --comments --wait --reconnect --connect-timeout=43200 mongo -e "select sleep(90); -- pi[long_sleep_test] "
```

When it's running, I can see **the query with comments** on the `show full processlist` results,

![image](https://user-images.githubusercontent.com/1828949/89952686-445ae480-dc60-11ea-9299-5a10ea194573.png)

And here's my check with `pymysql`,
```
do $$
import pymysql
conn = pymysql.connect(host='172.16.150.119', port=4000, database='procs', user='kf_yangyunxia', password='********')
cur = conn.cursor()
cur.execute("select sleep(90); -- [sleep_test]")
conn.close()
$$ language plpython3u;
```

When it's running, I found the comments were stripped,

![image](https://user-images.githubusercontent.com/1828949/89953751-458d1100-dc62-11ea-97f5-430d737a0c75.png)

**Comment by tminglei** [comment]
We won't strip comments by ourselves, but `mysql` command will strip comments by default.
To preserve comments when it was sent to server, we need add `--comments -c` option.

**Comment by methane** [comment]
OK, I understand your issue. Next time, please describe "what you tried" and "what you got" precisely.

This is completely unrelating to `-c` option of mysql CLI. MySQL server ignore everthing after `;` by default.
You need to enable MULTI_STATEMENT by `client_flag = MULTI_STATEMENT`.

**Comment by tminglei** [comment]
Yes, it works as you said. Thanks very much!!
I'll do it better next time.
