### ISSUE TITLE
SqlLAchemy multi  query gives 1064, "You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by nbkgit** [PyMySQL/PyMySQL#889]
According to the sql Alchemy website this should work

And i read here https://github.com/PyMySQL/PyMySQL/blob/v0.9.3/CHANGELOG#L66

that i should pass

client_flag=CLIENT.MULTI_STATEMENTS
I searched for several hours, how to input that in my code and i tried also sevral variants with no luck

python version 3.85

The **complete error message**

Exception has occurred: ProgrammingError
(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select * from test' at line 1")
  File "D:\Dokumente\newpy.py", line 12, in <module>
    cursor.execute("select * from table1; select * from test;")
**Code**
`from sqlalchemy import create_engine
import pymysql
user = 'root'
mysql_pass = 'testpassword'
mysql_ip = 'localhost'
cmd = 'SELECT * FROM table2;SELECT * FROM table1'
engine = create_engine("mysql+pymysql://{}:{}@{}:3306/testdb1?charset=utf8".format(user,mysql_pass,mysql_ip))
connection = engine.raw_connection()

try:
    cursor = connection.cursor()
    cursor.execute("select * from table1; select * from test;")
    results_one = cursor.fetchall()
    cursor.nextset()
    results_two = cursor.fetchall()
    cursor.close()
finally:
    connection.close()`

**Comment by methane** [comment]
You can use `connect_args`.
https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.connect_args

But please don't ask such questions about SQLAlchemy. I am not expert of SQLAlchemy.
You should find it from SQLAlchemy document by yourself. Or you can ask such question on Python community.
OSS maintainers are not free tech support.
