### ISSUE TITLE
When insert the data, the None type will be treat as empty string instead of null

### ISSUE THREAD

**Issue by lbeeon** [PyMySQL/PyMySQL#891]
**Describe the bug**
The version 0.10.0 will treat the None type as an empty string. 
Version 0.9.3 is working fine.

**To Reproduce**
Complete steps to reproduce the behavior:

Schema:

```
CREATE TABLE IF NOT EXISTS `rec_performance_click_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `test` VARCHAR(64) NOT NULL,
  `test2` VARCHAR(64) NOT NULL
);

```

Code:

```py
import pymysql
con = pymysql.connect(...)
data = list((
    None,
    "aaa",
))
cursor = con.cursor()
cursor.executemany(sql_cmd, data)
```

**Expected behavior**
The None type should raise an error 
Warning: (1048, "Column 'test' cannot be null")

**Environment**
 - docker python:3.7-stretch
 - PyMySQL version: 0.10.0

**Comment by methane** [comment]
> The version 0.10.0 will treat the None type as an empty string.

Your assumption is wrong. 0.10.0 treat None as NULL.

> **Expected behavior**
> The None type should raise an error
> Warning: (1048, "Column 'test' cannot be null")

0.9 didn't raise error too. 0.9 just emitted *warning*.

0.10 doesn't show warning automatically. You need to check it manually. This is intentional change.
See this comment: https://github.com/PyMySQL/PyMySQL/issues/792#issuecomment-487857290

**Comment by methane** [comment]
I think you can use more strict sql_mode, but I am not sure. I am expert of MySQL protocol, not MySQL server.
