### ISSUE TITLE
AssertionError: Result length not requested length:

### ISSUE THREAD

**Issue by imysm** [PyMySQL/PyMySQL#896]
**Describe the bug**
  File "/usr/local/python383/lib/python3.8/site-packages/pymysqlreplication/packet.py", line 153, in read
    return self.packet.read(size)
  File "/usr/local/python383/lib/python3.8/site-packages/pymysql/protocol.py", line 73, in read
    raise AssertionError(error)
AssertionError: Result length not requested length:
Expected=224.  Actual=220.  Position: 42.  Data Length: 262

**To Reproduce**

pymysqlreplication read binlog
Schema:

```
 CREATE DATABASE `crdb`   DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  ;
CREATE TABLE `tbl_o0_log` (
  `LOG_ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `TRANS_DATE` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
PRIMARY KEY (`LOG_SEQ`,`TRANS_DATE`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
 PARTITION BY RANGE  COLUMNS(trans_date)
(PARTITION p0 VALUES LESS THAN ('20190101') ENGINE = InnoDB,
 PARTITION p201901 VALUES LESS THAN ('20190201') ENGINE = InnoDB,
 PARTITION p201902 VALUES LESS THAN ('20190301') ENGINE = InnoDB),
 PARTITION pmax VALUES LESS THAN (MAXVALUE) ENGINE = InnoDB)
```

Code:

```py
import pymysql
import pymysqlreplication
```

**Expected behavior**

**Environment**
 - OS:  Linux
 - Server and version: [e.g. MySQL 8.0.21, MySQLDB]
 - PyMySQL version: 0.10.1

**Additional context**

**Comment by methane** [comment]
It's not a bug of this project. Report it to pymysqlreplication.

**Comment by imysm** [comment]
ok ，thak you.
But the pymysqlreplication project may be  no longer maintained
