### ISSUE TITLE
SQL syntax error occurs when passing future.types.newstr's instance to sql args

### ISSUE THREAD

**Issue by yagggi** [PyMySQL/PyMySQL#900]
**Describe the bug**

When porting code base from Python2.7 to Py3+，I used `future.types.newstr`(which is [`backport of the str object from Python 3`](https://python-future.org/what_else.html#str))，when pass instances of it to sql args I got :
```shell
ProgrammingError: (pymysql.err.ProgrammingError) (1064, u"You have an error in your SQL syntax; check the manual that
 corresponds to your MySQL server version for the right syntax to use near 'abc''' at line 3")
```
`select * from table where name = 'abc'` is turned into `select * from table where name = b''abc''`, It looks like something wrong when processing encoding escaping.

After some digging, I found [`escape_bytes`](https://github.com/PyMySQL/PyMySQL/blob/37fd1e1b0126d75d80eef59c053f80634b09bd75/pymysql/converters.py#L102-L104)method, it treats py2's bytes representation without `b` prefix, but `future.types.newstr` has added the prefix in `__repr__` and `__str__` method, so this is the probelm.

IMO we should check the return value of `obj.__repr__()` method to determine if adding prefix or not, instead of only check python version, what do you think?

**To Reproduce**
Complete steps to reproduce the behavior:

Code:
Ensure future is installed: `pip install future`

```py
Python 2.7.16 (default, Sep 12 2019, 17:39:28)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymysql.converters import escape_bytes
>>> from builtins import str
>>> ordinary_bytes = 'abc'.encode('utf-8')
>>> ordinary_bytes
'abc'
>>> bytes_for_porting = str('abc').encode('utf-8')
>>> bytes_for_porting
b'abc'
>>> escape_bytes(ordinary_bytes)
"'abc'"
>>> escape_bytes(bytes_for_porting)
"'b'abc''"
```

**Expected behavior**
`escape_bytes` method should remove `b` prefix in `future.types.newstr`, so can avoid syntax error in sql.

**Environment**
 - OS: MacOS Catalina
 - Server and version: MySQL 5.6
 - PyMySQL version: 0.10.1

**Comment by methane** [comment]
newstr doesn't add `b` prefix. Do you mean newbytes? [ref](https://github.com/PythonCharmers/python-future/blob/28b336151e991ddb8d8a4fb48c48f0e2b9784f55/src/future/types/newbytes.py#L138-L142).

PyMySQL supports only some builtin and stdlib types. Supporting more types is not business of this lowest level library.
Higher level library like ORM should support converting other types. Or you should convert newbytes to normal bytes by yourself.

**Comment by yagggi** [comment]
yeah sry i mean newbytes
ok got it
