### ISSUE TITLE
None Type object has no attribute 'read'

### ISSUE THREAD

**Issue by asbuch** [PyMySQL/PyMySQL#901]
I get this AttributeError when lots of db communication is going on through sqlalchemy 1.3.20, using pymysql 0.10.1 as driver.  I use multiple threads, each of which get their session from sqlalchemy's scoped_session object, so I think that part is ok?  Sorry for not providing code to reproduce the error, this would be a small project, but it may be possible to see what the problem is from the attached exception log.

[exception.log](https://github.com/PyMySQL/PyMySQL/files/5441868/exception.log)

**Comment by methane** [comment]
This exception means you're using closed connection. It is curious because you are using scoped_session correctly, as far as you said.
But I can not say anything more without reproducer. If you can not share reproducer, please investigate it by yourself and share what cause the error.

**Comment by asbuch** [comment]
Thanks for the comments.  The error was mine, I had a query of the form
q = session.query(...).filter(PythonClass.attribute == mappedObject).

Then I used q.with_session() from a different thread.  But the mappedObject still belonged to the original thread.
So probably there is nothing wrong with PyMySQL, this is at worst a question about throwing the most appropriate exception.
