### ISSUE TITLE
update null value got a ProgrammingError

### ISSUE THREAD

**Issue by flysee** [PyMySQL/PyMySQL#902]
Code:
```py
import pymysql
con = pymysql.connect(...)
cursor = con.cursor()
sql = "update `drug` set url=%s where id = 1;"
cursor .execute(sql, (None))
```
**Environment**
 - OS: [e.g. Windows, Linux]
 - Server and version: [e.g. MySQL 8.0.19, MariaDB]
 - PyMySQL version: PyMySQL==0.9.3

**Comment by methane** [comment]
https://stackoverflow.com/questions/12876177/how-to-create-a-tuple-with-only-one-element

**Comment by flysee** [comment]
i take a stupid mistake,thx
