### ISSUE TITLE
pymysql.err.InternalError: (5004  xxxxxx  is multi ts)

### ISSUE THREAD

**Issue by LiuYingjie-rd** [PyMySQL/PyMySQL#904]
pymysql.err.InternalError: (5004, u"query[select us.id,us.unitid,us.planid,us.userid,us.stype,us.content,us.addtime,us.modtime from unitsetting us left join unitinfo ui on us.unitid = ui.unitid left join planinfo pi on ui.planid = pi.planid where us.stype=6 and (us.content like '%129%' or us.content like '%198%') and ui.isdel=0 and pi.subject in (1,2,3,4)  and  pi.isdel =0;] is multi ts")

when I try to select a shardingdatabase，error like this. But I success select data when I run sql in mysql command line.

**Comment by methane** [comment]
Please fill template. I don't know anything about your environment.
https://github.com/PyMySQL/PyMySQL/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

At least, the error is not caused in this driver. The error came from the server you are connecting to. But I don't know even which server you are using.

> when I try to select a shardingdatabase，error like this. But I success select data when I run sql in mysql command line.

Can't you reproduce the issue in mysql cli with transaction?
As defined in DB-API 2.0, PyMySQL use transaction by default.
