### ISSUE TITLE
when run manage.py runserver

### ISSUE THREAD

**Issue by samarFayez** [PyMySQL/PyMySQL#905]
![image](https://user-images.githubusercontent.com/30325727/99903619-1ad53e80-2cce-11eb-96b6-ce36a8eff539.png)

**Comment by samarFayez** [comment]
python version Python 3.5.6 :: Anaconda, Inc.

**Comment by methane** [comment]
I do not support environment specific issue.
You need to fix your environment.

If you are using only binaries from anaconda, you may able to ask support for anaconda. But I am not sure.
