### ISSUE TITLE
Update documentation to mention that Cursor.execute eagerly downloads rows

### ISSUE THREAD

**Issue by MaxG87** [PyMySQL/PyMySQL#910]
Cursor.execute eagerly downloads rows. This is not mentioned in the documentation.

I had a hard time to find out whether to use `fetchone()`, `fetchall()` or `fetchmany()`. According to my experiments this does not matter because all rows are downloaded right when executing a statement. I documented my experiments [at StackOverflow](https://stackoverflow.com/questions/65394616/is-pymysqls-fetchone-buffered/65394617#65394617), but I think the details do not matter too much here.

I found that very surprising. I think the Documentation should mention this explicitly to avoid bad surprises.

**Comment by methane** [comment]
I already replied in the SO.

See also https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.SSCursor

**Comment by MaxG87** [comment]
I am very sorry, but I don't consider this to be properly resolved. Just having SSCursor around does not answer how the fetch family methods differ. And the SO-Question is not part of the official documentation.

It really would have saved time to if I there would have been simple 3 lines describing that there is no real difference in the three fetch methods. I am not complaining here, thats how documentations evolve. But this time could be saved for others who then do not need to search the internet or waste time implementing something around `fetchmany` instead of using `fetchone` or `fetchall`.

**Comment by isam-os** [comment]
the problem is like https://github.com/PyMySQL/PyMySQL/issues/766
sscursor's does not work ... 

answer on SO is useless it not work anyway sscursor cursor dictcursor and so on 
fetchone waits ALLLLLLL DATA always ! and when programm is done(with sscursor) we WAIT ALLLL DATA !!!!!!! until it download 

PS: mysql-connector-python works perfect fetchone , pymysql is not work 

windows7 py 3.8.0 

may be it too spam like 766, maybe im wrong

**Comment by methane** [comment]
Yes, it's spam like #766 because you don't provide complete, runnable, reproducible example.

**Comment by isam-os** [comment]
> Yes, it's spam like #766 because you don't provide complete, runnable, reproducible example.

ok, later 
but ... u need just run sniffer(network monitor) on big tables ANY example, from docs or u answer on SO

**Comment by isam-os** [comment]
hehe 

the code like this  without with 

```

cursor = connection.cursor(pymysql.cursors.SSCursor)
sql = "SELECT `msisdn`, `st_time`, `Usages` FROM `mts_usage_raw` LIMIT 1000"
cursor.execute(sql,())
result = cursor.fetchone()
print (result)
print("found row --- %s seconds ---" % (time.time() - start_time))
print("--- %s seconds ---" % (time.time() - start_time))
print('end programm')
```

```
(venv) c:\0test\pymysql-test-oncefetch>py t2.py
('77777777777', datetime.date(2020, 1, 1), None)
found row --- 0.00500035285949707 seconds ---
--- 0.00500035285949707 seconds ---
end programm

Exception ignored in: <function SSCursor.close at 0x0000000002B39160>
Traceback (most recent call last):
  File "c:\0test\pymysql-test-oncefetch\venv\lib\site-packages\pymysql\cursors.py", line 401, in clo
se
  File "c:\0test\pymysql-test-oncefetch\venv\lib\site-packages\pymysql\connections.py", line 1261, i
n _finish_unbuffered_query
  File "c:\0test\pymysql-test-oncefetch\venv\lib\site-packages\pymysql\connections.py", line 692, in
 _read_packet
  File "c:\0test\pymysql-test-oncefetch\venv\lib\site-packages\pymysql\connections.py", line 729, in
 _read_bytes
AttributeError: 'NoneType' object has no attribute 'settimeout'
Exception ignored in: <function MySQLResult.__del__ at 0x0000000002BB3E50>
Traceback (most recent call last):
  File "c:\0test\pymysql-test-oncefetch\venv\lib\site-packages\pymysql\connections.py", line 1152, i
n __del__
  File "c:\0test\pymysql-test-oncefetch\venv\lib\site-packages\pymysql\connections.py", line 1261, i
n _finish_unbuffered_query
  File "c:\0test\pymysql-test-oncefetch\venv\lib\site-packages\pymysql\connections.py", line 692, in
 _read_packet
  File "c:\0test\pymysql-test-oncefetch\venv\lib\site-packages\pymysql\connections.py", line 729, in
 _read_bytes
AttributeError: 'NoneType' object has no attribute 'settimeout'

(venv) c:\0test\pymysql-test-oncefetch>



```

cursor.close is problem

**Comment by methane** [comment]
> cursor.close is problem, **fetch ALL DATA**

OK, that is what you haven't said. `fetchone()` doesn't download all data. So there is not problem in this use case:

```py
cursor.execute(query, params)
for row in cursor:
    process(row)
```

Do not download all data is not regular pattern, because MySQL server need to prepare all data anyway. You should use `LIMIT` clause instead.

**Comment by isam-os** [comment]
> > cursor.close is problem, **fetch ALL DATA**
> 
> OK, that is what you haven't said. `fetchone()` doesn't download all data. So there is not problem in this use case:
> 
> ```python
> cursor.execute(query, params)
> for row in cursor:
>     process(row)
> ```
> 
> Do not download all data is not regular pattern, because MySQL server need to prepare all data anyway. You should use `LIMIT` clause instead.

of course, then you need to change the documentation  ;)

_This package contains a pure-Python MySQL client library, based **NOT** on PEP 249.

with cursor.close_

and of course 

_Unbuffered Cursor, mainly USELESS for queries that return a lot of data, or for connections to remote servers over a slow network. bcz on  "not regular pattern" we do not close the cursor as in "pep 249", we download all the data and kill the slow network

I'm sure it's okay

PS: mysql-connector-python works perfect fetchone and CLOSE.cursor ,  just doing exception "not all data fetch"

PSS: then it remains to find out why there are so many questions about fetchone and why there is no clear answer, because all these people use "is not regular pattern"  , it's obvious

**Comment by methane** [comment]
> _This package contains a pure-Python MySQL client library, based **NOT** on PEP 249.

What part of this library against PEP 249?

> _Unbuffered Cursor, mainly USELESS for queries that return a lot of data, or for connections to remote servers over a slow network. bcz on "not regular pattern" we do not close the cursor as in "pep 249", we download all the data and kill the slow network

It is useful, as I already demonstrated in https://github.com/PyMySQL/PyMySQL/issues/910#issuecomment-759876533

> PS: mysql-connector-python works perfect fetchone and CLOSE.cursor , just doing exception "not all data fetch"

I don't know much about mysql-connector-python. Did you confirm you can reuse that same connection without fetching remaining data?? Any code example??

> PSS: then it remains to find out why there are so many questions about fetchone and why there is no clear answer, because all these people use "is not regular pattern" , it's obvious

"So many"? How many?? All of the questions is because just they didn't use `LIMIT` clause???

**Comment by methane** [comment]
https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursorbuffered.html

> For queries executed using a buffered cursor, row-fetching methods such as fetchone() return rows from the set of buffered rows. For nonbuffered cursors, rows are not fetched from the server until a row-fetching method is called. In this case, you must be sure to fetch all rows of the result set before executing any other statements on the same connection, or an InternalError (Unread result found) exception will be raised.

Is this your "perfect"?

**Comment by isam-os** [comment]
> https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursorbuffered.html
> 
> > For queries executed using a buffered cursor, row-fetching methods such as fetchone() return rows from the set of buffered rows. For nonbuffered cursors, rows are not fetched from the server until a row-fetching method is called. In this case, you must be sure to fetch all rows of the result set before executing any other statements on the same connection, or an InternalError (Unread result found) exception will be raised.
> 
> Is this your "perfect"?

Sorry for my impertinence , I'm sure you know better than I do how things really are.

```
if there is it is possible to get
"(Unread result found) exception will be raised."

```
instead of downloading data, so that everyone understands that something is wrong with the code, with fetchone()
