### ISSUE TITLE
Compare the fetch-methods in the documentation

### ISSUE THREAD

**Issue by MaxG87** [PyMySQL/PyMySQL#911]
I had a very hard time to find out whether to use `fetchmany()`, `fetchone()` or `fetchall()`. This is related to #910 and the there mentioned [question at StackOverflow](https://stackoverflow.com/questions/65394616/is-pymysqls-fetchone-buffered/65394617#65394617).

I would have loved to see some structured argumentation on that matter in the documentation. Some that discusses benefits and drawbacks of each method in comparison to other methods.

**Comment by methane** [comment]
>  the there mentioned [question at StackOverflow](https://stackoverflow.com/questions/65394616/is-pymysqls-fetchone-buffered/65394617#65394617).

It seems you post the question, you answered it, and you chose your answer, and you mention it....

I replied in the SO question. https://stackoverflow.com/a/65405727/3430118



> I would have loved to see some structured argumentation on that matter in the documentation. Some that discusses benefits and drawbacks of each method in comparison to other methods.

They are implemented because they are defined by the [PEP](https://www.python.org/dev/peps/pep-0249/). You can read the PEP.

**Comment by MaxG87** [comment]
The answer you provided at SO is not helpful at all. You just point to another class without the slightest hint of how this class would help.

It really would have saved time to if I there would have been simple 3 lines describing that there is no real difference in the three fetch methods. I am not complaining here, thats how documentations evolve. But this time could be saved for others who then do not need to search the internet or waste time implementing something around fetchmany instead of using fetchone or fetchall.
