### ISSUE TITLE
Did pymysql ended python2 suppport or is it a bug?

### ISSUE THREAD

**Issue by Azee77** [PyMySQL/PyMySQL#935]
**Describe the bug**
Cannot install pymysql on python2

**To Reproduce**
pip install pymysql

Code:

```py
pip install PyMySQL
Collecting PyMySQL
  Using cached https://files.pythonhosted.org/packages/2b/c4/3c3e7e598b1b490a2525068c22f397fda13f48623b7bd54fb209cd0ab774/PyMySQL-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1f8gkR/PyMySQL/setup.py", line 6, in <module>
        with open("./README.rst", encoding="utf-8") as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
```

**Expected behavior**
avoid usage of py3 syntax

**Environment**
 - OS: [Windows, Linux]
 - PyMySQL version: latest

**Comment by methane** [comment]
![image](https://user-images.githubusercontent.com/199592/103858848-6b78ed80-50fc-11eb-8fc2-b2ddc366530b.png)

**Comment by Azee77** [comment]
looks like this information is not availabe straight forward. anyway, thanks for the update.

**Comment by methane** [comment]
Changelog is the first document you must read when new major version is released. It's "straigt forward".
