### ISSUE TITLE
SyntaxError during installation of pymysql-1.0.1

### ISSUE THREAD

**Issue by jmesquivel15** [PyMySQL/PyMySQL#942]
I tried to install the latest version of pymysql but encountered an error during the process. It shows invalid syntax on files connector.py, cursors.py, and protocol.py. Even though it showed successfully installed the package, it doesn't appear in the list of packages if you query using pip3 list. 
Please see the attachment for the detailed error encountered.
![pymysql_installation_SyntaxError](https://user-images.githubusercontent.com/44048828/104041659-5d1df500-5214-11eb-9922-23a9a5453f22.png)

**Comment by methane** [comment]
Check changelog before reporting issue.

<img width="331" alt="image" src="https://user-images.githubusercontent.com/199592/104073607-7beeac80-5251-11eb-9699-ad52e0aad066.png">

**Comment by jmesquivel15** [comment]
Yes, I have read the changelog before reporting it. I just got confused with the release history because the version 1.0 has been yanked. Anyway, thank you for your response.
