### ISSUE TITLE
PREPARE works on phpmyadmin but doesn't when used with pymysql

### ISSUE THREAD

**Issue by XcomReborn** [PyMySQL/PyMySQL#943]
I have created a test database called test inside it has a table called testTable with an autoincrement id value and a name field that takes a varchar(30).

The PREPARE statement queries (4 of them) execute fine when copied into phpmyadmin but I get the error 👍 2021-01-08 18:26:53,022 (MainThread) [ERROR] (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET\n    @name = 'fred';\nEXECUTE\n    statement USING @name;\nDEALLOCATE\nPREPARE\n  ' at line 5")

The test code:

```
import pymysql
import logging


class TestClass():

	def __init__(self):
		# mysqlconnections

		self.mySQLHostName = "localhost" 
		self.mySQLHostPort = 3306
		self.mySQLuserName = "userName"
		self.mySQLpassword = "pass"
		self.MySQLauthchandb = "mysql"
		
	def QueryMYSQL (self, query):
		try:
			#logging.info("QueryMYSQL  : " + str( query)) # Uncomment to print all mysql queries sent
			conn = pymysql.connect(host=self.mySQLHostName, port=self.mySQLHostPort, user=self.mySQLuserName, passwd=self.mySQLpassword, db=self.MySQLauthchandb, charset='utf8')
			conn.autocommit(True)
			cursor = conn.cursor()
			if cursor:
				returnSuccess = cursor.execute(query)
				
			if cursor:
				returnValue = cursor.fetchall()
			#logging.info ("return value : " + str(returnValue)) # Uncomment to print all returned mysql queries
			if cursor:
				cursor.close()
			if conn:
				conn.close()
			return returnValue
		except Exception as e:
			logging.error("Problem in ConnectTomySQL")
			logging.error(query)
			logging.error(e)
			return False

# Default error logging log file location:
logging.basicConfig(format='%(asctime)s (%(threadName)-10s) [%(levelname)s] %(message)s', filename= 'ERROR.log',filemode = "w", level=logging.DEBUG)
logging.info("Logging Started")

test = TestClass()
result = test.QueryMYSQL("Describe test.testTable")
print(result)
query = """
PREPARE
    statement
FROM
    'INSERT INTO test.testTable (id, name) VALUES (NULL , ?)';
SET
    @name = 'fred';
EXECUTE
    statement USING @name;
DEALLOCATE
PREPARE
    statement;
	"""
result = test.QueryMYSQL(query)
print(result)
```

I'm assuming this is a library issue rather than a mysql issue? I am trying to use prepared statements to prevent code injection from user input as I understand this prepared statements are the best way to do this rather than trying to pre filter user input and missing something.

**Comment by methane** [comment]
Multistatement can be used by attacker when there is a query injection vulnerability. So it is disabled by default.

>  as I understand this prepared statements are the best way 

You are totally wrong. Your use of prepared statement doesn't protect you from SQL injection at all. If you enable multistatement, your "prepared statement" can be attacked by SQL injection.

But I am not free tech support nor free teacher for you. OSS maintainers are not. Please don't ask here.

**Comment by XcomReborn** [comment]
Thanks I'll pass your comments onto the author of "Learning PHP, MySQL and JavaScript" O'Reilly 5th edition. He appears to be under the misconception and I quote "Let me introduce the best and recommended way to interact with MySQL, which is pretty much bulletproof in terms of Security" Its in the Using Placeholders section pg 260. Do you have an email so he can contact you directly? He clearly needs to be corrected because this book is a major text on the subject.

**Comment by methane** [comment]
I haven't read the book but I suppose you are misunderstanding.

There are two different "parepared statement".

* One is used by the protocol level prepare command. That's what the book says. With the command, you can avoid embedding parameters in statements.
* One is used by SQL statements like `PREPARE` and `EXECUTE`. That's what you are using. You are embedding parameters in the query (e.g. `@name = 'fred';`, so it will cause SQL injection if you failed to escape the parameter properly.

In case of PyMySQL, it don't support prepare command yet. But it supports placeholder, and safe placeholder substitution.

```py
cur.execute("INSERT INTO test.testTable (id, name) VALUES (NULL , %s)", ("fred",))
```
