### ISSUE TITLE
Data Error raising  at test test_issue_321 in file pymysql/tests/test_issues.py

### ISSUE THREAD

**Issue by asellappen** [PyMySQL/PyMySQL#951]
**Describe the bug**
I am working for IBM to port the package into power cpu and i came accross the below issue during the testing,It's failing for intel and power as well,Can you please help to fix in the test script pymysql/tests/test_issues.py ,

Failing at fun test_issue_321 in the line in the line 416,417,418 at insert to mysql tables as below.

     sql_insert = "insert into issue321 (value_1, value_2) values (%s, %s)"
        sql_dict_insert = (
            "insert into issue321 (value_1, value_2) "
            "values (%(value_1)s, %(value_2)s)"
        )
        sql_select = "select * from issue321 where " "value_1 in %s and value_2=%s"
        data = [
            [("a",), "\u0430"],
            [["b"], "\u0430"],
            {"value_1": [["c"]], "value_2": "\u0430"},
        ]
        cur = conn.cursor()
        self.assertEqual(cur.execute(sql_insert, data[0]), 1)
		
		
		data = b"\xffV\x05#HY000Incorrect string value: '\\xD0\\xB0' for column 'value_2' at row 1"
    def raise_mysql_exception(data):
        errno = struct.unpack("<h", data[1:3])[0]
        errval = data[9:].decode("utf-8", "replace")
        errorclass = error_map.get(errno)
        if errorclass is None:
            errorclass = InternalError if errno < 1000 else OperationalError
>       raise errorclass(errno, errval)
E       pymysql.err.DataError: (1366, "Incorrect string value: '\\xD0\\xB0' for column 'value_2' at row 1")
pymysql/err.py:143: DataError
=========================== short test summary info ============================
FAILED pymysql/tests/test_issues.py::TestGitHubIssues::test_issue_321 - pymys...
============ 1 failed, 153 passed, 11 skipped, 1 xfailed in 11.98s =============
The command "python -m pytest pymysql/tests/" exited with 1.

have debugged and found the value data[0] , [("a",), "\u0430"] & [["b"], "\u0430"] etc are failing with Incorrect string value: '\\xD0\\xB0' for column 'value_2' at row 1

**To Reproduce**
Complete steps to reproduce the behavior:
ran the below travis scripts created by me for CI and testing 
====================
language: python
dist: bionic
arch:
  - amd64
  - ppc64le
services:
  - mysql
python:
 # - 3.7
  - 3.8

sudo: required
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test1'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test2'
  - python3 -m pip install PyMySQL
install:
  - pip install -r requirements-dev.txt
  - pip install python-coveralls
  - pip install pytest
  - python setup.py install
  - pip install --no-deps -e .
script:
  - python -m pytest pymysql/tests/
=====================================================
The script using python -m pytest pymysql/tests/ at the above calling  pymysql/tests/test_issues.py and it fails with dataerror as mentioned below

  pymysql.err.DataError: (1366, "Incorrect string value: '\\xD0\\xB0' for column 'value_2' at row 1") 
Schema:

```
CREATE DATABASE ...
CREATE TABLE ...
```

Code:

```py
import pymysql
con = pymysql.connect(...)
```

**Expected behavior**

The build and test is failing as below due to tes issue ,it should pass in travis 
>       raise errorclass(errno, errval)
E       pymysql.err.DataError: (1366, "Incorrect string value: '\\xD0\\xB0' for column 'value_2' at row 1")
pymysql/err.py:143: DataError
=========================== short test summary info ============================
FAILED pymysql/tests/test_issues.py::TestGitHubIssues::test_issue_321 - pymys...
============ 1 failed, 153 passed, 11 skipped, 1 xfailed in 11.98s =============
The command "python -m pytest pymysql/tests/" exited with 1.
Done. Your build exited with 1.

**Environment**
 - Linux 
 - MySQL 8.0.19
 - PyMySQL version: PyMySQL-1.0.2

**Additional context**

**Comment by methane** [comment]
What is your database default charset?
Tests assume utf-8.

**Comment by asellappen** [comment]
good catch ,thanks you .It works after setting the charset.
  - mysql -e 'ALTER DATABASE test1 CHARACTER SET utf8 COLLATE utf8_general_ci'
  - mysql -e 'ALTER DATABASE test2 CHARACTER SET utf8 COLLATE utf8_general_ci'
