### ISSUE TITLE
Version 1.0.2 when used with pandas.read_sql now display b'mydata' instead of mydata

### ISSUE THREAD

**Issue by JohnOmernik** [PyMySQL/PyMySQL#958]
Something has changes when using the pandas.read_sql() with pymysql. It used to just show string fields in the database as they were, now it displays b'data' instead of just data.   Nothing in my environment has changed excepts pymysql v0.10.1 -> 1.0.2

**Comment by methane** [comment]
Please provide a sample table, data, and code without using panda.
