### ISSUE TITLE
Connection.__del__ doesn't close the connection properly.

### ISSUE THREAD

**Issue by roelschroeven** [PyMySQL/PyMySQL#961]
When you don't close a connection explicitly, the Python runtime eventually calls the `__del__` method which (IMO) should properly close the connection. PEP 249 says about Connection.close(): "Close the connection now (rather than whenever `.__del__()` is called)." That strongly suggests that the difference between `close()` and `__del__()` is not what happens, but only when it happens.

But `__del__` is bound to `_force_close`, which closes the connection without a QUIT message. MariaDB (and presumably MySQL) is not very happy with that. It writes warnings in its error.log:
`[Warning] Aborted connection 48939 to db: '****' user: '****' host: 'localhost' (Got an error reading communication packets)`

I could fix that in my client code of course, and I will. But still I think it would be better to do a proper close in `__del__`, if the connection is not already closed.

**Comment by methane** [comment]
`__del__` is very danger method. Doing anything complex in it is bad idea. I want to minimize blocking operation in `__del__`.

**Comment by roelschroeven** [comment]
That's a fair point.
