### ISSUE TITLE
Python 2.7.16 install V1.0.x TypeError: 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by gaofei1982** [PyMySQL/PyMySQL#968]
pip2 install  pymysql

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3VcoEj/pymysql/setup.py", line 6, in <module>
        with open("./README.rst", encoding="utf-8") as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

=========
why change setup.py  io.open to open ？

**Comment by methane** [comment]
https://github.com/PyMySQL/PyMySQL/blob/master/CHANGELOG.md#v100

![image](https://user-images.githubusercontent.com/199592/108823872-5a306580-7604-11eb-91b8-98c34e45898c.png)

**Comment by gaofei1982** [comment]
But 2.7.16 install V1.0.x error, how can I fix it?

**Comment by gaofei1982** [comment]
OK, thanks.
