### ISSUE TITLE
pymysql/cursors.py:170: Warning: (3090, '')

### ISSUE THREAD

**Issue by mouday** [PyMySQL/PyMySQL#970]
/Users/.pyenv/versions/py370/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (3090, '')
  result = self._query(query)

peewee + pymysql

**Comment by methane** [comment]
How to reproduce it? Please provide a complete step.

**Comment by mouday** [comment]
this peewee:
`total = DataModel.select().count()`

and this echo sql
```
('SELECT COUNT(1) FROM (SELECT 1 FROM `tag_data` AS `t1`) AS `_wrapped`', [])
```

**Comment by methane** [comment]
It is not a complete step to reproduce.
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by mouday** [comment]
I already handled this problem, before, My PyMySQL version is 0.9.3, and I update it to version 1.0.2. now, this warning is hidden.

```bash
pip install -U pymysql
```

and thank you see this issue, please close it.
