### ISSUE TITLE
test_connection.py failing with syntax error KeyError: 'database'

### ISSUE THREAD

**Issue by asellappen** [PyMySQL/PyMySQL#975]
**Describe the bug**

test_connection.py is failing with syntax error KeyError: 'database' during test execution for line current_db = self.databases[0]["database"]  at test script pymysql/tests/test_connection.py from func def test_select_db

**To Reproduce**
build and test as below 
pytest -v pymysql

Schema:

mysql/mariadb db

Code:

https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/tests/test_connection.py
the keyword "database' causing the issue it should be referred as "db" 

The problem is at 
pymysql/tests/test_connection.py at line 449 under function test_select_db

self.databases[0]["database"]
self.databases[1]["database"]

should be replaced as below 

  def test_select_db(self):
        con = self.connect()
        current_db = self.databases[0]["db"]
        other_db = self.databases[1]["db"]
		

**Expected behavior**
test script should continue

**Environment**
 - OS:  Linux
 - Server and version: MySQL 8.0.19, MariaDB
 - PyMySQL version: master

**Additional context**
Its a keyword issue and needs to be corrected.

**Comment by methane** [comment]
test_connection don't fail on our CI. It's your environment issue. Use `database`, not `db` in your `databases.json`.

**Comment by asellappen** [comment]
> database

running from travis build ,found databases.json under .travis folder and changing as suggested

**Comment by methane** [comment]
I don't use travis now.

**Comment by mcepl** [comment]
> test_connection don't fail on our CI. It's your environment issue. Use `database`, not `db` in your `databases.json`.

It doesn't make sense. I use `ci/databases.json` from your tarball and yet I still get this error:
```
[   67s] =================================== FAILURES ===================================
[   67s] ________________________ TestConnection.test_select_db _________________________
[   67s]
[   67s] self = <pymysql.tests.test_connection.TestConnection testMethod=test_select_db>
[   67s]
[   67s]     def test_select_db(self):
[   67s]         con = self.connect()
[   67s] >       current_db = self.databases[0]["database"]
[   67s] E       KeyError: 'database'
[   67s]
[   67s] pymysql/tests/test_connection.py:449: KeyError
[   67s] =========================== short test summary info ============================
[   67s] FAILED pymysql/tests/test_connection.py::TestConnection::test_select_db - Key...
[   67s] ============ 1 failed, 151 passed, 13 skipped, 1 xfailed in 12.49s =============
```

[Complete log](https://github.com/PyMySQL/PyMySQL/files/6893575/_log.txt) with all details of packages used and steps taken.
