### ISSUE TITLE
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)

### ISSUE THREAD

**Issue by reik-wargaming** [PyMySQL/PyMySQL#976]
**Describe the bug**
Using `pymysql.connect` can cause `UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)`

**To Reproduce**
Connect to a database having a long hostname (i.e. AWS RDS), long username, and long password. 

```
connection = pymysql.connect(
      host=HOSTNAME,
      user=USERNAME,
      password=PASSWORD,
      connect_timeout=2
  )
```

**Expected behavior**
The database connection is returned.

**Environment**
 - OS: AWS Lambda (Amazon Linux?), Python 3.8 runtime
 - Server and version: -
 - PyMySQL version: 1.0.2

**Additional context**
I believe this is the reason: https://bugs.python.org/issue32958 - looking for ideas, workaround or fix. If this is the case, hostname+username+password must be under 64 characters. Unfortunately, with the RDS database that I am using, the hostname alone is already close to 60 characters (`customer-db.xxxxxxxxxxxx.ap-southeast-2.rds.amazonaws.com`). I really don't want to compromise security by using a super short username or password.

Stacktrace:
```
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 40, in handler
audit = request_handler.handle_request()
File "/var/task/request_handlers.py", line 51, in handle_request
connection = pymysql.connect(
File "/var/task/pymysql/connections.py", line 353, in __init__
self.connect()
File "/var/task/pymysql/connections.py", line 613, in connect
sock = socket.create_connection(
File "/var/lang/lib/python3.8/socket.py", line 787, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
File "/var/lang/lib/python3.8/socket.py", line 918, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
```

**Comment by methane** [comment]
> I believe this is the reason: https://bugs.python.org/issue32958 - looking for ideas, workaround or fix. If this is the case, hostname+username+password must be under 64 characters.

We don't use username and password in `connect()`. So length of username and password is not a problem.
Your hostname is too long or you failed to copy&paste the host name.

**Comment by reik-wargaming** [comment]
Sorry, this was reported to me and I was given the stack trace. However, I tried to replicate the issue but it was working fine, even with longer hostnames. Closing.
