### ISSUE TITLE
select_db() configuration should persist between reconnections

### ISSUE THREAD

**Issue by kace** [PyMySQL/PyMySQL#977]
**Schema:**

Given a MySQL server with 2 databases - "foo" and "spam".

**Code:**

```py
import pymysql

db = pymysql.connect(
    database="foo",
)

# Queries here will target the `foo` database by default as configured in the constructor

# Switches the database for this connection to target the `spam` database
db.select_db("spam")

# Queries here will target the `spam` database as configured in the `select_db()` call

# Reconnect to server
db.close()
db.ping(reconnect=True)

# Expectation: queries after reconnection will target the `spam` database as last configured in the `select_db()` call
# Reality: queries after reconnection revert to targeting database specified in constructor, in this case `foo`
```

**Description:**

I'm not sure if the above behavior is intentional but I found it confusing while using `PyMySQL`. It makes sense to me to persist the configuration changes from the `select_db()` call between reconnections however if you don't agree it might be useful to explain this behavior of `select_db()` in the documentation.

**Comment by methane** [comment]
I don't recommend to use reconnection. It doesn't keep any server side states, not only current db.
You should use connection pool, or create a new connection every time.
