### ISSUE TITLE
Error when trying to create stored procedure

### ISSUE THREAD

**Issue by scottfrazer** [PyMySQL/PyMySQL#98]
``` python
import pymysql
conn = pymysql.connect(host='127.0.0.1', user='hydrant-test', passwd='', db='hydrant-test')
cur = conn.cursor()
cur.execute("""
  DELIMITER @@
  CREATE PROCEDURE test()
  BEGIN
    SELECT 1;
  END
  @@
  DELIMITER ;
""")
cur.close()
conn.close()
```

The error I receive is:

```
pymysql.err.ProgrammingError: (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER @@\n  CREATE PROCEDURE test()\n  BEGIN\n    SELECT 1;\n  END\n  @@\n  DELIMI' at line 1")
```

The SQL in the python code above works through normal means (same user and DB)

**Comment by EgorAlmikeev** [comment]
> I can run following code.
> 
> ```python
> import pymysql
> conn = pymysql.connect(user='root', passwd='', db='test_pymysql')
> cur = conn.cursor()
> cur.execute("""
>   CREATE PROCEDURE test()
>   BEGIN
>     SELECT 1;
>   END
> """)
> cur.close()
> conn.close()
> ```

Thanks a lot, man! I've been trying to figure out whats wrong with pymysql for a day, but it just doesn't need to change the delimiter, lol :D

**Comment by gghez** [comment]
what about executing a complete script file already containing DELIMITER statements ?

**Comment by methane** [comment]
Use mysql command, or parse it by yourself.
It is not driver's business.
