### ISSUE TITLE
Different version cause an error

### ISSUE THREAD

**Issue by qiezikuangge** [PyMySQL/PyMySQL#982]
Hi, I meet an error when I use `pymysql.connect` with python2 environment. The package version is 0.6.2
But it be solved when I change environment to python3. The package version is 1.0.2
And I must use some package on python2 environment. So, I want to get some suggestions
This is my operation.

![image](https://user-images.githubusercontent.com/50002441/115985931-9e2def80-a5e0-11eb-984d-5149e8a42bcc.png)

**Comment by methane** [comment]
https://stackoverflow.com/questions/45368336/error-keyerror-255-when-executing-pymysql-connect
