### ISSUE TITLE
autocommit mode is not set when global autocommit=0

### ISSUE THREAD

**Issue by zhenying1992** [PyMySQL/PyMySQL#985]
**Describe the bug**
autocommit mode is not set when global autocommit=0

**To Reproduce**
set global autocommit=0;

Code:

```py
import pymysql

conn=pymysql.connect(
    host=***,
    port=***,
    user=***,
    passwd=***,
    db=***,
    )

c = conn.cursor()
c.execute("""select @@autocommit;""")
assert c.fetchone()[0]==False

conn.autocommit(True)
c.execute("""select @@autocommit;""")
assert c.fetchone()[0]==True
conn.close()
```

**result**
    assert c.fetchone()[0]==True
AssertionError

**Environment**
 - Server and version: MySQL5.7.21-21
 - PyMySQL version: 0.10.1

**Comment by mgm-dev** [comment]
Hi, I have try to replicate this bug but have failed. Which version of python are you using?

**Comment by zhenying1992** [comment]
> Hi, I have tried to replicate this bug but have failed. Which version of python are you using?

python version: 3.6.7

**Comment by methane** [comment]
I can not reproduce it. PyMySQL `autocommit()` works fine.
Ask to your DB admin.
