### ISSUE TITLE
Charset with name "latin1" is converted to "cp1252"

### ISSUE THREAD

**Issue by FredericoCoelhoNunes** [PyMySQL/PyMySQL#997]
**Describe the bug**
On the `charset.py` file, line 21:
```
 if name == "latin1":
        return "cp1252"
```

This causes the following error on my insert:

`UnicodeEncodeError: 'charmap' codec can't encode character '\x96' in position...`

I fixed this issue by manually setting `self.encoding` (on `connection.py`) to "latin-1".

**To Reproduce**
N/A, question is about the code itself.

**Expected behavior**
I expect PyMySQL to use latin-1, and not Windows-1252, when specified. Perhaps it's my lack of knowledge about encodings, but I find it strange that my insert works when I hardcode the latin-1 encoding, and stops working when PyMySQL converts latin-1  into cp1252.

**Environment**
 - OS: Ubuntu 18.04
 - Server and version: N/A
 - PyMySQL version: 1.0.2

**Additional context**
N/A

**Comment by methane** [comment]
latin1 in MySQL is cp1252, not latin-1. But it is slightly different from Python cp1252.
There is no way to make 100% people happy.

You should stop using latin-1 and use UTF-8 instead.
If you keeps using legacy encodings, you should solve such troubles by yourself.
