### ISSUE TITLE
2003 error in WSL environment

### ISSUE THREAD

**Issue by cs99619** [PyMySQL/PyMySQL#998]
In the WSL environment, the following errors are generated when connecting to the database:
`(2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 22] Invalid argument)")`

**Comment by methane** [comment]
Are you really sure only the "WSL environment" caused the issue?
Do you think everyone in the world using WSL facing this issue?

If I try to reproduce it and I can not, I waste my time.
Please investigate it by yourself and give me more information to reproduce it.
